### ISSUE TITLE
If having corrupt Z-Wave Node config it wont refresh if "Refresh Node Info" is used... Domoticz or/and OZW issue?  

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#1209]
I have posted this issue at OZW but was directed back here, any ideas?

https://github.com/OpenZWave/open-zwave/issues/1073

Thanks!
//Ricard

**Comment by TimelessNL** [comment]
**My workaround is:**
Keep using the "refresh node" button, if that does not help restart disable/enable OpenZwave in Domoticz. if both do not help I manually unpower/power the USB socket (which is basically a unplug/replug).

I must add that there were times these steps did not solve anything and I just left it there out of pure frustration. But after some days it got fixed anyhow without my input.

**Additional info:**
I also having the same issue very often. Especially because I cannot get OpenZwave to run stable for more than 5 days, it causes Domoticz to hang and after a manual(automatic) restart I frequently see a "corrupt node".

All my nodes are using Zwave+, what about you? Because my problems began when I started using Zwave+.

**Final thought:**
I know my workaround is far from ideal, but I did not find the time to investigate it any further. Hope it helps anyway.

_PS. maybe it's best to open a topic on the [Domoticz Forum](http://www.domoticz.com/forum/) because this is not directly a coding issue._

**Comment by RicardP** [comment]
Hi TimelessNL, thanks for sharing your experience. Yes there is some ways to fix corrupt nodes, however I never saw it heal itself in any case as you did. I stop the Domoticz service and manually delete the node (node /node) in .xml file. after starting up again the corrupt node config is fresh rebuilt. This complete procedure should be done by OZW if pushing the "Refresh Node Info", but it does not.

Of course nodes should not even get corrupt in first place, so something is also wrong at CRC checking the node sent data to the Controller and/or OZW. 

I have only Zwave+ equipments.

I do not have any stability issues with OZW/Domoticz.

Yes and No about this is a forum issue.. because it cant be meant that the "Refresh Node Info" should behave like it does = Bug, As you noted I thought it was a sole OZW issue but OZW developer Fishwaldo pointed me back to Domoticz developers to fix it with his support.

**Comment by gizmocuz** [comment]
Seems not a domoticz issue reading the ozw thread? If note, please close this issue

**Comment by RicardP** [comment]
Yes they did made a fix for next major release, hope it will be soon.

Over and out! :)

**Comment by TimelessNL** [comment]
Hi RicardP. What changeset fixed this issue? Could you link it here to make your issue report complete?

**Comment by RicardP** [comment]
Well, it is only closed from Domoticz point of view, it is being continued at OZW, no verified or confirmed fix for it. Should be included in OZW "1.6 milestone" but release date is undefined since long time.

Here it is: https://github.com/OpenZWave/open-zwave/issues/1073
