### ISSUE TITLE
 influxdb push wrong time stamps

### ISSUE THREAD

**Issue by ayounas** [domoticz/domoticz#1232]
Version: 3.6708
Build Hash: 7b91f74

Hello 

I configured power monitoring device and a temperature measurement device to push data to influxdb. 
But the time stamps sent with data are very random therefore not usable for creating graphs.

Below is the data from influxdb showing random time stamps

> select * from Instant
name: Instant
time        idx name        value
----        --- ----        -----
-1614265344 192 Power-Usage 627
-858905600  192 Power-Usage 627
25996288    192 Power-Usage 676
90767360    192 Power-Usage 708
846127104   192 Power-Usage 676

> 
> select * from Temperature
name: Temperature
time      idx name                      value
----      --- ----                      -----
551159808 199 Outside-Front-Temperature 7.7
680701952 199 Outside-Front-Temperature 7.6
745473024 199 Outside-Front-Temperature 7.7

> 
> 
>

**Comment by gizmocuz** [comment]
Strange, i don't have this issue here
I will remove the timestamp from domoticz, this way influxdb will generate the timestamp, maybe this causes some milliseconds to be off, but not a problem i suppose ?

Could you try beta 6722 ?

Are you experienced with InfluxDB ? I would like to add a button '(Re-)Create Database'
With an aggregation function (creating daily tables with min/max/avr, and for counters the counter value of course)
And a retention, 1 year (this last one i understand how to make)

Do you use grafana by any change ? Would be nice to have on our wiki a grafana section with some example, like... how to get the total kWh/m3 from the starting of today ?

Maybe you can send me a PM on the forum ;)

**Comment by gizmocuz** [comment]
Ps. Seems your temperature timestamps are correct ?

Ps2. I dont have this issue bdw...

**Comment by ayounas** [comment]
Cheers Gizmocuz

Removing timestamp from domoticz have fixed the issue. It is quite strange that you are not getting similar issue, probably the libraries i got have some bug .
Also temperature time stamps even not in -ve and not as random as energy but converting 745473024  gives GMT: Mon, 16 Aug 1993 03:50:24 GMT , but that is fixed now.

 I have sent you a pm on forum about grafana


before update
2134559232          192 Power-Usage 482
2135467520          192 Power-Usage 547
2136375808          192 Power-Usage 1545
2140103168          192 Power-Usage 1480
2141642752          192 Power-Usage 386
2142828032          192 Power-Usage 563
2143736320          192 Power-Usage 643
2144644608          192 Power-Usage 1738

after update to  6722

1487281265959940076 192 Power-Usage 370
1487281295978841479 192 Power-Usage 1867
1487281301987135421 192 Power-Usage 354
1487281326000207517 192 Power-Usage 370
1487281344011683119 192 Power-Usage 338
1487281404030241737 192 Power-Usage 386
1487281410038273823 192 Power-Usage 354
1487281446052312609 192 Power-Usage 370
