### ISSUE TITLE
Add Nest Two authentication factor

### ISSUE THREAD

**Issue by Plasmagun86** [domoticz/domoticz#1340]
Nest add two authentication factor recently.
Domoticz can't handle it for the moment.

**Comment by gizmocuz** [comment]
True, can you help with this ?

**Comment by candrea77** [comment]
I've got a session with an help desk agent.
This is how nest manage 2FA
```
Two-factor authentication confirms a user's claimed identity by using two components:
email and password
an SMS based second-factor PIN authentication

Setting up 2FA
In the Nest App’s Account Menu, select Mange Accounts, then Accounts Security. This will reveal a ‘Two-Factor Authentication’ toggle slider.

Sign in to the account.
Next, input a trusted phone number. Nest will send a verification code to this number. Finally, enter the verification code that was sent to your phone number to complete the two-factor authentication enrollment process.
Once ‘Two-Factor Authentication’ is enabled, the verification code input field will appear on the login screen. When you log in, you will request a verification code and enter it in the verification code field.

App users are prompted for a verification code:
**When your sign-in expires, which is automatically set to one year from the first time you sign in using 2FA**. 
Anytime you try to sign in to your account after logging out.
When attempting to change your 2FA enrollment.
```

Plasmagun86 : I don't have any nest device ..... give it a try and let us know (personally I don't think it can work .... otherwise it is a non-sense).
Maybe it save some cookies on PC where you login ..... so no access from domoticz.

**Comment by candrea77** [comment]
I created a nest account (without device .... I don't have one) and obviously despite I was logged in with my PC with 2FA, I can't login with domoticz.

Also, as from nest chat support, nest does not support a feature like "password for app" at the moment.

**Comment by dotms** [comment]
I think logging in with a username/password is the wrong route: one that should not be used for programmatic access. I've been exploring the Nest plugin code in Domoticz for a bit and it looks like an old, unofficial API is being used which is intended for use by the mobile application.

The right direction should be doing it the official way: requesting an API token and use the correct calls for the v6(?) API. Unfortunately that also means that adding a Nest thermostat will be a little more cumbersome since you have to sign up for said API.

**Comment by dotms** [comment]
On a sidenote: I'm currently working on a replacement plugin for Nest which works using the official public API, REST and authenticating via OAuth. It will be an adjustment of the current plugin. Got the basics working for both the thermostat and protects, but need to do additional testing and user interface modifications.

**Comment by gizmocuz** [comment]
Great, could you submit a patch for this ?

**Comment by FoUStep** [comment]
I agree with gizmocuz, I want to use Domoticz but I haven't bought any transceiver (for my rolling shutters or lighting) yet. I have a Nest and wanted to test this first, but without 2FA that's not possible for me. Hopefully you can submit a patch (beta or not), but I am willing to test this.

**Comment by dotms** [comment]
I'm not actively working on it any more (at the moment), mainly because the amount of work and the seemingly lack of interest. Domoticz does not really appear to be prepared for providing an interface to enter one-time credentials or keys so I had to work around that. It works now but isn't fancy. I lack the skills to rewrite bigger parts of Domoticz to provide that.

Other than that I was looking at getting websockets implemented since that is the preferred way of communicating with the Nest API (as opposed to polling) but ran into issues getting things to work (please note that I'm only a novice at C++ and I don't really have an understanding how websockets work). 

I have my unfinished code still on a computer somewhere. I'll see if I can tidy it up a bit and write some basic instructions down over the course of the next week(s). Busy IRL :)

**Comment by mDieli** [comment]
@dotms , Did you find the code on your computer and did you have any time to tidy it up a bit an write some basic instructions?
It would be great if Nest would be working (again) in Domoticz :)

**Comment by dotms** [comment]
@mDieli Took a little longer than expected but I submitted a pull request to have this integrated in Domoticz. See also http://www.domoticz.com/forum/viewtopic.php?t=17370 and https://github.com/domoticz/domoticz/pull/2026.

**Comment by mDieli** [comment]
@dotms 
Superthanks! Just tested it in my test environment and all is looking great!

**Comment by marceldejongnl** [comment]
@dotms Thanks for your work, hope this gets in the beta soon!

**Comment by mDieli** [comment]
@dotms I just saw a denied pull-request with a comment from gizmocuz:
"Is it possible you could submit the pull request against the development branch ? Patches against the master branch are not allowed (Sorry)"

Thank you in advance!!

**Comment by dotms** [comment]
Almost there, see https://github.com/domoticz/domoticz/pull/2095 .

**Comment by gizmocuz** [comment]
Implemented
