### ISSUE TITLE
Teleinfo usb issue

### ISSUE THREAD

**Issue by nonolk** [domoticz/domoticz#1441]
Since some beta version, the teleinfo information are no more automaticaly updated, and I have to set a delay on the device in order to restart it every minutes in order to get the information again.
`2017-04-05 11:21:00.268 Error: Teleinfo hardware (13) nothing received for more than 1 Minute!....
2017-04-05 11:21:01.268 Error: Restarting: Teleinfo
2017-04-05 11:21:01.467 Teleinfo: Teleinfo uses serial port: /dev/ttyUSB-teleinfo
2017-04-05 11:21:01.485 (Teleinfo) Teleinfo CRC check mode set to 1`
If needed I can give you more information, but I'm in a quite standard subscription (Heures Pleines/Creuse) with only one "phase".

Thank you in advance.

**Comment by nonolk** [comment]
As another information it just work perfectly on in the last stable release

**Comment by nonolk** [comment]
Another information it just work perfectly on in the last stable release
Last but not least here the usb "dongle" I'm using:
[https://www.domotique-store.fr/domotique/usages/mesure-de-consommation-energetique-domotique/mesure-de-consommation-via-teleinfo-edf/672-module-teleinfo-usb-cartelectronic-usbticlc-win.html](url)

**Comment by DebugBill** [comment]
Hi,

I developped the updated support for Teleinfo and apparently I have created a bug wich I don't understand yet. On my system it works fine.... but there are already 3 people reporting issues (but not exactly the same)

Do you compile yourself? Or do you keep the Domoticz log information? I would like to know for sure if something is getting in during that minute and not processed, or if nothing comes in at all because the serial port driver process for some reason.

In your specific case, the Teleinfo module will by default update every minute at most and every 5 minutes at least. If consumption (Amps) is stable during 5 minutes, no update will occur, and only a meter update will happen evey 5mn. If consumption changes frequently, then all meters will be updated every minute (at least this is how I designed it in my head, maybe not how I coded it, I have to check thouroughly :-) The goal is not to update if there is no changes so the database is not overloaded with identical data. I consider the Index update as non critical.
The "one minute no update" could then be perfectly normal depending on your specific situation

In the version currently submitted to Gizmocuz you have the ability to set the update rate you want. Still it will never be less than 5mn, so the watchdog should be set to 5mn or more, but you can ask for more frequent updates, like every 30 sec.

**Comment by nonolk** [comment]
Hello DebugBill,

So no I didn't compile it by myself, I'm using the lastest beta build coming from here. Just tell me how to activate the logs you need and I will.

As information, I'm running Domoticz on a rpi3.

**Comment by DebugBill** [comment]
You need to compile yourself in order to activate logs.
Anyway, I've just had a strange message here too and I have activated the logs. I also run on a Pi3. I will see if I can understand the origin.

**Comment by pepsi92** [comment]
Hi,

Thanks for the good job on this Teleinfo module. Unfortunatly, I think I also have an issue with my Teleinfo USB module since I updated to Domoticz release 3.7212 (it worked fine with 3.71xx for me). Now, it seems domoticz stop collecting the data after some hours and I have to stop/start domoticz to fix it.

My current setting is : 
- Domoticz 3.7212 running on a Synology DS416play with DSM 6.1. I'm using the package from Jadahl
- Teleinfo USB module (working perfectly as I still can get the data at system level using "cat /dev/ttyUSB0")

I trying to reduce the delay down to 1 minute but it does not fix the issue.

In the log, no real information, except : 

```
2017-04-05 18:34:30.113  Error: USBTIC hardware (6) nothing received for more then 1 Minute!....
2017-04-05 18:34:31.114  Error: Restarting: USBTIC
2017-04-05 18:34:31.146  Teleinfo: USBTIC uses serial port: /dev/ttyUSB0
2017-04-05 18:34:31.377  (USBTIC) Teleinfo CRC check mode set to 1
```

Thanks for your help on this issue.

**Comment by DebugBill** [comment]
Hi,
There is definitely a problem, and it happened to me also today. Up to now i've not managed to track it down but I definitely will. Stay tuned, the version currently under review may fix it (it did not happen for me in the last 10 hours....

**Comment by DebugBill** [comment]
OK, I confirm I have the issue too but did not see it because the watchdog successfully restarts the hardware after 5mn inactivity .

It happens very seldom, twice this night while the system was almost idle, and none during the day. It looks like it is unpredictable and unrelated to other events (but probably isn't.... just need to find the cause)

I've added lots of debugging info to my code to track this down, but as it seems to happen only at night it may take a few days before I solve it.

**Comment by DebugBill** [comment]
I found the cause for the bug. It is not really one in fact and there is a workaround.

I'm really concerned with limiting useless databases updates as it wears off the SD card for nothing  (mine was dead after only two years). For that reason I only update data it power consumption or intensity have changed since the last update (it also allows for recalculating the alert levels). By definition, meter index changes all the time, at least because of the computer running Domoticz, so I dont consider it. I update it with the others when there is a change. If after 5mn no update happened, I update everything anyway, so you always have at minimum one update every 5mn.
Because of various delays in the code, those 5mn could sometimes be up to 5mn 20sec..... and the system would think there is a problem.

So the workaround is:
- don't sleep, switch on and off lights, coffee makers, boilers.... at least every 5 mns :-) (this explains why it only happened at night to me)
OR
- change the watchdog setting in the hardware tab for that device to 10mns.

When my latest update will be merged, the problem will disappear, but the 5mn interval will last, so leave the watchdog set to 5mns, not less.

I need to read the code for the watchdog to see if I can do better for those of you who want more frequent updates. I did not touch the part of the original code for Teleinfo that deals with it and it is still very basic (but enough for the job I thought)

**Comment by pepsi92** [comment]
Hi. Thanks for this information even if I'm not sure your workaround (the second one :) ) will fix the issue for me. Before I reduced the watchdog to 1min, it was set to 15min ... and I was facing the issue.
Nevertheless, I will follow your recommandations and set it to 10min and see what happen.

**Comment by nonolk** [comment]
Hello DebugBill,

Thank you for looking at this issue, but I think the same as pespi92, it will not solve the issue for me, I already implemented the workaround ( I set the watchdog to 1 minutes), for instance before I had not update for a complete day. because when it goes in timeout, the only thing you can do is to restart, therefore I was more thinking about a deadlock issue (or something like that).

Best regards,

**Comment by DebugBill** [comment]
Hi,

The fix is not approved yet.
Send me your email address at "debugbill at thauvin.org" so I can send you back a pre-compiled binary for Pi including it and some other improvements (details are in pull request 1440). It will be a good way for me to have them tested.
I did not have any restart for 24h with it

**Comment by DebugBill** [comment]
Nonolk, your mail system rejected my message, pretenting it is unsollicited :-)

Anyway, the fix is merged now so you should be able to download it as soon as the packages are refreshed (don't know how often that happens, but at least daily)

**Comment by gizmocuz** [comment]
it could take up to an hour

**Comment by gizmocuz** [comment]
(update should already be there... you could try Setup->Check for updates)

**Comment by nonolk** [comment]
Hello again,

Sadly it introduce a new bug, as I'm no more able to modify, neither to recreate the device, as once deleted I can't add it anymore. I can't even select the tty to listen to.

Ps, it's the same with the latest beta release.

Best regards,

**Comment by scottydj2** [comment]
Think the debug build fails due teleinfo rather than m_teleinfo1 in EcoDevices.cpp around line 446.

**Comment by nonolk** [comment]
Hello Debugbill,

Debugbill I saw it an unblocked it so I was able to test (The .gz extension is blocked by my antispam, I have to check why, as it shouldn't be).

Forget my previous statement, it was due to my browser cache :-(

Best regards,

**Comment by DebugBill** [comment]
Yes, when the GUI is modified (which it is with this patch) the cache must be refreshed. I've also noticed Domoticz sometimes fails in spotting that the cached files are obsolete. I know it it something Gizmocuz is concerned with. It would be nice (and faster) to reload only the changed files. I fear some other users will report this as a bug :-)

For line 446, you're right, it is an old DEBUG statement that I did not update after making other changes. thanks for reporting it, I will fix that.

**Comment by DebugBill** [comment]
Hi,

If the bug does not appear anymore, can you cloe the issue?

Thanks

**Comment by pepsi92** [comment]
Hi,
I cannot confirm yet it works for me as I'm waiting for an available package for Synology. Nevertheless, if you think it is fixed, ok to close the issue and if I still have the issue when I'm able to test, I'll reopen it.
Best regards,

**Comment by nonolk** [comment]
Hello Debugbill,

Sorry I was away due to professional reasons (some times the weekend is the best time to upgrade systems ;-) ) So for me it seems this issue is gone. But I noticed something strange, I had to do completely reinstall domoticz in order to be able to recreate the teleinfo devices properly.
I was able to add the hardware but the devices were never created even after several hours (I was able to add any others devices (rflink Zwave...)) But after restarting from scratch, I was able to get the teleinfo devices and everything is working properly. So please tel me if you want me to close this issue, or if you still want to keep it to trouble shoot the devices creation/update.

Best regards,

**Comment by DebugBill** [comment]
Hi,

I made a mistake sending you a binary only. As the GUI was changed too, some javascript files and index.html also needed an upgrade. I think your problem was due to the mismatch between those files. It also explains why reinstalling everything fresh solved it.

I think we can close this issue, and if needed reopen a dedicated one if the problem you described appears again.

**Comment by nonolk** [comment]
Hello DebugBill,
Ok I close this issue.

I wish you a good weekend.

**Comment by pepsi92** [comment]
Hi,
I just upgraded to 3.0.7310 (synology package from jadahl) but unfortunatly I still have the issue. After a few minutes, domoticz stop collecting the values from the teleinfo module :-(
Still the same errors in the log.
Additionally, the value displayed in the dashboard tile is now doubled for the usage value (it is displayed ok in the Utility tab).

![capture ecran 2017-04-12 a 23 10 53](https://cloud.githubusercontent.com/assets/18167025/24979733/988d9d4a-1fd5-11e7-8467-0197adb28308.png)
![capture ecran 2017-04-12 a 23 11 48](https://cloud.githubusercontent.com/assets/18167025/24979732/988d3b02-1fd5-11e7-9bd7-5b242754259a.png)
![capture ecran 2017-04-12 a 23 12 32](https://cloud.githubusercontent.com/assets/18167025/24979734/988f1a08-1fd5-11e7-9039-c7d7967a0d10.png)

Is it possible to reopen this issue or should I create a new one ?

Thanks for your help (everything was working fine before I upgraded to 3.0.72xx)

**Comment by DebugBill** [comment]
Hi,

The display issue is a different bug, I have it too but it is not linked to Teleinfo. From what I've seen, it only appears when switching to the dashboard tab and disappears at the next data update. You can open a speccific issue for this one, explaining how you get it. Attach the same screenshot.

For the Teleinfo stopping, change the watchdog to 5mn, 1mn will definitely make false positive appear.

**Comment by pepsi92** [comment]
Ok thanks. I've changed the watchdog to 5min ... will see if it fixes the issue in a couple of hours.
I do not know if it is feasible but maybe it can be a good idea to implement a constraint in the code to avoid users to use less then 5min or at least update the Wiki to add a warning about this constraint.

**Comment by pchevali** [comment]
Hi, 
I have experienced the same issue with the recent upgrade of the code. Solved it by changing the watchdog value as you said. 
However I don't think that the problem should be adressed by changing watchdog value.
As I understand the Watchdog field fills in the m_iDataTimeout variable and the Rate limit fills in m_iRateLimit. 
I think you wanted to limit maximum sample rate and minimum sample rate with these threshold. Why don't you add another field in the interface in order to define this other threshold ?
Watchdog should be kept for the case of data timeout on the input (serial input after parsing) in my opinion, at least it's displayed this way in the interface.

Thanks

**Comment by DebugBill** [comment]
Hi,

In fact I did not want to let the user input a minimum sampling rate but only a maximum (ie: m_iRateLimit). The more inputs I offer to the user the more question and misunderstanding it creates :-)
For the minimum rate I decided to base it on the watchdog value so there is no confusion; if it updates, it means it works and the watchdog is happy.
Still, for alerts I only update if there is a change. So if the value does not change for days you will not see any alert being updated. Only conters and meters are. My goal here is to limit database updates as it wears out SD cards (mine died after only 2 years)

**Comment by pchevali** [comment]
I understand your point but the drawback I have noticed is that the plot gets all messy if the interval is not 5 minutes  : 
![image](https://cloud.githubusercontent.com/assets/1221917/25393637/47d192ce-29dc-11e7-8210-e7fc34043e1e.png)

If power doesn't change ( PAPP ) then no value appears in the DB until the next change in papp or watchdog- 10ms timeout. Then the sample stored in the database is saved with counter index (total power consumption). The plot is using the index variation to draw the power consumption, resulting in gaps if there is long periods of same power consumption, and spikes just after a sample is received.
I hope I am clear enough :)

The minimum sampling time is useful to avoid killing sdcards ( although after experiencing the same problem I used tmpfs for data storage,  UPS for rapberry pi and regular backup), but if the plot expects a 5 minute sampling period, maybe 5 minute should be set as the minimum sampling period ( no more than 5 minutes between samples).
This change is aimed at fixing a low level problem( storage over activity ) by changing the sensor sampling frequency ( input), which is critical data ( well no life at stakes, but for something used for datalogging and analysis this is important).
Maybe this should be handled at storage level, by adding a layer for data compression ( no writes until a change in the value for example )  this could apply to all sensors not only this power meter which is only part of the problem ( if you divide by 2 the sampling frequency your SD card will last 4 years but if you had 4 thermometers it will shrink to 1 year). And when reading data there would not be any problem as the same layer will handle the data decompression.

As a conclusion, I think that something as to be done to preserve forward compatibility, otherwise after the next release version, many people will notice the same problem as me ( messy plot). Because the values I had before for watchdog and minimum sampling period were the default values. 

Thanks

**Comment by pchevali** [comment]
Well looking at the plot it's not that clear, but what I see is long 0 period, and then a spike in consumption, although looking at the power consumption there is neither spikes or 0 power comsumption....

**Comment by DebugBill** [comment]
Hi,

I understand what you describe even though it is not very clear on the graph. By the way, I am unable to get the same graph on my system. I don't have a HC/HP contract and on my graph the index does not show at all. Weird.
I guess i got mislead by the RRDTools behaviour where the last value will bcan be considered valid for a long time when there is no update. 
Anyway, forward compatibility can be kept. By default the max rate is set to 60sec when no previous rate has been set, and at least on my system the watchdog default value is 5mn. Also, when disabling the watchdog I fallback to a 5mn increment. It is then only if the user specifies that he doesn't care if updates are done at a lower rate than 5mn through the watchdog that I will update that slow. I guess in that case he knows what he is doing.

**Comment by pchevali** [comment]
Hi,

OK. I commented on your commit set fixing issue 1441 because this morning I noticed something else.
Due to value change monitoring ( check if PAPP change and minimum time interval above a given value ), I was still noticing spikes and holes. I have set the minimum interval to the same watchdog value and now everything is ok, as before the changes.

**Comment by DebugBill** [comment]
I'm sorry but I can't reproduce your bug, I don't even get the same graph. I've set my own system to 60 second maximum rate and 1 hour watchdog

![settings](https://cloud.githubusercontent.com/assets/25805255/25473733/deeb6892-2b30-11e7-9713-e8b2638f05c6.png)

This is an empty flat were most of the power consumption is the telecom equipment and the Raspberry :-) So it is quite steady and should generate the same issues as yours. I don't see any surges as you describe. Also on your graph there are two sets of data, index and power when I have only one. In fact I don't understand which graph you are looking at.

![graph](https://cloud.githubusercontent.com/assets/25805255/25473815/2926ed96-2b31-11e7-9b04-6dd2d7ef7634.png)

**Comment by pchevali** [comment]
Hi,

I think I am not plotting the same thing as you : 
![image](https://cloud.githubusercontent.com/assets/1221917/25474223/acc5ca36-2b32-11e7-8d39-6a793319c739.png)

This is the device on which I look at the log.
And there how it is Right now : 
![image](https://cloud.githubusercontent.com/assets/1221917/25474266/dde7e068-2b32-11e7-9746-a33170f7fef7.png)

This is this sensor : 
![image](https://cloud.githubusercontent.com/assets/1221917/25474318/130b1742-2b33-11e7-9169-a0e50bdf1a29.png)

On your plot there is "Last 7 days", and it seems to be a 24hour graph.

This is the version I am running ( I have local modifications but not on the poer meter part) : 
![image](https://cloud.githubusercontent.com/assets/1221917/25474470/a2bd6bce-2b33-11e7-8a27-a1d58657b6b6.png)

**Comment by DebugBill** [comment]
Well...... mine is the same device:
![device](https://cloud.githubusercontent.com/assets/25805255/25475003/9f1e31e0-2b35-11e7-80b9-5668cf8a5993.png)

The only difference I see is that I have no data for meter2. I need to create fake data and see if that triggers apparition of the daily usage line you have. Also the consumption is so low that it is decimal, il could be the reason I don't see the line. Maybe there is a bug in the graph display too, but I never walked this part of the code so I may not be able to fix it easily. I'll turn on the heating for a few minutes so I use at least 1kWh today.

**Comment by DebugBill** [comment]
Ok, there is a bug.... if you check "decimal" in the P1SmartMeter settings on settings tabs you get the index line printed and your strange surges in consumption.
And appart from that I don't see any difference in decimals being printed or not. I had three before, and still three after.
Try unckecking this option and you should be happier with the result... but will loose the index.

Now it needs someone to look into this area of the code which has not been designed initially for Teleinfo but for its Dutch equivalent. Risk is to break something that works for other users.

**Comment by DebugBill** [comment]
BTW, my screenshot for 7 days shows only 24hours because I used the "zoom" function

**Comment by pchevali** [comment]
I see. So there is 2 different visualisation method depending on the decimal parameter...

**Comment by DebugBill** [comment]
Looks like it, and the code in main/WebServer.cpp that produces it is quite messy. Starts at line 12686, RType_HandleGraph if you want some reading.
