### ISSUE TITLE
Avoid hardware thread stop & start sequence when changing parameters

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#1445]
Current implementation is stopping then starting the hardware thread when a parameter is modified.
This implementation is useless in some cases since the changed parameter may be changed without a restart (like a timeout for example).
This change will also avoid the hardware thread to lose its context (authentication token...)

**Comment by gizmocuz** [comment]
Well, lets say you are going to setup your hardware parameters only once, or maybe.. change them later one more time
I see no reason why not to restart, and yes, most hardware needs to be restart because of these changes
If your hardware is setup correctly, then it wont be restarted until domoticz is restarted
