### ISSUE TITLE
Please add two factor authentication (like Webmin)

### ISSUE THREAD

**Issue by pvangorp** [domoticz/domoticz#1448]
Can you please add two factor authentication like Webmin is using Google Auhtenticator. I've configured fail2ban, but after the block period, they try I again and again. I changes the port to a non-standard port instead of 443. The attacks stopped, but it's anoying to type https and the port each time.

**Comment by DebugBill** [comment]
Why don't you change the block period in fail2ban? On my system, once you're blocked, it is forever. Not going very often to Russia or China I feel the risk of blocking myself is rather limited.

From a personnal point of view, I don't want Google to know I am using Domoticz. I never use third parties authentication using Google, Facebook and others and I've stopped using some applications that were forcing me to have an account with a third party rather than a purely local one.

**Comment by pvangorp** [comment]
You've got a good point. I thought it was more secure.

**Comment by DebugBill** [comment]
And you are right, it most certainly is. It is really the privacy issue that bothers me :-)
