### ISSUE TITLE
Fail set blinds percentage in mysensors device

### ISSUE THREAD

**Issue by miguelingles** [domoticz/domoticz#1543]
Blinds percentage don't work in mysensors device. Only work up down stop.

**Comment by gryzli133** [comment]
did someone find the solution for that already?

**Comment by LemarinelNet** [comment]
I'm going to use blinds with MySensors and domoticz.
I'll test in a few days and give feedback.

**Comment by gryzli133** [comment]
Perfect! :-)

**Comment by gizmocuz** [comment]
Is this working ? Maybe an example sketch to play against could help development

**Comment by gryzli133** [comment]
Here an easy code for ESP8266 using WiFi gateway. The code is working fine for me as a dimmer instead of Roller Shutter widget. I use it now only as percentage setpoint from Dimmer. It would be nice, if I could use the UP and DOWN button, as well as the percentage setpoint in domoticz.

https://github.com/gryzli133/RollerShutter_MySensors_ESP8266_Gateway

**Comment by gryzli133** [comment]
I was testing MySensors with Domoticz's blinds widget. There is an issue with the percentage bar. I got it working, but I need two widgets:
- dimmer - to use the percentage
- venetian blinds EU - to use the close, stop and open commands
I have 25 blinds at home, so I need 50 widgets just for the blinds at the moment...

It would be great if someone could repair the blinds percentage widget for mysensors.

If someone could add also STOP button (f.e. Venetian Blinds EU Percentage), the we would have all we need to use full functionality of MySensors Blinds with Domoticz. I hope someone can help us with that issue...

Thanks in advance!

**Comment by ppenguin** [comment]
Is anybody actively working on this?
It seems to be a long-standing issue which hasn't been solved yet.
I just changed from openhab2 to domoticz but since the roller blinds are my main application for now it's kind of disappointing.
If nobody is working on this, I will try to do something...

**Comment by gizmocuz** [comment]
Did someone solved this ?

**Comment by gizmocuz** [comment]
Okey, i am going to try to implement this.

It will be based on type S_COVER which supports V_UP/V_DOWN/V_STOP and V_PERCENTAGE

I think i will have to introduce a new switch type, a blinds percentage with stop button

**Comment by gizmocuz** [comment]
Have to put this on the roadmap after a next stable release as this will need some time/testing

**Comment by ppenguin** [comment]
That would be great. And indeed the functionality with both percentage and stop would be the only sensible way IMHO (like in other systems). I had started to look at the code to do something about it, but I have been far too busy to actually get any results, and that's not likely to improve anytime soon. Hope it works out!

EDIT (16-12-2018): is there any news about this? I'm still extremely busy, and haven't really gotten into the sources, but I might find some time around Xmas but don't want to do double work... Cheers, ppenguin

**Comment by gizmocuz** [comment]
@ppenguin , if you could help with this, that would be great !

**Comment by gryzli133** [comment]
someone can help to solve that issue?

**Comment by gryzli133** [comment]
no one use mysensors to control Blinds/RollerShutter?

**Comment by ppenguin** [comment]
Sorry, must be a tough issue, I've kind of gotten used to living without %, but am sometimes quite unsatisfied with it. I haven't found any time for this and unfortunately won't in the near future, far too busy, so I think there's more chance I'll check out an alternative controller. It would cost me at least a few evenings to understand where to look (starting from zero) and a few more to implement I guess.

**Comment by gryzli133** [comment]
can someone point me to the code responsible for Blinds using MySensors? Then I will try to find why the percentage is not working. There much to much code, so starting from zero will be a never ending story ;-)

**Comment by rwaaren** [comment]
sudo grep -irn --color=auto --include \*.h --include \*.cpp blinds | grep -i sensors
at my local source clone directory give

```
hardware/MySensorsBase.h:449:   void UpdateBlindSensorLastUpdate(const int NodeID, const int ChildID);
hardware/MySensorsBase.h:454:   bool GetBlindsValue(const int NodeID, const int ChildID, int &blind_value);
hardware/MySensorsBase.cpp:505:                                         UpdateBlindSensorLastUpdate(nodeID, itt.childID);
hardware/MySensorsBase.cpp:851:                 SendBlindSensor(pChild->nodeID, pChild->childID, pChild->batValue, intValue, (!pChild->childName.empty()) ? pChild->childName : "Blinds/Window");
hardware/MySensorsBase.cpp:1099:void MySensorsBase::UpdateBlindSensorLastUpdate(const int NodeID, const int ChildID)
hardware/MySensorsBase.cpp:1193:bool MySensorsBase::GetBlindsValue(const int NodeID, const int ChildID, int &blind_value)
hardware/MySensorsBase.cpp:1467:                                _log.Log(LOG_ERROR, "MySensors: Blinds/Window command received for unknown node_id: %d", node_id);
hardware/MySensorsBase.cpp:1563:        else if (packettype == pTypeBlinds)
hardware/MySensorsBase.cpp:1565:                //Blinds/Window command
hardware/MySensorsBase.cpp:1566:                int node_id = pCmd->BLINDS1.id3;
hardware/MySensorsBase.cpp:1567:                int child_sensor_id = pCmd->BLINDS1.unitcode;
hardware/MySensorsBase.cpp:1578:                        if (pCmd->BLINDS1.cmnd == blinds_sOpen)
hardware/MySensorsBase.cpp:1582:                        else if (pCmd->BLINDS1.cmnd == blinds_sClose)
hardware/MySensorsBase.cpp:1586:                        else if (pCmd->BLINDS1.cmnd == blinds_sStop)
hardware/MySensorsBase.cpp:1592:                        _log.Log(LOG_ERROR, "MySensors: Blinds/Window command received for unknown node_id: %d", node_id);
hardware/MySensorsBase.cpp:1619:                        _log.Log(LOG_ERROR, "MySensors: Blinds/Window command received for unknown node_id: %d", node_id);
hardware/MySensorsBase.cpp:1975:                        pChild->SetValue(vType, int(blinds_sOpen));
hardware/MySensorsBase.cpp:1979:                        pChild->SetValue(vType, int(blinds_sClose));
hardware/MySensorsBase.cpp:1983:                        pChild->SetValue(vType, int(blinds_sStop));
hardware/MySensorsBase.cpp:2256:                        if (!GetBlindsValue(node_id, child_sensor_id, blind_value))
hardware/MySensorsBase.cpp:2258:                                SendBlindSensor(node_id, child_sensor_id, pSensor->batValue, blinds_sOpen, (!pSensor->childName.empty()) ? pSensor->childName : "Blinds/Window");

```

**Comment by gryzli133** [comment]
thank you, do you also know where is the part, where MySensors objects are linked to Domoticz objects? I think, there is the bug, because other types of Blinds are working (BleBox etc) but MySensors not

**Comment by gizmocuz** [comment]
As you can see the code you are looking for is inside the mysensors classes
They are small, so it should not be to hard to find out
This in combination with visual studio, setting break points, you should be able to debug your issue quickly
But it has been tested with mysensors before...
Try the mysensors boiler template code

**Comment by gryzli133** [comment]
Do you have an idea why the widget is not shown correctly? Maybe there is some correlation between the problem with logic and the GUI.

Here an example screen shot from forum - but everyone I know that was trying to use Blinds with MySensors and Domoticz have similar problem: https://live.staticflickr.com/65535/48461005176_304d621edf_b.jpg

**Comment by gryzli133** [comment]
I don't know why, but one set of my blinds is now working well with Blinds Percentage! These are the latest ones that I add in summer this year. The only problem I'm facing now is, that I cannot set Percentage from Floor plan. Because of few hundreds of smart devices, I'm forced to use them only from Floor plan. The solution with dimmer was not nice, but at least let me use them with the right symbol.

Is there a possibility to add Venetian Blinds with Percentage? Would be nice to have "stop button" also available. Sometimes it is easier to set the blinds with buttons than with slider.

**Comment by gryzli133** [comment]
Here you can easily see, that is nice to see how far they are open (inverted type -> 100% fully open). Unfortunately I cannot see now the percentage when using floor plan with Blinds symbol.

![image](https://user-images.githubusercontent.com/30415928/103282952-8f8b4f00-49d7-11eb-9d9e-1c524a540d8d.png)

**Comment by gryzli133** [comment]
Here you can see why it is difficult to control my 300m2 house without proper function in Floor plan. These are just switches, where still 50+ are not finished yet, so it will be even more later (18x boost function from Thermostat, multiple movement sensors and contactrons). 

Similar problem is with Thermostat, because I cannot set the temperature from Floor plan -> it show me the log, what actually is not so important. You will probably use the log from temperature measurement rather than from setpoint.

![image](https://user-images.githubusercontent.com/30415928/103284106-a1babc80-49da-11eb-87df-4c06ca13f0fe.png)

**Comment by gizmocuz** [comment]
How about you work with room plans ? sure when you don't filter you see all devices
(But yes, maybe we could add the percentage behind the 'Open' word ?)
Could you make a PR for this ?

**Comment by gryzli133** [comment]
Room plan is working fine, but I have more then 20 rooms / sections, so to find them in the list is involving scrolling etc. When I want to see if there is no light on, or no door/window open, floorplan is the only one way to do it in seconds, everything else increase the time and so make the sens of having smart home. I have 4 floorplans covering my whole house (Ground and second floor, garage and office), so in worst case I just check 4 screens and I know if the blinds are down, doors/windows are closed, lights off etc. And the most important case - My wife is just using the floorplan ;-)

Maybe you can change it like this:
0%      => close
1-99% => percentage
100%   => open

Or even just show percentage when the device is percentage type? Not really need the see text when seeing the percentage - this could be discussed. Of course your solution is also OK.

I'm not familiar to GitHub (just use it to share/backup my Arduino codes), never used it before, so would be nice if you could assist me or do it by yourself.

I know this is another point, but what about the issue with thermostat -> could it be possible to change the setpoint from floorplan?

Let me show you some summary about problems I'm facing with floorplan. 

At the moment the only way to use some percentage device is for me to use standard dimmer:
PROS:
- you can switch on/off just with single click
- you can select the level with slider
- you can access log and notification
CONS:
- timers are not accessible, but this is not critical - just nice to have feature and the space for that would be there
![image](https://user-images.githubusercontent.com/30415928/103286158-13e1d000-49e0-11eb-8e36-acf481a82571.png)

on the Blinds we are missing the slider:
- you can switch on/off just with single click
CONS:
- slider is missing -> you don't know the actual possition and also cannot set the position by yourself
- STOP button is missing -> even when I select venetian blinds EU there is no STOP button in the floor plan
- the best would be to have Blinds with UP/STOP/DOWN button + percentage slider -> would it be possible to have it?
![image](https://user-images.githubusercontent.com/30415928/103286199-21975580-49e0-11eb-8149-0f3153040497.png)

custom icon / other icon. For example FAN icon. You can see the value, but you cannot change it. This makes it also not usable. 
![image](https://user-images.githubusercontent.com/30415928/103286724-2c061f00-49e1-11eb-996e-08ef2f932da0.png)
![image](https://user-images.githubusercontent.com/30415928/103286803-5d7eea80-49e1-11eb-9ef6-034c9ddf421d.png)

and thermostat is the worst one, you cannot change the temoerature from the icon, it jumps to log, but there is even a separete button for log, but no way to access the setpoint...
![image](https://user-images.githubusercontent.com/30415928/103286350-50adc700-49e0-11eb-82aa-5dcc140fd818.png)

Sorry for cross/posting! Let me know if I should spread the issues for more threads or it is enough if I summarize the issues with floorplan here?

Thanks for your help! Domoticz is a really nice system, I was facing some problems at the beginning, but since last update in April the system in up and running 24/7 this is what I wannted to get -> 100% on time with my smart home.
![image](https://user-images.githubusercontent.com/30415928/103287193-265d0900-49e2-11eb-8004-d1710070ba9c.png)

**Comment by waltervl** [comment]
Tested in 2022.1. Blinds percentage shows percentage. Also able to set percentage from Floor plan.
