### ISSUE TITLE
No need to be allowed to see/edit/delete cams..

### ISSUE THREAD

**Issue by florian-guillemard** [domoticz/domoticz#161]
Hi guys,

I'm using Domoticz v2.3448 and I just found yesterday 2 bugs.

The first one is that if you create an user who is viewer or user or admin, well everyone can see/edit/delete cams with the url:

---

http://192.168.X.X/#/Cam
or
http://www.your-domain.com/#/Cam

---

You can have the data in JSON too:

---

http://192.168.X.X/json.htm?type=cameras
or 
http://www.your-domain.com/json.htm?type=cameras

---

Is everyone as this problem ?

It would be nice if we can choose the "Actives menu" for "Cam".

There is a variant of this problem.
If you don't have give access in "actives menu" to Lights/Temp/Weather..., the users can use the URLs /#/LightSwitches or even /#/Users

I hope there will be a fix..

**Comment by gizmocuz** [comment]
Thanks for reporting!

Fixed in beta #3452, if you see more that needs to be changed, please submit a git pull request with the needed changed.

Not fixed, when a user has no Lights in the activate tabs, he can still call it, if he knows how.
Dont think this is a bad security issue, but you could change this (code fix) in app.js if you like
