### ISSUE TITLE
Domoticz Python Plugin System to support asynchronous calls?

### ISSUE THREAD

**Issue by Hedda** [domoticz/domoticz#1620]
Is it possible to have Python plugins in Domoticz support async calls?

See dicussion: https://www.domoticz.com/forum/viewtopic.php?f=65&t=17312

**Comment by chrysn** [comment]
As the library author of aiocoap which Hedda is presumably trying to run, let me elaborate in brief what would be needed to support the library in a plugin:

aiocoap needs to wait for different kinds of events: name resolution, socket activity (not only received packages, but also ICMP messages), and timeouts. As I understand the [plugin architecture](https://www.domoticz.com/wiki/Developing_a_Python_plugin), the plugin code can only run when an event gets along, and those events are exclusively those that happen due to activity of the underlying transport.

This mechanism *could* be extended to allow registering timer callbacks, to open server sockets, to receive ICMP messages, but unless Domoticz aims to become an operating system, I wouldn't go that route. (Plus it'd still need considerable adaptation on the Python side).

As asyncio main loops are complex, platform dependent, and thus tricky to integrate into an existing main loop, I think the best way forward would be to allow plugins to spawn a thread, to open their own sockets using Python primitives as they seem fit, and to provide one way for the thread to notify the main thread that it should please process pending C++ API calls. That approach would allow both blocking plugins and asyncio plugins (which would just start up an asyncio main loop in their own thread).
