### ISSUE TITLE
Event Editor cursor out of sync Beta v3.8337

### ISSUE THREAD

**Issue by corbinmunce** [domoticz/domoticz#1774]
http://192.168.5.28:8080/#/Events
Using dark-th3me

Trying to edit a script, and the cursor position on screen is not lining up with the actual cursor position when typing.

If I disable this in custom.css, looks to fix:
`font-family: Ubuntu !important; */`

**Comment by gizmocuz** [comment]
you need to use the default theme, or the dark-theme needs to be fixed (see the styles folder, you might need to import a css stylesheet)

**Comment by gerard33** [comment]
This was caused by the Ace editor not being able to show the Ubuntu font correctly (it can only show monospace fonts).
Due to the GUI work changes the Events page now can also be changed with themes. As my dark-th3me has a standard Ubuntu font, that font is also applicable for the code editor, which won't work.

Made a fix for this with PR #1785.
