### ISSUE TITLE
Since 3.8360 Totally none (http?) external connection/services possible/working

### ISSUE THREAD

**Issue by freemann** [domoticz/domoticz#1782]
Since Version 3.8360 my instance isn't sending Email/GCM notifications.
Further investigation (log and wan/wifi check) shows that my wan/wifi is working properly and domoticz log shows all kind of (http) connection errors.

for more info see;
http://www.domoticz.com/forum/viewtopic.php?f=6&t=19085

issues with;
1. SMTP
2. GCM
3. NetAtmo
4. ThermoSmart
5. DarkSky
6. NMA
7. Evohome 
8. Nest
9. Toon
10. ICY Thermostat

Looks like the following is working;
- WeatherUnderground
- Logitech Harmony
- Philips Hue Bridge

Hope you guys can fix this soon 👍

**Comment by harryd100** [comment]
Not completely true, when compiled from source V3.8363 there are no problems

**Comment by freemann** [comment]
also see this Thermosmart topic with a (probably) related/same issue;
http://www.domoticz.com/forum/viewtopic.php?f=6&t=19103

**Comment by freemann** [comment]
3.8367 same issues:
![screenshot - 26_08_2017 10_04_20](https://user-images.githubusercontent.com/601053/29739766-13da4338-8a46-11e7-8e47-e1a04e6efa2c.png)


Some system info;

> Linux raspberrypi 4.9.35-v7+ # 1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

> Linux version 4.9.35-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) # 1014 SMP Fri Jun 30 14:47:43 BST 2017

> No LSB modules are available.
> Distributor ID: Raspbian
> Description:    Raspbian GNU/Linux 8.0 (jessie)
> Release:        8.0
> Codename:       jessie

Rpi is recently (today) updated to latest packages/kernel.

**Comment by anconakip** [comment]
Toon also no connection.....

**Comment by GJRos** [comment]
Pushover is also not working. Log output testing pushover.

2017-08-26 16:26:55.831 Error: Pushover:
2017-08-26 16:26:55.831 Error: Notification sent (pushover) => Failed

**Comment by BUSHA** [comment]
Telegram notifications via HTTP doesn't work too.

**Comment by freemann** [comment]
Back on the latest stable(Build Hash: 494fff7,Build Date: 2017-07-30 12:19:41 V3.8153) and everything is running great again 👍 

💘 domoticz!

**Comment by Haringstad** [comment]
Adding to the list: No connection with the EvoHome plugin (http api Honeywell)

**Comment by harryd100** [comment]
>Already reported in the first post

**Comment by xbeaudouin** [comment]
@Haringstad I have 3.8360 on production box at home on FreeBSD (my own FreeBSD port) and EvoHome, Netatmo and Darksky are perfectly working. Maybe the issue is somewhere else.
Maybe this related to my transparent proxy at home ?

**Comment by harryd100** [comment]
@xbeaudouin, as mentioned in the second post, if you compile from source you are save

**Comment by JurikRistjouw** [comment]
@freemann thanx, for now also back to release. instant connect....

@gizmocuz  I see what you mean there... same screen
![image](https://user-images.githubusercontent.com/8580506/29788333-7cf32a2c-8c32-11e7-8a44-2f489e16907b.png)

**Comment by gizmocuz** [comment]
Setting up a new build system, this time no 'apt-get distupgrade' but a new fresh 'strech' install

**Comment by JurikRistjouw** [comment]
@gizmocuz Great! can you let me know when i can update and test again with the new build?

**Comment by heggink** [comment]
did the new beta fix this?

**Comment by BUSHA** [comment]
@heggink nope. Main suggestion in our case - downgrade to stable.

**Comment by anconakip** [comment]
Correct. I am downgraded to the last stable and everything works again.

**Comment by heggink** [comment]
np, compiled myself so everything fine. just curious if this was resolved and I can revert to regular updates.

**Comment by JurikRistjouw** [comment]
@heggink not fixed in latest beta as of yet. Also waiting to get back in the beta loop.

**Comment by peliilep** [comment]
Maybe not that relevant for everyone, but API calls (HTTP) to api.pilot.patrickferreira.com (pilot app on iOS) are also not working.

**Comment by JurikRistjouw** [comment]
correct me if i am wrong, but my guess is that every API with external references are not working due to recompilation in a new build environment. Some magically introduced bug has appeared. As @heggink and @gizmocuz have stated and found out that the source is not the problem.

**Comment by gizmocuz** [comment]
Correct.. no idea yet what is wrong

**Comment by djvdorp** [comment]
I am seeing similar issues with my Nest running latest beta:

```
2017-09-01 22:42:45.154 Nest: Worker stopped...
2017-09-01 22:42:45.154 Nest: Worker started...
2017-09-01 22:42:51.649 Error: Nest: Error login!
```

Via: https://www.domoticz.com/forum/viewtopic.php?t=19126
Via: http://www.domoticz.com/forum/viewtopic.php?f=6&t=17085&start=20#p148741

I read on the wiki that it is possible to downgrade from **beta** to **stable**, but I don't want to lose the _my.domoticz.com_ access and would prefer to help solving, is there a starting point where one would suggest to begin looking, or is is possible to get some debug or more verbose logging info enabled?

**UPDATE:** downgrading to stable (v3.8153) still supports _my.domoticz.com_ and works well.

**Comment by JurikRistjouw** [comment]
@gizmocuz anything I can do? Besides setting up a working buildserver... I would like to help out, but have no clue on where to start helping you with the buildserver (is there a wiki page?). I also have a 1gbit centos server i could use to distribute and host some stuff.

**Comment by gizmocuz** [comment]
Its weird... i just wrote a small test application on the same RPi where domoticz does not correctly make HTTP connections anymore, using the same HTTPClient class.... and the test application worked.
I am now debugging domoticz, addeed a HTTP GET at the start of the application, see if that works... something is different.... something has screwed up since updating to raspbian stretch and linking openssl statically, but that linking should not make a difference since the curl library is all it's needed for http calls...

**Comment by gizmocuz** [comment]
if i just do a HttpClient::GET right after the main application entry, it fails...hmmm

**Comment by gizmocuz** [comment]
Okey, i get this curl response code back: "CURLE_OUT_OF_MEMORY" ....just a simple HTTPS get request... hmmm.. remember, same class i used in my previous test project...

**Comment by gizmocuz** [comment]
HTTP works, i think i know whats going on...

**Comment by pierrenicolasr** [comment]
Which version of openssl are you linking against ?

**Comment by gizmocuz** [comment]
Check:
- Curl is initialized with 'curl_global_init(CURL_GLOBAL_ALL);', so with the OpenSSL part => OK
- Tried disabling SSLv3 with curl_easy_setopt(curl_, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2)); => No fix

So i think this is the root cause: (linking twice to OpenSSL now)

https://curl.haxx.se/mail/lib-2008-01/0160.html

Since raspbian Stretch, the openssl library is not installed, and version 1.1 is the default. before on jessie (and older) we used 0.1 (dynamically linked)
Now OpenSSL is statically linked.
I suspect we link the dynamic lib, and the static lib now, and two contexts are created and this will fail inside curl (see link above)

Might be caused by 'libcurl4-openssl-dev' ... 

Now building a test without static linking openssl (CMake -DOPENSSL_USE_STATIC_LIBS=No option)

**Comment by gizmocuz** [comment]
Now i receive the following warnings:

> [ 22%] Linking CXX executable domoticz
> /usr/bin/ld: warning: libssl.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libssl.so.1.1
> /usr/bin/ld: warning: libcrypto.so.1.0.2, needed by /usr/lib/gcc/arm-linux-gnueabihf/6/../../../arm-linux-gnueabihf/libcurl.so, may conflict with libcrypto.so.1.1
> [100%] Built target domoticz
> 

BUT... the HTTPS call succeeded .... so it is definitely related to static linking openssl, and probably by double linking against the openssl library

**Comment by gizmocuz** [comment]
Somehow the executable depends on both openssl versions now:

ldd ./domoticz | grep ssl
        libssl.so.1.1 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1 (0x76e5b000)
        libssl.so.1.0.2 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.2 (0x7682d000)

**Comment by MAkerboom** [comment]
My private compiled and working version doesn't:

$ ldd ./domoticz | grep ssl
        libssl.so.1.0.0 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.0.0 (0x76bd5000)

**Comment by gizmocuz** [comment]
At the moment i am building from scratch, and also using libcurl static... takes 2 hours... see how that goes
@MAkerboom, whats your build system ?

**Comment by gizmocuz** [comment]
(And try building without static openssl and LDD again)

**Comment by MAkerboom** [comment]
RPI 2
Raspbian GNU/Linux 8.0 (jessie)

**Comment by gizmocuz** [comment]
Yes, jessie... thats the issue, we are on Stretch now...

**Comment by heggink** [comment]
Just so I understand, domoticz DOES support stretch ie I can upgrade jessy with no issues? I did see some libssl (1.0.0) issues being reported by people on stretch. Seems awfully related ;-)

**Comment by JurikRistjouw** [comment]
very nice! hope to see it all working again soon :)

**Comment by gizmocuz** [comment]
OK... i give up... spent hours on this... we need to link libcurl and openssl statically ... can't get that to work... keep getting 'undefined reference' errors
Maybe we should ship the openssl 0.1 library  with the executable ? But that would be very lame... 

Hope someone else can find a way... the final binary needs to be tested on clean raspbian jessie and stretch

**Comment by xbeaudouin** [comment]
@gizmocuz okay (I'll have to find a RPI3 with free space). Or make a cross compilation stuff...
Just a small question, why do we need libssl.so.1.1 ? (I am not sure of that).

**Comment by matteos1** [comment]
also i've rpi 3 and the error for me is on netatmo station

**Comment by gizmocuz** [comment]
Okey... going back to normal linking openssl...
Everyone who wants to use the feature updates should install libssl 1.0.0 via 'sudo apt install libssl1.0.0'
Building domoticz from scratch now on a new build platform (found a arm system that is much faster then the raspberry pi 3, so hopefully once done and tested on a jessie platform (and stretch) i can confirm all is working OK and can close this issue.
Stay tuned...

**Comment by ultrara1n** [comment]
Fingers crossed 🤞

**Comment by gizmocuz** [comment]
Unfortunately it seemed to work.. but now i want to install libssl 1.0.0 on a raspbian stretch.. and it does not know the package....

**Comment by Dylantje** [comment]
did you do a dist upgrade?
My Rpi:
`pi@raspberrypi:~$ sudo apt-get install libssl1.0.0
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd
De status informatie wordt gelezen... Klaar
libssl1.0.0 is reeds de nieuwste versie.
0 pakketten opgewaardeerd, 0 pakketten nieuw ge▒nstalleerd, 0 te verwijderen en 6 niet opgewaardeerd.
pi@raspberrypi:~$
`

**Comment by freemann** [comment]
Here also checked on Jessie:
pi@raspberrypi:~ $ sudo apt-get install libssl1.0.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl1.0.0 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $

**Comment by gizmocuz** [comment]
so both of you are able to run the latest beta ?

This is my output:

> pi@raspbuild:~/domoticz $ sudo lsb_release -d ; sudo apt-get dist-upgrade ; sudo apt-get install libssl1.0.0
> Description:    Raspbian GNU/Linux 9.1 (stretch)
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Calculating upgrade... Done
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package libssl1.0.0 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libssl1.0.0' has no installation candidate
> 
> 

Now i was able to copy/paste the required libraries (libssl and libcrypto 1.0.0) from another system and was able to launch domoticz... but this is not the way of coure..
Also in the install script (sudo line) we can not depend on libssl1.0.0 i suppose...

**Comment by MAkerboom** [comment]
sudo apt-get install libssl1.0.0 -t stretch-backports

May be?

**Comment by Dylantje** [comment]
Did ./updatebeta

`Restarting Domoticz... (please standby...)
[....] Restarting Domoticz Home Automation System: domoticz/home/pi/domoticz/domoticz: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory
 failed!
`
Still error

**Comment by Dylantje** [comment]
MAkerboom:
`pi@raspberrypi:~$ sudo apt-get install libssl1.0.0 -t stretch-backports
Pakketlijsten worden ingelezen... Klaar
E: The value 'stretch-backports' is invalid for APT::Default-Release as such a r                                       elease is not available in the sources
pi@raspberrypi:~$ sudo apt-get install libssl1.0.0 -t stretch-backports
`

**Comment by Dylantje** [comment]
Gizmocuz:
Update to release is working...
`Restarting Domoticz... (please standby...)
[....] Restarting Domoticz Home Automation System: domoticz2017-09-09 14:28:12.763  Domoticz V3.8153 (c)2012-2017 GizMoCuz
2017-09-09 14:28:12.787  Build Hash: 494fff7, Date: 2017-07-30 12:19:41
2017-09-09 14:28:12.790  System: Raspberry Pi
2017-09-09 14:28:12.792  Startup Path: /home/pi/domoticz/
domoticz: Domoticz is starting up....
. ok
`
And the beta still not..

**Comment by Dylantje** [comment]
@ gizmocuz u can use my system like before,,,

**Comment by gizmocuz** [comment]
@MAkerboom well i can do this:

```
wget http://ftp.nl.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
```

but i can not put this in the install script

@Dylantje , what raspbian version do you have ? you can try 

`sudo apt-get libudev-dev`

**Comment by Dylantje** [comment]
`pi@raspberrypi:~$ sudo apt-get libudev-dev
E: Ongeldige operatie libudev-dev
pi@raspberrypi:~$ sudo apt-get install  libudev-dev
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd
De status informatie wordt gelezen... Klaar
libudev-dev is reeds de nieuwste versie.
0 pakketten opgewaardeerd, 0 pakketten nieuw ge▒nstalleerd, 0 te verwijderen en 6 niet opgewaardeerd.
pi@raspberrypi:~$
`
My system:
Linux raspberrypi 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l

**Comment by gizmocuz** [comment]
@Dylantje , do a 
sudo lsb_release -d

**Comment by Dylantje** [comment]
sorry... noop here :-)
  Debian GNU/Linux 7.11 (wheezy)

**Comment by gizmocuz** [comment]
wheezy ? that is even before jessy which is before stretch
You also have some pending updates, you can try to do a 
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

But maybe backup first

**Comment by Dylantje** [comment]
E: Some index files failed to download. They have been ignored, or old ones used instead.
pi@raspberrypi:~$ sudo apt-get upgrade
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd
De status informatie wordt gelezen... Klaar
0 pakketten opgewaardeerd, 0 pakketten nieuw ge▒nstalleerd, 0 te verwijderen en 0 niet 
pi@raspberrypi:~$ sudo apt-get dist-upgrade
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd
De status informatie wordt gelezen... Klaar
Opwaardering wordt doorgerekend... Klaar
0 pakketten opgewaardeerd, 0 pakketten nieuw ge▒nstalleerd, 0 te verwijderen en 0 niet opgewaardeerd.
pi@raspberrypi:~$

Still got:
 Debian GNU/Linux 7.11 (wheezy)

Can i not upgrade to stretch with the cli?

**Comment by gizmocuz** [comment]
@Dylantje , you can try this:

```
wget http://ftp.nl.debian.org/debian/pool/main/s/systemd/libudev1_234-3_armhf.deb
sudo dpkg -i libudev1_234-3_armhf.deb
```

**Comment by Dylantje** [comment]
Error:
`pi@raspberrypi:~$ wget http://ftp.nl.debian.org/debian/pool/main/s/systemd/libud                                                                                                                                                             ev1_234-3_armhf.deb
--2017-09-09 15:21:15--  http://ftp.nl.debian.org/debian/pool/main/s/systemd/lib                                                                                                                                                             udev1_234-3_armhf.deb
Herleiden van ftp.nl.debian.org (ftp.nl.debian.org)... 130.89.149.21, 2001:67c:2                                                                                                                                                             564:a120::21
Verbinding maken met ftp.nl.debian.org (ftp.nl.debian.org)|130.89.149.21|:80...                                                                                                                                                              verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 119658 (117K) [application/x-debian-package]
Wordt opgeslagen als: 'libudev1_234-3_armhf.deb.2'

100%[======================================>] 119.658     --.-K/s   in 0,07s

2017-09-09 15:21:15 (1,70 MB/s) - ''libudev1_234-3_armhf.deb.2'' opgeslagen [119                                                                                                                                                             658/119658]

pi@raspberrypi:~$ sudo dpkg -i libudev1_234-3_armhf.deb
(Database inlezen ... 61186 files and directories currently installed.)
Voorbereiden om libudev1:armhf 234-3 te vervangen (door libudev1_234-3_armhf.deb                                                                                                                                                             ) ...
Uitpakken van vervangende libudev1:armhf ...
dpkg: dependency problems prevent configuration of libudev1:armhf:
 libudev1:armhf is afhankelijk van libc6 (>= 2.17); maar:
  Versie van libc6:armhf op dit systeem is 2.13-38+rpi2+deb7u12.

dpkg: error processing libudev1:armhf (--install):
 vereistenproblemen - blijft ongeconfigureerd
Fouten gevonden tijdens behandelen van:
 libudev1:armhf
pi@raspberrypi:~$
`

**Comment by gizmocuz** [comment]
@Dylantje 
maybe easier to backup the domoticz folder, install the latest raspbian, copy the folder back (and startup script and possible udev rules)...
But start with a full sd card backup so you can always go back

**Comment by molusk** [comment]
@Dylantje you should upgrade your raspbian instead of playing Frankenstein ;-)
If your raspberry is only running Domoticz, it should be fine. If you run something else, please check it is fully compatible with Jessie or Stretch before upgrading.
Anyway, backup your configurations.

Then edit /etc/apt/source.list and replace every occurrence of wheezy by jessie or stretch.
Run apt update, then apt upgrade and finaly apt dist-upgrade.
This can be very long.

You can also follow @gizmocuz and go for au fresh install.

Anyway, thank's @gizmocuz it works very well now !

**Comment by Dylantje** [comment]
what do i need to edit here??
edit /etc/apt/source.list

Will try this first

**Comment by darkrain-nl** [comment]
> what do i need to edit here??
edit /etc/apt/source.list
Will try this first

Please be carefull, doing this may result in a fresh install anyway, I have tried this on two device and both failed and needed a fresh install...

The latest Domoticz beta is working well for me by the way, Raspian Jessie.

**Comment by Dylantje** [comment]
brick or not...:-)
When i try this i learn something :-)
New install is simple...

Only some more work.. [ do not have a lot time this weekend

**Comment by molusk** [comment]
@Dylantje as I said, put jessie instead of wheezy in /etc/apt/source.list (once per line)

Maybe you should do it in 2 steps : wheezy to jessie (update, upgrade and dist-upgrade), check everything works fine and then jessie to stretch.

**Comment by JurikRistjouw** [comment]
jessie here also and working with the new beta 🥇 Thanx guys

**Comment by freemann** [comment]
Just updated to 8390 and my Domoticz is sending emails again and until i'm not seeing any http related errors. Will test for a couple of days and after that close this issue.

Thanks for fixing guys!!!! 
Have a nice sunday!

**Comment by pierrenicolasr** [comment]
+1 just updated, seems to work. Yay !

**Comment by matteos1** [comment]
Not work netatmo

**Comment by matteos1** [comment]
Now Also netatatmo work

**Comment by Dylantje** [comment]
dear all
Fresh install:
`pi@raspberrypi:~ $ sudo lsb_release -d
Description:    Raspbian GNU/Linux 9.1 (stretch)
`
Only still no running domoticz:
`pi@raspberrypi:~ $ sudo service domoticz.sh status
* domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Mon 2017-09-11 22:05:11 CEST; 32s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1595 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 1607 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

sep 11 22:05:10 raspberrypi systemd[1]: Starting LSB: Home Automation System...
sep 11 22:05:11 raspberrypi domoticz.sh[1607]: /home/pi/domoticz/domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared
sep 11 22:05:11 raspberrypi systemd[1]: Started LSB: Home Automation System.
`
Did try the:

`pi@raspberrypi:~ $ wget http://ftp.nl.debian.org/debian/pool/main/s/systemd/libudev1_234-3_armhf.deb
--2017-09-11 22:07:40--  http://ftp.nl.debian.org/debian/pool/main/s/systemd/libudev1_234-3_armhf.deb
Herleiden van ftp.nl.debian.org (ftp.nl.debian.org)... 130.89.149.21, 2001:67c:2564:a120::21
Verbinding maken met ftp.nl.debian.org (ftp.nl.debian.org)|130.89.149.21|:80... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 119658 (117K) [application/x-debian-package]
Wordt opgeslagen als: 'libudev1_234-3_armhf.deb.1'

libudev1_234-3_armhf.deb.1            100%[======================================================================>] 116,85K  --.-KB/s    in 0,07s

2017-09-11 22:07:40 (1,60 MB/s) - ''libudev1_234-3_armhf.deb.1'' opgeslagen [119658/119658]

pi@raspberrypi:~ $ sudo dpkg -i libudev1_234-3_armhf.deb
(Database wordt ingelezen ... 128289 bestanden en mappen momenteel ge▒nstalleerd.)
Uitpakken van libudev1_234-3_armhf.deb wordt voorbereid...
Bezig met uitpakken van libudev1:armhf (234-3) over (234-3) ...
Instellen van libudev1:armhf (234-3) ...
Bezig met afhandelen van triggers voor libc-bin (2.24-11+deb9u1) ...
pi@raspberrypi:~ $
`
Reboot the system...
Only no Domoticz @ port:ip

**Comment by gizmocuz** [comment]
Is that the stable or the beta?

**Comment by Dylantje** [comment]
Started with the release i think. When i use the bash script.
That was not working
Did ./updatebeta and also not working

**Comment by BadFoo** [comment]
Dylantje, you are not alone ;)
I also tried with a fresh Stretch install this weekend and had the same problem as you.
unfortunately I did not have time to investigate further.

**Comment by gizmocuz** [comment]
could you start domoticz by hand so you know what is causing the issue ?

cd domoticz
./domoticz

**Comment by BadFoo** [comment]
restarted from scratch, Raspbian GNU/Linux 9.1 (stretch)
installed domoticz with:
"sudo curl -L install.domoticz.com | bash"
then did an ./updatebeta
Had to install "libssl1.0.0_1.0.1t-1 + deb8u6_armhf.deb"
Then ldd shows no missing dependences.
starting domoticz by hand just gives: "Illegal instruction"
Not very helpful, is there a way to make it more verbose?

**Comment by gizmocuz** [comment]
@badfoo what type of hardware?

**Comment by BadFoo** [comment]
Found the verbose flag, still same output: Illegal instruction

**Comment by BadFoo** [comment]
Raspberry 1b+

**Comment by Dylantje** [comment]
bussy @ work.. Sorry no time to test Gizmocuz
@ the weekend 
me a rpi B
https://www.sparkfun.com/products/retired/11546

**Comment by BadFoo** [comment]
Ran with gdb, although without any symbols, but still...
This is what I could get:

Program received signal SIGILL, Illegal instruction.
0xb6e73b10 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0

**Comment by BadFoo** [comment]
Never mind, that seems to be normal behaviour for openssl
https://bugs.launchpad.net/raspbian/+bug/1154042

**Comment by gizmocuz** [comment]
Else i could revert to raspbian jessie (and see if we can fix it for stretch), but in the end, these problems will rise again

**Comment by Dylantje** [comment]
did have some time...
New setup stretch install
Use the install script from the wiki.
Installer works fine.
Pi says working:
`pi@Slave:~ $ sudo service domoticz.sh status
* domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Wed 2017-09-20 19:36:33 CEST; 1min 17s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2289 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 2299 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

sep 20 19:36:33 Slave systemd[1]: Starting LSB: Home Automation System...
sep 20 19:36:33 Slave domoticz.sh[2299]: /home/pi/domoticz/domoticz: error while loading shared
sep 20 19:36:33 Slave systemd[1]: Started LSB: Home Automation System.
pi@Slave:~ $
`
Only when i see the webui in my browser..
Domoticz offline.. :-(

Perhaps other options found for this??
Or gizmocuz you can use my system to test and look for solutions

**Comment by gizmocuz** [comment]
try a

cd domoticz
./updatebeta

**Comment by Dylantje** [comment]
did update to the last beta
webgui says error

CLI:
`domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Sat 2017-09-23 13:19:55 CEST; 1min 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1835 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 1845 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

sep 23 13:19:55 Slave1 systemd[1]: Starting LSB: Home Automation System...
sep 23 13:19:55 Slave1 domoticz.sh[1845]: /home/pi/domoticz/domoticz: error while loading shared libraries: libssl.so.1.0.0:
sep 23 13:19:55 Slave1 systemd[1]: Started LSB: Home Automation System`
 I run:
Raspbian GNU/Linux 9.1 (stretch)

**Comment by Dylantje** [comment]
mmm is there no one else with problem with stretch???

Or do i need to flash jessie?

**Comment by molusk** [comment]
No issues here with stretch.

```
$ dpkg -l | grep libssl
ii  libssl1.0.0:armhf                  1.0.1t-1+deb8u6                   armhf        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.2:armhf                  1.0.2l-2                          armhf        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:armhf                    1.1.0f-3                          armhf        Secure Sockets Layer toolkit - shared libraries
```

What did you change between your configurations 6 and 3 days ago ?
6 days ago, the service was starting and the issue may have been an error on the port you were trying to access (8080 by default but you may have changed it in your previous config and forget to change it back to that one in your new install).

**Comment by BadFoo** [comment]
@Dylantje It looks like you are missing the ssl lib.
Try:
wget http://ftp.nl.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_armhf.deb

I have not been able to start domoticz on stretch, get illegal instruction :(
@molusk Care to share the steps you took to get it working (on a fresh stretch install)?
If I do "dpkg -l | grep libssl" I get the exact same output as you.

**Comment by Dylantje** [comment]
mmm  
Did try to install @ Badfoo 
No errors etc. Reboot, only no working Domoticz with webgui:

` domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Wed 2017-09-27 18:54:15 CEST; 2min 35s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 385 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/domoticz.service

sep 27 18:54:14 slave systemd[1]: Starting LSB: Home Automation System...
sep 27 18:54:15 slave domoticz.sh[385]: Illegal instruction
sep 27 18:54:15 slave systemd[1]: Started LSB: Home Automation System.
pi@slave:~ $
`
RPI says domoticz is working, only no webui...


@ molusk:
`pi@slave:~ $ dpkg -l | grep libssl
ii  libssl1.0.0:armhf               1.0.1t-1+deb8u6              armhf        Se                                                   cure Sockets Layer toolkit - shared libraries
ii  libssl1.0.2:armhf               1.0.2l-2                     armhf        Se                                                   cure Sockets Layer toolkit - shared libraries
ii  libssl1.1:armhf                 1.1.0f-3                     armhf        Se                                                   cure Sockets Layer toolkit - shared libraries
pi@slave:~ $

`
Is this correct?

**Comment by BadFoo** [comment]
@Dylantje 
Ok, so now you also get "illegal instruction". Welcome to the club ;)
I dont think domoticz is working, thats why you have no web ui.
If you run htop you should see something like ".../domoticz -www" around the top of the list. I suspect you dont.
Also if you start domoticz manually, like: 
cd domoticz/
./domoticz
You will probably get "illegal instruction"

Am I right? If so then we have 2 "stretch" systems setup from scratch with the same error. I wonder what @molusk did to get his system working.

**Comment by gizmocuz** [comment]
I would undo this openssl lib installation and first try building domoticz by hand
there is an excellent tutorial on our wiki that i always use on new (build) systems
this you should get started

**Comment by Dylantje** [comment]
Rob,

I did the wiki with the bash script.... before i install the openssl lib
And that was not working.....

I think i have to go back to jessie?
i try 4-5 times with different ways....
Also the manual way without the script... 

No luck...
I did this truc with wheezy more then 10 times, for my friends... and my slave
Only with stretch i cannot get it to work grrr..

**Comment by Dylantje** [comment]
mmm 
Will try to make my slave working, stretch is no option.
So is there a place where i can download Jessie?
The place where i can find raspian for rpi, is only stretch to find.

Or are there more os for the rpi what will work with Domoticz..?

**Comment by Dylantje** [comment]
Tsja...
Did try the system work with dietpi....[ jessie based ] [ perhaps set to standard gizmocuz, is a clear setup for more hardware devices ]
I do the bash install version, looks ok without errors
When i install domoticz looks everything ok:
https://drive.google.com/file/d/0B75a4ntvk2vkVlNwUFhIM2N4LTg/view?usp=sharing
Only the icon on the left upper corner is strange:
https://drive.google.com/file/d/0B75a4ntvk2vkTnNHMmdCSmJZMWs/view?usp=sharing
When i add sensors, strange to:
https://drive.google.com/file/d/0B75a4ntvk2vkcUFQLW5BQUgxb1U/view?usp=sharing
And:
https://drive.google.com/file/d/0B75a4ntvk2vkaXJKSDZ5eTFMaXM/view?usp=sharing

Only the system is running stable.
Now i update to the latest beta:
`root@DietPi:~#  sudo service domoticz.sh status
* domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh)
   Active: active (exited) since zo 2017-10-01 13:46:02 CEST; 1min 0s ago
  Process: 2043 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 2075 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

okt 01 13:46:02 DietPi domoticz.sh[2075]: Illegal instruction
okt 01 13:46:02 DietPi sudo[2057]: pam_unix(sudo:session): session closed for user root
okt 01 13:46:02 DietPi systemd[1]: Started LSB: Home Automation System.
okt 01 13:46:02 DietPi systemd[1]: Started LSB: Home Automation System.
`
Katsheng.... not working any more... 👎 

So there is something else wrong then stretch i think??
Only are there no more people that have problems?

**Comment by BadFoo** [comment]
maybe too late but anyway...
You can find Raspbian Jessie here:
http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/

**Comment by freemann** [comment]
For me and I think for most people this issue is solved.
For people with still simular issues; please open an new issue with a detailed description.

Thanks guys!

**Comment by gizmocuz** [comment]
It is still a big issue... and i am trying to get it to work with a static linked openssl/crypto library... problem is, compiling takes 1 hour during each test
