### ISSUE TITLE
AreWeInLocalNetwork and Nginx

### ISSUE THREAD

**Issue by NewFolk** [domoticz/domoticz#1823]
Hello,
Looks like function AreWeInLocalNetwork 
in [cWebem.cpp](https://github.com/domoticz/domoticz/blob/1b19fd0d1b58e08342a03ec3e31e20825f8dee43/webserver/cWebem.cpp#L1131) works only with local proxy server.

I have Nginx as reverse proxy and configuration like

proxy_pass https://192.168.1.10:443; #DomoticzIP
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;

And settings Local Networks (no username/password):
127.0.0.1, 192.168.1.*

It does not ask password without depends if Im logging from intranet or from internet.

if I disable Local Networks settings in logs I see `Login successful from 192.168.1.1 for user 'XXXX'` #Router with Nginx

**Comment by gizmocuz** [comment]
In the latest commit i moved the code
could you try removing the following line in

cWebemRequestHandler::handle_request

remove:
if (session.remote_host == "127.0.0.1")

**Comment by gordonb3** [comment]
You wouldn't want to do that. This would allow anyone to spoof IP addresses by simply setting the appropriate proxy headers. What you need to do is replace the hardcoded localhost IP with the one belonging to the host that runs your Nginx server. Preferably this should be a configurable value in the settings screen.

**Comment by NewFolk** [comment]
Yes, this will be a great option.

**Comment by gizmocuz** [comment]
if the original socket is received on the localhost (127.0.0.1) which can not be spoofed by a header, we check for the existence of the NGINX header that is added in the NGINX (server) configuration file
I do not believe this is a header anyone can add right ?

**Comment by gordonb3** [comment]
In essence anyone can add any header. We actually do that ourselves in various parts of the code to pass authentication keys etcetera. This is why you want to limit which callers may define another origin and possibly bypass authentication by doing so.

However by hardcoding the localhost address this limits the possibility of running a front end web server to be on the same machine as Domoticz only. By allowing a different IP address to be specified here one can offload the Nginx service and any other pages served by it (e.g. Wordpress) to different hardware without breaking logging functionality or authentication.

**Comment by gizmocuz** [comment]
Sorry i was not talking about http headers but the headers that have to be manually added to the nginx configuration file like you can see above
Surely i would suspect nginx would filter out fake nginx headers as well?

**Comment by gordonb3** [comment]
Those are not different from any other http header. It is therefore impossible to tell from any received http package where those headers were set and if they are legit.

**Comment by vzorge** [comment]
I am having the same issue, my nginx is not running on the same server as my domoticz.

Could it be an idea that you can supply what IP is your nginx server, if any. Instead of hardcoding it to 127.0.0.1, maybe make it a setting. Perhaps just on the server itself at first in some script?

Or perhaps make the check like this:
Do normal check as is, if the result of AreWeInLocalNetwork is true, only then check if there is a header like X-Real-IP and if so, alter the AreWeInLocalNetwork check based on that header.
This way, spoofing a header can never make it pretent you are in the local network. It can only make it appear as if you are not.

**Comment by gordonb3** [comment]
Just checking - does current beta solve this issue for you?

**Comment by vzorge** [comment]
Unfortunately no.
If I check cWebem.cpp line 1142 (sorry linking does not seem to work right now) I see that it still checks if host == 127.0.0.1 before checking for a proxy. This does not take this new function into account. And since my proxy server is on another server, it does not work.

**Comment by gordonb3** [comment]
You're in the wrong branch. `master` is the `stable` version (3.8153). You need to get into the `development` branch for beta. Current beta will require you to specify the address of your proxy server(s) in the settings page, even if it is localhost.

**Comment by vzorge** [comment]
Then I will need to look further why it did not work. I will check more tomorrow

edit: Turns out the SD card on my pi is corrupt and after every reboot it resets all data. So this may be why I could not get it to work. Going to get a new SD card and do a fresh install of domoticz and will check back once I have that all done.
