### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by heggink** [domoticz/domoticz#1955]
From oct 20th to Nov 9th, my memory usage for the domoticz process was VERY stable. As of Oct 9th, it's starting to gradually go up. Not as bad as with the Blockly leak but around 1.7% per day. I updated a couple of times to new beta's (currently on 8740) but the increase remains (last update 17th).
![domo_mem](https://user-images.githubusercontent.com/3987735/33038088-ce53ee5e-ce33-11e7-8c25-bca609499ece.jpg)

http://www.domoticz.com/forum/viewtopic.php?f=6&t=19186&p=158521#p158521 references this although I am not sure this is a fair representation of facts (too many different betas).

**Comment by Siewert308SW** [comment]
Could it be that something has been changed so the old fix for has been killed.
https://github.com/domoticz/domoticz/commit/d7841bbfc83e7ebf951eb708a92297f237ca992e

Struggling with this issues for a longtime until this https (ssl) thingy popped up in my mind.
To check if https is the issue again i disabled it a few hours ago.
It is to early to say but maybe this issues popped up again but for now the memory curve looks stable but will report tomorrow about my findings.
![chart_mem1](https://user-images.githubusercontent.com/25230393/33095419-e6a13a68-cf03-11e7-832a-70a3c27f4f49.png)

**Comment by Siewert308SW** [comment]
Over a period of 12hr memory increased from 7.1 after reboot to 7.55%.
So it didn't increased that fast before i disabled https.
Still to early i think to make any conclusions, for now i will let Domoticz run and see if it stabilizes. 
Will report after work tonight...

**Comment by Siewert308SW** [comment]
Quick report,
Memory has increased since 6am this morning from 7.55% to 7.98% thats aprox 10hr
Mean while i'm installing the latest Domoticz beta (same as daily driver) on my 2th Pi3.
Will let it run clean without scripts and such to see how that goes...

**Comment by LemarinelNet** [comment]
Here is my contribution after almost 48H of memory tracking.
I'm on DEBUG build, and the memory usage is also growing, but it seems to grow by step every hour !?

![domoticzmemory](https://user-images.githubusercontent.com/10656218/33162142-206e2308-d028-11e7-8e23-77159578a1f9.png)

I'm letting this continue to grow, and will report later.

Edit : The first "big" grow on 21/11 20h00 is because of activation of xiaomi-robot plugin. I'm trying to disable it to check if memory continues to grow or settles...

**Comment by Siewert308SW** [comment]
For now still testing on two systems.
One system is my daily driver with a Domoticz 3.8742 beta version.
Other system i use for pihole now also contains a bare Domoticz 3.8742 beta version.

My daily Pi3 i only use Lua, Bash and some python scripts.
I don't run any python plugins but did install the libpython3. to get rid of the annoying error saying no libs found.
Also https has been disabled.
As you can see in the screenshot below the memory still increases every hour.
![chart-mem4](https://user-images.githubusercontent.com/25230393/33179924-5c86e33c-d06b-11e7-82ba-e836a732187d.png)

Bare system only contains Domoticz and didn't install libpython3.
Also https has been disabled but eventsystem is enabled.
This system has been stable regarding the memory for 20hr, one rise is seen but thats do to me.
![chart-mem_pi2](https://user-images.githubusercontent.com/25230393/33179941-68022b54-d06b-11e7-8faf-48957a6295a7.png)

Now on my bare test system i installed the libpython3.
Will see tomorrow morning how this goes.
If all goes well then i continue with other new settings or events to see if it affects the memory.

Current System:
![schermafdruk 2017-11-23 16 31 01](https://user-images.githubusercontent.com/25230393/33183602-c222ad68-d078-11e7-8a91-10e077ee199e.png)

Edit:
@gizmocuz 
I know it's to early to say something about this.
But i just noticed that the memory increases after installing libpython3. which also activates the plugin system...
See the screenshot below, at 4pm i installed libpython3. at my test Pi then rebooted and memory is rising.
Bare system has no scripts and such, it as clean as it can be.
![chart-mem_pi3](https://user-images.githubusercontent.com/25230393/33184170-9836d418-d07b-11e7-8a1b-8e5890eb328c.png)

Edit2:
Maybe i cheered to early.
Looks like my test system runs with a stable memory usage.
While my daily driver system without libpython3. still has increasing memory.
For now i keep my mouth shut until i find the cause...

**Comment by Siewert308SW** [comment]
@gizmocuz 

Maybe someone with some more experience can take a look at this. 
I have two screenshots.
As you can see that when the plugin system is enabled then memory starting to increase while there aint no scripts in the plugin folder.

1. My daily Pi3 without Libpython3.
![chart-mem5](https://user-images.githubusercontent.com/25230393/33196745-8a454162-d0e1-11e7-8a34-81b9d9629f74.png)

2. My test bare Pi3 with libpython3.
![chart-mem_pi4](https://user-images.githubusercontent.com/25230393/33196757-9304de66-d0e1-11e7-80ef-1676b813f773.png)

After work this evening i will report the memory usage again...

**Comment by Siewert308SW** [comment]
After a closer look on both my system it looks like the culprit isn't the libpython3. install
Both system do have a increase in Memory usage.
But the test Pi3 didn't increase that fast as it isn't running any scripts.
For now i disabled the event system on my test Pi3 to see what happens in the upcoming hours.

edit:
10min after i disabled the event system i already see a drop in memory usage.
It dropped from 5.89 to 5.6% and still decreasing.
Take in mind no scripts running.

edit2:
After a few hours without the event system enabled the memory dropped even more till 4.9% and is now running stable.
Will let it run overnight and see what happens.

But someone with more experience do have to look where the culprit is.
As on even a bare system without scripts the memory increases and decreases then run stable if the eventsystem is disabled.

**Comment by gizmocuz** [comment]
Are you sure this is not 'cached' memory ? (And this will be purged when needed by the system)
Do you have any python scripts ? Maybe instead of disabling the whole event system (re)move those scripts so we can be sure it is python related ?

**Comment by LemarinelNet** [comment]
On my Stable version of domoticz, the memory usage is flat and stable at 1.9% since 5 days (since I launched it !).
No python scripts involved...

**Comment by heggink** [comment]
No python in use here. Doesn't look like cache. If it was then putting stress on the system would release it which is not happening (tried it). Also, there is a distinct difference in behaviour before and after Oct 9th (for me at least, since I don't update every day, any issue may have been introduced before). Unfortunately, I cannot disable events since this is my live system :-(.

**Comment by Siewert308SW** [comment]
Not at home right now.
But disabled a few scripts on my daily system. 
And memory seems to be stablelized. 
Looks like updating devices by curl http json make the memory increasing

**Comment by gizmocuz** [comment]
And this in case with Python, or also when you use Lua ?

**Comment by heggink** [comment]
In the process of doing some more testing. I have 2 systems: main domo with most devices and lots of external scripts updating using curl (largely bash) and a slave (meterkast, p1 smartmeter and a few others) with few updates. slave system memory very stable where main keeps increasing. Just created a dummy switch on my slave which I update constantly to see what the mem usage does. Since then, memory has started to gradually increase as well (after 3 hours by nearly 1%). Putting some stress on the system did not lower domoticz usage (so seems to be real, not cache) but not an academic conclusion (I'll drop cache in a bit to see). So far, first conclusion is that the http calls indeed increase mem usage.

**Comment by heggink** [comment]
indeed, memory slowly increases. dropping cache (echo 3 > ../drop_caches freeing page cache inodes and dentries, thought I would never use it but helpful now) does nothing so stays at the same (ie not a cache issue).

**Comment by Siewert308SW** [comment]
@gizmocuz 
No matter what script, Lua, bash or python.
All http calls in any script causes the increase of memory used by Domoticz.
If i remove those scripts then the memory doesn't increase and stays stable.
Tested on both my Pi3 (jessie) with Domoticz 3.8747.

On my test system without scripts the memory stays stable.
If i insert a script Lua, bash or python which contains a http call then the memory starts to increase.
Do i remove those scripts then the memory is stable again and even decreases overtime.
 
Domoticz current Memory usage with scripts using http calls
If hit shift-m in top then Domoticz is on top of everything ;-)

 1177 root      20   0  254608  20732  12960 S   1.3  2.1  23:42.10 domoticz

**Comment by gizmocuz** [comment]
If you are calling a json command directly, it also increases ? Do mind we store 300 log lines at max. This could increase the memory slightly
When you create a crontab that updates a temp sensor every minute, you will see a big increase after 24 hours ? (not running any other scripts)

Then it looks like an issue in the web server that had some updates recently...

**Comment by Siewert308SW** [comment]
Yep...
Do keep in mind have set my short log to 1 day.
But for example i use chopperrob his presence python script.
Also a bash to update a virtual text device.
A bash to update virtual devices regarding my PIco UPS to keep track of battery voltage, temp and such.
All virtual devices are updated by a json call and do increase the memory.

I know the log has 300 lines and can increase the memory.
But after 24hr the log should have reached his max 300 lines, right.
After that the memory still increases.
Haven't tested in long term like a week, but 50% total free mem left if i do "free -h" after 24hr is a bit to much.
Memory usage in Domoticz is at that time approx 8% and started from 4%.
And no sighs of stabilization just a increase.

**Comment by szczukot** [comment]
I see this same behavior:
![image](https://user-images.githubusercontent.com/10205661/33391157-7654e800-d538-11e7-8f4f-fa91fad400b2.png)

**Comment by Siewert308SW** [comment]
@szczukot 

Also caused by scripts using http calls to update virtual devices and such?
Does it also stays stable if you disabled or remove those scripts?

Hope someone is busy looking into it ;-)

**Comment by heggink** [comment]
I took a quick look at the code but, since my coding days are 25+ years back, I don't trust myself making these kinds of adjustments and get away with it. Fact that I stopped at C (no C++ skills at my end) also doesn't help so hopefully gizmocuz has time to look at it.

**Comment by szczukot** [comment]
YEs, i think script is problem.
I added a only one script a few months ago.
![image](https://user-images.githubusercontent.com/10205661/33396673-947a49c2-d549-11e7-8845-25b177a1ce00.png)
Earlier I don't see problem

**Comment by LemarinelNet** [comment]
Hi,

I did a test on an empty raspberry Pi B (512MB)
Only domoticz is running on it (latest beta version)
Only 1 hardware device defined (Dummy with 1 device : Percentage)

On the same RPi : a bash script running outside of domoticz, calling json update of the percentage device every second.

Here is the  result of almost 48 hours :

![chart](https://user-images.githubusercontent.com/10656218/33398647-fab61fbc-d54f-11e7-8000-d400272f8f74.png)

**Comment by travellingkiwi** [comment]
Assuming that graph is MemTotal - MemFree (And I admit I haven’t looked to see how it’s calculating the memory %’ge internally), Can you do a 

cat /proc/meminfo 

on that rip? We should be able to confirm then if the memory is being used by an app, or it’s just buffers/cache (Which is technically used but it’s just a buffer for disk and file IO and it's normal to grow to fill the memory that isn’t being used for anything else).

What you really want to graph is MemTotal - MemAvailable. MemAvailable being the amount of memory available for starting new apps without swapping.


H

**Comment by LemarinelNet** [comment]
That graph is obtained from : 

top -b -n1 | grep "domoticz" | awk '{print $10}'

So, If i'm not too bad on unix, we get the list of processes : 
top -b (batch mode) -n1 (number of iterations, only one)
grep... get the line concerning domoticz,
awk : get only the 10th field, which is %MEM

According to "man top" :  
%MEM  --  Memory Usage (RES)
           A task's currently used share of available physical memory.

So it should mean that domoticz is  using more and more of the available phys memory...

**Comment by travellingkiwi** [comment]
Not doubting, But am I looking at the same thing?

I can’t find any code in the domoticz sources that does a top (That graph is the Motherboard memory graph from Domoticz right?)… A quick grep through the code reveals about 6 lines where ‘top’ and ‘domoticz’ exist and they’re all comments with URL’s in them

I can however find the HardwareMonitor code that computes % memory used as Total - Free. Which will give you a bad result as it doesn’t take into account the Buffer & cache.



H

**Comment by heggink** [comment]
Not sure I understand the concern: I also tested this on my slave ras-pi and saw the mem increase. Looking at the linux process stats, I record mem in use. Dropping the cache did not change it's mm usage at all and it kept increasing. There is definitely a mem increase going on and it is related to calling the webserver (http calls to domoticz). Or am I missing the point here? Happy to look at sys mem and cache as well (I use my own tracking and update domoticz myself outside of motherboard sensors and use meminfo for that).

**Comment by LemarinelNet** [comment]
There is no code in domoticz which retrieves the used memory. My percentage virtual device representing the used memory is updated via a batch call.
This %MEM is obtained by the command line top -b -n1 | grep "domoticz" | awk '{print $10}' and then sent to domoticz via json API.

Just to narrow a bit the problem : I do the same on my "production" RPI : domoticz STABLE version, many devices, many JSON updates, but memory usage is still very constant and flat .
The problem was introduced between stable and beta versions.

**Comment by szczukot** [comment]
Maybe find bad commit.
I know - log time needed :(

**Comment by Siewert308SW** [comment]
Any idea how to solve or how to dig into this issue?
Unfortunately i don't have any C or C++ skills so i'm can't be helpful there.

For now i disabled all bash scripts which used to do update some virtual devices by http calls.
I only let Chopperrob presence detection python script running as i need it to ;-)
For now my bare RPi3 with same specs as my production Pi3 only no scripts still stable while my production Pi3 memory increases.

Maybe a stupid action from my side but i always disable all logs in /etc/rsyslog.conf
So don't know the exact cause but after 3 days continues running i discovered the day before yesterday my Pi3 was shutdown.
I did noticed by the mem graph that the Pi was shutdown due to out of memory so as it seems as there was non left.

As for this afternoon i'll be off for two days so i will disable Chopperrob presence detection python script.
And see what happens when i get home Monday morning.

Only stuff that will be running are:
1x Bash to scrap data from weatherunderground devices and write to txt file
1x python script to auto tweet weather txt file every hour
1x bash script which makes 3 times a day a backup of all my scripts, db and Domoticz main worker file
And off cource all my 23 Lua event scripts ;-)

**Domoticz Mem% after 10hr**
![chart](https://user-images.githubusercontent.com/25230393/33512678-2571ad0c-d735-11e7-9ae5-d79a0e81a9fa.png)

**Domoticz  Process Usage after 10hr**
![chart1](https://user-images.githubusercontent.com/25230393/33512684-40fd9a36-d735-11e7-8ccc-f417a09bf9b9.png)

**Domoticz top (shift-m) after 10hr**
![schermafdruk 2017-12-02 07 08 39](https://user-images.githubusercontent.com/25230393/33512709-7169d91e-d735-11e7-8440-943b66dff244.png)

**Raspberry specs**
![schermafdruk 2017-12-02 07 11 45](https://user-images.githubusercontent.com/25230393/33512714-9523926e-d735-11e7-81df-0548e30c4316.png)

**Comment by Siewert308SW** [comment]
Back home and here are some stats from both my Rpi3 systems.
Both systems stats are recorded in about 30hr

**Raspberry Pi3 with only domoticz and no scripts:**
![schermafdrukpihole](https://user-images.githubusercontent.com/25230393/33525629-fa94cede-d833-11e7-9c90-d2e72f4acca8.png)

![chart_pihole1](https://user-images.githubusercontent.com/25230393/33525640-33e5023a-d834-11e7-9446-8018b0eff206.png)

![chart_pihole2](https://user-images.githubusercontent.com/25230393/33525644-3928da8c-d834-11e7-8cf2-1ee74f49e1a1.png)

**Raspberry Pi3 with domoticz and scripts (production system:**
![schermafdrukdomoticz](https://user-images.githubusercontent.com/25230393/33525652-5b0258a4-d834-11e7-9b04-33cea5a6f9d5.png)

![chart_pi1](https://user-images.githubusercontent.com/25230393/33525662-83bacf92-d834-11e7-9d4a-c28d7edd85e1.png)

![chart_pi2](https://user-images.githubusercontent.com/25230393/33525664-8b3707c2-d834-11e7-9f9c-b28f20379c1a.png)

I know these stats can't point to a specific culprit.
But it shows that there is something not right, as both systems do have a increasing memory usage.
If i only could point or know where to look would help.
 
After doing a Domoticz update by ./updatebeta the Process Usage dropped.
![chartpi4](https://user-images.githubusercontent.com/25230393/33525713-861d3904-d835-11e7-8dbb-06a9c2d4d821.png)

**Comment by jvandenbroek** [comment]
It most likely has something to do with this patch: https://github.com/domoticz/domoticz/pull/1905
I've profiled it with valgrind and there are indeed memory leakages in the webserver code, but it's very hard to debug this patch since it's a really big one. If this can't be fixed easily, we might need to consider reverting (again) this patch @gizmocuz ?

**Comment by Siewert308SW** [comment]
@jvandenbroek could be indeed, but could it be that there is something else as well or the issue in there for a longer period say before the patch?
As this issue does exist longer then that patch.

**Comment by jvandenbroek** [comment]
Well not according to @heggink , his graph clearly shows an increase on Nov 9, also not updating his beta daily, this seems to be most likely cause if this specific issue. Yours might be different.

**Comment by Siewert308SW** [comment]
Could be indeed, then first see if the TP his issue is solvable then see if it's also the culprit on my side.

**Comment by jvandenbroek** [comment]
To be sure, I've compiled and profiled before and after and indeed, it does confirm my assumption:

Commit https://github.com/domoticz/domoticz/commit/84486bcdb9f2bf363aacbf4f873a1db809a59b8b:
```
==10434== LEAK SUMMARY:
==10434==    definitely lost: 16 bytes in 1 blocks
==10434==    indirectly lost: 0 bytes in 0 blocks
==10434==      possibly lost: 7,224 bytes in 13 blocks
==10434==    still reachable: 333,698 bytes in 202 blocks
==10434==         suppressed: 0 bytes in 0 blocks
```


Commit https://github.com/domoticz/domoticz/commit/9636378bc492c2602c5e0402e4e28df0f77d8fe8:
```
==13401== LEAK SUMMARY:
==13401==    definitely lost: 33,928 bytes in 158 blocks
==13401==    indirectly lost: 5,024 bytes in 157 blocks
==13401==      possibly lost: 7,224 bytes in 13 blocks
==13401==    still reachable: 331,826 bytes in 180 blocks
==13401==         suppressed: 0 bytes in 0 blocks
```
'Stresstested' with @dannybloe 's integration test under dzVents/runtime/integration-tests
Don't worry about the 1 lost block or possibly lost ones, that's Python and doesn't seem to increase.

**Comment by SargonofAssyria** [comment]
In my case the memory leakage became visible on the 31 of august when I updated to the last stable

**Comment by rkluwen** [comment]
What if you run valgrind with --leak-check=full.
Does it give any pointers? (pun intended)

**Comment by Siewert308SW** [comment]
~~How do i call valgrind to monitor Domoticz?
 sudo valgrind /etc/init.d/domoticz.sh --leak-check=full~~

Thx for the answer guys...

**Comment by jvandenbroek** [comment]
@rkluwen ~~https://pastebin.com/T0d8VB15~~
Oops, compiled wrong branch, will post a new one, hold on ;)

Ok, here is the full summary: https://pastebin.com/7x1bNVk5 (including Python, but those don't increase on usage).

**Comment by Siewert308SW** [comment]
@jvandenbroek 
How do get/call those valgrind reports?

**Comment by Siewert308SW** [comment]
Just curious.
Want to help where I can. 
But waiting 3 days for anwser on how to get those reports by valgrind is a bit to much in my opinion. 

No where on the internet is stated how to get leak report for Domoticz.
So I'll ask once more if it's still needed and helps to solve this memory leak issue. 
What is the exact ssh valgrind command to get those reports.

**Comment by rkluwen** [comment]
Thanks, Joost.

Apologies I don't check these Domoticz e-mails that frequently. But in 
your pastebin, I see some server-side code that I will be sure to check.

Cheers,

Rene

------ Origineel bericht ------
Van: "Joost van den Broek" <notifications@github.com>
Aan: "domoticz/domoticz" <domoticz@noreply.github.com>
CC: "rkluwen" <rene@kluwen.com>; "Mention" <mention@noreply.github.com>
Verzonden: 6-12-2017 14:43:01
Onderwerp: Re: [domoticz/domoticz] Memory leak? (#1955)

**Comment by Siewert308SW** [comment]
Cmon guys, wth is going on?
Feeling ignored here, at this point I can't help or deliver stuff so others can fix. 
Two weeks waiting for a answer which I asked several times is to much. 
Why isn't there anyone willing to guide someone who wants to help but don't have the tools or 100percent knowledge. 
I'm not a total noob, only asked if something can't be found in the internet. 
It ain't the first time and always gave the benefit of the doubt.
What me stings more is that's always a user error. 
See you domoticz, was fun the past two years.

**Comment by gizmocuz** [comment]
I can't help you with this, but here a screenshot of my latest memory usage running the latest version.
It seems 'cache' and it seems it gets cleared over time:

![image](https://user-images.githubusercontent.com/2265299/33837289-2641bf52-de8c-11e7-98c6-87bf3c7c7108.png)

you might have to use valgrind (but i have no experience)

**Comment by Siewert308SW** [comment]
@gizmocuz 
Don't know whats different on your side.
But on my side it aint cache as it isn't cleared and after aprox 40hr the memory gets full and system crashes completely.
A clean/bare domoticz (no scripts) will take week before it crashes.
@jvandenbroek already pin pointed the commit patch which probably is the culprit.

As for Valgrind, as my previous post already stated.
I asked a few time how to do a propper valgrind but after weeks no reply.
And it aint the first this is happening to me for two years now.
So got a bit fed up and started to look for alternatives as i feel ignored.
This way i can't be helpfull with debugging and learning how to debug.

**Comment by heggink** [comment]
It's definitely NOT cache since forcing rasbian to drop cache does NOT clear it and domoticz process memory keeps increasing over time (I measure the domoticz process memory specifically and update a virtual switch in domoticz).
I updated to the latest beta yesterday and will let it run for a couple of days again and report back. A bit busy at the moment but if nothing changes, I'll buy a separate rpi3 and build a test system specifically for this. Won't have that done before year end unfortunately so any help from others is appreciated (@jvandenbroek @rkluwen ).

**Comment by gizmocuz** [comment]
@Siewert308SW, my systems runs now for a long time (weeks) if you look at the memory graph you do see that it drops back...
I'm sorry i can't help you with valgrind, i have to google this also

**Comment by heggink** [comment]
[valgrind.zip](https://github.com/domoticz/domoticz/files/1555859/valgrind.zip)
Just ran a test on my ubuntu box. compiled domoticz with Debug, created 2 dummy switches (one on/of and one percentage). WIth bulk on/off updates, memory creeps up and is not released when the system is told to drop cache. Then ran the same test under valgrind (attached the zip in case anyone wants to take a look). Will go through the results myself later.

**Comment by LemarinelNet** [comment]
The biggest lost memory that valgrind did find seems to be due by line 143 : 
https://github.com/domoticz/domoticz/blob/development/webserver/server.cpp#L143

The most strange is that this file did not has so many changes in last commit from nov. 3...
I didn't digged in the code, but this kind of memory lost is due to objects getting instanciated , with no pointer to keep a reference to it, so the code is not able to destruct it later...

it would be easy to point that the web server is leaking memory  : just do a bash "infinite loop" which calls domoticz JSON api, and we should see the memory growing quickly !

**Comment by Siewert308SW** [comment]
@gizmocuz 
Whats so different to your system as you don't have the issue and we all do?
As for valgrind, yep google it, no info on what the exact ssh command is to monitor Domoticz.
Seems all others in this thread can or know what they are doing but refuse the answer.

@heggink 
Want to ask you how to do a valgrind on domoticz?

@LemarinelNet 
Could it be this issue crept in way earlier then the 3th of Nov.
As we are and report memory issues way back since late 2015.
And as some do not suffer and others do it could become a problem with certain scripts.

**Comment by heggink** [comment]
@Siewert308SW I just compiled with Debug (cmake -DCMAKE_BUILD_TYPE=Debug .) installed valgrind and ran:
valgrind --leak-check=yes ./domoticz

redirected the output and deleted domoticz from that (deleted lines starting with "2017-12-13" in vi).

**Comment by LemarinelNet** [comment]
I'm also surprised to know that this leak is soooo old !
I'm using the stable version on my "production pi" without any visible leak, but on a "test pi", just running a "curl" or "wget" command every second on domoticz json did show a big leak after 2 days...

**Comment by gizmocuz** [comment]
@LemarinelNet 
The handle_accept function (the line with 'new') is there for a long long time... Strange that this now shows a memory leak
It's kind of like the boost example
http://www.boost.org/doc/libs/1_39_0/doc/html/boost_asio/example/http/server/server.cpp

@Siewert308SW 
I think this is because i do not use the web interface that much.
All is automatic in domoticz, only one external call from the local Alexa client
That is why i do not experience this memory leak. Also when i use the web interface, it is minimum, checking some graphs, doing some work for 5 minutes and thats it...
I do not have a script that requests a new page and closes the connection (because we try to keep the connection open)

**Comment by gizmocuz** [comment]
@heggink 
If you want to compile in DEBUG mode, you have to issue 'cmake -DCMAKE_BUILD_TYPE=Debug .'

**Comment by heggink** [comment]
@gizmocuz sorry, that's what I did. wrong copy/paste
corrected

**Comment by heggink** [comment]
Any clue on a possible solution then? I'm just an old C programmer (remember kernighan & ritchie?) who has no clue on C++ and went into sales :-). Love to help out more but this is as far as I feel comfortable.

**Comment by gizmocuz** [comment]
i suspect a problem maybe here
https://github.com/domoticz/domoticz/blob/development/webserver/connection.cpp#L32

A solution... hmmm first i would like to know if you are using an external script/device that calls domoticz that often to causes the system to run out of memory. If yes, what is it ?
I am not good in scripting (sorry!) could you post a script that calls domoticz in a loop that causes the memory issue ?
Partly reverting the websocket implementation in the server part should solve the problem, but i would like to test some things before doing so (like shared pointers instead of using 'new', or trying to place a 'delete' somewhere)

**Comment by LemarinelNet** [comment]
@gizmocuz  It seems that the boost example isn't complete, since it does allocate/instanciate new objects, without managing a pointer on them. This actually leads to memory leaks. 
The more you call the http server, the more the memory is allocated and never freed, so the leak occurs...

Seems to be the same issue that is frequently when you search for "boost server memory leak" on google.
One example here, https://stackoverflow.com/questions/41934622/memory-leak-in-boost-asio-async-tcp-echo-server-example 
perhaps an idea to follow : http://www.technical-recipes.com/2011/using-smart-pointers-to-avoid-memory-leaks/

@heggink in C++, when you use classes, you then instanciate objects which are "kind of structs". You can ask the computer to instanciate an object with the `new` keyword. It then make a reservation of some memory needed by the object, and returns a "pointer" to the memory location which has been allocated.
It's like the "malloc" you should already know.
But, when you have finished using this object, it's up to the developper to free this allocated memory, by calling "delete" on the pointer. This tells the system that you don't need anymore the memory that has been allocated before, and the system is told that it can use it for something else.
In this case, it could be that the "new" keyword is used to instanciate a new connection object, but the pointer is never stored, and so we don't have a track to delete it later....
I don't have enough time at the moment to check further, but it seems to be this, as valgrind is saying...

**Comment by LemarinelNet** [comment]
@gizmocuz I think the first thing to try, to be sure that the websocket iimplementation is our guilty, would be to check-out the code just before this commit, then compile it, and stress-test the webserver part with curl or wget. 
A simple bash script would be for example : 

```
#!/bin/bash
while :
do
	curl -s "http://yourDomoticzIP:8080/json.htm" >/dev/null
done
```

Beware that this script will run as many http calls as it can, and so can lead to server and/or client crash !! Do it on a test environment !
PS : if you can compile a RPi debug binary of some code before websocket implementation, I can stress-test it...

**Comment by heggink** [comment]
that's exactly what I did: while loop with a curl to localhost.

**Comment by gizmocuz** [comment]
Thanks for the script...
The websocket implementation is not in the current stable release. So it should be easy to say if this is causing the problem

**Comment by gizmocuz** [comment]
Okey, a quick profiling in Visual Studio in combination with the script also reveals that the most memory is indeed allocated by
https://github.com/domoticz/domoticz/blob/development/webserver/connection.cpp#L32

the 'new' line is also new in the beta version (as is of course the websocket part)

I will first send an email to the creator of the pull request (it would be great if we got websockets working!)

**Comment by heggink** [comment]
@gizmocuz I have just started the same test on Stable. Still interested or shall I abandon it?

**Comment by gizmocuz** [comment]
@heggink sure i am interested to see a confirmation that it does not happen in the stable ! ;)

**Comment by heggink** [comment]
It's been running for a while now with no increase at all so, so far so good. Just tried to access the domoticz log for the switch to see how many updates it did. Apparently so many that it's became completely unresponsive ;-) before giving me the result: >77K switches (on-off) with no loss of memory so far.
106K and no increase. Stopped as off to Star Wars movie.

**Comment by SargonofAssyria** [comment]
May I bring to your attention that I discovered a memory leak when I switched to the latest stable on my production system where I run only stable versions.
See; https://www.domoticz.com/forum/viewtopic.php?f=6&t=19186&p=160721&hilit=memory#p160721

**Comment by rkluwen** [comment]
I made a pull request to address this issue.

**Comment by LemarinelNet** [comment]
I'm not sure to understand why websockets have to do with json calls ?
If I'm not wrong, websockets are used on the "dashboard", i.e. the web U.I ?

So do the JSON api has something to do with websockets ?

**Comment by gizmocuz** [comment]
Pull request has been merged and this indeed seems to solve the problem.
@LemarinelNet , @heggink  is it possible you could verify this ?

**Comment by heggink** [comment]
So that requires me to pull the latest beta, recompile and test? Happy to do so. Cannot commit to a time today but will try asap.

**Comment by gizmocuz** [comment]
Correct, at the moment i am building the arm 32 and 64 builds and those should be available online after an hour (building takes a looooong time)

**Comment by heggink** [comment]
Running the test on Ubuntu now. Will report back in an hour or 2.

**Comment by Siewert308SW** [comment]
@heggink
Thx for the info. 
Can't test the memory leak fix right now. 
Won't be home earlier then Saturday

**Comment by heggink** [comment]
After more than 2hrs of testing, memory stable at 0.4%. Tried to see how many switches the dummy device did but that locks up both chrome and edge for over 30 mins. Suspect at least a few 100.000 switches so looks like we are good to go. Thanks all for resolving this issue especially @rkluwen .
@SargonofAssyria can I suggest you open a separate bug request to track your issue wrt Stable?

**Comment by LemarinelNet** [comment]
Would be interresting to have a new valgrind report of this stress-test...

**Comment by heggink** [comment]
Will facilitate as soon as I find some time.

**Comment by heggink** [comment]
[valgrind2.zip](https://github.com/domoticz/domoticz/files/1559511/valgrind2.zip)
This hasn't run for long but definitely looks a lot better.
We can **close** this, agree?

@gizmocuz when do you expect the rpi binary ready?

**Comment by LemarinelNet** [comment]
Well, looks waaaaay better !
16 bytes lost instead of 16MB !
it seems ok to me !

**Comment by jvandenbroek** [comment]
Great to see this being addressed, thanks @rkluwen , looks good now!

**Comment by heggink** [comment]
Closed

**Comment by gizmocuz** [comment]
Thanks all for testing !

**Comment by heggink** [comment]
![mem](https://user-images.githubusercontent.com/3987735/34056129-23152e4c-e1d2-11e7-8731-4890564c657d.jpg)
Nice :-)

**Comment by Siewert308SW** [comment]
Hope to find the other issue.
I know it does increase a bit as the log is filling up with 300lines.
Got home earlier and updated my clean Rpi3 (no scripts and such) just a bare Domoticz installation.
Done nothing and see what happend.
Will let it run the entire weekend to see what happens.
![chart](https://user-images.githubusercontent.com/25230393/34056411-2fd7308e-e1d3-11e7-9255-b37dc54b997b.png)

Keep in mind it's just Domoticz, no scripts no nothing and OS does nothing or i didn't instruct it to do something.
