### ISSUE TITLE
Feature Request: Python Plugin Extra information

### ISSUE THREAD

**Issue by imcfarla2003** [domoticz/domoticz#1993]
Can I ask that we get a few more variables passed through to the python plugin

We could do with:
Domoticz["Runtime"].Revision - this would return the revision number of the build of Domoticz
Domoticz["Runtime"].Port - this would return the port the web interface is running on
Devices[unit].SwitchType - this would allow to distinguish the different types of switches easily

Justification:
The new Devices[unit].TimedOut parameter is available from (I think 8651) but to be able to identify if it is available you have to call back into Domoticz to get the Revision.  But to call back into the web interface you need to know what port it is running on. So we need the second parameter.

These could be added to the 'Settings' dictionary but i think it would be worth creating a new 'Runtime' dictionary

Maybe include everything returned by /json.htm?type=command&param=getversion

**Comment by febalci** [comment]
May i kindly add also the folder information for the "Custom" webpages (www/templates folder)? So that the plugins may export additional information required like image or table or whatever as a custom webpage. Since the location of templates folder differs according to the OS and platform, it is not efficient and true to use '../../../www/templates' instead of '/usr/local/domoticz/www/templates'.

Please note that the location for the templates folder is different in Synology, raspberry and windows..

**Comment by gizmocuz** [comment]
Please use our forum
