### ISSUE TITLE
Memory leakage!

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#2000]
After upgrading from latest stable to beta v. 3.8789 there is still memory leakage.
The previous problem with Websocket might be solved, but there is still an other one.
My System:
Version: 3.8789
Platform: Linux domoticz 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
Plugin/Hardware: Raspberry PI 3 with RFXCOM, RazBerry, etc....
Using dzVents with several scripts, all kind of bash scripting to update for instance my APC UPS sensors.
Al you can see from the year graph it started with updating to the latest stable on the 1 aug 2017
Normally I logrotate every day and restart Domoticz, for not getting out of memory.

I have a slave system, which is still on version V 3.8153, with less scripting and devices.
The memory leak is present there too, its less but still there.
The slave has only RFLink as hardware and P1 Smart Meter, and some virtual hardware for Weather etc...

This is the script I use to get the memory use of Domoticz:
ps aux|grep "domoticz/domoticz"|grep -v grep| awk '{print $4}'

![2017-12-17_11-06-29](https://user-images.githubusercontent.com/24824113/34078456-10d38716-e31b-11e7-9d74-f60ec60355c0.png)

**Comment by gordonb3** [comment]
That's not how you measure such a thing. It is normal for a process to gradually build up its physical memory usage as the Operating System does not grant an allocation request until the process actually starts using it. What you need to monitor if you suspect a memory leak is the virtual memory size (VSZ) which is the total memory that the process claims.

**Comment by bizziebis** [comment]
So it's normal for Domoticz to grow 18MB in memory each day? I also noticed the memory leak which was not there in the last stable, but got introduced with the websockets, and got semi-solved with a recent patch.

**Comment by gizmocuz** [comment]
The websocket leak I found has been patched which is one step closer in the right direction
It was also not complicated to find thanks to the help here with the bash script
And the use of the memory profiler on visual studio
Anyone including you can also perform these steps to hunt for additional problems (even if you do not have Windows you can use virtualbox.. all software is free to test)

**Comment by SargonofAssyria** [comment]
You can discuss the way the measurement is done. Fact is that Domoticz is eating up memory which eventually end up with an out of memory ergo crash or lockup of the system. This memory leakage is not due to Websockets, but is introduced between that latest 2 stables as you can see from the graph.
Unfortunately I cannot debug, its a production system and I do not have the resources to build a lookalike test system. Neither do I have the knowledge.

**Comment by gordonb3** [comment]
@bizziebis
Depends on how long it does so. A process may allocate a huge amount of memory at startup, but until it actually starts using it the Operating System will only assign virtual memory to that request. Therefore, as the program runs virtual memory will be converted to physical memory, resulting in the graph shown above.

Also, since there is a database involved you need to take into account that the virtual memory size is likely to grow at first as well. Particularly since this database does not contain any user manageable settings or constraints for cache size. On my system this appears to be fairly restricted, starting with 148M - which is significantly bigger than the image size that is less than 10M - and gradually building up to around 157M within the first few minutes. It stabilizes at around 162M after a few days. In my case most of this memory remains virtual memory/gets assigned to swap as the machine I run Domoticz on only has 512M available and needs to share that with other services as well. On a dedicated machine with 1G memory like the Pi3 however this may easily all become physical memory at some point in time. Meaning that the numbers shown in the graph above are all within the expected range and thus do not lead to any suspicion that there could be a memory leak.

**Comment by SargonofAssyria** [comment]
@gordonb3 
Please explain to me why the memory consumption on stable version 3.5877, which I used before august 2017, does NOT show the phenomena of memory consumption. The hardware setup is almost the same, the scripts are almost the same. And I did NOT change any scripts or hardware at the time I updated from V3.5877 to V3.8153 I just updated to the latest stable. I left system unchanged for a few weeks to be sure that everything was working as expected. I reported it for the first time here: https://www.domoticz.com/forum/viewtopic.php?f=6&t=19186

Current memory consumption is already above 10% and still growing (coming from 3%)

**Comment by gordonb3** [comment]
As said: on my own instance I see an immediate request for 148M at startup, which in your case would translate to 14% of internal memory - if virtual memory is converted to physical memory. You're not there yet, so with this info you cannot draw the conclusion that there is a memory leak.

Again: you need to look at the virtual memory size. That is the amount of memory that the process wants to use. What you are looking at is the amount of memory that the Operating System allows the process to use for instant access, i.e. physical memory.

**Comment by SargonofAssyria** [comment]
Oke, I will let it grow and see what happens. Just for curiosity I used smem.
Just for information, this is the output:
 PID User     Command                         Swap      USS      PSS      RSS
  992 root     /usr/sbin/apache2 -k start         0    13644    15282    23216
  474 pi         node-red                                   0    49716    49824    51472
  985 root     /home/pi/domoticz/domoticz   0    97332    97642   100080

Domoticz is the most memory consuming process, and also slowly growing.
B.t.w. my Domoticz VSZ is currently at 399M, so I should wait until RES reaches 339M?
The last hour VSZ grew with approx. 1Mb

**Comment by gordonb3** [comment]
No. The point here is that RES is not only limited by what the process wants but also by what the OS allows it to use. You need to watch VSZ, which as a rule should stabilize at some point in time (and probably should have given its current size). If you see VSZ still incrementing after a couple of days it may be interesting to note whether that occurs in some fixed rate. If at that same time you see RES incrementing with some fixed ratio compared to the increment of VSZ that will be an indication that the process most likely spawns new I/O threads without destroying the ones that are no longer used. If then you like to investigate further you can disable hardware and/or scripts one by one and verify if that stops (or slows down) the incrementing.

**Comment by SargonofAssyria** [comment]
I made a script that runs every minute and logs the output of the domoticz process of ps command to a file.
I let that run for a day or so and will make a graph of the data.
I have a production Domoticz, so I am not able tot stop hardware and script for longer time.
Still no explanation for the difference between V3.5877 to V3.8153. Would like to know your opinion on that.

**Comment by gordonb3** [comment]
Can't answer that question. There are over 2,000 individual commits between those versions and I really do not know them all. In fact I have an issue with 3.8153 and above myself which I still have not been able to figure out as nothing I can measure or log shows any problem and yet it causes my system to become completely unresponsive after a few days.

**Comment by SargonofAssyria** [comment]
I had the script running for 5 hours. The graph is showing the difference to the first data item.
Just for getting a better view the difference is shown. 
VSZ raised from 411.272 Kb to 416.648 Kb and RSS raised from 102.232 Kb to 107.344 Kb
VSZ raised 5.275 Kb and RSS raised 5.112 Kb
I keep it running for some time.
![image](https://user-images.githubusercontent.com/24824113/34220806-33d4f022-e5b6-11e7-9ce9-bdf0a9f22fb9.png)

**Comment by gordonb3** [comment]
Okay, so it looks like you have an increment in memory usage at a fixed interval of ~15 minutes. Can you relate that to any script or device?

And I concur at this point that you have a memory leak.

**Comment by Siewert308SW** [comment]
Just to let you know, Previous Websocket patch didn't fix my Memory leak.
Will take awhile as i'm a noob at this but figuring out why and watch the culprit is.
At the moment a RPi3 with Stretch and latest Domoticz beta and in use as production machine running.
Also a second RPi3 with Jessie with the latest stable release and in use as PiHole and Auto Weather Tweet machine running.

Just setup the second Rpi3 from scratch as previously i ran it with the latest Domoticz Beta but want to see if this issue occurs in stable also.
Yesterday i took 3 different Domoticz github checkouts:
Stable version 3.5877
Stable 3.8153

I noticed that there was a TCP commit, could it be related to our issue?

**Comment by SargonofAssyria** [comment]
I have several dzVents script than run every minute or once a day or on device trigger.
My Bash, Python and Perl scripts are running very 5 minutes via cron or once a day via cron.
I saw the jump every 15 min. but could not find any script that runs in the same pace.
I keep on looking for some logic.
The RSS line is smooth so that 'jump'  might come from something else.

**Comment by SargonofAssyria** [comment]
This is what happened when I stopped both Event system and dzVents at around 13:08
VSZ dropped and RSS stayed at the same level, did not increase anymore.
VSZ did not drop to the level of the start of the recording.
All data is related to the start of the recording.
The last records are from starting the event system and dzVents again.
![image](https://user-images.githubusercontent.com/24824113/34260983-e10d8a86-e667-11e7-80c1-30e2ac95f037.png)

**Comment by Siewert308SW** [comment]
When i conduct a valgrind on Domoticz with libpython installed i see something which tells me the python plugin system has a mem leak.
Could be wrong, someone with more experience who want to take a look at this?

**Valgrind with libpython:**
https://pastebin.com/euv95et7

**Valgrind without libpython:**
https://pastebin.com/xgFADQmC

Ran tests 4 times with and without libpython3. and each time the same results...

**Comment by SargonofAssyria** [comment]
I do not use a Python plugin. So that not my memory leak.
I am currently on Holiday, I check more next year.

**Comment by Siewert308SW** [comment]
@SargonofAssyria 
I don't use it either but still running in the background, removed all those example scripts.

**Comment by SargonofAssyria** [comment]
I deleted the complete content of the plugins dir and restarted Domoticz.
Still the Memory Leakage is growing at a steady pace.

**Comment by Siewert308SW** [comment]
@SargonofAssyria yep... same behaviour.

@gizmocuz 
This valgrind log output doesn't tell me anything.
I do see some reference to some Domoticz funtions and such.
https://pastebin.com/2ujXaxVK

If i'm right i see some reference to realloc (https://github.com/domoticz/domoticz/search?utf8=%E2%9C%93&q=realloc&type=) which lost some memory.
Until someone have a look with C experience i can try to revert this change and see what will happen.

**Comment by dnpwwo** [comment]
Bear in mind that Python is used by both the Plugin Framework and by the event system to support Python event scripts.  Removing all Python plugins therefore, does not mean that Python is not active on your system.

**Comment by Siewert308SW** [comment]
@dnpwwo 
true and there for i'm conducting two different tests.
at the moment running stable V3.5877 with only some hardware sensors and see if the memory increases.
If it doesn't increase i'll go back to stable V3.8153 but with https://github.com/domoticz/domoticz/commit/fa89f01550a88424a07feb885f24a5317c67804f

Hope it shows some results.
If it aint the case then i'll take a other approach.
In which i revert back to stable V3.5877 and do a git reset --hard SHA1 to a specific committed commit until i reach V3.8153.
And hope to narrow down in which timeframe the issue occurred.
I know it's time consuming but don't know any other method to seek the cullprit.

**Comment by Siewert308SW** [comment]
I know i'm throwing out some unsubstantiated arguments.
But found something interesting this morning.
At the 24th july 2017 @jvandenbroek committed a block memory fix. (https://github.com/domoticz/domoticz/commit/c8ec141f3b998ba5ef811074cd2214a677b2a51d)
In this commit he removed:

`if (lua_state == NULL)
		return NULL;

	lua_state = luaL_newstate();`

At the 25th july 2017 @gizmocuz merged pull request #1714 from jvandenbroek/blockly-mem-fix
If you take a look here then not all the changes made in original fix where committed.
As @gizmocuz suggested to put back check for allocation

So this what i'm going to do instead of my previous statement about reverse engineering.
I'm going to compile the latest beta with the original fix https://github.com/domoticz/domoticz/commit/c8ec141f3b998ba5ef811074cd2214a677b2a51d

I'm a total noob and no experience in C or C++ but just doing a reverse engineering.
Hope to see some results...

**Comment by Siewert308SW** [comment]
just a update about my progress...
8hr on the way with the above mentioned tryout and first from source build.
started at 4.40% memory usage, at the moment 4.44%
so far so good lets hope this is the culprit.
will let it this build run till tomorrow morning.

**Comment by gordonb3** [comment]
@Siewert Good find. As hinted before: watch the vmem size to verify - this is really where it all happens.

**Comment by Siewert308SW** [comment]
Thx...

But first want to see if this lucky shot is the culprit. 
Will check vmem later this evening and then tomorrow morning. 
Only afraid of screwing up the memory usage. 

@gordonb3 
just want to know what you want to see regarding vmem.
Swap or the VIRT used by Domoticz as seen in htop or something else?

**Comment by Siewert308SW** [comment]
Back for some reports...
To test if the memory still has a leak with my findings and to ensure blocky and Lua still working.
I took the test to other level and ran the first test on a non modified Beta 3.8796.
Made two events 1. in blocky and 1. in Lua.
Both scripts are running in a loop.

Scripts works like this: 

if (otherdevices[Dummy 3] == Off and otherdevices[Dummy 4] == Off)
   then	
      commandArray[Dummy 3]=On
      commandArray[Dummy 4]=On AFTER 20

elseif (otherdevices[Dummy 3] == On and otherdevices[Dummy 4] == On) 
   then
      commandArray[Dummy 3]=Off
      commandArray[Dummy 4]=Off AFTER 20
end 

I ran both scripts overnight (7hr) and noticed the memory increased a bit as i expected due to the log filling up.

- Memory usage rose from 4.4% to 4.7% (thats okay, i think)
- Domoticz Process Usage rose from 20Mb to 24.5 Mb and rose by 0.5 every two hours.
- As for the Vmem it started at 186Mb and rose to almost 300Mb

At the moment running a second test with the old fix implanted which is now running for 4hr.
- Memory usage stable at 4.4% to 4.5% (thats okay, i think)
- Domoticz Process Usage rose from 21Mb to 21.6 Mb and rose by 0.2 every two hours.
- As for the Vmem (VIRT Htop) it started at 186Mb and is still 186Mb

Will let it run for a couple more hours.
As i'm not completely convinced yet i will implant this fix into my production system tonight or tomorrow to see how that goes.
Mean while some else who can try this fix also?

**Comment by gordonb3** [comment]
That first one looks bad to me. vmem should not increment if you keep calling the same function over and over again.

**Comment by Siewert308SW** [comment]
@gordonb3 

How does this look then.
Screenshots are with the fix and time between those shots is 6hr.
Bear in mind two scripts (blocky and lua) are running a loop every 20seconds.

![schermafdruk 2017-12-28 09 07 25](https://user-images.githubusercontent.com/25230393/34415427-f56ab486-ebee-11e7-8885-2531be44082e.png)

![schermafdruk 2017-12-28 16 33 39](https://user-images.githubusercontent.com/25230393/34415431-fabc4b7a-ebee-11e7-8c25-46568363c694.png)

![schermafdruk 2017-12-28 16 54 10](https://user-images.githubusercontent.com/25230393/34415596-ebfcadfe-ebef-11e7-9d23-e04cb45223a5.png)

**Comment by Siewert308SW** [comment]
At the moment compiled a version for my production RPi.
Running same fix but with all my scripts and such. 
Lets see if it indeed improved. 
Will report in the morning.

**Comment by gordonb3** [comment]
Those are six hours apart? I think you nailed it.

**Comment by Siewert308SW** [comment]
@gordonb3 Yep... first image taken at 9am and second image at 4:30pm, bit more then 6 hr apart.
At the moment my production system is running with this fix.
Will see tomorrow if by stressing it a bit more due to my production system holds.
I do hope so, i know it was a lucky shot but glad i found the cause by comparing the initial fix and merged fix.
Hope it will hold in a long term as 6 hr is a bit short, my2cents

**Comment by Siewert308SW** [comment]
Had my production system submitted to the test with this fix.
Which contains all my scripts (bash,lua and python) and it ran over 12hr without issues.

-Memory usage stable between 4.6% to 4.7% (thats okay)
-Domoticz Process Usage rose from 32.07Mb to 32.79 Mb and rose by 0.1 every three hours.
-As for the Vmem (VIRT Htop) it started at 294.7Mb and after 12hr still 294.7Mb

Top screenshot at first initial startup:
![top_start](https://user-images.githubusercontent.com/25230393/34432452-926e82de-ec77-11e7-83b7-4365e9c18179.png)

Top screenshot 12 hours after startup:
![top_end](https://user-images.githubusercontent.com/25230393/34432460-a6a7b482-ec77-11e7-88d8-82b4f5c953e0.png)

p.s
Could be me.
But does this code change also have effect on Python Plugins?
I ask this as i had some issue with a plugin which crashed on reboot but still running after awhile.
If i reboot with this fix i don't see any errors in the log.

edit:
Made my first pull request: https://github.com/domoticz/domoticz/pull/2028

**Comment by SargonofAssyria** [comment]
I deleted the 2 lines and compiled version v3.8797:
-	if (lua_state == NULL)
-		return NULL;

I left the system running for more than 12 hours and this is the result.
The Y-axis is the difference with memory at the start of domoticz, to get a better graph.
![image](https://user-images.githubusercontent.com/24824113/34460425-ef3fab90-ee0d-11e7-85bb-1950fd06df32.png)
It looks to me that the problem is not solved. With my knowledge of programming I can not think why those 2 lines should increase memory. I agree with @jvandenbroek that those lines are redundant, so there is no harm in deleting them, but does not solve the problem.
B.t.w. when I switched to beta and added some devices I found a "new" Process Usage device from the Motherboard. Looking at the source, it looks to me that is the VmRSS Memory of Domoticz. Am I right?
That graph is increasing the same as my RSS graph. Why (for what purpose) is that device created?

**Comment by Siewert308SW** [comment]
Really weird.
Here is my graph after 12hr running...

![mem_log](https://user-images.githubusercontent.com/25230393/34460908-e9b9ad74-ee1c-11e7-9f01-043ef632015e.png)

**Comment by SargonofAssyria** [comment]
Version: V3.8153 (stable)
Platform: Linux domoticzslave 4.9.72-v7+ #1069 SMP Fri Dec 29 17:21:52 GMT 2017 armv7l GNU/Linux
Hardware: Raspberry Pi 3 with P1 USB and RFLink V48

I left the system running with switching between Eventsystem and dzVents enabled/disabled, see picture.
The graph represents the memory difference between current and first memory data.
From that I conclude that the Eventsystem is causing the Memory Leakage.
I have no idea what caused the system crash in the middle of the night. Normally this does not happen.
Monit kicked in to restart the system.
![2018-01-06_11-48-12](https://user-images.githubusercontent.com/24824113/34639123-f82c7b4a-f2d9-11e7-8fdc-eb87aabf7d15.png)

**Comment by SargonofAssyria** [comment]
FOUND IT!!! At least for 99%
See: https://www.domoticz.com/forum/viewtopic.php?f=6&t=19186&p=165178&hilit=Leakage#p165178

**Comment by SargonofAssyria** [comment]
After 1 day extra I could state that my Memory Leakage problem is solved as in the forum topic described.

**Comment by C-Duv** [comment]
@Siewert308SW I am curious on what program/executable gives the output [you gave a snapshot](https://user-images.githubusercontent.com/25230393/34415596-ebfcadfe-ebef-11e7-9d23-e04cb45223a5.png) of.
Is it Domoticz's builtin? Third-party? Handcrafted by you?

**Comment by Siewert308SW** [comment]
@C-Duv 

Thats just the MOTD which you get to see when you log in via ssh into your system.
Its available in my GitHub, not the most recent one but still in handy for some.
https://github.com/Siewert308SW/MyDomoticz-Scripts/blob/master/bash_profile

**Comment by C-Duv** [comment]
Thanks, nice script (and interesting lua scripts organization to reduce CPU usage).
