### ISSUE TITLE
Timers on whole hours fails intermittently on stable V 3.8153

### ISSUE THREAD

**Issue by daljian** [domoticz/domoticz#2027]
Hi,
This bug is a spin-off from #2016 and the original bug contains more details than summarized in this post.

Timers that are scheduled to fire on the hour (XX:00) are not triggered, and it affects (at least) single switches and groups.

I've seen two scenarios;
a) All failing (Timers consistently failing every hour)
b) All working (Timer consistently working every hour)

The case **a** is the error scenario that needs fixing, type **b** is what makes it intermittently.
Several persons and systems have been able to reproduce the error case, here is one comment from @allan-gam in #2016 
---%<---
Theses are the easy steps I do to reproduce the behavior on a clean new Stable V 3.8153 (clean DB):

- 1. Create a Dummy hardware
- 2. Create a virtual switch
- 3. Add 6 timers for the virtual switch

```
Yes | On Time |   | 11:05 | No | Off | Everyday
Yes | On Time |   | 10:00 | No | On | Everyday
Yes | On Time |   | 09:10 | No | On | Everyday
Yes | On Time |   | 09:20 | No | Off | Everyday
Yes | On Time |   | 11:00 | No | On | Everyday
Yes | On Time |   | 10:05 | No | Off | Everyday
```
(The time when I added these timers was about 09:05. I added the timers in the order they appear in the list above)

- The 'On' event for 10:00 does not happen. The two previous and the following events did occur.

I had a look at the source code but I decided it's better to let the guys who created the Scheduler.cpp have a look at it. I haven't fixed it.
---%<---

For completeness I'm also adding en example of case **b** (everything working).
In my attempt to look for clues I created two dummy switches and scheduled first one to have these timer settings:
"dummy"
XX:00 Off
XX:10 On

"dummy2"
XX:00 On
XX:10 Off
As you can see, with this configuration everything is working the way it should.

Version: 3.8153
Build Hash: 494fff7
Compile Date: 2017-07-30 12:19:41
![image](https://user-images.githubusercontent.com/6747784/34432585-e24e75ec-ec78-11e7-94e6-5428cbe00ad7.png)
![image](https://user-images.githubusercontent.com/6747784/34432587-e7b39882-ec78-11e7-9307-0bf1d900339b.png)

If I find some more clues I will add them here. 

Thanks
/Göran

**Comment by daljian** [comment]
For people looking for a workaround it seems that if you don't schedule timers to fire on xx:00 it is working - so don't do that (ie add or remove a couple of minutes and you shoud be fine).

**Comment by teeminus** [comment]
I can confirm this bug. All schedule timer set to xx:00 won't trigger, whereas timers set to xx:yy (yy != 00) will work.

**Comment by gizmocuz** [comment]
I checked this with the latest version, and i have no issues.

> 2018-06-24 08:00:01.196  Status: Schedule item started! Name: MyDummySwitch, Type: On Time, DevID: 4219, Time: 2018-06-24 08:00:01

I created a dummy switch, added an ON-TIME timer at 08:00, and it's working

The ordering in the table does not matter

Closing this topic, please feel free to re-open if there are still issues

**Comment by aldavis0101** [comment]
I am having this issue with 4.97, running on RPi3 Stretch.

**Comment by sweetpants** [comment]
@aldavis0101 Please upgrade first to latest Beta

**Comment by aldavis0101** [comment]
OK, upgraded to V4.10252; Build Hash: e2dde5d9; Build Date: 2018-12-03 09:01:03. Same problem. Timer events on-the-hour do not fire. Changing to 1 minute past seems to fix it.

I glanced at the code in main/Scheduler.cpp and I think there is a flaw. In CheckSchedules it takes the current time, say T0, and says if T0 > itt.startTime, fire. Then, in DeleteExpiredTimers it takes the time *again*, say T1, and deletes any timer for which T1 > itt.startTime. What if T0 == itt.startTime, so the timer does not fire (since the check is >), then the time advances so that T1 is past itt.startTime? The timer will be deleted having never fired. At least that's the way I read it. An easy fix would be to use the time taken in Do_Work and pass it to both CheckSchedules and DeleteExpiredTimers so that they are in sync. I did not try this as I am not set up to build from source. If needed I can attempt it.

**Comment by gizmocuz** [comment]
@aldavis0101 , at what time ? for example 15:00 , this should of course work

**Comment by aldavis0101** [comment]
Say the event is scheduled for 15:00, and Do_Work happens to call CheckSchedules right at 15:00:00.
In CheckSchedules, mytime() returns 15:00:00. The test atime > itt.startTime fails (they are equal) so the event does not fire.

Then, in the same iteration of its loop, Do_Work calls DeleteExpiredTimers. There, mytime() is called again. Say some time has elapsed, perhaps because the system is especially busy, so the call returns (say) 15:00:01. The test there says (paraphrasing) "delete any event prior to 15:00:01", which deletes the 15:00 event, without it ever having fired.

**Comment by gizmocuz** [comment]
That doesn't sound good... and you got a busy/blocking system then
Seems that 'AdjustScheduleItem' should be called inside the 'if (bOkToFire)' ?

**Comment by aldavis0101** [comment]
It's not the call to AdjustScheduleItem that's the problem... it's the fact that DeleteExpiredTimers is using a different time. I think the solution is to use the time taken in Do_Work and pass it to both CheckSchedules and DeleteExpiredTimers so they are using the same reference. Currently they use the same check ("is the current time past the event's scheduled time") but with possibly different current times. I propose to use the same check with the same times. In this way the timer would only be deleted if it actually fired, since the conditions are the same.

I built from source last night. My plan is to a) verify my hypothesis by logging the times used in both CheckSchedules and DeleteExpiredTimers; and then, if confirmed, b) implement the proposed fix and see if it works.

**Comment by aldavis0101** [comment]
OK @gizmocuz, sorry, now I see what you're getting at. DeleteExpiredTimers only handles single-shot (FIXEDDATETIME) timers. The rest are handled by CheckSchedules. But it has the same problem: it refetches the current time, which may have elapsed since the CheckSchedules. I need to analyze this some more.
I think it's important to get this right: for a home automation program to be worth anything at all, the timer functions need to be rock solid.

**Comment by aldavis0101** [comment]
OK, I've dug into this a bit more. I added some debug log items; one in CheckSchedule every time a timer is checked; one in AdjustScheduleItem whenever the timer is updated; and one in ReloadSchedules. Here are some snippets from the log file with annotations interspersed. First I set a timer for 22:00:

`2018-12-05 21:55:45.874  [73386430] Debug: AdjustScheduleItem: dummy now at 1544068800 (2018-12-05 22:00:00)`

At 22:00:00, Check Schedule is called. The check is an inequality, so the timer does not fire.

`2018-12-05 22:00:00.698  [70fff430] Debug: CheckSchedules for dummy, 1544068800 > 1544068800?`

Since the timer does not fire, AdjustScheduleItem is not being called at that point. But before CheckSchedule gets to try again, there is a call to ReloadSchedules, which _does_ call AdjustScheduleItem. By that point, the time has advanced and it looks like the timer is in the past, so it gets updated to the next day, without ever having fired.

`2018-12-05 22:00:01.000  [6ffff430] Debug: in ReloadSchedules()`
`2018-12-05 22:00:01.001  [6ffff430] Debug: AdjustScheduleItem: dummy now at 1544155200 (2018-12-06 22:00:00)`

By the time CheckSchedule tries again, it's too late:

`2018-12-05 22:00:01.698  [70fff430] Debug: CheckSchedules for dummy, 1544068801 > 1544155200?`

So where is this call to ReloadSchedules coming from? Is there some event that calls ReloadSchedules on the hour? One suspicious place is MainWorker::getSunSettings(), which if there is no Location setting, calls ReloadSchedules. It looks sort of like perhaps getSunSettings is being called by MainWorker::Do_Work() at the top of every hour, but it's not clear to me.

It seems like either we need to be careful about when reloads happen, or make AdjustScheduleItem smarter about not updating timers that have not fired yet. Or something. At any rate I am nearly certain there is an actual issue here that needs to get fixed.

**Comment by aldavis0101** [comment]
I added a couple more debug calls and tried again at 23:00. Sure enough, it's that call to GetSunSettings which seems to happen every hour which triggers the timer adjustment before it fires.

`2018-12-05 23:00:00.426  [70fff430] Debug: CheckSchedules for dummy, 1544072400 > 1544072400?`
`2018-12-05 23:00:00.906  [6ffff430] Debug: Calling GetSunSettings`
`2018-12-05 23:00:00.907  [6ffff430] Debug: GetSunSettings is reloading the schedules`
`2018-12-05 23:00:00.907  [6ffff430] Debug: in ReloadSchedules()`
`2018-12-05 23:00:00.908  [6ffff430] Debug: AdjustScheduleItem: dummy now at 1544158800 (2018-12-06 23:00:00)`
`2018-12-05 23:00:01.427  [70fff430] Debug: CheckSchedules for dummy, 1544072401 > 1544158800?`

**Comment by aldavis0101** [comment]
There is another thing I don't get about this. In AdjustScheduleItem, in the "daily time" cases including ONTIME, it says:
`while (rtime < atime + 60)
{
   ltime.tm_mday++; ..... `
Here, rtime is the timer's current setting, and atime is the current time. What this says is, "if the timer is scheduled to fire before one minute from now, bump it to the next day". This will have the effect of skipping a timer that is scheduled to fire even a few seconds in the future. This can happen anytime there is a reload (which calls AdjustScheduleItem). What is the thinking behind the 60-second adjustment?

Here is my current half-baked thought on how this overall issue might be fixed. The basic issue is that there are two asynchronous processes happening: (1) CheckSchedule, which says "if the timer's time is in the past, fire it", and (2) AdjustScheduleItem (via reloads, which can happen at any time), which says "reset the timer's time for the next point in the future". The problem is that these two steps are using a different basis for what "now" is (compounded by the 60-second slew described above). It seems to me that the basis for adjusting timers should not be the current time, but whatever time it was when they were last checked, even if that was slightly in the past. That way, if they have not yet fired, they will still fire on the next iteration of CheckSchedule. So instead of:

    Check: if scheduled time < now then fire
    Adjust: if scheduled time < now + 60 then bump
It should be:

    Check: last_check = now; if scheduled_time < last_check then fire
    Adjust: if scheduled_time < last_check then bump
This could be accomplished by maintaining last_check as a data member in CScheduler, rather than re-calling mytime() in the Adjust/Reload/Delete functions.

**Comment by aldavis0101** [comment]
I did some more testing to confirm this issue. Then I tried the fix described above, and it works. How should I proceed?

@daljian and anyone else that may be having this issue, you can try another workaround other than setting your timers for :59 or :01. Go to Setup-->Settings and enter a latitude and longitude in the Location pane. This causes the hourly reload to be skipped since the sun settings will not have changed.

**Comment by aldavis0101** [comment]
@gizmocuz, or anyone? This is a real bug. I think you can reliably reproduce it by clearing your location settings and setting a timer for the top of the hour. In any case I think have a fix. What should I do.

**Comment by gizmocuz** [comment]
@aldavis0101 , sorry, i have no issues yet, and haven't found anyone with this issue yet
Currently i am occupied on other things, and can not re-test the whole scheduler again
Maybe during the holiday season which is soon... or a free weekend...

**Comment by daljian** [comment]
I'm pretty sure I have this issue, but I'm using the minute shift workaround since I opened the bug.
Going through the comments in this and base bug we can find at least following persons successfully reproduced the xx:00 issue.
me, aldavis0101, teeminus, allan-gam, Ittiz, ghost

I know some of these tests go way back - but it's likely same issue as xx:00 has been confirmed be problematic from the past up until now (didn't check revision history, but if these areas are untuched it's even more likely same issue).

In my own tests I have seen some intermittent behaviour which doesn't help for developers..

I can assist in any tests during the holidays if you want me to test anything. I have a few Pis lying around.

Let me know in that case.

Thanks for writing all this code, so that I can spend time writing other code :)

**Comment by daljian** [comment]
@aldavis0101 How can I test your fix?
It could be good to test two systems, one with your fix and one without. I can setup two Pis and do some testing.

**Comment by gizmocuz** [comment]
@daljian , Please not that setting a timer to 00:00 might be a whole other bug than issues here

**Comment by daljian** [comment]
Yeah, I mean any hour on the hour. xx can be any hour. E.g. 09:00 10:00 ...
