### ISSUE TITLE
Wrong Battery and RSSI value > Dummy switch over MQTT

### ISSUE THREAD

**Issue by 0n3-70uch** [domoticz/domoticz#2067]
Hello,

I found a little problem with the latest release and beta version of Domoticz. I implemented the RSSI and Battery feature into the Sonoff-Tasmota firmware. But Domoticz send ` "Battery" : 255` and `"RSSI" : 12` after every switch command. Look here: 

```
domoticz/out {
   "Battery" : 255,
   "RSSI" : 12,
   "description" : "Controlicz:Schrank",
   "dtype" : "Light/Switch",
   "id" : "00014054",
   "idx" : 4,
   "name" : "Fabian > Schrank",
   "nvalue" : 0,
   "stype" : "Switch",
   "svalue1" : "0",
   "switchType" : "On/Off",
   "unit" : 1
}
```

Battery and RSSI integration:
https://github.com/arendst/Sonoff-Tasmota/pull/1604

Greetings Fabi

**Comment by gizmocuz** [comment]
What does the battery level display under the devices tab in the gui ? if it does have a value from 0-100 then it should also be send via MQTT (and not 255, which means no battery)

**Comment by 0n3-70uch** [comment]
Hi, one example: 
The Sonoff switch send a status update (`domoticz/in`) with idx:4 and battery:65. Domoticz show the correct value of 65% for the device 4.
Now I switch the device to on or off. Domoticz send out a command (`domoticz/out`) with battery:255 and not with 65. So the value under the device tab is wrong.

**Comment by gizmocuz** [comment]
If you switch the device to 'On' could you also provide the battery status ?

**Comment by 0n3-70uch** [comment]
You mean sending the battery status again?
Yes it's possible but only with a second message. Because the outgoing message from the sonoff device is a command message and not a telemetry message. And it seems impossible to add the battery and rssi values to the command message.

**Comment by gizmocuz** [comment]
How it works on a real switch received by 433/868Mhz supporting battery/rssi status, when a switch command is received, it includes the battery level as well.
For zwave, it send send as well.
So i think when you send your On/Off command, you should also provide this information

**Comment by 0n3-70uch** [comment]
Ok I will add the rssi and battery status to every switch command. So the sonoff will send the command and telemetry status..

But the log will include the wrong values as well ;-). (if there is any log for these things)

**Comment by jannnfe** [comment]
Hey @0n3-70uch and @gizmocuz 
Could you solve the problem? For me, the battery and the RSSI are always set to standard values.
I use Domoticz in conjunction with eDomoticz for HomeKit and Sonoffs.
Here I once saved the logs what happens when you switch a device on the various interfaces:

Turn on Domoticz:
![bildschirmfoto 2018-09-21 um 11 52 16](https://user-images.githubusercontent.com/30130742/45874858-4084f700-bd96-11e8-84d9-8071247a3cdc.png)

Turn on Sonoff Webpage:
![bildschirmfoto 2018-09-21 um 11 50 28](https://user-images.githubusercontent.com/30130742/45874855-3fec6080-bd96-11e8-94bb-a21334665933.png)

Turn on HomeKit eDomoticz:
![bildschirmfoto 2018-09-21 um 11 50 56](https://user-images.githubusercontent.com/30130742/45874857-4084f700-bd96-11e8-97a9-dda124b0a440.png)

The only platform on which everything runs properly is when you turn on the device on the Sonoff side.
How do I get around that Battery and RSSI are not reset across all three platforms?

Thanks!

**Comment by 0n3-70uch** [comment]
Hi, thats a problem with the dummy switches. They always store the default settings.
Little workaround: Activate the DomoticzUpdateTimer in your Sonoff device.

**Comment by jannnfe** [comment]
Hey @0n3-70uch thanks for the quick reply!
That is a pity and incomprehensible to me. Your solution is unfortunately only a drop in the bucket but better for the first than nothing. Perhaps there is something going on in the development of Domoticz in this direction.
Maybe the whole thing has to do with this mistake: https://github.com/domoticz/domoticz/issues/2719
Thank You!

**Comment by 0n3-70uch** [comment]
Yeah the solution is not so nice but working... Hope someone will find a better fix.
