### ISSUE TITLE
dzVents: Global variables are overwritten and shared among scripts without warning

### ISSUE THREAD

**Issue by rrozema** [domoticz/domoticz#2150]
Version: 3.8922
Build Hash: d7fbdec9
Compile Date: 2018-02-13 08:42:51
dzVents Version: 2.4.1

Below script defines 2 variables at the top for the names of the devices used within the script. When this script is included as a dzVents event script it works perfectly well. However after making a copy of the script, changing the both names in the copy and saving it under a new name to control 2 other switches in the same way, the 2nd script did work, but the first didn't anymore. When setting debug mode on on, I found that both scripts were triggered for the 2nd set of switches and none for the first set of switches. Only after I changed the names of the variables in either copy, or hard coded the devices names in both scripts both worked again. Apparently the variables had received the value of the last copy of the script for both copies of the script. Can you please either give an error or warning when the same variable is used in 2 scripts, or even better, make that the variables are valid and set only within the context of each script?

```
MASTER = 'Keuken: Plug'
SLAVE = 'Keuken: S2'

return {
	on = {
		devices = {
			MASTER,
			SLAVE
		}
	},
    logging = {
        level = domoticz.LOG_INFO
    },
    execute = function(domoticz, device)
        if (device.name == MASTER) then
            if (device.state ~= domoticz.devices(SLAVE).state) then
                domoticz.devices(SLAVE).setState(device.state).silent()
            end
        elseif (device.name == SLAVE) then
            if (device.state ~= domoticz.devices(MASTER).state) then
                domoticz.devices(MASTER).setState(device.state).silent()
            end
        end
	end
}
```

**Comment by dannybloe** [comment]
Yup, that's because you didn't declare the variables as locals. Like I always say: NEVER define variables as global. ALWAYS use local!! Did I say ALWAYS? No? Ok: ALWAYS define as local. local!!

So: 
local MASTER = ...
local SLAVE = ...

And please use the forum instead of this tracker next time!!

See: http://lua-users.org/wiki/ScopeTutorial

**Comment by rrozema** [comment]
I'll use the forum next time.

Yet, I still think this is a bug, even though it is documented: you're expecting end users to know about the internal implementation of the dzVentz mechanism. They're presented a screen in which they can create a script and there's no functional reason why this script should interact with any other script. Or is there a reason why they should interact with each other that I don't know about?

**Comment by dannybloe** [comment]
It is not a bug. Each script is a plain old Lua module and they all share the same global scope like all Lua modules do. That’s why you have to declare variables as local because if you don’t there will be side effects. Exactly like in your case. You need some understanding of scoping if you’re going to write programs or scripts. Hence the link I gave you.
