### ISSUE TITLE
Stupid else if logic in Blocky

### ISSUE THREAD

**Issue by csipeter** [domoticz/domoticz#2154]
Hi!
Else if works really stupid in blocky:
![image](https://user-images.githubusercontent.com/36097293/36422852-11700c34-163e-11e8-9275-be27044fba46.png)

this blocky produces following log:
2018-02-20 12:54:00.269 EventSystem: Event triggered: temperature-log_1
2018-02-20 12:54:00.269 Fahaz.temp>=24
2018-02-20 12:54:00.269 24;45;0
2018-02-20 12:54:00.269 Fahaz.temp<23
2018-02-20 12:54:00.269 24;45;0

(It was allready reported and closed but NOT SOLVED)

**Comment by gizmocuz** [comment]
Please use the forum. You can also consider using dzVents or Lua

**Comment by xztraz** [comment]
Made a forum post
http://www.domoticz.com/forum/viewtopic.php?f=31&t=22320

the odd behavior is documented in the wiki.
https://www.domoticz.com/wiki/Blockly#Control

**Comment by gizmocuz** [comment]
Thanks, as you can see here, there is something wrong with the temperature value here, it should be '24' not '24;45;0', i will do some investigation

**Comment by gizmocuz** [comment]
Okey, this is not the problem, have a look in the 'EventRules' table at this blockly,

There is only one condition, and when this condition is met, it writes all the log actions

Blockly (in Domoticz) works as If->then, or If->then->else

If you therefor rewrite your blockly as:

![image](https://user-images.githubusercontent.com/2265299/36597462-77c57da8-18a9-11e8-8265-a9bc3e22df52.png)

and the temperature is above 10, you will get:
2018-02-23 14:50:00.283  EventSystem: Event triggered: TestRob_1
2018-02-23 14:50:00.283  Temp greater or higher then 10
2018-02-23 14:50:00.285  16.3;50;1

now when i make the temperature below 9 (because 9 does not trigger an action, like your 23):
(Via the JSON API)

2018-02-23 14:54:00.291  EventSystem: Event triggered: TestRob_2
2018-02-23 14:54:00.292  Temp lower then 9
2018-02-23 14:54:00.292  4.9;50;1

Yes, i know, but that is how it was designed years ago, and it should be used for easy actions.

You can consider this as a short coming...
