### ISSUE TITLE
Open source disaggregation

### ISSUE THREAD

**Issue by arnekaas** [domoticz/domoticz#2171]
I working on open source disaggregation, see GitHub.com/disaggregation and www.arnekaas.nl/disaggregation. I would like to insert the functionality in domiticz, but don't really know where to start.

By disaggregation I mean identifying subheads in energy meter data. for example, a water cooker of 2020W with change the power reading of my smart meter from 120W to 20140W en then back to 120W after some readings. With the written code I'm separating the energy usage from the water cooker from the bulk.

Is there someone who is interested in helping? @gizmocuz ?

**Comment by gizmocuz** [comment]
Interesting project!
I am not a python coder... but i can not see where you read the actual (smart)meter and use these results ?
Because for a test, we could poll the Domoticz JSON API and get the current smart meter readings.

For example:
http://<IPAddress>:<port>/json.htm?type=devices&rid=1768

where 1768 is my smart meter device, it returns a result field 'Usage':

"Counter" : "25443.377",
"CounterDeliv" : "0.000",
"CounterToday" : "3.953 kWh",
"Usage" : "510 Watt",
"UsageDeliv" : "0 Watt",

There are various was we could implement this code, for example via a pytjon plugin, or via c++ code

But i would like to see some real-time test results first ;) You could try starting with writing a python plugin that uses the smart reader values, and calls your functions

**Comment by flatsiedatsie** [comment]
Oh man, I've been hoping that we would one day see power disaggregation in an open source project! This is to great!!

**Comment by gizmocuz** [comment]
@arnekaas, could i assist you with this ?

**Comment by arnekaas** [comment]
I'm still working on it. See gitHub.com/disaggregation. I've almost finished the stand alone RaspberryPI installer. The installer installs a logger, a disaggregator (very basic) and a results viewer (web-app). I'm looking for testers that are able the help improve the code some more.

**Comment by gizmocuz** [comment]
@arnekaas , how are your tests going ? I remember we called, but what would be the next step?

**Comment by MrHobbes74** [comment]
@arnekaas, it seems the project is dead (only one small update in 2019)? It is a pity, because it would be great to add this to Domoticz (or even, just to have it on the PI...).

**Comment by waltervl** [comment]
Closing this, no progress.

**Comment by gizmocuz** [comment]
https://github.com/nilmtk/nilmtk
