### ISSUE TITLE
Python plugin on RPI failed with urllib.request

### ISSUE THREAD

**Issue by gysmo38** [domoticz/domoticz#2188]
We found an issue on RPI with last version v3.8975 and some versions before.

If the plugin use urllib.request, Domoticz have a segmentation fault at the startup.

In my case (MELCloud plugin) the line is
`from urllib.request import Request, urlopen`

We are severals people with this issue: thread 

> Can this help solve the segmentation faults when importing python modules in plugin?? 

on the forum.

It work without problem under Ubuntu.

**Comment by 999LV** [comment]
As reported by myself (Logread user) and others in that same forum thread, it appears that this issue boils down to the way the domoticz binaries are compiled for the Raspberry platform: Static linking of the openssl library causes a segmentation fault when a python plugin imports any one of several communication modules like http.client or urllib.request. This appears on Raspbian Stretch with python version > 3.4.

The issue disappears when domoticz is compiled with dynamic linking of openssl... so the question is, why is static linking used in the first place for the pre-built binaries ? Why would the default not be changed to dynamic linking ? 

May be I’ll open a new issue thread with a different title so raise attention to the possible solution rather than the symptom.

**Comment by gizmocuz** [comment]
There is already a discussion about this.
But (sadly) the short answers, there is a different version of the openssl library on different distributions. stretch, jessie, wheezy.
So the only way to make it kind of working without having to create 100 different binary versions is to static link the library.
Static linking is not something new, and is used quite often. Why python has an issue with this, i do not know. But is this a Domoticz issue ? This should be possible without issue... i hope

**Comment by gysmo38** [comment]
Ok, i am a beginner in coding so I do not understand everything...
Is there a workaround to use urrlib with domoticz and rpi binaries?

**Comment by dnpwwo** [comment]
@gysmo38,

Using urllib.request or http.client is not formally supported by the Plugin Framework (it works for most platforms or versions though) because they are external imports.

Have a look at https://www.domoticz.com/wiki/Developing_a_Python_plugin#Connections if you want to connect to an http server.  The framework has built in support so you don't need to use an external library.

There is an HTTP example as well that ships with Domoticz

Not technically a 'workaround' I know but ...

**Comment by gysmo38** [comment]
Ok thank you for the answer.
My plugin connect to https website, so I have no choixe to use urllib :(

**Comment by dnpwwo** [comment]
There is experimental support for HTTPS in the framework if you specify it as the protocol (apart from that it works the same as HTTP).  You could try it and see if it works for you.

**Comment by gysmo38** [comment]
Ok good news :) I will try. It will be official support in the future?

**Comment by gysmo38** [comment]
Hello,
I try with builin function but with no luck.

I have a good answer code 200 but it like my post data not work.

Have you got an example?

I try like this:

`data = "AppVersion=1.9.3.0&Email=login&Password=password"
  headers = { 'Content-Type': 'multipart/form-data;', \
                        'Cache-Control': "no-cache", \
                        'Host': self.melcloud_baseurl, \
                        'User-Agent':'Domoticz/1.0', \
                         }
            Connection.Send({'Verb':'POST', 'URL':self.melcloud_urls["login"],'Headers': headers, 'Data': data})`

I also try with urlencode but same result

**Comment by dnpwwo** [comment]
Yes, definitely. 
The only known issues at the moment are around disconnecting HTTPS connections.

**Comment by gysmo38** [comment]
Ok thank you.
I start rewriting my plugin. I manage to connecto to the website.
I am not a programmer so it is a little hard to understand how it work and find the best solution :p

**Comment by gysmo38** [comment]
It work thank you. Is there a way to not have dump of packet in debug mode?

Each time i send a command, i have a lot of debug...

**Comment by dnpwwo** [comment]
@gysmo38,

There is if you are running a very recent beta.

You can now specify a logging 'mask' for debugging:

		PDM_NONE = 0,
		// 1 is mapped to PDM_ALL in code for backwards compatibility
		PDM_PYTHON = 2,
		PDM_PLUGIN = 4,
		PDM_DEVICE = 8,
		PDM_CONNECTION = 16,
		PDM_IMAGE = 32,
		PDM_MESSAGE = 64,
		PDM_QUEUE = 128,
		PDM_ALL = 65535

If you use Domoticz.Debugging(62) # 2+4+8+16+32

you should get what you want

**Comment by jia175891641** [comment]
@dnpwwo 
you means use  urllib.request or http.client is not a best way for http conection?
but it is work normaly at windows 8.1 （ python 3.6 domoticz 3.9000）  Can I continue to use it（import urllib.request）?
Will this issues be repaired in the near future?(import urllib.request work normaly at raspberry)
>

**Comment by dnpwwo** [comment]
@jia175891641,

Python libraries for connections normally work (although there have been issues in the past with specific versions).  

The preferred way to make connections is to use the built in connection object [https://www.domoticz.com/wiki/Developing_a_Python_plugin#Connections](url) because they work asynchronously and do not stall the plugin while waiting for responses.  They can also recieve data at any time rather than needing to poll periodically.
