### ISSUE TITLE
No connection to Evohome API?

### ISSUE THREAD

**Issue by bertoost** [domoticz/domoticz#2209]
Hi,
I am getting this error when connecting Domoticz to my Evohome account, with the WEB API hardware.

```
Error: (Evohome) HTTP client error at login!
```

I am sure the username and password are correct.

Domoticz version: v3.9014

Also having issues with other outgoing connections (like a notifications api)

Thanks!

**Comment by rwaaren** [comment]
If you compiled locally it might be worthwhile to look at 
http://www.domoticz.com/forum/viewtopic.php?f=12&t=21365&hilit=evohome

**Comment by bertoost** [comment]
I don't have built Domoticz myself. I use it as Docker container with this image; https://hub.docker.com/r/joshuacox/mkdomoticz
Also tried the curl request from the forum and that gives me a successful response. So I think this might be the certificate issue as described. I will try to go inside the container and rebuild Domoticz

**Comment by gordonb3** [comment]
Looking at that dockerfile, it seems you have the wrong version of openssl in your container to be able to run a precompiled Domoticz. Please see [this forumpost](https://www.domoticz.com/forum/viewtopic.php?f=3&t=19341) for more information.

**Comment by bertoost** [comment]
I will check that out tonight.. It's not my Docker image, but I can fork it of course to test it and if it works I will PR the updates :-) thanks @gordonb3

**Comment by bertoost** [comment]
Hm it didn't work out for me. With some hassle I was able to install the libssl version as described in the forum post. Although I couldn't find the Domoticz installation in the Docker container. Also updating to beta was not possible via the Web UI

**Comment by gordonb3** [comment]
Okay.

A second investigation of the dockerfile shows that you are in fact building Domoticz from source there. That means that my previous comment was in fact wrong (because that applies to the prebuilt/binary releases) and the conflict is introduced some place else. You may want to extend the cmake command to include the following defines:

 		-DCMAKE_BUILD_TYPE="Release"
		-DUSE_STATIC_BOOST="No"
		-DUSE_STATIC_OPENZWAVE="No"
		-DUSE_OPENSSL_STATIC="No"
		-DUSE_STATIC_LIBSTDCXX="No"

This is a subset of the cmake command I use myself to build Domoticz and I have that running with openssl 1.02n on Gentoo Linux

To build beta you need to insert the following line before running cmake:

 		 git checkout development && \

Or, to build a specific version you can also enter the corresponding commit hash code instead of `development` here.

You may also like to note the `apt-get remove` command in that dockerfile. This is where it removes git and all the required include files for building Domoticz, so yes the update button in the GUI will not be functional. If you like that button to work you'll need to at least remove that action from the dockerfile.

**Comment by gordonb3** [comment]
Just checking - did that work out for you?

**Comment by gizmocuz** [comment]
No response for over two month from OP, closing issue. Feel free to open again if needed
