### ISSUE TITLE
Virtual UV sensors issue

### ISSUE THREAD

**Issue by empierre** [domoticz/domoticz#223]
Hello,

  a virtual UV sensor does not have graph nor reports values.
  here is the comparison in the device table between a real and a virtual, the virtuial does not show the unit. 
    218 RFXTrx 433  E300    0   UV  UV  UVN800  0.0 UVI
    382 dummy   141CD   1   mUV UV  UVN128,UV138    0, 0    -   -
  also in the UI, only edit and notifications are allowed

**Comment by gizmocuz** [comment]
I added a dummy UV sensor, added it to the system from the devices page, and in the weather page i see this sensor
it has 3 options, log/edit/notifications, pressing the log will display an empty graph (because there is no data)
Now after 15 minutes i have a line (all zero)
So i think it is the data you provide to this sensor that is not correct (sValue/nValue)
sValue should be UVLevel;0
(0 is temp, which is not used)

**Comment by empierre** [comment]
Hello,
Hello,

  What I show here is the device tab listing not the values I input. 

  On both browsers and mobile device have no log on this device although I am running the last beta from yesterday. Any hint ?

**Comment by gizmocuz** [comment]
It is working from the weather tab ?
On the devices tab i also have 3 buttons, remove/edit/log
![uvdev](https://cloud.githubusercontent.com/assets/2265299/11418601/9ca6be70-9421-11e5-96d3-14ca3329398f.PNG)

and it displays the log/graph
try adding a new one, dont touch it, check in 10 minutes the graph

**Comment by empierre** [comment]
This is not what I have, sorry I can't make a capture now but here are the values:

382 dummy 141CD 1 mUV UV UVN128,UV138 0, 0 - -

you can see it is 0,0 in the data not 0 UVI (you have my database to check this)

**Comment by empierre** [comment]
Hello,

  out of despair I deleted it and recreated a new that is now functionning
as it should
