### ISSUE TITLE
Allow Python Plugin to stop itself

### ISSUE THREAD

**Issue by 999LV** [domoticz/domoticz#2265]
It would be useful in my view that a python plugin can stop itself from running, e.g. if the host domoticz version is not high enough, or an external library that is needed is not installed or a piece of hardware that the plugin should connect with is not available, etc...
Though my c++ coding skills are not that proficient, I am willing to take a shot a implementing this (adding a Stop method to the python Domoticz object, i.e. calling Domoticz.Stop() from within a plugin would call StopHardware within Plugins.cpp).
Before I take a stab at it, I’d appreciate any views on any unintended or side effect of implementing this, especially from @dnpwwo 
Thanks.

**Comment by dnpwwo** [comment]
Probably not a hard feature to implement but not sure how it would be used in the real world.

If external hardware is not available it seems to make sense for the plugin to periodically look for it so that Domoticz can interface to it when it does become available.  I can't think why a user would want to have to manually restart the plugin for that to happen.

The other cases you mention don't require the plugin to actually stop it can just do nothing in onHeartbeat and have no real effect on Domoticz.

**Comment by 999LV** [comment]
Thanks for your feedback. Fair points and not worth the effort most probably.
