### ISSUE TITLE
Teleinfo CRC validation

### ISSUE THREAD

**Issue by domcars0** [domoticz/domoticz#2333]
I think it's important to NOT disable de CRC message validation (as it's said on the Teleinfo setup interface). So the setup to disable this control is not really useful. 
Furthermore it could be very useful to disable the logs of those errors (I have one error every ~2 minutes, so my logs are full of this msg!).
The isCheckSumOk() function could have two parameters (teleinfo.CRCmode1 and m_bDisableCRC) and the checksum errors would be logged only if m_bDisableCRC is false.
And , of course, we will always process the line only if the checksum is ok 
```
	if ( isCheckSumOk(teleinfo.CRCmode1, m_bDisableCRC ))
                         MatchLine();
```
Thanks.

**Comment by gordonb3** [comment]
I think the TeleInfo code is probably related to the P1 code? When adding the CRC check to the latter I chose to make the CRC check optional because there appeared to be more people complaining about the CRC errors being logged than there were happy to receive clean data only. I'm guessing the concept may have been copied or similar circumstances may have been in order to lead to the same decision.

I do agree with your point, but I'm afraid there are still a lot of users that rather see bad data than errors in their log. As far as that log is concerned, I have a feeling that the lead dev on this project thinks it is better to log too much than too little.
