### ISSUE TITLE
Python plugins: all connections closed before onStop is called

### ISSUE THREAD

**Issue by 999LV** [domoticz/domoticz#2383]
Issue: I am writing a plugin that interacts with a backend over a http connection. When the plugin stops, I want to send cleanup commands to the backend and stop it as well... unfortunately this is not possible since the plugin framework disconnects all connections prior to calling the onStop callback.

@dnpwwo, do you think this change could safely be implemented ? I am not familiar with c++ but I edited Plugins.cpp to call onStop before the transports disconnection loop is launched, but then I realized that Connection.send() fails when called from the onStop callback, due to the m_stoprequested = true flag (I think).
Rather than messing further with code that I do not fully understand, I submit this change request for your consideration.
Logread.

**Comment by dnpwwo** [comment]
@Logread,

The onStop callback serves a specific purpose (it is the final callback called signalling that the plugin has stopped) and moving it could break existing plugins. As, as you have discovered, there is some cascading logic in the plugin stop process that would be hard to change.

Finally, how would the plugin framework know when to close any open connections?  Your clean up might require 1 or more calls so it would never know when it could close connections from poorly written plugins.

Sounds like what you are looking for is an 'onStopping' or 'onStopRequested' callback that could be queued at the start of CPlugin::StopHardware(). A clone of class onStopCallback would probably do it but you would need to move the logic from CPlugin::StopHardware() into a new Plugin::Stopping() function otherwise the disconnects would be queued right after onStopRequested so any Sends() would queue after the Disconnect()s (and would therefore fail).

Its not a bad idea and it could be done but unfortunately I don't have time to test it right now.  If you want to give it a go I can review you change

**Comment by 999LV** [comment]
@dnpwwo , thanks for your feedback... looks like your suggestion to create a "onStopRequested" callback is the way to go... I'll try to give it a shot if I can find the time since I find this could be useful generally speaking
For now, I solved my immediate issue by having the plugin onStop() send a SIGTERM signal to a handler in the backend to do the clean up, but this is a bit crude...
Will share changes with you if and when I manage to take this forward.
