### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by emontnemery** [domoticz/domoticz#2391]
To reduce the very large number of user issues due to the browser cache / app cache not being invalidated as expected, domoticz needs a more reliable cache busting mechanism.
(Discussed a little bit in #2254)

A simple and widely used approach is to "fingerprint" the assets with the hash of the asset.
For example, instead of requesting domoticz.js, browser should request domoticz-82e33bb5.js where 82e33bb5 is the hash of domoticz.js. After a change of domoticz.js, the hash will be different and browser will no longer use an old cached version.
In this way, it is much less likely to have bugs/issues due to mismatch between html, js and css.
This can for example be done by physically renaming all the files in the file system, or by letting the webserver translate the request for domoticz-82e33bb5.js to domoticz.js.
A variant of this method is to add the fingerprint in a query string instead of as part of the filename, e.g. the browser requests domoticz.js?ver=82e33bb5.

I propose to add this as a build step.

There are a lot of tools available for such fingerprinting, so the question is what is suitable for domoticz.

**Comment by Tontze** [comment]
+1

**Comment by dannybloe** [comment]
Good points. At work we use webpack to create builds and webpack can automatically add build hashes to all files and references. Perhaps it is a good idea to look at adding a build step to prepare all web assests. That can take care of cache problems and can also do proper minification of code. On top of that you can do compression on the webserver level.

**Comment by gizmocuz** [comment]
Caching should just work. It should be very strange that an old file would be served.
When people switch between beta/stable that is giving issues

**Comment by gizmocuz** [comment]
But related to the appcache, we can replace the version number in the file dynamically with the build hash, and it will request all files again

**Comment by emontnemery** [comment]
@gizmocuz Yeah, the appcache _should_ just work and refresh all resources when the manifest is changed. But based on the number of user issues / complaints it seems it doesn't really work reliably.

The concept of appcache itself has been deprecated, and is pending removal from at least Chrome and Firefox, so Domoticz needs an alternative no matter what..

For the cache handling, a cache busting other than relying on changes in the appcache manifest is needed. Fingerprinting with hashes, either by query strings or by filename, seems to be very widely used and considered "best practice", so I suggest to add such fingerprinting as a build step.
It could also be done "on the fly" by the domoticz web server by rewriting the webpages.

For serving the "domoticz offline" page, a service worker can be used instead of the appcache, but that's perhaps a separate topic.

**Comment by gizmocuz** [comment]
i think we have two threads trying to accomplish the same ;)
Appcache is mostly used to store the 'application' offline on the users browser, but also on the mobile devices.
This is working perfectly ! When i launch my domoticz homescreen shortcut it starts in a sec, no files are being requested (only the api)
I don't think they will  phase this out without an alternative for this

**Comment by HoekieN** [comment]
Firefox has already removed it a while ago: https://www.fxsitecompat.com/en-CA/docs/2016/application-cache-support-will-be-removed/
And in Chrome it also has the status deprecated: https://developers.google.com/web/tools/lighthouse/audits/appcache

**Comment by gizmocuz** [comment]
@HoekieN , i know. As said, it is not only used in browsers but also for offline applications (which i find much more important)

**Comment by emontnemery** [comment]
@gizmocuz _To solve the appcache issue, maybe instead of the version number, we replace this (with a tag as we already do on some places) it with the build hash._
Then I propose to instead include hash value of each file in the appcache manifest.
Either like so:
js/domoticz.js # 036b37f0
Or like so:
js/domoticz_036b37f0.js

**Comment by dannybloe** [comment]
I would do the first (perhaps with a ? like domoticz.js?hash=123. Because that makes debugging client-side easier.. files then always have the same name in lists.

Beware though that if you follow this path you have to do the same for ALL assets that are loaded into the client like images, fonts, jsons etc etc. That means you have to dynamic rewrite things like src tags in html or url() calls in css files (e.g. url(/path/to/image.png?hash=123), everywhere. That's why I suggested to use professional build tools like webpack because they have systems to scan and transform all assests in all files everywhere (file-loaders, css-loaders, extracters, packers etc etc). You don't want to write that stuff yourself. That's insane.

So, it is NOT sufficient to just add a hash to the js files. Won't be enough to solve caching issues.

**Comment by gizmocuz** [comment]
@emontnemery , no there is no reason to do this. The files in this appcache file should be named correctly.

we could replace

`# ref 1516`

with

`# ref #REVISIONID`

And in the code that serves the appcache file (builds it for the theme files) replace it with the actual revision hash

**Comment by emontnemery** [comment]
@dannybloe Sure, I'm with you. I was thinking about using something really simple like https://webassets.readthedocs.io to not have to add nodejs as a dependency just for cache busting.

**Comment by emontnemery** [comment]
@gizmocuz What is `#REVISIONID`, I mean what do you suggest to derive it from?

**Comment by gordonb3** [comment]
I'd say the problem is most likely not with appcache itself, but the browser refreshing it from it's main cache. This would most likely become an issue when people are downgrading Domoticz and the local cached version is newer than what the server provides. The browser logic will then pick the wrong version. There could also be other issues involved that would confuse this logic, like an incorrect time on either client or server. For instance: a Pi does not have a realtime clock. If you don't run the correct routine after a power down that means that Domoticz will be running in 1970 and it will depend on how long the Pi has been running whether newly installed files will in fact have a newer timestamp or one that is older than the browser has.

**Comment by gizmocuz** [comment]
@emontnemery , 'tag' that will be replaced with the build hash

**Comment by emontnemery** [comment]
@gizmocuz Yeah, but not clear to me what "build hash" is. Is it git SHA-ID?

**Comment by gordonb3** [comment]
Just hover over the version number in the top bar of Domoticz. It's the first seven digits of the commit ID

**Comment by emontnemery** [comment]
@gordonb3 OK, using git commit ID doesn't seem like a good idea:
- It's not useful during development; auto generated cache manifest won't be changed until a git commit so you will still have to manually modify the manifest to trigger a refresh of the app cache
- There will be a lot of unnecessary app cache refreshes, looking at domoticz' commit history, roughly 20% of the commits touches the www sub tree

**Comment by gordonb3** [comment]
If that's your concern, you can use `-nocache` startup parameter to skip appcache

But yes: updating the appcache with every commit would trigger needless updates and it will also not help with people that somehow manage to store updated files with an older timestamp than the version they have in their browser cache.

Cache busting would fix that, but it shouldn't be necessary to actually name the files that way. In fact that could make things very messy because the install routine will most likely not clean the versions that have become obsolete in the target directory. By simply adding `?v=1234567` to the uri that should trigger the browser to ignore the version in cache.

**Comment by emontnemery** [comment]
@gordonb3 My concern is that appcache refresh is not working for domoticz web ui, and of course there could be several root causes:
- domoticz developer forgets to bump html5.appcache
- appcache support in browser is buggy
- domoticz handling of appcache is buggy
- something else

Here's a fresh example from #2389 where at least the first potential cause can be ruled out:

```
@gizmocuz
Contributor
gizmocuz commented 2 days ago
Set Level with a level of 0... should this not be Off instead ?
Made some changes, could you test beta 9440 ?

@balintkozma
balintkozma commented 2 days ago
Yes, good point, it is a shutter actually, and all the other level values I want to set fail the same way.
Tested with 9440, it is the same.

@gizmocuz
Contributor
gizmocuz commented 2 days ago
Can you clear your browser cache and appcache (two different things) and try again ?

@balintkozma
balintkozma commented 2 days ago
&para is now escaped well, but the %20 space problem is still there, still cannot execute the action because of this.
```

**Comment by gordonb3** [comment]
No. I don't think it is the appcache support. The most likely thing that will happen is that the browser references its regular browser cache while fetching the listed files. The way that cache works is that it should check the timestamp of the file in cache with the one reported by the server to verify whether the cached version is still valid. There are two possible disturbances here:
1. the browser does not perform the check because the local copy is very recent
2. the server reports the same or an older timestamp for the file

Both will lead to the appcache being filled with the older cached version resulting in the reported errors. This also shows why simply clearing the appcache is not sufficient, because if you do the browser will once again fill it with the older version that is in the browser cache - which is why you need to clear that as well.

**Comment by balintkozma** [comment]
In #2389 I meant with "it is the same" that it still didn't work, it wasn't the cache deletion that paritially solved my issue, rather gizmocuz's commit. He just wanted to be 100% sure.

**Comment by emontnemery** [comment]
@balintkozma OK, thanks for confirming!

@gordonb3 Are you sure that's a case when it goes wrong, I mean, can you reproduce it? If you can, the way domoticz is using the appcache is not correct..

There are some potential issues with domoticz' javascript for appcache control:
- We listen for cache events, but the case when the event has been fired before the event listener is added is not accounted for
- There's no explicit call to `appCache.update();` so we rely on the browser to update the cache
- When reloading the page after a cache refresh, `forceGet` parameter of `location.reload(forceGet)` is not set

**Comment by gordonb3** [comment]
I never have this issue, so I'm quite sure that it has nothing to do with how appcache functions. As far as I can see this limits the origin of the issue to appcache being filled from the wrong location.

```Which can only be the browser cache (in @gizmocuz's words: different from appcache)```

Can I make my system do it? Probably yes, but that doesn't really prove that this is actually what happens at other users' sites. One should realize though that the tip to clear both the appcache and the browser cache didn't just drop out of the sky. It must have been noted at least once that clearing the appcache doesn't prevent the browser to fill it again with the wrong version. I for one would not be surprised even a bit to see this happen when people move from beta to (older) stable.

**Comment by gordonb3** [comment]
Should add that one reason for my system never being confused about whether to grab a file from cache or remote server is probably because I always limit the cache size on my machines to 50MB. It is very likely that any Domoticz appcache file that was in there will have long been flushed from browser cache when it wants to renew the appcache.

**Comment by gizmocuz** [comment]
So we are in an kind of war scenario between appcache and Cache API.

See Browser compatibility:
https://developer.mozilla.org/en-US/docs/Web/API/Cache

It's not strange that iOS/Safari is not supporting it, because it seems it is in their advantage to keep supporting appcache:
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/SafariJSDatabaseGuide/OfflineApplicationCache/OfflineApplicationCache.html

I've find this library:
https://developers.google.com/web/tools/lighthouse/audits/appcache

Specifically:
https://github.com/googlearchive/sw-appcache-behavior

Maybe this could be of interest ? Not sure if this is working on iOS this needs testing (browsing with HTTP from Safari to domoticz (port 8080) and from Safari create a shortcut on the homescreen.
Next see if it launches straight away without requesting any file (except API calls of course)

**Comment by gizmocuz** [comment]
The appcache is now forced to refresh on every new build, hopefully this solves the issue
Next to the appcache we also return the 'expires' header for images

**Comment by emontnemery** [comment]
What does this mean:
_Next to the appcache we also return the 'expires' header for images_
Aren't the images included in the cache manifest? Or that's for user defined images?

**Comment by gizmocuz** [comment]
@emontnemery , sure they are (the once that needs caching)

**Comment by gordonb3** [comment]
Returning to my comment `can I make my system do it`

Playing around with manipulating compression behaviour I instantly ran into the caching mechanism returning gzipped versions where I expected plain html and vice-versa. Funny enough Firefox web inspector doesn't show these fields, but I could see the request come in and Domoticz return a `not modified` response.

I did find something fishy though. All files that are uncompressed in the web root get current time as the last modification time in the return header. Meaning that every (originally uncompressed) file that users have in browser cache will be newer than the original. And possibly its successor as well.

**Comment by gordonb3** [comment]
Another thing. This is something you can try yourself.

If you go into the settings and change the theme you'll see Domoticz refresh the cache, only the result of that is that the theme in fact did not change at all. However, if you delete the offline web content and the cache before clicking `Apply Settings` you'll see that it does change the theme directly.

One note: Because I build Domoticz from GitHub archive all files in the `www` folder have the exact same timestamp. Depending on which theme was updated last and the direction of the theme switch you take you may see a somewhat different behaviour on your system; i.e. switching from A to B may work but from B to A not.

**Comment by emontnemery** [comment]
@gordonb3 An issue I see is that after making a modification to the appcache manifest, I have to refresh the domoticz page TWO TIMES before I see updated content. This is mentioned as a typical issue if javascript handling of application cache events is incorrect, i.e. there's a bug in domoticz web ui.
Can you reproduce this also?

Edit: You write:
_I instantly ran into the caching mechanism returning gzipped versions where I expected plain html and vice-versa_
Where is this code?

By the way, note that http cache rules are ignored when updating the application cache:

> HTTP caching rules, such as Cache-Control: no-store, are ignored for the purposes of the application cache download process

https://www.w3.org/TR/2011/WD-html5-20110525/offline.html#downloading-or-updating-an-application-cache

**Comment by gordonb3** [comment]
Doesn't seem to work that way in Firefox.

Using the `web developer -> web console` I can see Firefox using the web cache asking the server whether it's okay to use the cached version or feed new content. Because Domoticz responds with a `not modified` it uses the cached version. There are also some lines in there that just say `cached` - I'm a bit puzzled what cache is meant here.

There are also some other problems. e.g. images have an expiration date of November 20, 1963 while Domoticz seems to want to set that to December 26, 2099. Apparently Firefox does not accept that value and the last note in https://tools.ietf.org/html/rfc7234#section-5.3 possibly explains why.

**Comment by emontnemery** [comment]
@gordonb3 I think what you see in the developer console is Firefox' request to the application cache, not the application cache's request to the domoticz server?
Maybe it's related to what I mentioned earlier about strange/broken handling of application cache javascript events.
_When reloading the page after a cache refresh, forceGet parameter of location.reload(forceGet) is not set_
If forceGet is set to true, the browser cache should be forced to refresh, maybe worth a try?

I have also seen mentioned that one must be very careful with correct cache headers from the server when using the application cache. Not using any cache header was specifically warned against (this is what domoticz does, right?). I'll try to find the article again.

**Comment by gordonb3** [comment]
No. The request is definitely sent to Domoticz. However part of the request is a `If-Modified-Since` tag that prompts the web server to verify the file's modification time and return a HTTP-304 if that time is the same or older.

You probably have a point about the `forceGet` / `forceReload` flag. I'd say that if you set this that would prompt the browser not to include the `If-Modified-Since` request header and cause Domoticz to return the file's content.

**Comment by emontnemery** [comment]
Setting the "forceGet" flag should only affect the request from Firefox to the application cache, it will not affect the refresh of the application cache itself.

If the application cache is not fully refreshed, but the application cache is instead using logic provided by headers such as `If-Modified-Since`, that seems to be at odds with:

> HTTP caching rules, such as Cache-Control: no-store, are ignored for the purposes of the application cache download process

Edit:
It's mentioned later in the application cache spec that:

> If this is an upgrade attempt, then use the newest application cache in cache group as an HTTP cache, and honor HTTP caching semantics (such as expiration, ETags, and so forth) with respect to that cache.

Then I think it's fairly clear that one issue is unsuitable (or in fact the total absense of) HTTP caching rules sent by domoticz. This means that the browser will revert to default caching rules for the resources during an application cache upgrade.

**Comment by gordonb3** [comment]
No go: doing `window.location.reload(true)` does not change behaviour.

Also I found what `cached` means in the `Transferred` column. It means that the file was served from appcache, which from looking at the return apparently loads quicker than the browser can handle the content for display. The trouble with that is that because it is a background routine you can't actually see if that returned a 304 as well or a 200, but since I currently don't have any other stuff cached from resetting it various times I'd say that will have been been a 304 and there won't be much sense in letting the server spit out debug log entries to verify.

**Comment by gordonb3** [comment]
>Edit: You write:
I instantly ran into the caching mechanism returning gzipped versions where I expected plain html and vice-versa
Where is this code?

I've submitted a pull request: [2416](https://github.com/domoticz/domoticz/pull/2416)
With regard to compressing web content during build/install you should note that there is a routine in cWebem that can insert dynamic code in .html files based on the following tag:
`<!--#embed` foo `-->`
This is mostly about comboboxes and to make that work files that contain this tag may not be stored compressed.

**Comment by emontnemery** [comment]
@gordonb3 Are any issues related to caching solved or improved by #2416?

**Comment by gordonb3** [comment]
Actually, 2416 was closed because Gizmocuz wanted the two subjects split.

Too soon to tell how the patch affects the various issues reported. The corrected timestamping should fix a number of faulty cache decisions, but whether a user will notice that remains to be seen. A disturbing factor will be that anything that the user's browser currently has cached wrong will stay wrong. One thing that is noticeable is that with this patch you can switch themes on the fly.

**Comment by gizmocuz** [comment]
I think we solved this now, lets close the topic. Feel free to re-open when needed
