### ISSUE TITLE
Switch selected from devices not showing up under Switches

### ISSUE THREAD

**Issue by jkransen** [domoticz/domoticz#2441]
I select a Z-Wave switch from the Devices list. I can switch it there and see the lamp turn on/off. However, when I add it and give it a name, it does not show up in the Switches tab. Instead the tab remains empty and states "No lamps/switches added to the system yet". I am sure it worked like that before on a previous installation. I am on the latest beta version on a clean Raspberry Pi installation, with apt upgraded to all latest versions. I have a Z-Stick dongle, pre-filled with all my z-wave nodes, so I did not add any nodes from Domoticz.

Removing and adding again does not make a difference.

When I click "Learn" under Switches, and manually click the physical switch, I get an error "Already in use by Kinderkamer lamp" (precisely the name I assigned in adding the Device from the Devices list).

Also, I can still assign the switches to rooms, add them to the floor plan, and switch them from there. But from the floor plan, when pressing the Favourite star, the browser page and even Domoticz itself seem to hang.

Someone at the forum suggested this:

> Goto your www/js directory and check if exists:
>
> domoticz.js.gz (delete it)
> domoticz.js (keep it)
>
> restart domoticz and try again

I found both files, deleted the .gz file and rebooted, but this had no effect.

Version: 3.9501
Build Hash: 4eb1bc70
Compile Date: 2018-05-25 16:53:11
dzVents Version: 2.4.5
Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124]

**Comment by sweetpants** [comment]
This discussion should be held on the forum. Have you also cleared your app and browse cache (2 things)?

**Comment by gizmocuz** [comment]
Did you switch back to a previous version/stable ? you can also login your rpi and issue

cd domoticz
rm -Rf www
./updatebeta

next clear browser cache + appcache

**Comment by jkransen** [comment]
I was configuring a fresh installation, there was no cache. Cache refreshed lots of times since, also manually. I removed www and updated beta (again), with no effect.

Please take bug reports seriously.

**Comment by gizmocuz** [comment]
@jkransen , you should take both our answers seriously !

Anyway, more important, did you perform my steps ?
If yes, open a browser (chrome) in private mode and try

**Comment by jkransen** [comment]
I did, and I cleared the caches... again, but with no effect. However, opening from a private window made the switches show up! So it seems we isolated the bug. Can you reproduce? I'll be glad to provide more feedback to make this project robuster and better.

**Comment by gizmocuz** [comment]
So that means the browser cache or the appcache is not cleared as mentioned by sweetpants
If you use chrome:

**Browser cache:**
On your computer, open Chrome.
At the top right, click More .
Click More tools Clear browsing data.
At the top, choose a time range. To delete everything, select All time.
Next to "Cookies and other site data" and "Cached images and files," check the boxes.
Click Clear data.

**Appcache:**
browse to "chrome://appcache-internals/" (without the quotes)

**Comment by michaelgalassi** [comment]
I had this problem too.  I use Firefox instead of Chrome and found that my resolution required these steps in this order:
1) clear the browser cache (preferences, privacy & security, clear data)
2) ssh (domoticz server)
3) cd domoticz; rm -rf www; ./updatebeta
4) reboot
That reboot may not have been needed but Linux isn't as robust as Unix so I've gotten in the habit of rebooting when I change stuff.
Thank you @gizmocuz for having taken the time to help out.
