### ISSUE TITLE
Interval time in use graphs of counters

### ISSUE THREAD

**Issue by FrankVteZ** [domoticz/domoticz#2499]
Hello,

First of all: I appreciate the effort that is put into the Domoticz project! Absolutely great.

First:
I would like to have the graphs of my counters with a more detailed interval time (the time between two displayed values of the short time).

A counter manually made (with decimals, interval time 6 minutes), is only showing a graph with values per hour,

An automatically made counter (like Gas, Electric):
Gas is also shown per hour, where measurements take place with an interval of 5 minutes (ESMR smart meter)
Electricity is shown per 5 minutes and is stored with a 5 min interval too.

It would be great if user-defined and pre-defined counters could be shown in the graph with better detail

For domestic users this would be a great improvement, since it is much better to see where to save money with a more direct feedback.

Secondly: 
I would appreciate is the the (automatic) devices setup for the P1 smart meter gives a separate counter for the values imported.
Now my deviceIdx shows a value of "use1;use2;return1;return2,con;prod"
In my case the counters "return1;return2" are even not added to the utility list for some unknown reason and no clue how to add them manually.

But for a starting user it is difficult to get these values into a graph without having a script to write to pull these values apart.

Using: Domoticz v3.9558, running on Synology NAS DS218plus DSM 6.1
(question also raised at the domoticz forum with advise to ask  it here at github)

**Comment by gordonb3** [comment]
I fear we have a situation of lost in translation

[The forum topic referenced is here](https://www.domoticz.com/forum/viewtopic.php?f=14&t=23868)

I have established that the missing electricity delivery graph lines are due to the fact that OP's solar installation is heavily underpowered and he is in fact not delivering to the grid but merely reducing his usage when the panels are producing energy.

With regards to the other issues raised this appears to be related to the chosen graph type, which not just depends on the web GUI but also seems to cause webserver only to include full hour values in the json output. As such I guess this may be seen as a feature request to extend the API to allow more fine grained resolution in the output than dictated by the default graph type choice.

**Comment by gizmocuz** [comment]
@gordonb3 , thanks for the help!

**Comment by FrankVteZ** [comment]
As I understand, the case not solved but should be a request since none of the user-defined counters do better then an update once/hour. Graphs e.g. for darksy weather, temperature, energy (electricitiy) it is possible, but not for the user-created grapsh, with data from  json, dzvents, python or whatever input is used.
A wish to userdefined graphs up to the densitiy of the logging interval would be very useful!
