### ISSUE TITLE
Deleting value from graph (shift) deletes all after that

### ISSUE THREAD

**Issue by sweetpants** [domoticz/domoticz#2510]
I think this needs to be resolved before new stable. I verified it with latest Beta and it is still there.

https://www.domoticz.com/forum/viewtopic.php?f=6&t=23871#p183734

After shift+click all data until the current date/time is deleted instead of just one datapoint.

**Comment by gizmocuz** [comment]
Thats strange as i can't remember something changed for more then a year there.
What sensor did you tested with ? Will this happen on a normal temp/hum sensor ?
I will do some testing before releasing a new stable

**Comment by sweetpants** [comment]
Yes, Temp+Hum sensor shows the issue

**Comment by gizmocuz** [comment]
I don't have this. I am in the log of a temp/hum sensor, shift-click on a datapoint in the month graph (20 june), deleted it, and only that data is removed.

Internally it calls this JSON API:

http://127.0.0.1:8080/json.htm?date=2018-06-20&idx=1234&param=deletedatapoint&type=command

which calls in Domoticz 'Cmd_DeleteDatePoint', which calls 'CSQLHelper::DeleteDataPoint'

Wait a minute... i see something there... it goes OK for the month and year graph, not for the short-log graph!

Someone changed some code there:

> 		//GB3:	ToDo: Database should know the difference between Summer and Winter time,
> 		//	or we'll be deleting both entries if the DataPoint is inside a DST jump

Fixed in upcoming version

**Comment by harryd100** [comment]
Thankx. will test this when merged

**Comment by gizmocuz** [comment]
Just merged... binary is building which could take some time as i've made a lot of changes ;)

**Comment by sweetpants** [comment]
Just tested, seems fixed, thanks
