### ISSUE TITLE
MD5 hash is "public"!

### ISSUE THREAD

**Issue by rldn21** [domoticz/domoticz#2586]
Hi folks, 

While scripting a alarm system within Domoticz i found a sort of leak in a JSON output in "http://ip:port/json.htm?type=settings".

If you go to the url above, you can find your SecPassword MD5 hash. 
With this MD5 hash you can simply disarm / arm the alarm / security panel in Domoticz by:

Disarm:
http://ip:port/json.htm?type=command&param=setsecstatus&secstatus=0&seccode={MD5_HASH}

Can you please explain why the MD5 hash is public?

**Comment by dotms** [comment]
By the looks of it the SecPassword hash is implemented as a preference/setting. Judging from the code all database variables are read and for each known variable the best way to display it is determined. I don't see any form of filtering.

One thing to note is that if you set a username/password for domoticz these settings are not publicly available since the web site (including the json output) is protected then.

Question remains if there is an actual need for secrets like these to be displayed.

Edit: having the website protected also disables the access to the security panel. Kind of defeats the purpose :(

**Comment by jvanderzande** [comment]
The information needs to be available when you want a Web-Frontend to be able to configure Domoticz!
So, a userid/password should always be asked for in case you can't trust the local lan clients, and I assume that at that time only Admins will be able to get this data.

**Comment by freemann** [comment]
My/most domoticz installs are not publicly available, so IMHO not a real issue. A public install is asking for troubles.

**Comment by gizmocuz** [comment]
In this case we could not send the md5 hash and when storing the settings check if the 
Admin password is entered. If not, do not change the admin password.
The same can be done for the email password

Regarding protection, sure you need to protect your installation with a username and password
The security panel is local.. you can configure the system so it would not ask for a username and password in your local network or even better.. not specifically for your tablet's IP address.

**Comment by gordonb3** [comment]
Hmmm... While I do see your point, it becomes kind of senseless when you send the disarm command like that. With the current implementation of https allowing multiple sites to be hosted on a single IP - which means exposing the URI - I'm not even sure whether it is safe to use GET for this at all.
