### ISSUE TITLE
Xiaomi Gateway 'whois' message is sent with wrong source address

### ISSUE THREAD

**Issue by astafyev** [domoticz/domoticz#2629]
https://github.com/domoticz/domoticz/blob/31aa4ca3537a48fdec0c3b8e9b9d7e9d1fe60cbc/hardware/XiaomiGateway.cpp#L773
I'm running v4.97 on OpenWRT on Xiaomi 3G router and have an issue with Xiaomi Gateway discovery. Despite the fact that correct local IP to listen to is found, 'whois' message is sent with the wrong source address. In my case source address is the public WAN address of my router instead of local IP. I think that happens because the socket is bound to correct local IP two lines after 'whois' is sent. As a result, Xiaomi Gateway doesn't respond to this message and it is not discovered by Domoticz.

**Comment by emontnemery** [comment]
@astafyev The socket is bound to the multicast address, not local address, on the line you're referring to though:

```
boost::asio::ip::address listen_addr = boost::asio::ip::address::from_string(m_localip, ec);
boost::asio::ip::address mcast_addr = boost::asio::ip::address::from_string("224.0.0.50", ec);
boost::asio::ip::udp::endpoint listen_endpoint(mcast_addr, 9898);
...
socket_.send_to(boost::asio::buffer(*message), remote_endpoint);
socket_.set_option(boost::asio::ip::multicast::join_group(mcast_addr.to_v4(), listen_addr.to_v4()), ec);
socket_.bind(listen_endpoint, ec);
```

**Comment by astafyev** [comment]
@emontnemery Actually the socket is bound twice:
`				socket_.bind(boost::asio::ip::udp::endpoint(boost::asio::ip::udp::v4(), 9898));
				std::shared_ptr<std::string> message(new std::string("{\"cmd\":\"whois\"}"));
				boost::asio::ip::udp::endpoint remote_endpoint;
				remote_endpoint = boost::asio::ip::udp::endpoint(mcast_addr, 4321);
				socket_.send_to(boost::asio::buffer(*message), remote_endpoint);
				socket_.set_option(boost::asio::ip::multicast::join_group(mcast_addr.to_v4(), listen_addr.to_v4()), ec);
				socket_.bind(listen_endpoint, ec);`
I'm not so familiar with Boost and don't know how it should behave after first bind, but I see in tcpdump that packet source address is my router's WAN real IP address. And there is no response from gateway. If I manually send 'whois' command using netcat and local ip as source address I got response from gateway and Domoticz successfully recognizes it.

**Comment by emontnemery** [comment]
@astafyev Yeah, I get what you're saying, but I don't think it's as simple as moving the send_to() after the 2nd bind since it would then send with the **multicast** address as source address instead of with the default local address.

@corbinmunce:
This must be a bug right,
`socket_.bind(boost::asio::ip::udp::endpoint(boost::asio::ip::udp::v4(), 9898));`
In this case, we should bind to local_addr instead of default to boost::asio::ip::udp::v4()?

Given the name of the listen_endpoint variable, should this line:
`boost::asio::ip::udp::endpoint listen_endpoint(mcast_addr, 9898);`
Be changed to:
`boost::asio::ip::udp::endpoint listen_endpoint(listen_addr, 9898);`
