### ISSUE TITLE
adjustment value doesn't work for xiaomi temperature-hum+baro sensor

### ISSUE THREAD

**Issue by ricky074** [domoticz/domoticz#2840]
Hello,

I'm on domoticz beta V4.10171 and I use xiaomi temp+hum+baro sensor (Zigate plugin)
I would like to offset pression values with the adjustment possibility but it doesn't work.
It's the same wtih the temperature values...

**Comment by gizmocuz** [comment]
Please use our forum

**Comment by pipiche38** [comment]
@gizmocuz I'm not sure if the forum will help. I do have the same trouble. If I set adjustment to a particular value, there is no change to what is displayed ! and it was working before !

Is the behaviour of the adjustment changed ?

**Comment by pipiche38** [comment]
@gizmocuz the Adjustment parameters are not accessible in the Python plugin framework, so who is in charge of using it and making the correction ?

**Comment by gizmocuz** [comment]
Please use the forum! I am not into python/lua/dzVents or anything ... we have forum sections for them

**Comment by pipiche38** [comment]
@gizmocuz this is ok, but still 
(1) we don't know if the issue is on python/lua/dzVents or if this is an issue on Domoticz core

On one side, I see AddjValue is taken into account in mainworker.cpp for Temp, 
It is commented for Humidity

And in our case, this is simply not taken into account. So I'm more than willing to post on the forum (it is alreday done), but I think the issue is much more in Domoticz

**Comment by gizmocuz** [comment]
Sure it is a Domoticz issue, if it's in the core or via scripts.... The developers are monitoring the forum, so please use the forum

**Comment by pipiche38** [comment]
OK. I'll do, but I'm not positive of the results when I see post on the same matter , where people are talking about distance from the controller !
https://www.domoticz.com/forum/viewtopic.php?f=6&t=24567
