### ISSUE TITLE
Generic sysfs GPIO active_low not working properly

### ISSUE THREAD

**Issue by Vulpecula-nl** [domoticz/domoticz#2844]
I have a problem with some input gpio's that needs to be active_low. In Domoticz the value of these inputs are always the opposite of what it has to be. For testing purpose I have connected a pin with button. When the button is not pressed (button makes no connection, pin is HIGH (3.3V)) I expect the value in Domoticz to be `Off`. When the button is pressed (button makes connection, pin brought to ground) I expect the value in Domoticz to be `On`. During executing the command lines below this scenario applies.

I think the active_low parameter is implemented double. Raspbian itself will alter the value of the sysfs gpio when the `active_low` is set. Because when I look at the `value` via the commandline it's altered depended on the `active_low`. 

```
pi@raspberrypi:/sys/class/gpio/gpio21 $ cat active_low
1
pi@raspberrypi:/sys/class/gpio/gpio21 $ cat value
0
pi@raspberrypi:/sys/class/gpio/gpio21 $ echo 0 > /sys/class/gpio/gpio21/active_low
pi@raspberrypi:/sys/class/gpio/gpio21 $ cat active_low
0
pi@raspberrypi:/sys/class/gpio/gpio21 $ cat value
1
```
In Domoticz it will also be done. When I look at the file hardware/gpio.cpp lines: 454 to 457, keep in mind the values above, then the state true is incorrect.

```
if (it->GetActiveLow() && !value)
        state = true;
else if (value)
	state = true;
```

I think the first if statement with getActiveLow is not neccessary. Because the value is already corrected by Raspbian's sysfs.

Could someone help me with these thoughs? Maybe I completly thinking incorrectly.

Hardware: Raspberry Pi 3 Model B
OS: Raspbian Stretch Lite
Domoticz version: 4.9700

**Comment by waltervl** [comment]
As nobody has the same issue after 4 years I close this issue.
Sysfs GPIO is handled in Domoticz by hardware/SysfsGpio.cpp

**Comment by sancho679** [comment]
Hi @waltervl,

I hope you and other experts are able to help with this issue, as f.ex. I DO have the same issue since a very long time already .... 
I have just retried today to check if the issue with thenon-functional logic inversion via "active_low" flag got solved in the meantime in domoticz, but unfortunately, it seems it still did not.

The possibility to invert the GPIO logic is heavily needed in cases you have a "Door Contact" device, or any other input indicating On/Off state connected to a GPIO input port and which provides a logic signal that is ACTIVE-LOW, that means when f.ex.
- "HighLevel" voltage at GPIO input is mapped to state "Door Closed" and "LowLevel" voltage at GPIO input is  is mapped to "On state"
- "HighLevel" voltage at GPIO input is mapped to state "Off" and "LowLevel" voltage at GPIO input is mapped to state "On"

I was helping myself with defining the device type as "Door Lock Inverted" inside domoticz as a workaround all the time, which does the inverting of the logic levels / states of the device inside domoticz, but since such an inverted device alternative does not exist for all device types in domoticz (e.g. there is no "Door Contact Inverted" or "On/Off Switch Inverted" device type), you will end up with other problems and downsides when doing so ...

I have spent many hours searching the web for solutions for this problem. The "official" solution from the wiki recommends to set the "**active_low**" flag on SYSFS level, in order to get inverted logic states, see https://www.domoticz.com/wiki/GPIO#Active_low_relays

However, the problem is that it does not work (anymore?):
Setting "**active_low**" flag on linux SYSFS level does not have any effect on the logic state of the corresponding GPIO device inside domoticz.

When "**active_low**" flag is set, it can be seen that a logic inversion is indeed performed on SYSFS level, when printing the content of the corresponding "value". However in domoticz, the logic state remain unaffected by setting "**active_low**" flag, and it is also always the same as the one shown by wiringPi tool "**gpio**" or the "**raspi-gpio**" tool. 


Please see the outputs of following 2 command sequences (1st part with **active_low** flag _disabled_ and end part with **active_low** flag _enabled_) for demonstration of the problem:

_Test part 1: "active_low" flag NOT set_

```
pi@raspi-ospi:~ $ cat /sys/class/gpio/gpio9/value
0
pi@raspi-ospi:~ $ echo 0 > /sys/class/gpio/gpio9/active_low
pi@raspi-ospi:~ $ cat /sys/class/gpio/gpio9/active_low
0
pi@raspi-ospi:~ $ cat /sys/class/gpio/gpio9/value
1
pi@raspi-ospi:~ $ gpio read 9
1
pi@raspi-ospi:~ $ raspi-gpio get 9
GPIO 9: level=1 fsel=0 func=INPUT
```

_Test part 2: "active_low" flag set_

```
pi@raspi-ospi:~ $ echo 1 > /sys/class/gpio/gpio9/active_low
pi@raspi-ospi:~ $ cat /sys/class/gpio/gpio9/active_low
1
pi@raspi-ospi:~ $ cat /sys/class/gpio/gpio9/value
0
pi@raspi-ospi:~ $ gpio read 9
1
pi@raspi-ospi:~ $ raspi-gpio get 9
GPIO 9: level=1 fsel=0 func=INPUT
```

Note that the "real" input signal voltage level at this GPIO #9 was HIGH level throughout the test, i.e in both parts of the test.
As said, the state of the corresponding device associated with GPIO #9 remained at HIGH level thought the test as well, even though after each re-configuration of the GPIO port #9 (inside _/etc/rc.local_), the host was rebooted and domoticz restarted to allow for the changes of "**active_low**" flage to take effect inside domoticz.

I would really appreciate of someone could try to confirm this issue, maybe by trying to reproducing it. 
I really think that current "Generic SYSFS GPIO" hardware implementation has in domoticz has a bug wrt. to this **active_low** flag support.

Here are some details of the environment where I have been able to reproduce this:

Hardware: Raspberry Pi 3 Model B
OS: Raspbian 10 Buster
Domoticz version: Version: 2023.2
