### ISSUE TITLE
Zero Counter T2 values for in monthly overview.

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/domoticz#2855]
With V 4.10181 (and earlier), the web-interface report for energy consumption does show 0 values in  the Counter T2 column, although consumption is shown and the database (multi-meter calendar) does contain the Counter T1, Counter T2 and usage values:
![meter-webinterface report](https://user-images.githubusercontent.com/34967010/48262889-6fc5f500-e424-11e8-9dc4-61ec4fe5c390.png)
![multi-meter-calendar-database](https://user-images.githubusercontent.com/34967010/48262894-73f21280-e424-11e8-8e60-d19a9a43f4fd.png)

At least one other user reporting the same issue, see [forum-post](https://www.domoticz.com/forum/viewtopic.php?f=6&t=25574&p=197264#p197264).

**Comment by gordonb3** [comment]
So what do you see reported for `c3` in `json.htm?type=graph&sensor=counter&idx=1000&range=year&actmonth=11&actyear=2018`?

**Comment by TychoHae** [comment]
Can confirm that i have the same problem. The c3 values given by json.htm?type=graph&sensor=counter&idx=10&range=year&actmonth=11&actyear=2018   are correct in my case

 (my 'Stroom' (current) idx is 10 )

   "ValueQuantity" : "",
   "ValueUnits" : "",
   "result" : [
      {
         "c1" : "1743.833",
         "c2" : "0",
         "c3" : "1846.839",
         "c4" : "0",
         "d" : "2018-11-01",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "0.783",
         "v2" : "1.940"
      },

etc.

**Comment by bikeymouse** [comment]
Yep same here. 
C3 is filled with the calculated start of the day Counter of T2, which is:
databasevalue:  "Counter3" - "Value5" (End of the day Counter minus usage).

{
   "ValueQuantity" : "",
   "ValueUnits" : "",
   "result" : [
      {
         "c1" : "9823.160",
         "c2" : "0",
         "c3" : "7745.293",
         "c4" : "0",
         "d" : "2018-11-01",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "4.691",
         "v2" : "10.301"
      },
      {
         "c1" : "9827.901",
         "c2" : "0",
         "c3" : "7755.594",
         "c4" : "0",
         "d" : "2018-11-02",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "3.729",
         "v2" : "9.636"
      }, etc..

**Comment by gordonb3** [comment]
Okay, then the problem has to be in the web front-end javascript.

As you may know there have been some changes to this front-end with respect to compression. Would it be possible for you to clear the www folder and completely and rebuild it from the current version? Just to exclude the possibility that you may have a compressed old version and an uncompressed new version in there (because the compressed version is served first).

**Comment by gordonb3** [comment]
PS do mind your local browser cache

**Comment by bikeymouse** [comment]
Some additional info, I notice the result alway includes the first day of the next month and an additional record for the last day with missing values for c1,c2,c3 and c4:. 
E.g. for august the last 3 records are:

...
      {
         "c1" : "9410.103",
         "c2" : "0",
         "c3" : "7425.755",
         "c4" : "0",
         "d" : "2018-08-31",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "3.424",
         "v2" : "8.098"
      },
      {
         "c1" : "9413.561",
         "c2" : "0",
         "c3" : "7433.853",
         "c4" : "0",
         "d" : "2018-09-01",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "10.793",
         "v2" : "0.000"
      },
      {
         "d" : "2018-09-01",
         "r1" : "0.000",
         "r2" : "0.000",
         "v" : "11.249",
         "v2" : "23.566"
      }
   ],

I'm not sure if this is by design but this seems strange to me?

**Comment by bikeymouse** [comment]
Clearing cache and/or using private mode, has no effect. 
I'm not sure how to rebuild the www folder.

**Comment by TychoHae** [comment]
moving the www directory and upgrading to the server release with ./updatedomo  helped.
I will check if reverting to official beta will let the problem reapear.

**Comment by TychoHae** [comment]
updating to beta with ./updatebeta does not let the problem reapear

**Comment by gordonb3** [comment]
Sorry, yes. Copy the www folder from a `git clone` or run the update script which will essentially do the same thing. But I think we already got our answer form @TychoHae

**Comment by bikeymouse** [comment]
Mmmm, I did the same (moved the www folder, ./updaterelease and then ./updatebeata, cleared caches) but the error is still there.

@TychoHae I'm also wondering how you could see that everything worked after ./updaterelease, because - as I was afraid of - Domoticz did not start up with that version: Error: Database incompatible with this Domoticz version. (You cannot downgrade to an old Domoticz version!) 
After ./updatebeta I got back to the old situation again.

**Comment by TychoHae** [comment]
i didn't try ./updaterealease now because i had that : Error: Database incompatible with this Domoticz version. (You cannot downgrade to an old Domoticz version!)  earlier this week.

you say:
"Mmmm, I did the same (moved the www folder, ./updaterelease and then ./updatebeata, cleared caches) but the error is still there."

 but what you should do is 'move the www folder, ./updatedomo, clear caches' that recompiles domoticz from the most recent source
 sorry I should have said 'server revision' instead of 'server release'

another point is that it immediately worked in Falkon browser , but for Firefox i had to not only clean the browser cache but also delete the html5.appcache file in the www directory

**Comment by bikeymouse** [comment]
I now have tried Chrome, Safari and Brave all with history/caches cleared but no improvements.
Are you absolutely sure you see non-zero values in the T2 _**counter**_ column?

Also, I don't have a updatedomo script in my Domoticz folder, where did you get that from?

**Comment by TychoHae** [comment]
might have been included in older versions
 
either that or it came with a previous attempt to  compile from git

you can find it here

https://github.com/domoticz/domoticz/blob/development/updatedomo

I actualy assume you should have git installed also on your system

**Comment by gordonb3** [comment]
I guess this needs some better explaining. Unsure if this will do it though...

This is also purely theoretical as I don't actually use the update scripts myself. As far as I can see the scripts will pull in new files, overwriting what already exists and create what does not exist. What the update scripts apparently do *not* do is delete files that have become obsolete. This causes a problem with the project's transition from compressed .js.gz files to uncompressed .js files because the internal webserver in fact prefers the already compressed versions but these are the old ones.

By running updaterelease you most likely pulled in the compressed versions again which we wanted to get rid of. You should run updatebeta only, or if te version actually does need to be different from the one currently installed clear the www folder once more between running updaterelease and updatebeta.

**Comment by bikeymouse** [comment]
>You should run updatebeta only, or if te version actually does need to be different from the one currently installed clear the www folder once more between running updaterelease and updatebeta.

Mmm, your explanation is clear and makes sense. 
So I tried again, as described. But still missing the counter 2 values. Tried again. Used other browsers, cleared everything. No change. 
Perhaps specific files I can delete or check after ./updatebeta?

**Comment by gordonb3** [comment]
Can't tell. It's strange that it apparently worked for @TychoHae but somehow doesn't for you. Should still keep an open mind on the possibility that there is in fact an error in the current .js files. I am currently unable to verify - should be in a couple of days if the problem then still exists.

**Comment by gizmocuz** [comment]
It's true, it doesn't work at the moment. Probably caused by a (needed) JS/Angular upgrade.. 
Will have a look

**Comment by gizmocuz** [comment]
Thanks for reporting! Solved in beta 10198

**Comment by bikeymouse** [comment]
Yep, it is working again. Thanks Gizmocuz!
