### ISSUE TITLE
Adjust doesnt' work for some !

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#2881]
We have tried to use the forum in order to get support and identify where the problem is, but it looks like nobody is catching the topic.

https://www.domoticz.com/forum/viewtopic.php?f=4&t=25607

**Comment by gizmocuz** [comment]
Yes, but it has been explained before.
Devices that are being updated via the 'normal/standard' way, for example via the CDomoticzHardwareBase::SendTempSensor call, are being adjusted.
That is because in (for example) MainWorker::decode_Temp the addjustment value is taken count of.
Now it seems that some script systems are poking directly to the database, and do not follow the normal way of updating sensors.
For example, if you update a dummy temp sensor via JSON (udevice call) the adjustment value is taken into account because it's been taken care of
So to the authors of those systems, i urge you to use "MainWorker::UpdateDevice" !
That's all i can say about it, please discuss this with the authors of those (script) systems where it does not work please.
I did my best to make it work for all devices in the above mentioned function... for a reason...

I think some functions in PythonObjects.cpp needs to be re-programmed to call the above mentioned function

**Comment by pipiche38** [comment]
Please find here attached a plugin which simulate a Temperature sensor. Every heartbeat ( 10" ), the temperature is updated to 25°

If in Domoticz you request an adjustment
[plugin.py.gz](https://github.com/domoticz/domoticz/files/2615284/plugin.py.gz)
, this is never taken in consideration and the Sensor remains at 25°
<img width="558" alt="screenshot 2018-11-26 at 12 29 18" src="https://user-images.githubusercontent.com/8291674/49011514-f5f96f80-f176-11e8-9301-bf5249553d2c.png">

**Comment by pipiche38** [comment]
Could you kindly re-open this issue, in order that is visible.
I might investigate, but I'm not easy in C++ so might need guidance

**Comment by gizmocuz** [comment]
Thanks for this, i thought you where using the event system
If you create a virtual temp sensor (from the hardware page on a dummy hardware),
and use the JSON api 'udevice' to update the temp sensor, it should work

(/json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=TEMP)

**Comment by pipiche38** [comment]
Will try that.

I had a look to the code, and unfortunatly this is a big change as today the given API for update is only based on nValue and sValue as well as Subtype. While if we want to use the SendTempHumiPressur would require the 3 values in a raw.
EDITED/ just realized that the 3 values are in the sValues. So that should be feasible .

**Comment by pipiche38** [comment]
@gizmocuz 
I have made some progress on the code, but I have some issues to decode a strings into int in C++
For instance sValue received by the Python plugin comes in that format "0.0;50;1;1010;1" and I need to convert into int temp, hum, baro, nforecast

Do you have recommendation , or code example doing that ?

My idea is to use strtok( sValue, ';'), but then how to you convert the 0.0, 50, 1, 1010, 1 into int ?

**Comment by pipiche38** [comment]
Ok , I found sscanf(). 
Now strungling to get access to SendTempHumiPressur method in the PluginPython.cpp
