### ISSUE TITLE
Wrong case on filename  Config/telldus/TZWP102.xml

### ISSUE THREAD

**Issue by tkrill** [domoticz/domoticz#2894]
I had problems adding a  Telldus TZWP-102 . No configuration where listed for the device.

Cause seems to be that the config file is named TZWP102.xml while the manufacturer_specific.xml says telldus/tzwp102.xml

Looking further this seems to root from OpenZwave. Will open ticket there instead.

**Comment by tkrill** [comment]
OpenZwave have this fixed.

https://github.com/OpenZWave/open-zwave/commit/bbad59086c86448a0c5eedf8327fe09fc28eb1dd#diff-2b708cce833d951e17ae7b9faf0705ce

**Comment by gizmocuz** [comment]
Thanks! I just updated the configuration files this morning, so it should be ok now

**Comment by marin849** [comment]
The file is "back" to capitals in the official download of Domoticz 2020.2.11995.
I discovered it because my configuration disappeared after updating Domoticz, so I had to rename the file and exclude/include and remap the sensors again.

In OZW it is small: https://github.com/OpenZWave/open-zwave/blob/master/config/telldus/tzwp102.xml
