### ISSUE TITLE
EUROtronic EUR_SPIRITZ Wall Radiator Thermostat

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#2906]
This thermostat creates a few devices, under which a 'Thermostat Mode' device.
When you edit the device you can change the mode, but on the web display of this device the mode is not visible, nor is the icon changed to an Off display when the mode is 'Off'
There is nothing visible on the outside display of the device.

**Comment by pipiche38** [comment]
I had a look to that one, as I wanted to use this sType in order to create a Thermostat Mode inside a dedicated plugin.
Unfortunately it looks like sTypeZWaveThermostatMode is RESERVED to ZWave Hardware only and the modes seems to be hardcoded or something like that !

Could we have a widget sTypeThermostatMode which should be based on the same approach of the ZWaveThermostatMode but instead having the various mode stored in the Options field, as it is done for the Switch Seelctor ?

**Comment by waltervl** [comment]
Still an issue or already solved in some release?

**Comment by kiddigital** [comment]
Can be closed as duplicate/follow-up by #4525
