### ISSUE TITLE
PVOUTPUT API changes

### ISSUE THREAD

**Issue by zandhaas** [domoticz/domoticz#2911]
### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for Domoticz CODE Bugs only. Please do not use this for general questions, howto, or this is not working conversations. If you have a question, please post to our forum at https://www.domoticz.com/forum
* Please use the search feature to see if your issues have been raised or addressed first.
* First try to update to the latest beta version.
* Always state your version when reporting code related issues
* Often we will require Log Files and Screenshots to help diagnose the issue.

**Comment by zandhaas** [comment]
PVOUTPUT has limited the number of API calls to 6 per hour.
Bacause the PVOUTPUT importer imports data every 5 minutes we get login erros the second half hour.

It would be nice to ad an variable in which we can set the frequency for importing PVOUTPUT data

**Comment by gizmocuz** [comment]
I don't like to have 100's of configuration parameters, it confuses users a lot
So setting it to poll every 10 minutes will solve the problem ?

**Comment by Aad3229** [comment]
If I may comment: It would be perfect to change the interval to 10 minutes, this will solve the problem. I already posted this request in the domoticz forum (https://www.domoticz.com/forum/viewtopic.php?p=200354#p200354)

**Comment by Aad3229** [comment]
New comment on the PVOutput forum: they set the rate limit back to what is was:

"The rate limit has been increased to 12 and 60 per hour for regular and donation accounts respectively.
Get Statistics results for the same query are now cached for 24hrs and will result in the same statistic for 24 hrs. Making a request every 5-minutes is now redundant."

Only now in domoticz the PVOutput Today count and the Total count are not updated anymore. This has to do with "Get Statistics results for the same query are now cached for 24hrs and will result in the same statistic for 24 hrs" . 

So now the problem is worse then before

**Comment by gizmocuz** [comment]
So the poll interval should be set back to 5 ?

**Comment by Aad3229** [comment]
PVOutput has reset the number of API calls to 12 per hour (as it was before). The limit of 6 calls has been cancelled. So as far as I know the interval in domoticz can be set to 6 calls an hour or not have to be changed. Setting the number of API calls in domoticz to 6 per hour however saves overhead. The problem now is that "Get Statistics" results for the same query are now cached for 24 hrs and will result in the same statistic for 24 hrs. So the "PVOutput today count" and the "Total count" in domoticz only updates once a day. 
I don't think domoticz can solve the 24 hour caching of the "get statistics" query in PVOutput?
