### ISSUE TITLE
Aqara wired wall switch -> Convert to wireless (not working)

### ISSUE THREAD

**Issue by vbbelous** [domoticz/domoticz#2945]
Aqara wired wall switch (no neutral): QBKG03LM (double button), QBKG04LM (single button)
MiHome -> Aqara wired wall switch -> Menu -> More function -> **Convert the button to a wireless switch (On)**
When button was click - MiHome log display "Click" or "Double-click" but **Domoticz log is empty and there are no events**.

**Comment by vbbelous** [comment]
if add XiaomiMessage: 1
When system started In log display devices as "ctrl_neutral1" and "ctrl_neutral2", but no messages when button was clicked (

**Comment by gizmocuz** [comment]
Please use the forum

**Comment by timdonovanuk** [comment]
Any update on this? The poster was ignored on the forum so....

http://www.domoticz.com/forum/viewtopic.php?f=6&t=26424&p=203572&hilit=aqara+switch#p203572

**Comment by gizmocuz** [comment]
Well this is not the place to discuss this, the forum is

**Comment by timdonovanuk** [comment]
It's an issue with the code, so why not exactly? There is also no discussion of the *issue* the forum.

**Comment by gizmocuz** [comment]
Yes, and here this should be discussed by developers. If you are one, and want to have a look at this issue, please!

**Comment by timdonovanuk** [comment]
Sure, will you reopen the issue then? ;) 

I don't have a domoticz compatible USB device yet, purchase of one depends on its ability to handle this exact issue. So I cannot do any tests. However I've taken a look at the code, I would imagine it's an issue in XiaomiGateway.cpp around line 1246 with the way aqara broadcasts the switches. I would hazard a guess putting the switch in "decoupled mode" adds 2 additional channels (2 & 3) so that the physical state of the switch can still be assessed on channels 0 and 1, with the decoupled state of the switch assessed on channels 2 & 3. At the moment only 2 channels are assessed:

std::string aqara_wired1 = root2["channel_0"].asString();
std::string aqara_wired2 = root2["channel_1"].asString();

**Comment by waltervl** [comment]
Stale, can be closed
