### ISSUE TITLE
Kindly asking...

### ISSUE THREAD

**Issue by RicardP** [domoticz/domoticz#2977]
...what damaged the win beta builds? :)

**Comment by Olifant1990** [comment]
Why did you close this question?
I want to know this too :)

@gizmocuz ?

**Comment by RicardP** [comment]
Well, I thought after a day open it was read by those concerned, meant just a hint :)

**Comment by gizmocuz** [comment]
It's probably a visual studio version issue that needs to be fixed... you should be able to find it in the appveyor logs

**Comment by Olifant1990** [comment]
I have no experience with Appveyor/the build mechanism, but the only hard error I can see is this:

Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:01.61
Collecting artifacts...
Found artifact 'domoticz_windows_x86.zip' matching 'domoticz_windows_x86.zip' path
Found artifact 'History.txt' matching 'History.txt' path
Found artifact 'history_windows_x86.txt' matching 'history_windows_x86.txt' path
Found artifact 'version_windows_x86.h' matching 'version_windows_x86.h' path
Uploading artifacts...
[1/4] domoticz_windows_x86.zip (13,525,668 bytes)...100%
[2/4] History.txt (88,184 bytes)...100%
[3/4] history_windows_x86.txt (88,184 bytes)...100%
[4/4] version_windows_x86.h (82 bytes)...100%
Deploying using FTP provider
Cannot connect SFTP server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Could this be the reason?
And can someone change this somewhere?
Because I don't know the login details of some FTP server etc. :P

**Comment by gizmocuz** [comment]
Appveyor is currently working again, but the problem is with FTPS.
I will do another attempt to use the same deploy mechanism that i use for travis buils (making use of curl)

@Olifant1990 , you do not need the FTP details, they are already in the script ($(FTP_HOST) etc)

**Comment by gizmocuz** [comment]
Closing this for now, got it working again (not with FTPS unfortunately)

**Comment by RicardP** [comment]
Thanks!! :)
