### ISSUE TITLE
Week and month report incorrect

### ISSUE THREAD

**Issue by enboer** [domoticz/domoticz#3007]
I have added a watermeter which uses a counter. The day graph is ok but the week and year not. On the forum I posted details: 
https://www.domoticz.com/forum/viewtopic.php?f=6&t=26664&p=204522#p204522

As described there the database values for the day usage are ok, but the json string reports wrong values.

Currently I am on the lastest beta 10394

**Comment by gizmocuz** [comment]
Don;t encounter this issue here..

![image](https://user-images.githubusercontent.com/2265299/52174363-d728e200-2792-11e9-9cb5-b119995223a8.png)

21324-20960 = 364

graph:
![image](https://user-images.githubusercontent.com/2265299/52174365-e7d95800-2792-11e9-9572-f5d8d8e5177b.png)

My meter type is:
![image](https://user-images.githubusercontent.com/2265299/52174370-f7f13780-2792-11e9-8145-b037d74ae766.png)

is yours different ?

**Comment by enboer** [comment]
Yes that is also what I have, but the report is incorrect. Imagine it is Monday, in the weekreport I see the correct value of the Monday during the day. But after midnight, so the next day the value is something I cannot determine where it comes from.

**Comment by gizmocuz** [comment]
That is the current counter value (from the devicestable) and the first counter value of the day (from the Meter table), or the last value from the meter table minus the first value

**Comment by enboer** [comment]
I was able to solve the issue, seems that the meter_calender table was not correct. When I looked at this table I saw all values. But if I sorted on a field/column I saw all kind of null/empty data.
I exported the table to .sql, deleted it and imported the .sql file again. Now I see correct data.

**Comment by gizmocuz** [comment]
Great! Closing issue
