### ISSUE TITLE
Virtual switch selector - more function

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#301]
Hello
I want start use seitch selector but...
1. Good option will be add when user add level to can set type level:
- normal button ( as now)
- double position button on/off (example to on off mute in AV Reciver)
- push button (as button in scene, one click one position)
1. Next feature should be good is to add option add on command to every button/level. Better for user will be that user can set on some level command on and  command off on every level. 
2. End option is add level/info text to show text info with option to can set also command by http with set time refresh. Or with own IDX to user can add to cron script which send to IDX info to show.

When user create push button , user has only option to add one command.
When user create button on/off , user has two command: fist to ON and second to OFF.

This function will be good to control some devices. I want use push button to control my AV Reciver DENON which has send command by http. To set VOLUME + - and double position button to MUTE ON and MUTE OFF.

Please developer who improved this function switch selector add option as i describe.

![selector](https://cloud.githubusercontent.com/assets/4134018/12195075/fb0c4436-b5f4-11e5-9794-ac429f4d0821.jpg)

**Comment by gaudryc** [comment]
I'm sorry but a Selector Switch can only have one level (state) at a time, and it will stay like this otherwise it would not be a selector switch.

What you need is a 5 in 1 device :
- one button switch to power On/Off ;
- one Selector switch to select the audio source ;
- two push buttons to change volume ;
- one button switch to mute.

At this time you can do all you want using 5 switch devices and/or making a custom HTML page.

**Comment by ghost** [comment]
:(
But is any chance to change Switch selector as i describe in future ? You can think about it ?

**Comment by gaudryc** [comment]
I'm adding :
- a parameter to hide Off level ;
- a list of actions to execute each time a level is activated (one action per level) ;
- tooltips on Rename/Edit/Delete buttons.

Do you need something else ?

**Comment by ghost** [comment]
Good Job :)

But maybe you can add select button type as normal, on/off and push button(as in scene or wake on lan button). ? Then i can use it to set Volume command in my Denon AV Reciver.

**Comment by gaudryc** [comment]
I will not change the purpose of this switch. I have to keep it as simple as possible so that it can serve various purposes.
What you need is another switch, a dedicated switch.

**Comment by ghost** [comment]
But add option to user can select type switch. User will decided what switch want use.

**Comment by gizmocuz** [comment]
@gaudryc, i agree

**Comment by ghost** [comment]
But maybe you can add switch selector with slider dimmer ?
When slider dimmer was implement with switch selector i can done control my Denon in one device :) And then i describe how. But i must have Switch selector with dimmer. All in one. Is any chance ?

**Comment by nayrnet** [comment]
The current Dimmer switch needs more steps, it cant be used as a volume control with a range of only 14. (ie, 14=100%, 7=50%)

Ive used the percentage output to show volume, but I set it externally from domoticz.. need a switch like a dimmer thats with at least 100 steps (0%-100%), probably displayed as a knob that can be turned and two buttons for +/- fine tuning.

Im fine with different switches for selecting inputs and toggling mute, thats how I expect it to be, I see no point in a specific receiver multifunction device but volume is entirely unworkable.. I had this same issue with the dimmer switch trying to hookup 3 channel LED lights for my aquarium, 14 steps were not suitable for getting any decent color out of the dimmers.

I think the best solution is a % display that pops up a text input with arrows kinda like the heater setpoint when clicked, and a slider/knob with the capability to set at least every other %.. I dont see why this cant just be the standard dimmer for everything and just have the device calculate to the nearest step it supports.

**Comment by gizmocuz** [comment]
the pTypeGeneral switch has more steps

**Comment by mzuidwijk** [comment]
I would love to have a virtual RGB dimmer. One that can pass the RGB code to a lua script. I've got some home made RGB led's which I'd like to use in Domoticz.

**Comment by nayrnet** [comment]
@gizmocuz, but how do I use that switch? If I add a virtual switch and make it a dimmer I get 0-15 as 0%-100%

**Comment by mzuidwijk** [comment]
@nayrnet try this link: http://blog.quindorian.org/2015/01/esp8266-wifi-led-dimmer-part-4-of-x.html
32 steps dimmer (actually 31, 0==off)

**Comment by nayrnet** [comment]
actually I got what I wanted by changing it to: pTypeLimitlessLights, sTypeLimitlessWhite

the pTypeGeneral,sTypeSwitch @gizmocuz suggested did not work for me.

I have since created a proposal for a better dummy switch, here: https://github.com/domoticz/domoticz/issues/379

**Comment by nayrnet** [comment]
Spoke too soon, that did not work.. I cant update it at all with JSON.

Thanks for the tip but 32 steps is still not enough IMHO, my AVR has 185 steps for volume, most I am willing to cut that back to is 100, loosing nearly half the resolution.. any other ideas?

Selector switch has been a godsend for my AVR, went from a dozen buttons and a ton of scripts to toggle devices, and now this:
![screen shot 2016-01-24 at 1 31 50 am](https://cloud.githubusercontent.com/assets/3732081/12535869/5e408e7a-c24f-11e5-891d-8959943610a9.png)

but alas, that volume slider is just for looks right now because my software is dividing the output by 1.85 thus sending in ranges from 0-100.. I could modify my software, but I'd rather not have a volume control that goes from too quiet, to too loud in a single step

**Comment by gizmocuz** [comment]
I think this switch is pretty nice made at the moment ! Could we close this issue ?

**Comment by gizmocuz** [comment]
Closing issue
