### ISSUE TITLE
New beta version

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#3017]
The new **beta** version notification display "latest changes, click here"
If we click "here" the history file of the **stable** version is displayed !

**Comment by gizmocuz** [comment]
Nope , don't have that issue here...

![image](https://user-images.githubusercontent.com/2265299/52258867-f2c1f300-2920-11e9-8730-b45b3ae5a338.png)

![image](https://user-images.githubusercontent.com/2265299/52258883-feadb500-2920-11e9-84cd-b275cb15f2c3.png)

Not that there are any changes documented currently, for now best to check on github

**Comment by ghost** [comment]
OK
For stable version, press "Click Here"
For beta version, check github
