### ISSUE TITLE
EnOcean ESP3 : device profile D2-14-30 not handled - But should be ?

### ISSUE THREAD

**Issue by msalles-winn** [domoticz/domoticz#3036]
Domoticz last release version 4.97
Raspberry PI 3
Tested with git clone, cmake, make yesterday same result

Hardware used : EnOcean ESP3
Hardware EnOcean : INSAFE+ Origin, EPP D2-14-30 (https://www.enocean-alliance.org/product/indoor-air-quality-monitor-and-smoke-detector-insafe-origin/)

Problem : 

> 2019-02-08 10:40:43.378  Status: New sensors allowed for 5 minutes...
> 2019-02-08 10:40:47.289  Status: EnOcean: 01 (0D/07) D4 40 FF 6D 00 30 14 D2 81 00 0B 4E 80 00 FF FF FF FF 4A 00
> 2019-02-08 10:40:47.290  EnOcean: destination: 0xffffffff RSSI: 26
> 2019-02-08 10:40:47.290  EnOcean: teach-in request received from 81000B4E (manufacturer: 06D). number of channels: 255, device profile: D2-14-30
> 2019-02-08 10:40:47.290  EnOcean: Sender_ID 0x81000B4E already in the database

After a moment : 

> 2019-02-08 10:47:47.438  Status: EnOcean: 01 (0C/07) D2 00 00 F0 E2 BA 00 81 00 0B 4E 80 00 FF FF FF FF 4F 00
> 2019-02-08 10:47:47.438  EnOcean: destination: 0xffffffff RSSI: 21
> 2019-02-08 10:47:47.438  EnOcean message VLD: func: 00 Type: 00
> 2019-02-08 10:47:47.438  EnOcean: Unhandled RORG (d2)

I read the source code of EnOcean ESP3.cpp, it seems to be handled (D2 = VLD ?), I am a developper but not really low level. 

As I do not understand the source code properly, it seems to be unhandled, but it can be a bug. 

If it is not a bug, it could certainly add some code to handle this kind of device but I would need some documentation to do so.

**Comment by gizmocuz** [comment]
Did you try the beta version?

**Comment by msalles-winn** [comment]
Yes. I also cloned the github project, compiled it and runned it on my rasp, same result.

**Comment by alexis-via** [comment]
Looking at the source code EnOceanESP3.cpp, you can see that profile D2-14-30 is not supported. It should not be very difficult to add. The specs of the profile are here http://tools.enocean-alliance.org/EEPViewer/profiles/D2/14/30/D2-14-30.pdf
I recently added support for the smoke detector profile F6-05-02, cf my pull request https://github.com/domoticz/domoticz/pull/4629/files
The diff is big because I also added support for RSSI. In your case, only a small subset is interesting: line 1955 of the diff and above:
```
SendSwitch(id, 1, batterylevel, alarm, 0, "Detector", m_Name, rssi);
```
You would also need a call to SendTempHumSensor() like here:
https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1717

So start at this line of code: https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L2201
add your "else if", parse the Enocean packet according to the specs and call SendSwitch() for the smoke alarm and SendTempHumSensor() to report temperature and humidity. Happy hacking :)

**Comment by efdeb** [comment]
I do not own the device, so the implementation is only based on EnOcean ESP3 specification.
Can someone confirm it is now OK ?
