### ISSUE TITLE
Json/url api for user variable changed since 4.10456?

### ISSUE THREAD

**Issue by Xorfor** [domoticz/domoticz#3067]
According to the wiki page https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s, the types for the user variables were defined as:

0 = Integer, e.g. -1, 1, 0, 2, 10 
1 = Float, e.g. -1.1, 1.2, 3.1
2 = String
3 = Date in format DD/MM/YYYY
4 = Time in 24 hr format HH:MM
5 = DateTime (but the format is not checked)

But this seems changed today? It looks now that the types are:

0 = Integer, e.g. -1, 1, 0, 2, 10 
1 = Float, e.g. -1.1, 1.2, 3.1
2 = Date in format DD/MM/YYYY
3 = Time in 24 hr format HH:MM
4 = String
???

Current scripts with json/api calls to uservariables with the type string, date and time are not working anymore and have to be changed!!!

**Comment by gizmocuz** [comment]
Thats why i made the patch yesterday to avoid using number internally and i looked this function "CSQLHelper::CheckUserVariable" when making the enum, but that was not in logical order

Corrected both, should work again.

There is no type 5... and i would not use that, because when we are extending the user variable types, the next in line is '5', it's type to be seen yet

At the moment, if you specify an invalid type (like 17) the check function still returns OK, i think this should return a error ?

**Comment by Xorfor** [comment]
Thnx. It works again correct.

Yes, please return "status": "ERR". And in "message" something like "Invalid data type"?

**Comment by gizmocuz** [comment]
@Xorfor , thanks for the feedback !
What JSON call should return the error ?

I see some funky UserVariable code... and i see your problem/issue as well...

Corrected the code... Also type '5' is not known anymore. If it needs to be a DateTime (with an undefined format).... i suggest to use a string for this ;)

Hope all works correct now (beta 10531+, could take a few hours until beta is available)

https://github.com/domoticz/domoticz/commit/bf19d8bbb9fac08bc3ae93740cb46545d8e1826b

**Comment by Xorfor** [comment]
@gizmocuz 
I did a lot of testing and all json calls gave the correct responses with the messages. 
I also updated the wiki page to remove type '5' (and also changed 'saveuservariable' to 'adduservariable' :) )
Thnx!

**Comment by gizmocuz** [comment]
Thank you for the feedback and changes !!
