### ISSUE TITLE
Weather Underground plugin broken due to API change

### ISSUE THREAD

**Issue by funxiun** [domoticz/domoticz#3127]
Due to a change in the API the Weather Underground (wunderground) plugin stopped working.

Links to how the new API is working and how to obtain new API keys is discussed over here: https://apicommunity.wunderground.com/weatherapi/topics/turning-off-pws-associated-keys

Thanks in advance for fixing this! :)

**Comment by Utopia69** [comment]
new api docs
https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit

**Comment by gizmocuz** [comment]
Try beta 10572, i don't see any 'visibility' values anymore...

**Comment by Utopia69** [comment]
with beta 10572 I get:
Error: Wunderground: Error getting http data! (Check API key!)
I updated my api key already

**Comment by gizmocuz** [comment]
@Utopia69 , for location your HAVE to enter a VALID StationID or lat,long

**Comment by Utopia69** [comment]
@gizmocuz with location I use my station ID (ININOVE7).
Is pws: still needed?

**Comment by gizmocuz** [comment]
@Utopia69 , no idea... maybe, or you have to pay now...

Try the below URL: (change some parameters)

https://api.weather.com/v2/pws/observations/current?stationId=XXXXXX&format=json&units=m&apiKey=YYYY

**Comment by Utopia69** [comment]
ok great, works now
without "pws:"
Indeed visibility' isn't working (returned by api) anymore.
thanks

**Comment by funxiun** [comment]
Yes, I can confirm that the Weather Underground plugin is working again since beta 10572.
In the hardware config of the plugin the heading pws: string for the station ID is not needed anymore. Only the station id is needed.

Thank you very much for the fast fix!

**Comment by dyter** [comment]
https not work on my docker version, is it possible to have a http version of this or external plugin ?

_sURL << "http://api.weather.com/v3/location/point?geocode=" << szLoc << "&language=en-US&format=json&apiKey=" << m_APIKey;
sURL << "http://api.weather.com/v3/location/near?geocode=" << Latitude << "," << Longitude << "&product=pws&format=json&apiKey=" << m_APIKey;
sURL << "http://api.weather.com/v2/pws/observations/current?stationId=" << szLoc << "&format=json&units=m&apiKey=" << m_APIKey;_
instead of
_sURL << "https://api.weather.com/v3/location/point?geocode=" << szLoc << "&language=en-US&format=json&apiKey=" << m_APIKey;
sURL << "https://api.weather.com/v3/location/near?geocode=" << Latitude << "," << Longitude << "&product=pws&format=json&apiKey=" << m_APIKey;
sURL << "https://api.weather.com/v2/pws/observations/current?stationId=" << szLoc << "&format=json&units=m&apiKey=" << m_APIKey;_

thanks

**Comment by gizmocuz** [comment]
@dyter , no... everything is going to https soon, so you better get your docker fixed

**Comment by octavianrusu** [comment]
Thank you, wundergroud is working with domoticz again. 
However, there is an issue with the value for wind speed, the value is always bigger than reported by my station to wundergroud. It seems that there is a problem with the units. 
I did the following to understand what's happen: using the link to api weather I get 11 for wind speed (metric is stated in the response), but domoticz show 18 km/h (this is the unit for wind speed in domoticz settings). 
I don't know where this value is coming from but it is possible that domoticz assume the wind speed is in mph and convert it to km/h (the value would be 17,7, rounded to 18). 
Maybe something could be done to fix that.
Thank you.

**Comment by gizmocuz** [comment]
@octavianrusu , best to just start looking in the code,,,
the WU class is not big

https://github.com/domoticz/domoticz/blob/development/hardware/Wunderground.cpp

it is assumed it is being reported in m/s from WU

**Comment by peerk72** [comment]
it seems it's not working anymore
i think on line 156 the call to v2 off the api should be changed in a call to api v3
see also my comment in the domoticz forum 
https://www.domoticz.com/forum/viewtopic.php?f=12&t=27246&start=20#p216719

**Comment by gizmocuz** [comment]
@peerk72 , please do not cross post on 3 locations !
