### ISSUE TITLE
Openzwave cannot add values for slat en tilt position

### ISSUE THREAD

**Issue by Vinisz** [domoticz/domoticz#3221]
Although slat en tilt postitions can now be set in OZWCP, I'm unable to set them in domoticz.
Following is shown in the log when moving the blinds.

```
Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 72 (0x48), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian Blind slat position, Instance: 1, Index: 0
2019-05-16 09:56:34.148 Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 72 (0x48), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1
```

Version: 4.10763
Build Hash: 792e9a60
Compile Date: 2019-05-16 09:00:25
dzVents Version: 2.4.20
Python Version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

**Comment by gizmocuz** [comment]
Could you show a screenshot from the control panel ?
The should also be a warning/error for an unknown command class before this ?
Could you post your cache file ? (config folder, zwcache_xxxx.xml)
Please Select the controller (node 1), enable debugging, and disable/enable the hardware
Set the position a few times like 100%, 0%, and 50%
Then copy the log file (Config/OZW_Log.xml) and post this as well
Then select the controller (node 1) and disable debug logging, and disable/enable the hardware again

**Comment by Vinisz** [comment]
Ok, I can do that... but what exactly do you mean with “disable/enable the hardware” ?

**Comment by gizmocuz** [comment]
@Vinisz , from the hardware page select the zwave hardware, disable it, press update, then enable it, press update
This forces a restart of the zwave hardware

**Comment by Vinisz** [comment]
Ok, I think I am able to do this later today

**Comment by Vinisz** [comment]
Hi, I put everything in a zip, hope this helps and is enough....
For in the log, I did move the blinds as well as the slats positions to some different values from the OZWCP. please note that I am able to control both from the OZWCP just fine, I am only missing the ability to control the slats position from domoticz itself, if you can add that it would be really awesome, for me, it is about the only thing I am missing now...

[Venetian blinds case.zip](https://github.com/domoticz/domoticz/files/3204333/Venetian.blinds.case.zip)

**Comment by svde** [comment]
With recent domoticz and openzwave releases I'm also able to tilt using owzcp.

Looking at the domoticz.logDevice for that device in dzVents, I don't see any hints of how it can be done using dzVents (or domoticz).

**Comment by gizmocuz** [comment]
@svde , what do you mean with "using owzcp" ... does the value not show up in Domoticz?
If not, this has to be supported first.
Is the Tilt a button ? Or a value/slider position ?
Could you post a screenshot of this ?

**Comment by svde** [comment]
With "using owzcp" I mean changing the "0" into "50" and quickly pressing submit. Link to [picture](https://www.eijk.nu/se/Annotation%202019-07-16%20172314.png).

I think it's 0-99%.

**Comment by gizmocuz** [comment]
And is the Tilt added to domoticz as a switch (that you can set to a dimmer)

**Comment by svde** [comment]
No, it's not added. [These ](https://www.eijk.nu/se/Annotation%202019-07-17%20080643.png) are the devices I see for it. There is one [switch](https://www.eijk.nu/se/Annotation%202019-07-17%20081815.png), which I've added. It has two buttons (open / close) and a slider (the status they're showing is a bit off, at the moment the blinds are actually closed). These work for positioning the blinds, but not for tilting. I can imagine that a second set would need to be added to support tilting. Would be nice it it can be done on the same tile, but probably too small / busy.

[This](https://www.eijk.nu/se/2017.07.17.txt) is the result of a domoticz.logDevice for that device in dzVents.

**Comment by gizmocuz** [comment]
@svde , i think i forgot to post something yesterday. Could you update to version 11019 and check if the tilt sensor is added ? (make sure accept new hardware/devices is enabled in the settings first)

**Comment by svde** [comment]
> @svde , i think i forgot to post something yesterday.

@gizmocuz I noticed :-)

I'm on 11020 now, I don't see new devices in the "Setup --> Devices" list. Also no notable [differences](https://www.eijk.nu/se/2019.07.18.diff.txt) in the domoticz.logDevice.

> (make sure accept new hardware/devices is enabled in the settings first)

Not sure what you mean here.

**Comment by gizmocuz** [comment]
@svde , ok, so probably here it went wrong
In the settings, on the main page at the bottom , enable "Accept new Hardware/Sensors"
Then press the red Apply button on the top right
Next 'disable' the openzwave hardware, wait a few seconds, select it again, enable it and press update
Now (i hope) there should be two new switches (one of them tilt), you have to add them to the system, go to the light/switches, and set them as 'dimmer' (if there where not already)

**Comment by svde** [comment]
[This](https://www.eijk.nu/se/Annotation%202019-07-19%20080951.png) is my setting for "Accept new Hardware/Sensors".

Disable OpenZwave, press update.
wait 30 sec
Enable OpenZwave, press update.
wait for the OpenZwave device to complete its initialization dance.
Then the new devices should show up in the device list, but they don't :-/

**Comment by gizmocuz** [comment]
I hoped it was working... Ok i do not own such a node, could you debug the code ?
Otherwise you might be able to set it via a json call

https://www.domoticz.com/forum/viewtopic.php?t=12818

**Comment by svde** [comment]
Looking at the links, it seems that they're changing the configuration of the zwave device rather than the values. The "Venetian blind tilt position" is similar to the "Venetian blind slat position".

Some Openzwave [debugging](https://www.eijk.nu/se/2019.07.22.1.txt)

`    
  <CommandClass id="145">
    <Value genre="user" type="byte" instance="1" index="0" label="Venetian Blind slat position" value="0" min="0" max="100" units="%" />
    <Value genre="user" type="byte" instance="1" index="1" label="Venetian blind tilt position" value="0" min="0" max="100" units="%" />
  </CommandClass>`

**Comment by Vinisz** [comment]
Maybe not worth mentioning it, but you might have a look at openhab, they have it working.... (no idea if you can view that code or something...)

**Comment by svde** [comment]
Discussion on the openhab [forum](https://community.openhab.org/t/fibaro-roller-shutter-fgrm-222-with-venetian-blinds-lamellas-position/9396/7).

**Comment by petergebruers** [comment]
@gizmocuz cannot look at Domoticz code right now, so have to guess a bit but by looking at the log of @svde this is about tilt on a FGRM222, the older Fibaro roller shutter. It uses COMMAND_CLASS_MANUFACTURER_PROPRIETARY to get/set slat position. Is it possible you do not handle that CC?  Afaik apart from using that special CC, OZW creates ValueIDs for it like for any other class and that's why he sees both blind and slat position in ozwcp

**Comment by petergebruers** [comment]
I have had a quick look at that openhab discussion and indeed after a while they seem to realize the FGRM-222 indeed uses cc MANUFACTURER_PROPRIETARY.

If you look at the config file for this device, you will notice it already has an entry for cc 145 (iirc) == MANUFACTURER_PROPRIETARY - ozwcp works so no need to look in that direction...

**Comment by gizmocuz** [comment]
@petergebruers , i am unable to test this, but i implemented this in domoticz a few days ago (line 2261),
and only for this hardware:

		if (
			(pNode->Manufacturer_id == 0x010F)
			&& (pNode->Product_id == 0x1000)
			&& (pNode->Product_type == 0x0302)
			)
		{

@svde , could you check if your node has these id's ?

**Comment by svde** [comment]
Yes, they have those [ID's](https://www.eijk.nu/se/Annotation%202019-07-23%20093303.png).

**Comment by svde** [comment]
Is there anything I can do to move this forward?

**Comment by petergebruers** [comment]
At the moment, all I know is this:

- ozwcp can control position and tilt of your FGRM-222 so there is no OpenZWave issue with this device (which matters to me because I am an OZW contributor).

- @gizmocuz added this code on Jul 23:

```
if (commandclass == COMMAND_CLASS_MANUFACTURER_PROPRIETARY)
{

...

if (
    (pNode->Manufacturer_id == 0x010F)
    && (pNode->Product_id == 0x1000)
    && (pNode->Product_type == 0x0302)
    )
{
    //Fibaro FGRM222 Roller Shutter Controller 2
    //Slat/Tilt position
    if (vType == OpenZWave::ValueID::ValueType_Byte)
    {
        if (m_pManager->GetValueAsByte(vID, &byteValue) == true)
        {
            _device.devType = ZDTYPE_SWITCH_DIMMER;
            _device.intvalue = byteValue;
            InsertDevice(_device);
        }
    }
```

So if you run a beta, built after that date, you should see a "Dimmer" (if you accept new hardware) representing the value for that specific cc MANUFACTURER_PROPRIETARY which is that particular setting you are after...

Technically, that sounds correct, cannot test. I might be able to test this in September, but right now I do not have a FGRM-222 available...

Did you (re-test) with a beta after Jul 23?

**Comment by svde** [comment]
I'm on 4.12218. Accept new hardware is on. I have two FGRM-222's:

007 (0x07) | Sunscreen right | FIBARO System FGRM222 Roller Shutter Controller 2 | FIBARO System | 0x1000 | 0x0302 | 2019-08-24 11:32:03 | No
006 (0x06) | Sunscreen left | FIBARO System FGRM222 Roller Shutter Controller 2 | FIBARO System | 0x1000 | 0x0302 | 2019-08-24 11:32:53 | No

These are the [devices](https://www.eijk.nu/se/Screenshot%202019-08-24%20at%2011.43.46.png) that match "openzwave 006" (7 in total) and these [devices](https://www.eijk.nu/se/Screenshot%202019-08-24%20at%2011.44.24.png) match "openzwave 007" (6 in total).

Seems that a new device was created for the 006 (idx 512), I added it, and changed it to dimmer. When I slide the dimmer it doesn't change the "Venetian blind tilt position" but it changes the "Venetian Blind slat position" (just like the idx148 does).

Just speculating:
- the new code only adds the device for the first FGRM-222 (not for subsequent ones);
- the code operates the manufacture specific index 0 (slat position), while we're looking for index 1 (tilt position).

`  <CommandClass id="145">
    <Value genre="user" type="byte" instance="1" index="0" label="Venetian Blind slat position" value="0" min="0" max="100" units="%" />
    <Value genre="user" type="byte" instance="1" index="1" label="Venetian blind tilt position" value="0" min="0" max="100" units="%" />
  </CommandClass>`

**Comment by svde** [comment]
I also found this in the logging:

`Aug 24 08:11:38 void domoticz[18063]: 2019-08-24 08:11:38.550  OpenZWave: Value_Added: Node: 6 (0x06), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1
Aug 24 08:11:38 void domoticz[18063]: 2019-08-24 08:11:38.554  OpenZWave: Value_Added: Node: 7 (0x07), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1
Aug 24 08:11:38 void domoticz[18063]: 2019-08-24 08:11:38.574  OpenZWave: Value_Added: Node: 15 (0x0f), CommandClass: MANUFACTURER PROPRIETARY, Label: Venetian blind tilt position, Instance: 1, Index: 1`

and as a result of touching the dimmer device:
`Aug 24 11:27:31 void domoticz[18063]: 2019-08-24 11:27:31.010  Status: User: Admin initiated a switch command (512/Sunscreen left tilt/Set Level)
Aug 24 11:27:31 void domoticz[18063]: 2019-08-24 11:27:31.012  (OpenZWave) Light/Switch (Sunscreen left tilt)
Aug 24 11:27:42 void domoticz[18063]: 2019-08-24 11:27:42.962  Status: User: Admin initiated a switch command (512/Sunscreen left tilt/Set Level)
Aug 24 11:27:42 void domoticz[18063]: 2019-08-24 11:27:42.966  (OpenZWave) Light/Switch (Sunscreen left tilt)`

**Comment by gizmocuz** [comment]
@svde , unfortunately i don't own this hardware, but your point about only supporting index 0 could be right.
Could you try beta 11223 ? That might solve the issue (make sure accept new hardware is enabled, there could/should be a new switch which you have to set as dimmer)

**Comment by svde** [comment]
Tested it. New device was created. Added it, but sliding the dimmer doesn't do anything (no tilting).

**Comment by gizmocuz** [comment]
Could you post a screenshot of the two switches from the devices tab ?
(Just want to check the id's)
Getting closer...

Does the old switch/dimmer still work ? (tilt position)

Do you get a log message ? (OpenZWave: Domoticz has send a Slat/Tilt command)

**Comment by svde** [comment]
[006](https://www.eijk.nu/se/Annotation%202019-08-26%20091844.png) and [007](https://www.eijk.nu/se/Annotation%202019-08-26%20091907.png)

Old switch for the position still works.
I didn't try using the tilt through ozwcp. It's quite difficult to put a value in there and submit it, ozwcp refreshes the page and restores the current value. I need to be really quick...

[logs](https://www.eijk.nu/se/2019.08.25.txt)

**Comment by petergebruers** [comment]
I was able to test with a FGRM-222. So far I can tell OZW 1.6 and ozwcp (main repo version) support position and tilt, I mean besides that standard (dimmer-like) "Level" it has Values for:

Venetian Blind slat position: 0
Venetian blind tilt position: 0

I don't have Venetian blinds... It is actually the first time I use this module in that mode. Oh. Well. I learn something new every day 😀 -  When I change tilt, the motor spins for a time relative to parameter 12 (default 1.5 seconds) so that seems OK to me.

Back to domoticz... I don't see these values but that is no surprise... I have a different product ID

I'll see if I can make this work 😉

**Comment by petergebruers** [comment]
I was able to add tilt support, but that broke postition support and I won't have access to an FGRM-222 before... Next Thursday I think 😐

The issue with this command class is that it also exposes "dimmers" so to speak, like the main position (blinds mode)... but on the same instance ID. The problem with that is Domoticz generates device IDs like this in domoticz/hardware/ZWaveBase.cpp

```
ZWaveBase::SendSwitchIfNotExists(...
(...)
unsigned char ID1 = 0;
unsigned char ID2 = (unsigned char)((pDevice->nodeID & 0xFF00) >> 8);
unsigned char ID3 = (unsigned char)pDevice->nodeID & 0xFF;
unsigned char ID4 = pDevice->instanceID;

unsigned long lID = (ID1 << 24) + (ID2 << 16) + (ID3 << 8) + ID4;

char szID[10];
sprintf(szID, "%08lX", lID);
```

Then it queries the database and skips device creation if the ID already exists. There's no bug in that code, but as you can see to get unique IDs the instanceID must differ.

I can continue to work on this issue when I have access to my test device.

**Comment by petergebruers** [comment]
@gizmocuz Before solving the "Tilt" position there is a related issue.

As I posted, the database device ID of a switch is based on Node ID and Instance. My device has node 4 and it has only one instance, so there is only one possible (database) ID:

00000401

The FGRM however exposes a "switch" and a "mutililevel switch". As expected, the first is open/close, the second one determines blind position. Using string_id of the Z-Wave object, that is:

4.instance.1.index.0.commandClasses.37
4.instance.1.index.0.commandClasses.38

The second one does not get created because the first one gets stored in the database, then SendSwitchIfNotExists bails out when asked to create the second one.

What are the options here?

I see the full query uses ` (HardwareID==%d) AND (Unit==%d) AND (Type==%d) AND (SubType==%d) AND (DeviceID=='%q')`

HardwareID points to the Z-Wave driver
Unit is hardcoded as  unsigned char unitcode = 1; (in SendSwitchIfNotExists)
Type and SubType in this routine are pTypeGeneralSwitch, sSwitchGeneralSwitch

Unless you see another possibility, the only way to work around this is use different instanceID for each Value of this particular device.

I am rather new to the Domoticz code, I may be missing the point here...

**Comment by gizmocuz** [comment]
@petergebruers , yes this is also mentioned in the code, and I just wrote some small explanation in the PR
We have an option to correct it, but all users will loose there current switches (with timers/scripts/etc..)

best ID is <node_id><command_class><instance><index>

Of course small internal routines have to be adjusted as well... 

"IF" we are going this way, it's best to delete all current zwave switches in the database (with logs/timers/scenes/groups etc)

**Comment by petergebruers** [comment]
@gizmocuz thanks. I totally understand. ID structure change would have been done, if it did not cause so much trouble for existing users... BTW should you ever consider a new scheme I would suggest: Node ID, Instance ID, Command Class, Value Index (but that is 16 bit). So I would put Instance ID before Command Class, because conceptually an Node exists of Instances (aka End Points) And each End Point wraps Command Classes.

It seems like a daunting task to me, I don't have a "good plan".

I will try to implement the FGRM-222 by using different instanceIDs for each Value of this particular device.

**Comment by gizmocuz** [comment]
Index is a 8 bit value (any value above 255 seems not related to a real type..., so we're good... i think... (from what I have seen up till now))
The reason i think the instance/index should be at the back is because it numbers (for switches) in order (0,1,2,3)
This would maybe make it easier to read instead of having a command class (like 0x2B) at the end of an ID
Most users do not care about it, internally it is very good to have ;)

**Comment by petergebruers** [comment]
@gizmocuz 

Okay, have been digging throught the code where devices are created, found, added and how the IDs glue all this together. Quite interesting :wink:

I have been looking for a clean way to use a different InstanceID for Domicz's device ID, then the use the original InstanceID to send data to OpenZWave.

It looks like someone has had a stab at this before, can you tell a bit more about this?

```cpp
struct _tZWaveDevice
{
	int nodeID;
	int instanceID;
	int indexID;
	int orgInstanceID;
	int orgIndexID;
	int commandClassID;
```

Hmmmm.... instanceID and orgInstanceID sound like they fit my purpose. Checking the code, orgInstanceID is only used in very few places at the moment. Initially it is set to instanceID - that is good...

The string ID of the in-memory objects in map m_devices seems to be based on it, that is OK too:

```cpp
std::string ZWaveBase::GenerateDeviceStringID(const _tZWaveDevice* pDevice)
{
	std::stringstream sstr;
	sstr << pDevice->nodeID << ".instance." << pDevice->orgInstanceID << ".index." << pDevice->orgIndexID << ".commandClasses." << pDevice->commandClassID;
	return sstr.str();
}
```

The only other place where orgInstanceID is used:

```cpp
		//Search Energy Device
		const _tZWaveDevice* pEnergyDevice;
		pEnergyDevice = FindDeviceEx(pDevice->nodeID, pDevice->orgInstanceID, ZDTYPE_SENSOR_POWERENERGYMETER);
		if (pEnergyDevice == NULL)
		{
...
```

I've made a quick test to see if it can be used... I would say "yes".

In pseudo code, what I have done is this: if the device is a FGRM and wants to add a COMMAND_CLASS_SWITCH_MULTILEVEL (which would fail because the database already has a switch with the same ID) then set _device.instanceID = 0x10; - nice round number for testing.

Now I have my Position device as 00000410

Next step is being able to control it... For this I have to modify a line in SwitchLight(_tZWaveDevice* pDevice, const int instanceID, const int value) - without modification a change in value would use instanceID, which is 0x10... So to find the correct ValueID I have to use orgInstanceID  in the GetValueByCommandClassIndex call, like this

```cpp
if (GetValueByCommandClassIndex(pDevice->nodeID, pDevice->orgInstanceID, COMMAND_CLASS_SWITCH_MULTILEVEL, ValueID_Index_SwitchMultiLevel::Level, vID) == true)
```

For all existing devices, because orgInstanceID and instanceID are the same, everything stays the same. My Fibaro Dimmer still works as expected, and I can control the Blind Position.

I have not yet looked at Value Updates, I am reasonably sure that part will require modification too.

Before I do that, I want to check with you if I am on the right track. And any thoughts on instanceID and orgInstanceID...

**Comment by gizmocuz** [comment]
Yep, that's the code.
I used to use different instance id's, and i needed to have the original once, thats why i added it,
and i rebuild the string id's with them

And yes, your definitively on the right track, SwitchLight has to find the correct ValueID to switch

If it was me, I rewrote the whole ID generation for the switches... 

Maybe first get OZW (more) stable so we can make a new Release version, and start doing so in the next beta after...

**Comment by petergebruers** [comment]
> If it was me, I rewrote the whole ID generation for the switches...

Yeah, if we had a (working) crystal ball to see the future... Those things evolve, devices get more features...

> Maybe first get OZW (more) stable so we can make a new Release version, and start doing so in the next beta after...

Sounds like a plan.  I'll use orgInstanceID and instanceID to "hack in" FGRM support.

> Yep, that's the code.
> I used to use different instance id's, and i needed to have the original once, thats why i added it,
> and i rebuild the string id's with them

Thanks.

**Comment by petergebruers** [comment]
Forgot to tell... I think this is my first "serious" change to anything, and I am on old man and still learning how all the pieces of the (Domoticz) puzzle fit ;) - so don't accept the PR lightly. If you know a way to test this (eg have some well known users with big networks) then go ahead. I run this   on a 10 node network and it does not have, for example, an RBGW type of node. In fact, I consider Z-Wave to be "very difficult to test" because of the lack of simulated devices.

**Comment by gizmocuz** [comment]
@svde, is everything working correctly ? The patch has not been merged, but there have been other changes

**Comment by svde** [comment]
Unfortunately it's not working yet. I'm exercising patience and optimism. Thanks for checking back with me on this.

**Comment by petergebruers** [comment]
@svde @gizmocuz 
I see. I cannot work on this right now, I do not have a test device available. I think it would be irresponsible to fixup the PR and blindly merge. I may be able to have a look at it next week but I cannot fix a date yet.

**Comment by gizmocuz** [comment]
@petergebruers , i do have a FGRM-222 somewhere... so maybe i could get this to work.

**Comment by petergebruers** [comment]
> @petergebruers , i do have a FGRM-222 somewhere... so maybe i could get this to work.

I've fixed the PR, but it isn't tested with an FGRM-222. Please let me know if and when you can test, I'll do the same...

**Comment by petergebruers** [comment]
I'll probably be able to test this on 26 or 27 oct 2019.

**Comment by petergebruers** [comment]
After discussing this with @gizmocuz it was decided not to merge my PR because, in my words, it requires code changes that might have side effects. So it seems appropriate to solve the underlying issue (the generation of IDs) after the next stable (we've discussed this before and we agree). See:

https://github.com/domoticz/domoticz/pull/3624#issuecomment-546673624

When the ID generation problem is solved, the FGRM-222 does not need much special treatment (only handling of CC Proprietary) so the PR becomes pointless anyway.

At the moment, there is nothing I can do, so I'm out...

**Comment by Vinisz** [comment]
Hi Peter,

 

Was looking at this thread in Github, looks like this is still worked on.

I currently use homeseer as a controller but I wonder what the status of the FGRM-222 is, can it already do slat positioning or not at the moment ?

From what I see it needs a code change, if I am right, when can this be expected ? I’m looking forward to get back to domoticz but then this needs to work…

 

Greetings,

 

Vincent.

 

Van: Peter Gebruers <notifications@github.com> 
Verzonden: zaterdag 7 september 2019 20:40
Aan: domoticz/domoticz <domoticz@noreply.github.com>
CC: Vinisz <vszabang@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [domoticz/domoticz] Openzwave cannot add values for slat en tilt position (#3221)

 

I was able to test with a FGRM-222. So far I can tell OZW 1.6 and ozwcp (main repo version) support position and tilt, I mean besides that standard (dimmer-like) "Level" it has Values for:

Venetian Blind slat position: 0
Venetian blind tilt position: 0

I don't have Venetian blinds... It is actually the first time I use this module in that mode. Oh. Well. I learn something new every day 😀 - When I change tilt, the motor spins for a time relative to parameter 12 (default 1.5 seconds) so that seems OK to me.

Back to domoticz... I don't see these values but that is no surprise... I have a different product ID

I'll see if I can make this work 😉

**Comment by waltervl** [comment]
Is this solved?

**Comment by gizmocuz** [comment]
I think this is solved by using ZWaveJS2MQTT
