### ISSUE TITLE
Saturation option in bulb devices

### ISSUE THREAD

**Issue by poudenes** [domoticz/domoticz#3285]
Hi Guys,

Will it be possible to have a saturation slider next to brightness in bulb device?
Im using Milight bulbs and you can control saturation. @galinette2000 build a great Milight Plugin based on MQTT and is more then open to implement saturation also if Domoticz can handle this.

Cheers,
Peter

**Comment by dunchz** [comment]
Edit: I cannot figure out why, but for some reason it just 'popped' into working order, I'll keep quiet from here..

Original response:
I think the feature you are requesting is actually a recently introduced bug that now results in new Yeelights being added as RGB, instead of RGBWW (the latter two letters signifying its ability to do Warm White, as well as less saturated cooler whites). I ran into the issue, that while previously a Yeelight bulb had worked flawlessly (like its identical brethren hanging elsewhere in my place), but upon removing and readding the bulb it no longer gives me the option to add it as an RGBWW. Now my dashboard no longer allows me to set my Warm or Cool white options.

**Comment by waltervl** [comment]
Should be solved by the rgbww device
