### ISSUE TITLE
Update OpenZWave

### ISSUE THREAD

**Issue by ghost** [domoticz/domoticz#331]
Hello
Please update OpenZWave to version 1.4 because is now available:
https://github.com/OpenZWave/open-zwave/releases/tag/v1.4

**Comment by pepijng** [comment]
Please descibe what function in Domoticz is not working correctly without this update.

**Comment by nayrnet** [comment]
It appears a number of users are experiencing issues that are resolved by building everything from source with the latest OZW Libs.

see: https://www.domoticz.com/forum/viewtopic.php?f=6&t=9857
this just looks like an inquiry: https://www.domoticz.com/forum/viewtopic.php?f=6&t=9938

**Comment by gizmocuz** [comment]
The latest beta already used 1.4 ?

**Comment by nayrnet** [comment]
according to them not the RPI beta binaries.. not sure, Ive never used any prebuilt binaries so no idea how you guys do them.. I think they are wanting binary equivalent of building from source current OZW, since it alleviates some issues and I bet building on a PI is slow going.

ive just been monitoring activity on the forums and noticed the chatter.. personally not impacted.

**Comment by gizmocuz** [comment]
Stupid me, i updated the libraries for win32, but needed to compile OZW on the RPI as well.
Current beta has the new OZW (#4183)
