### ISSUE TITLE
Link specific OpenZwave version to the project

### ISSUE THREAD

**Issue by jputcu** [domoticz/domoticz#3321]
This is not really an issue but perhaps a suggestion to link to specific versions of OpenZwave.
This could be using `git submodule`, `CMake FetchContent` or `Conan` (...)
So when checking out this project and building you get the right version.
Perhaps it could also be used to avoid the OpenZwave Config file copy?

**Comment by gizmocuz** [comment]
@jputcu , thanks
The issue is, is that we want to support the latest version..., then it is a matter of latest Domoticz, latest OpenZWave, and you have the right combination.

In the past we had instructions on our wiki how to checkout a specific openzwave version and apply a patch (which was needed for the central scene command class for some time)

Another difference is that the original OpenZWave config folder has 10MB of images... which we do not use yet and makes the binary installer 10MB larger.

And Domoticz needs to find the config folder... it could be anywhere now (i build OpenZWave outside the domoticz folder, and when i launch my compiled domoticz excecutable it expects to find the config folder under the domoticz root folder by default

But once a month the same idea crosses my mind... 

... and it is an additional git command which is maybe already complex for non-developers and could be forgotten, resulting in no config files

I wished that the config folder was a sub module from OpenZWave so we can see changes in the library and configuration separately
If that was the case, we could easily do this

**Comment by jputcu** [comment]
The easiest way is the `git submodule` which locks a SHA1 of the OpenZwave in a subfolder which is easy to update to the latest. But at that time you have a fixed version which you know works.
The images inside the `Config` folder could be filtered out during a CMake install which is done prior to packaging.

**Comment by gizmocuz** [comment]
@jputcu , at the moment we are very happy with the latest openzwave code... hoping for some more patches.
Maybe this could be done on the master branch after making a new stable indeed

**Comment by gizmocuz** [comment]
But that also does mean when there are fixes/needed changes, people building Domoticz will use the old openzwave library... It's like using an old windows DLL... don't think that would be a good idea either...

**Comment by jputcu** [comment]
Because this is a difficult issue with multiple solutions, and I notice it is already present in your mind I'm going to close this to not clutter the issue list.
Thanks for the background information.
