### ISSUE TITLE
Xiaomi Gateway Fills log with 'Off'

### ISSUE THREAD

**Issue by sincze** [domoticz/domoticz#3346]
Running Domoticz version:

Domoticz V4.10730

I notice the following in the Xiaomi Gateway Log on my dashboard.

![image](https://user-images.githubusercontent.com/5776333/59974131-a104c700-95a8-11e9-8823-b847a623157f.png)

For some reason it keeps writing off in the device log, even during the night. 
I don't send the Off command nor do I touch the switch / light settings. Maybe it has something do to with the motion sensors attached (paired) to the Gateway device. As soon as I show myself to the motion sensor... 
![image](https://user-images.githubusercontent.com/5776333/59974044-a44b8300-95a7-11e9-8524-a6a89f22a194.png)

But that is all that is mentioned in the domoticz log.
The Motion device log (xiaomi motion sensor) shows:

![image](https://user-images.githubusercontent.com/5776333/59974083-0906dd80-95a8-11e9-9b0f-fd3e413e8fd5.png)

For some reason 'off' is written to xiaomi gateway device log many many times per day.

![image](https://user-images.githubusercontent.com/5776333/59974031-7bc38900-95a7-11e9-8bf6-499f4ad2136e.png)

**Comment by Trigun** [comment]
Hi Since,

It looks familiar, I had the same thing but in my case I had a php script that sends the off commands. Could this be the same in your case?

Kind regards/Met vriendelijke
Groet,

Bas Wiggers

Sent from my iPhone

On 23 Jun 2019, at 11:19, sincze <notifications@github.com<mailto:notifications@github.com>> wrote:


Running Domoticz version:

Domoticz V4.10730

I notice the following in the Xiaomi Gateway Log on my dashboard.

[image]<https://user-images.githubusercontent.com/5776333/59974131-a104c700-95a8-11e9-8823-b847a623157f.png>

For some reason it keeps writing off in the device log, even during the night.
I don't send the Off command nor do I touch the switch / light settings. Maybe it has something do to with the motion sensors attached (paired) to the Gateway device. As soon as I show myself to the motion sensor...
[image]<https://user-images.githubusercontent.com/5776333/59974044-a44b8300-95a7-11e9-8524-a6a89f22a194.png>

But that is all that is mentioned in the domoticz log.
The Motion device log (xiaomi motion sensor) shows:

[image]<https://user-images.githubusercontent.com/5776333/59974083-0906dd80-95a8-11e9-9b0f-fd3e413e8fd5.png>

For some reason 'off' is written to xiaomi gateway device log many many times per day.

[image]<https://user-images.githubusercontent.com/5776333/59974031-7bc38900-95a7-11e9-8bf6-499f4ad2136e.png>

**Comment by sincze** [comment]
My thoughts exactly. :)
This time however before posting I checked all the log files as the PHP script as you experienced it will show itself as 'admin: switched bla bla' in the Domoticz log. As it calls the API. But unfortunately no such message.

**Comment by sincze** [comment]
On Domoticz V4.10988
Still.
![image](https://user-images.githubusercontent.com/5776333/61646712-68413600-acab-11e9-81a2-650118e1a16a.png)

**Comment by gizmocuz** [comment]
@sincze , this is a issue with the plugin, it has to check if the state has changed, and if yes, then only update the switch in domoticz

**Comment by waltervl** [comment]
Still an issue?
