### ISSUE TITLE
Zwave Control Panel is empty

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#3349]
Domoticz 4.10929 (latest) and Open-Zwave latest build (1.6).

When opening the Zwave Control Panel from within Domoticz, the control panel is now empty. It does not show any node.

I already tried deleting the ozwcache file and restart Domoticz multiple times, bu the control stays empty.

**Comment by jotakar** [comment]
It's a fail in cp.js.
I think it would check if a value is not null before read **firstChild**. Page shows values of the net correctly if we change line **244 of cp.js**. Now in this line  you can see
````
nodes[id].values[k].value[l] = {item: items[l].firstChild.nodeValue, selected: (current == items[l].firstChild.nodeValue)};
````
If we add a conditional  
````
if (items[l].firstChild)
nodes[id].values[k].value[l] = {item: items[l].firstChild.nodeValue, selected: (current == items[l].firstChild.nodeValue)};
````
OZWCP page works fine ..

**Comment by petergebruers** [comment]
I am not a Domoticz developer but an OpenZWave developer and I can say two things.

I am not sure if this was fixed upstream, and upstream is
https://github.com/OpenZWave/open-zwave-control-panel

But I often use ozwcp for quick tests and I haven't seen it come up empty.

There are probably a few more changes between upstream and the version in Domoticz, I haven't checked.

The ozwcp repo has this text at the top "UNMAINTAINED - We are looking for someone to maintain ozwcp!". I would say if you would like to keep that project alive than please start from there and see if it needs more of your fixes. We'll gladly accept PRs. BTW Justin Hammond is working on a GUI replacement of ozwcp.

**Comment by Olivier6767** [comment]
I made the change mentioned above and I confirm that this does fix the OZW Control Panel.
With this change the information appears again!

Hopefully this change can be integrated.

**Comment by gizmocuz** [comment]
@Olivier6767 , can you make a PR?

**Comment by Olivier6767** [comment]
@gizmocuz, sorry but I'm not familiar at all with this process. I'm really not a developer, more an IT infrastructure guy...  I'm really more a user than a contributor, sorry...

**Comment by petergebruers** [comment]
In that case...

Let me have a look at how much Domoticz has diverged from upstream... And see if this patch was/is needed upstream.

**Comment by petergebruers** [comment]
Hehehe it has diverged a lot...

**Comment by petergebruers** [comment]
@Olivier6767 @jotakar what do you need the ozwcp panel for? The version embedded in Domoticz is outdated, and the "official version" is unmaintained but does improve compatibility. I could make a PR for that single line:

> if (items[l].firstChild)
> nodes[id].values[k].value[l] = {item: items[l].firstChild.nodeValue, selected: (current == items[l].firstChild.nodeValue)};

Just to make you happy, but there are probably more issues on that version.

But then you'll have to convince me that it is worth patching. I mean: you can do a lot with Domoticz without ozwcp... And @gizmocuz has to decide if I wants to update to the latest version of ozwcp, knowing that it is unmaintained...

**Comment by jotakar** [comment]
I llike OZWCP because this app talk directly with zwave devices. So when a new Domoticz or OZwave updates arrive and I see missfunction in the app, OZWCP is a good tool to detect these fails or misconfig settings. This is why  I like a working OZWCP in my Domoticz app. 
Now Domoticz is using a OZWCP version that is 3 years old!. Update and fixing every possible fail to use last build of OZWCP would be a hard work, and perhaps we could wait for the new CP what Justin Hammond  is working on. 
What I would do is add just this patch (what begins: if (items[].lastChild) ) to the OZWCP build Domoticz is using now.  
Thanks for yor work.
Edit: and there is another problem I describe and ifx in https://github.com/domoticz/domoticz/issues/3356

**Comment by petergebruers** [comment]
> So when a new Domoticz or OZwave updates arrive and I see missfunction in the app, OZWCP is a good tool to detect these fails or misconfig settings.

Yes, that is a useful function.



> Now Domoticz is using a OZWCP version that is 3 years old!

Yes, there are probably good reasons for that. I've had a little chat about this, it is history ;)



> perhaps we could wait for the new CP what Justin Hammond is working on.

I would prefer that indeed, because if I fix ozwcp on Domoticz then I am still not sure if it is 100% compatible with latest OZW. I've tried to "diff" but too many changes. And as you have said, ozwcp could be used as a diagnostic tool... but I would argue then it needs to be up-to-date. I know Justin is working hard on the new tool but there is no ETA.



> What I would do is add just this patch (what begins: if (items[].lastChild) ) to the OZWCP build

I'll see what I can do



> Edit: and there is another problem I describe and ifx in #3356

Yes, I am the same guy who responded there ;)
