### ISSUE TITLE
Issue: ZWave: Node not found!

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#3528]
Using release 4.10993 on Ubuntu 18.04

Since the release of yesterday evening (see issue #3525), I have 2 ZWave switches (on the same node) that don't work anymore. I get the following message when trying to action them:
`2019-07-13 10:34:24.553 Error: ZWave: Node not found! (NodeID: 64, 0x40)`

However the Node is fully recognized in OZW, for example this node also has a temperature sensor which keeps updating regularly.
Controller: AEON Labs ZW090 Z-Stick Gen5 EU
Node: Qubino (Goap) ZMNHBDx Flush 2 Relays+

Some other nodes are working correctly, but I have not tested them all.

I have connected the ZWave controller to another VM running Domoticz Stable (with Zwave 1.4) and can confirm that the switches work without problem, so the issue is not on the controller or node itself.

**Comment by tonbor** [comment]
Latest beta, with restart domoticz all battery powered z-wave devices are not recognized, all 0000

**Comment by tonbor** [comment]
2019-07-13 11:05:44.530 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 3 (0x03)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 5 (0x05)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 9 (0x09)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 13 (0x0d)
2019-07-13 11:05:44.530 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 3 (0x03)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 5 (0x05)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 9 (0x09)

2019-07-13 11:05:44.531 Status: OpenZWave: New Node added. HomeID: 3638704023, NodeID: 13 (0x0d)

![Screenshot_20190713-110359_Chrome](https://user-images.githubusercontent.com/42464290/61169521-08d28000-a55f-11e9-85df-35bd8a7d3823.jpg)

**Comment by Olivier6767** [comment]
I just found out I have another node where the switches don't work, same error:
`2019-07-13 11:47:50.502 Error: ZWave: Node not found! (NodeID: 65, 0x41)`
This node is a FIBARO System FGS222 Double Relay Switch 2x1.5kW

Also confirmed the swichtes work fine when connecting the Zwave controller to a Domoticz Stable version (4.10726) with ZWave 1.4.

**Comment by petergebruers** [comment]
Okay, not yet sure what is going on with the switches but I've issued a warning about this update

https://github.com/domoticz/domoticz/issues/3530

Explains why you get 0x0000 , it regenerates ozwcache




> I just found out I have another node where the switches don't work, same error:
> `2019-07-13 11:47:50.502 Error: ZWave: Node not found! (NodeID: 65, 0x41)`

Does the switch work with ozwcp?

**Comment by Olivier6767** [comment]
Yes I confirm that it regenerated the cache yesterday. But all my devices were re-discovered properly. I also checked Group Associations and they are fine.

I confirm that the switch DOES WORK with ozwcp.

**Comment by Olivier6767** [comment]
Here is more detailed information. The node having issues is a Qubino (Goap) ZMNHBDx Flush 2 Relays+.
It has 2 relays and a temperature sensor.
In Domoticz I have 3 switches: one for Relay1 (838), one for Relay2 (839) and one for both Relays together (837).

![image](https://user-images.githubusercontent.com/28684355/61170941-abdfc580-a570-11e9-9ab6-dd6ca177bf03.png)

The switch for Relay1 (838) and the switch for Relay2 (839) are NOT working since yesterday. However the global switch (Relay1 and Relay2 combined - 837) is working. 

In OZWCP, I see only one switch, and this is the combined one. It can be also be controlled from OZWCP.

I have other dual relay nodes (FIBARO), and in OZWCP I always only see 1 relay... so that may be normal.

I confirm again that all 3 relays work using Domoticz Stable with ZWave 1.4 using the same controller.

**Comment by petergebruers** [comment]
Thanks. The problem has been reported to OpenZWave and is under investigation.

**Comment by Olivier6767** [comment]
I confirm that with the release 11005 (revert) the problem is fixed.

**Comment by pokeron** [comment]
When I stop Domoticz the connection to my Fibaro battery operated devices (FIBARO System FGMS001-ZW5 Motion Sensor+, FIBARO System FGPB101 Button+ and FIBARO System FGK10x Door Opening Sensor+) is lost.

After the re-inclusion everything works as expected.

The only strange thing I see is the returning state for the FIBARO System FGMS001-ZW5 Motion Sensor+, this is always Off !!!. 

In the lua script I can work around this by determining if the 'svalue == nil' , if it is nil the state should be On. 

Version: 4.10988
Build Hash: 92aafc204
Compile Date: 2019-07-12 08:59:10
dzVents Version: 2.4.26

**Comment by gizmocuz** [comment]
@pokeron , try making sure 'accept new hardware' is enabled in the settings, and restart the openzwave hardware by disabling and enabling it again
Now check if you have new devices... and if those new once are the motion sensor

**Comment by pokeron** [comment]
@gizmocuz , accept new hardware is enabled. I did what you advised , after that I stopped domoticz (made a backup) and started again. I made some screenshots :
- Before starting the actions :
![Screenshot from 2019-07-15 18-57-34](https://user-images.githubusercontent.com/3851352/61235515-ff4f4080-a735-11e9-947b-34cd88b6644c.png)

![Screenshot from 2019-07-15 18-58-34](https://user-images.githubusercontent.com/3851352/61235545-0bd39900-a736-11e9-8def-b678e066aeaf.png)

![Screenshot from 2019-07-15 18-59-54](https://user-images.githubusercontent.com/3851352/61235557-12faa700-a736-11e9-880b-78b879d5bded.png)

- After disabling and enabling openzwave

![Screenshot from 2019-07-15 19-02-20](https://user-images.githubusercontent.com/3851352/61235632-3de4fb00-a736-11e9-9d05-a30d8cff68f5.png)

- After stopping domoticz and making a backup

![Screenshot from 2019-07-15 19-14-39](https://user-images.githubusercontent.com/3851352/61235707-7389e400-a736-11e9-8ab9-f75305e0ff9d.png)

![Screenshot from 2019-07-15 19-15-58](https://user-images.githubusercontent.com/3851352/61235724-7be21f00-a736-11e9-8d79-67c65363b6a3.png)

- Now I must wake the devices by hand

![Screenshot from 2019-07-15 19-17-43](https://user-images.githubusercontent.com/3851352/61235834-b9df4300-a736-11e9-87ad-821774d3a9e1.png)

With the last device in the list, sometimes I must exclude  and the include it because the column value shows the temperature instead of the on/Offf.

![Screenshot from 2019-07-15 19-58-27](https://user-images.githubusercontent.com/3851352/61237653-34aa5d00-a73b-11e9-91b7-45dd53b5e12d.png)

B.t.w do you have any idea why i only recieve an off state from the ' Magic Eye' devices even if it should be a on state.

From the log

 2019-07-15 19:30:34.898 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location)
2019-07-15 19:30:35.022 Status: dzVents: !Info: Forced --: ( 247429 ) Actie Device is Pirs-0051 Keuken -> Off
2019-07-15 19:30:35.031 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2019-07-15 19:31:05.109 Status: OpenZWave: Alarm received (Home Security: Clear)
2019-07-15 19:31:05.370 Status: dzVents: !Info: Forced --: ( 247430 ) Actie Device is Pirs-0051 Keuken -> Off
2019-07-15 19:31:05.379 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2019-07-15 19:31:39.045 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location)
2019-07-15 19:31:39.246 Status: dzVents: !Info: Forced --: ( 247431 ) Actie Device is Pirs-0051 Keuken -> Off
2019-07-15 19:31:39.256 Status: EventSystem: Script event triggered: /home/pi/domoticz/dzVents/runtime/dzVents.lua
2019-07-15 19:32:20.804 Status: OpenZWave: Alarm received (Home Security: Clear)
2019-07-15 19:32:20.924 Status: dzVents: !Info: Forced --: ( 247432 ) Actie Device is Pirs-0051 Keuken -> Off 
---------------------------------------------------------------------------------

**Comment by gizmocuz** [comment]
@pokeron , to check for new devices, you need to go to the devices overview.
Plz check if you have new once

**Comment by pokeron** [comment]
@gizmocuz , I did, there are no new devices, which is correct because inclusion for the device went ok after  I did a hard reset of my zwave controller device (Aeotec usb 5gen) and  included all devices while I was on the latest beta of Domotic. After stopping domitcz yesterday as mentioned in my latest post I had to remove one device end reinclude it ,this explans the gap in the nodeid numbers (see picture below)
![Screenshot from 2019-07-16 17-32-37](https://user-images.githubusercontent.com/3851352/61308215-0fc3f180-a7f0-11e9-8b69-5c7fece1c428.png)

**Comment by gizmocuz** [comment]
@pokeron , assuming you are talking about the FGMS001-ZW5, I happen to have such a device in front of me
Testing with the latest beta version, I do receive a ON for the switch when i wave my hand, and about 30 seconds later a OFF

![image](https://user-images.githubusercontent.com/2265299/61373877-44d94e00-a89b-11e9-9b7b-983df6601c5e.png)

Make sure you are looking at the correct switch, the ID should end with '35'

Ps. I did not modify any configuration option... all is default

**Comment by pokeron** [comment]
@gizmocuz , I'm using indeed the FGMS001-ZW5, included it in secure mode. This is the result of one of my sensors ;
![Screenshot from 2019-07-17 18-52-22](https://user-images.githubusercontent.com/3851352/61394921-83373300-a8c4-11e9-9539-775437125b60.png)
 I'm going to setup a new environment based upon and see if that helps.

**Comment by pokeron** [comment]
@gizmocuz , I found it , During the inclusion there are two switches a 'Sensor' and a 'Home Security'. I was sure that the switch 'Sensor' was the motion sensor. I didn't look at the 'Home Security' , After the fresh installation I looked at he 'Home Security' switch and saw that was the one reacting on motion.

Thnx for your inspiration :)

**Comment by gizmocuz** [comment]
@pokeron , yes that's why i mentioned you need the one with the DeviceID ending on 35
Great it's solved ! Closing issue
