### ISSUE TITLE
zwave groups empty on 1 qubino module

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3543]
i am experiencing problems with  a qubino ZMNHADX module

it was working perfectly but i had a power outage.
after that the switch is still working but the zwave groups seem to bee empty.
i can however not add controller 1 to group any group anymore(i need group 1 and nine)

i can add any other module to the group but the controller(1) i can not add)

eg with module 11 i can not add 1 to group 1 and 9 but i can add lets say 2(which does not exist)

i was running v4.10998 so i upgraded to the latest v4.11025 but the problem is still there

is there another way to add groups because from the user interface it is not working.

second question, where are those groups stored, inside the module bacause it makes no sense that a power outage can cause this

also stopped/started domoticz, disabled/enabled zwave controller and switched to polling but nothing helps

![temp](https://user-images.githubusercontent.com/16853535/61778730-99327f80-adff-11e9-800e-a4f98c2ab957.jpg)

**Comment by gizmocuz** [comment]
@GravityRZ , you could try via the control panel, but if that does not work, i think you need to exclude/include again
It is stored inside the node

**Comment by petergebruers** [comment]
Let's cross reference the OZW issue opened by @GravityRZ :

https://github.com/OpenZWave/open-zwave/issues/1895

I don't own this device so it might prove difficult to help... By this I mean it may be device-specific, because @GravityRZ posted ozwcp also does not allow to add "1" to group "9". this very likely causes the device NOT to send temperature updates... He worked around that problem by enabling polling.

Let's continue the discussion on the OZW tracker.
