### ISSUE TITLE
p1 not working with RFXcom XL

### ISSUE THREAD

**Issue by smausje** [domoticz/domoticz#3563]
p1 not working with RFXcom XL

I get the this err

RFXCOM: input buffer out of sync, going to restart!.... 

error message due to a long P1 message

The input buffer is too small defined in Domoticz and needs an update

**Comment by GravityRZ** [comment]
where did you buy this RFXcom XL?  a pull up resistor might be necessary(it was in my case)

**Comment by smausje** [comment]
hashop

 a pull up resistor is placed.

with RFXmngr i get the data from the kaifa meter

**Comment by GravityRZ** [comment]
i got it from the same place. maybee contact Bert from RFXcom(distributor)
He helped me with mine since i was the first RFXcomXL user with domoticz

i have a landis &Gyr E350 meter.
i only have the problems you discribe when i disconnect and connect the rfxcom from the usb port
domoticz and RFXcom does not like that. 
in my situation it stops with that error after a couple of reboots from the RFXcom
it could be that with your meter, the pull up resistor R15 needs to be a different value(mine is 2K2, i think it was 10K which was no good)

**Comment by gizmocuz** [comment]
@smausje , did you specify the correct meter type in the RFXTrx settings in domoticz ?

**Comment by gizmocuz** [comment]
@smausje , i hope the above solves the issue, if not, i made a new beta (11079) where the buffers have been increased.
But I hope that it is solved by specifying the correct meter type (DSM)

**Comment by smausje** [comment]
with the new beta on a window computer now it work fine, now i have to wait voor my synology.

my setting are correct.at first i have contact with Bert Weijenberg of RFXcom.

**Comment by gizmocuz** [comment]
Great thanks for the feedback, considering this closed now

**Comment by smausje** [comment]
After instal a new domoticz the problem is back.

**Comment by gizmocuz** [comment]
Nothing changed and it's also working correctly here?
