### ISSUE TITLE
Node is recognized but Domoticz beta ozw 1.6 will not update the node.

### ISSUE THREAD

**Issue by tonbor** [domoticz/domoticz#3578]
One Neo Coolcam plug Shenzhen Neo Electronics Co Ltd Power plug 12A+ | Shenzhen Neo Electronics Co Ltd | 0x1087 | 0x0003  is recognized but will not update. (An other same type has no problem).
Domoticz beta with ozw1.6 will not update the node. Pushing Refresh in the OZW panel updates the panel and Domoticz. Because I replaced it to another socket I readded it, no exclude only include. Voltage and ampere never updates. Watt and kWh after a new includes sometimes but only the time, the latest recordered value is kept, not the real actual value. My conclusion is there is something wrong in (the connection OZW 1.6 and) Domoticz. See over the internet more people complaining about no update OZW nodes by the controller.

![only kwh update opz panel](https://user-images.githubusercontent.com/42464290/63582888-2d783980-c59a-11e9-9e0b-ba119bfc7898.jpg)
ozw panel 

![only kwh update](https://user-images.githubusercontent.com/42464290/63582913-3a952880-c59a-11e9-91b8-9376df9a0429.jpg)
domoticz only update kwh, none others
![refresh opz panel domoticz](https://user-images.githubusercontent.com/42464290/63582917-3d901900-c59a-11e9-8b48-69ba547fef08.jpg)
pushing refresh in the ozw panel
![refresh opz panel](https://user-images.githubusercontent.com/42464290/63582923-3ff27300-c59a-11e9-9143-b938c7ee8795.jpg)

Well OZW lets Watt, Ampere and Volt just disappear, how can that be?
![only kwh ](https://user-images.githubusercontent.com/42464290/63610330-83200680-c5d9-11e9-92fb-0c236910538f.jpg)

_Originally posted by @tonbor in https://github.com/domoticz/domoticz/issues/3566#issuecomment-522572024_

**Comment by gizmocuz** [comment]
What a strange topic name

**Comment by tonbor** [comment]
Peter wants to split the issues from 3566, you close my splitting. We are all volunteers in our spare time. Not lots of time.

**Comment by petergebruers** [comment]
Guys, I understand both of you... I know what this issue is about, but surely it could be clearer ;)

@tonbor maybe change title to "Neo Coolcam Wall Plug value(s) do not update", maybe tell which values (status? V? W?)

@gizmocuz maybe reopen?

**Comment by petergebruers** [comment]
BTW I have a spare of that type of plug, I can test...

**Comment by tonbor** [comment]
@gizmocuz please reopen

**Comment by petergebruers** [comment]
I've tested this...

Build Domoticz + OZW from source. I don't think it would make any difference if you just downloaded a binary beta version because that part hasn't changed recently.

Delete ozwcache* and also delete domoticz.db - which is drastic and you should not do that, but it allows me to replicate my tests and have consistent results.

I then add OpenZWave hardware. My controller already has node 7 == Neo Power Plug and everything is default, except this: I used the original ozwcp to reset the energy meter (kWh)

<img width="682" alt="Screen Shot 2019-08-24 at 10 43 40" src="https://user-images.githubusercontent.com/5297547/63634908-09c9f780-c65d-11e9-9d37-dfd2ae432dae.png">

All those devices work as expected. By default this plug reports every 5 minutes, and when the load changes sufficiently, see "Configuration" parameters and manual.

Because Voltage fluctuates a bit, it easy to graph:

<img width="400" alt="Screen Shot 2019-08-24 at 10 45 11" src="https://user-images.githubusercontent.com/5297547/63634899-f585fa80-c65c-11e9-88c6-81cb236ba302.png">

This works for A and W as well but the data is sampled every 5 minutes and my tests were a bit shorter than that.

Still, the Domoticz logging proves the device reports every 5 minutes:

```
2019-08-24 10:47:23.613  (t) General/kWh (kWh Meter)
2019-08-24 10:47:23.646  (t) Usage (Power)
2019-08-24 10:47:23.647  (t) General/kWh (kWh Meter)
2019-08-24 10:47:23.676  (t) General/Voltage (Voltage)
2019-08-24 10:47:23.707  (t) Current (Current)
2019-08-24 10:52:23.585  (t) General/kWh (kWh Meter)
2019-08-24 10:52:23.617  (t) Usage (Power)
2019-08-24 10:52:23.617  (t) General/kWh (kWh Meter)
2019-08-24 10:52:23.648  (t) General/Voltage (Voltage)
2019-08-24 10:52:23.678  (t) Current (Current)
2019-08-24 10:57:23.556  (t) General/kWh (kWh Meter)
2019-08-24 10:57:23.589  (t) Usage (Power)
2019-08-24 10:57:23.590  (t) General/kWh (kWh Meter)
2019-08-24 10:57:23.619  (t) General/Voltage (Voltage)
2019-08-24 10:57:23.650  (t) Current (Current)
```

I've also add a 9 A load and turned it on and off, this is reported in Domoticz (if you refresh the page).

If this does not work for you, please check the parameters and also the "Group" panel - that plug should have "1.1" in group 1. Try to remove it and add it back.

**Comment by tonbor** [comment]
Dear Peter, thanks for testing. Well I got two Neo cam Plugs that are working fine in my network. It is not surprising that your test just turned out fine. Pity that you do not mention the version of Domoticz you did your test with.

**Comment by gizmocuz** [comment]
@tonbor , I can only assume he used the latest code from Github

@petergebruers , thanks for this test. You can also backup the database instead of deleting it ;)

It can not be said (for 100%) that 'everything' was default...
The configuration is stored inside the hardware of the Neo plug, not in the config of OZW/Domoticz.
If there where any configuration settings applied before, it is still being used like that

I don't know if it is possible, but maybe there is a 'reset' function for the plug ? Then you know everything is default.

Could there also be a firmware difference ?

**Comment by petergebruers** [comment]
@tonbor 

> Dear Peter, thanks for testing. Well I got two Neo cam Plugs that are working fine in my network. It is not surprising that your test just turned out fine. Pity that you do not mention the version of Domoticz you did your test with.

Sorry, I did not explicitly mention the versions but "Build Domoticz + OZW from source." in my case means I build OpenZWave from "master" branch and Domoticz from branch "development".

For Domticz that is Domoticz V4.11218, commit 473f43b85 BuienRadar Forecast URL - but version should not matter much, code supporting that type of device has not been changed in a while...

If 2 plugs are OK and the 3rd is not it is either Configuration Options, Group, a network communication issue, or maybe a mismatch of OZW Value IDs with data you have stored in the Domoticz db. The last one is purely theoretical, it is a bit hard to test.

If this is a test network, I would not hesitate and "exclude" and "include" that plug... If it is production that is probably annoying because you get a new node ID.

@gizmocuz 

> @petergebruers , thanks for this test. You can also backup the database instead of deleting it ;)

Hehehe ;) Yes users should do that, but in my case it is a test network and I really want repeatable results so "delete db" is the easiest way.

> It can not be said (for 100%) that 'everything' was default...

In general: indeed hard to tell when a device is in factory reset state. In my case: 100% certainty - device was reset. I exclude it and this devices resets all parameters (confirmed by reading them back). Not all devices do this (notable exceptions are qubino modules with temp sensors). Most Z-Wave devices reset to default when you exclude them.

> The configuration is stored inside the hardware of the Neo plug, not in the config of OZW/Domoticz.
> If there where any configuration settings applied before, it is still being used like that

Exactly, and ozwcache does not save settings (not now anyway) so without reading them back from the device that causes confusion. First thing to do is click that "Request current stored values from device" button.

And when a user upgrades from 1.4 this warning also applies to associations.

> I don't know if it is possible, but maybe there is a 'reset' function for the plug ? Then you know everything is default.

Yes it does have a reset procedure. The device also excludes itself from the network (not all devices do that, this one supports the locally reset command class and notifies OZW).

OZW 1.6 config files have metadata to store this information... Here it is...

```
    <MetaDataItem name="ResetDescription">Note:  to use the reset procedure only when the primary controller is missing or inoperable.
Restore the Device (Smart Plug) to Factory Default Settings

Reset procedure will delete all information on the Z‐Wave network and Z‐Wave controller or Z‐Wave Gateway, and restore the sensor to factory default settings.
1.Make sure the sensor is powered. 

2.Press and hold the button more than 10 seconds until the LED blink with red color. 

3.Release the button. </MetaDataItem>
```

I have tested the procedure, it works and the device gets removed from the "OpenZWave hardware".

> Could there also be a firmware difference ?

Yes, good point! I don't think that is very likely because I think I would have heard of them not reporting data, either here or on the Fibaro forum.

But @tonbor check anyway... In "Control Panel" toggle button "Information" mine says:

Application Version: 2.32

**Comment by tonbor** [comment]
@petergebruers 

Library Version: |  3
Protocol Version: |  4.05
Application Version: |  3.94
I presume you have an other id, see beginning of this thread.

**Comment by petergebruers** [comment]
Yes, mine has same display name but is called nas-wr01ze, yours is nas-wr01z

```
<Product config="shenzen_neo/nas-wr01z.xml" id="1087" name="Power plug 12A" type="0003"/>
<Product config="shenzen_neo/nas-wr01ze.xml" id="1027" name="Power plug 12A" type="0200"/>
```

I wasn't aware of the different models, reminder to self: maybe add model to name.

The difference imho is "unknown" because the manufacturer does not publish changes, they just add a small leaflet with config options when you buy them. And we have to go by what users contributed (config file). The config files look very similar.

I have 2 other Neo Wall Plugs, but only one available right now, I'll check that one.

You say 2 are OK, but the 3rd one not - all three same FW version?

**Comment by petergebruers** [comment]
Ah! My other plug:

```
1087.0003.0258
Node009,   Opening config param file /usr/local/etc/openzwave/shenzen_neo/nas-wr01z.xml
Protocol Version: 4.05
Application Version: 3.93
```

The protocol version tells me this one uses an older SDK than the first one I've tested (nas-wr01ze)

There is still a small difference, your fw is .01 higher at 3.94...

I'll try to test this one with both ozwcp and Domoticz today.

**Comment by petergebruers** [comment]
Did a quick test with ozwcp and I see no different report behaviour. This is the nas-wr01z fw 3.93

```
2019-08-25 12:32:08.472 Info, Node009, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.00
2019-08-25 12:32:09.428 Info, Node009, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 0.00
2019-08-25 12:32:10.454 Info, Node009, Received Meter Report for Electric - V (1) with Units V (4) on Index 4: 232.72
2019-08-25 12:32:11.424 Info, Node009, Received Meter Report for Electric - A (1) with Units A (5) on Index 5: 0.00
2019-08-25 12:33:55.459 Info, Node009, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.00
2019-08-25 12:33:56.452 Info, Node009, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 11.76
2019-08-25 12:33:58.445 Info, Node009, Received Meter Report for Electric - V (1) with Units V (4) on Index 4: 233.97
2019-08-25 12:33:59.217 Info, Node009, Received Meter Report for Electric - A (1) with Units A (5) on Index 5: 0.08
2019-08-25 12:35:10.452 Info, Node009, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.00
2019-08-25 12:35:11.228 Info, Node009, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 12.78
2019-08-25 12:35:12.438 Info, Node009, Received Meter Report for Electric - V (1) with Units V (4) on Index 4: 233.78
2019-08-25 12:35:13.224 Info, Node009, Received Meter Report for Electric - A (1) with Units A (5) on Index 5: 0.09
2019-08-25 12:40:10.427 Info, Node009, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.00
2019-08-25 12:40:11.239 Info, Node009, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 12.86
2019-08-25 12:40:12.411 Info, Node009, Received Meter Report for Electric - V (1) with Units V (4) on Index 4: 235.42
2019-08-25 12:40:13.236 Info, Node009, Received Meter Report for Electric - A (1) with Units A (5) on Index 5: 0.09
```

Reports big changes and when I toggle, and small changes every 5 minutes.

Have to go now, will try Domoticz later.

**Comment by tonbor** [comment]
well got the neocam working. excluded, reset included more nearby the gateway controller. got only two, ampere and voltage missing with ozw panel too. did renew node info with domoticz, ampere and voltage showed up. got it running now, still very strange.

**Comment by petergebruers** [comment]
@tonbor as promised, I have updated the OZW config database, when @gizmocuz builds a new Domoticz beta based on upstream OZW then you can see the new names if you do "refresh node info" on your wall plugs. You can test that if you want to, but you don't have to...

Older SDK version plug:
Shenzhen Neo Electronics Co Ltd NAS-WR01Z Power plug 12A

Newer SDK version plug:
Shenzhen Neo Electronics Co Ltd NAS-WR01ZE Power plug 12A

The only change is that name, configuration options remain the same.

BTW since you got it working, can this issue be closed?

**Comment by tonbor** [comment]
It failed again, but now it works for a week. Close this issue.
