### ISSUE TITLE
Increase temperature sensor reading resolution

### ISSUE THREAD

**Issue by lbdroid** [domoticz/domoticz#3580]
Many common temperature sensors (i.e. Bosch BME280/680) have an output resolution of 0.01 deg. C. It is frustrating that Domoticz clips it at 0.1 deg. C.

**Comment by gizmocuz** [comment]
Please use the forum, it is very frustrating indeed.... Not!... your BME280/680 has also a tolerance and for sure is also not correct

**Comment by lbdroid** [comment]
And apparently you don't know how to read a datasheet.

**Comment by petergebruers** [comment]
> And apparently you don't know how to read a datasheet.

I can assure you, he does know how to read data sheets, a few weeks ago we discussed some ;)

I understand you want 0.01 °C resolution but from an engineering perspective that is not very useful and actually misleading... But hey, some controllers like my HC2 support it, so "why not".

If you see "room temperature 21.23 °C" and the sensor has +/-0.3 °C accuracy you could say

21.2 °C
21.5 °C
21.0 °C

All representing the same measurement.

Dropping the last digit does help you realize: "this measurement does not have better accuracy".

In fact, when representing room temperature, I would even go as far as to claim 21 or 22 would be even less misleading, because room temperature changes with height (ballpark 1 °C per meter) and depends on the temperature of nearby objects.

That 0.01 °C however may make sense, when used in relative measurements. Though also noise, hysteresis, self heating by 0.5 °C (solely depending on sample rate of this sensor!) does spoil that.

But if you take all those effects into account, you might be able to say when room temperature (which is your personal definition, based on where and how you measure, your point of reference) has changed from 22.23 °C to 22.38 then you had a 0.15 °C temperature increase. Or say it had a 0.1 or 0.2 increase, which would be OK as well but in this case 0.15 is arguably more accurate. Of course, when someone enters the room and "mixes the air" you can have temperature changes exceeding that, so I am not really convinced that 0.01 resolution adds much information.

I am the proud owner of 4x FGT-001 aka the Fibaro TRV. To check their operation I have plenty of sensors, and I have been monitoring the setup closely, so I can go on about temperature measurement for quite a bit longer.

But I bet adding that extra digit would make quite a few users happy because indeed the data sheet does mention that resolution.

I understand the dilemma (to show or not to show...). My Multimeter says, my mains voltage is 238.70 V right now. Accuracy +/- 0.5% + 40d so I would call that: "238 V" ;) And 50.00 Hz (with a few tens of ppm accuracy, this time all digits are significant). If it dropped the (meaningless) digits I would probably say "hey, I payed good money for a 500000 count multimeter".

**Comment by lbdroid** [comment]
"If you see "room temperature 21.23 °C" and the sensor has +/-0.3 °C accuracy you could say

21.2 °C
21.5 °C
21.0 °C

All representing the same measurement."

There is a difference between absolute accuracy and relative sensitivity.

If you see room temperature 21.23 in your example, yes, it could represent anywhere from 21.20 to 21.26, but if that sensor has a sensitivity of 0.01 and you next see room temperature of 21.25, then regardless of where it falls in the range, it is 0.02 more than the previous reading.

**Comment by petergebruers** [comment]
Exactly. We can debate what 0.02 represents when that BME is used to measure room temperature - but indeed I mentioned this as well (see "... has changed from 22.23 °C to 22.38 then you had a 0.15 °C temperature increase.") so we do agree...

I don't know if the issue you report here is a "display issue" or a "database issue" or even a limitation of the code reading the BME.

Because github is mainly a tool to discuss code issues... Can you help point to where the issue is and how you would change that? I am not saying I am going to "fix" this (it is up to @gizmocuz to accept changes) , but I am interested...

I am an OpenZWave contributor (volunteer) and resolution aka scale and precision are well defined there... I occasionally chime in here.

**Comment by gizmocuz** [comment]
Such a resolution makes no sense and also depends on where/how this sensor is housed.
(And how the sensor is read  (oversampling)
So no...

**Comment by lbdroid2** [comment]
Its pretty sad that those apparently in charge of this project (@gizmocuz) are so hostile in their opposition to progress and improvement.

Domoticz is not perfect, but has potential. Unfortunately, without a willingness to realize potential, it is a complete waste of time.

**Comment by gizmocuz** [comment]
@lbdroid , @lbdroid2 , it is pretty sad how you react to issues and on open source projects where people devote a lot !! of free time in.

You do not even want to help, you want to get paid?

If you really think Domoticz has potential, misses features or is incomplete, you can help !
Not by shouting stupid remarks. (not only this issue topic)
If not, get a life!, do something else in your free time, and stop annoying me. 

And as a big reminder, I do not have to accept every opinion / idea !
