### ISSUE TITLE
Unable to permanently delete dead node

### ISSUE THREAD

**Issue by Kratax** [domoticz/domoticz#3609]
Hi,
I have several Danfoss popp radiator thermostat and I face repeatedly an issue. Repeatedly (usually when the change of batteries is needed), the node is not able to communicate with the gate and remains unknown in hardware tab (see the attached screen shot). With this, I am unable to make it again running nor delete them permanently. I have tried several advices from the forum including zw...cfg file and deletion of wake up part for dead nodes but after some time they appear again as Probe (sleeping). Is there any way of deleting them without need for full reset and deletion of all devices?
I tried deletion, exluding node, removing failed node, heal and remove, ...
I am on the latest beta (but the same issue is with the latest stable version).
Thanks a lot.
Regards,
Lubos

List of hardware
https://ibb.co/MpLyMhH

Ozw console
https://ibb.co/Q6KZmqv

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RicardP** [comment]
Hi @Kratax, it is often problems with removal of battery Nodes as they are not listening for commands more than once a while to save the battery... normally they should be updated by performing "Refresh Node Info" in OZW control panel and immediately triple click the Node button (check the Node manual). This is only valid if the Node is still valid by the controller (listed in OZW cachefile), and that you did not reset/factory default the Node.
What Domoticz version are you using? There is big improvements latest Domoticz betas (generally) containing much improved OZW 1.6. Last stable Domoticz is OZW 1.4 so if Z-Wave is an important part of your system I would suggest and update to latest Domoticz beta. 

I am on windows platform and prior any update I make a copy of the whole Domoticz installation folder. If something goes wrong I can restore it 100%.

As you find the problem in the OZW (Control Panel) you should look for further assistance at www.openzwave.com, because it is really not an issue in Domoticz.

**Comment by Kratax** [comment]
>Hi @Kratax, it is often problems with removal of battery Nodes as they are not listening for commands more than once a while to save the battery... normally they should be updated by performing "Refresh Node Info" in OZW control panel and immediately triple click the Node button (check the Node manual). This is only valid if the Node is still valid by the controller (listed in OZW cachefile), and that you did not reset/factory default the Node. ...

@RicardP I am on the latest beta.... Issue is as described that with this specific equipment after battery removal, you cannot connect again and need to re-add the node. After this, there is remaining "dead" node which cannot be anyhow removed... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RicardP** [comment]
@Kratax yes I understand, however it is still an issue connected to OZW/the device itself, and not an issue within Domoticz code. Please check OZW site for possible help.

Cheers!
