### ISSUE TITLE
no SSL/TLS supports for MQTT in Domoticz

### ISSUE THREAD

**Issue by mzy2240** [domoticz/domoticz#3611]
Howdy!

I am facing a problem that the mqtt broker used requires a SSL/TLS connection, so is it possible to somehow enable the SSL/TLS connection for the MQTT gateway function in Domoticz? I checked the forum but did not find anything useful. Thanks!!!

**Comment by gizmocuz** [comment]
Looking at the MQTT code in the repository  see there is a file 'tls_mosq.c'
But it seems the define WITH_TLS is not defined.

There is support in the hardware setup, and with this I assume someone got it working (CA Filename)

Since you are posting here I must assume you know something about coding/compiling, if not, best to ask on the Forum, and hope the one added the CA Filename can answer you

Assuming you are using a Raspberry Pi or another unix/linux distribution, you can compile Domoticz yourself, and you can tell CMake to not use the internal MQTT library but use a library on your system

-DUSE_BUILTIN_MQTT=NO

This assumes that you have installed mosquittopp

Could you try with this ?

Or could you enable the WITH_TLS option ?

Domoticz has already a preprocessor named WWW_ENABLE_SSL
I think when you add WITH_TLS, it should compile MQTT with TLS support

**Comment by gizmocuz** [comment]
Did you check the Domoticz log, when you specified the CA filename, did it return something like

> MQTT: Failed enabling TLS mode, return code: 10 (CA certificate: xxx')

**Comment by gizmocuz** [comment]
Please update to the latest beta version of Domoticz.
I enabled MQTT TLS (preprocessor) and also added the option to specify which version of TLS (in the hardware setup)
Best to check this via the pub/sub commandline tools

**Comment by gizmocuz** [comment]
Consider this implemented/fixed
