### ISSUE TITLE
Blockly Event works, but appears as an error

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#3689]
Hi, I'm glad that you develop Blockly! 

but since the last update is displayed with an error.

![sshot-2019-10-25- 1](https://user-images.githubusercontent.com/32480002/67587319-e5b98e00-f753-11e9-9566-71e3a0dfcc87.jpg)

**Comment by gizmocuz** [comment]
@salopette , you mean, one event displays with a 'Error'
Could it be that in this blockly that there is a device/sensor used that does not exist anymore?
What happens when you save it again ?

It could also mean that this hardware was disabled at one time... if you save it again, it should clear the error is there is nothing wrong with it

**Comment by salopette** [comment]
Resaving does not help.
All devices in the script are online!

**Comment by gizmocuz** [comment]
Could you make a change , then save, then change it again to what it should be, then save again?

**Comment by salopette** [comment]
I have now deleted and recreated the entire block. Now the mistake is gone!

**Comment by gizmocuz** [comment]
@salopette , it was not a mistake. This event was flagged as failed, that could be because there was a device/sensor/switch used "Xiaomi Gateway Doorbell" that did not existed anymore.
Maybe you included it multiple times, deleted it once while this blockly already existed

You can test this:
Add a virtual switch (Dummy hardware)
Use this switch in the above event, turn it on when the "Door klingel sensor" turns on
Verify that this happens
Now from the devices tab delete the virtual switch, ring the door klingel sensor,
you should also get a log line now that there was a problem with the virtual switch
When you now go to blockly(or refresh) then you will see it flagged as 'Error'
