### ISSUE TITLE
updatebeta problems due to dependency on  QLIBC_2.27

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#3737]
If you use beta branch of domoticz and Debian 9 (aka Stretch), this is now not working due to the GLIBC version.
The latest stable version of GLIBC is 2.24 using Debian Stretch.

See forum topics

[Database incompatible with this Domoticz version.](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30215)
[Version `GLIBC_2.27' not found](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30219)

**Comment by gizmocuz** [comment]
Can't the system be updated ? Do note that the arm x86 and x64 build systems are running Raspbian GNU/Linux 9

**Comment by rwaaren** [comment]
For some/most members probably yes. For others/few not yet. If no other option maybe a warning of some kind could prevent frustration.

**Comment by 0rsa** [comment]
Hi,
I'm the author of the domoticz thread.
I cannot update to Debian 10 because I use OMV (OpenMediaVault) which is not ready yet for Debian Buster.
If someone can provide me a zip file which contains one of the latest version working with glibc 2.24, I'll be very thankful to him.

**Comment by gizmocuz** [comment]
As mentioned, do note that the build system is running Debian 9 as well

**Comment by 0rsa** [comment]
Well, I switched to a fresh install of Debian 10 this night because I cannot wait more to have my domotic system working. Latest domoticz beta is working fine with my database backup and I will use individual tools in replacement of OMV.
Good luck to Debian 9 users and please add a big warning before updating next time or offer a way to rollback...

**Comment by gizmocuz** [comment]
@0rsa , maybe it is hard to read my replies ? The build system does NOT run Debian 10, but 9, has been for quite some time now.

I can't upgrade to 10 because of this exact issue.

So something else is going on... It could be the CMakeList.txt change or the update to OpenSSL 1.1.x

Anyway, It seems that you enjoyed my (still) manual builds for some time, and now when it does not work out for you (for whatever reasons that may be), your going to an quite offensive state...
"Well" do kindle not that it takes a lot of my (free) time as "well"

You can rollback quite easily by compile yourself, there is a excellent guide here:
https://www.domoticz.com/wiki/Installing_and_running_Domoticz_on_a_Raspberry_PI

You can revert to any previous commit

Another option is to run a command to archive the Domoticz folder, you could make a cronjob for it that does that once in a week

I just updated my production machine (also running "Debian GNU/Linux 9"), went fine and is running 11503 now.
I do upgrade my systems with 'sudo apt update/sudo apt upgrade', maybe that could have helped.

**Comment by 0rsa** [comment]
@gizmocuz Sorry if you took this "well" like that, don't forget english is not native language for everybody. I'm just a bit in a defensive state because my entierly automated house is completely broken for 2 days ago, just clicking one button without major change warning. I spent a lot of time to understand why. Error message at startup is very clear "Version `GLIBC_2.27' not found" and I don't know how I can guess I have to update "OpenSSL" or read "CMakeList.txt".
I never used your manual builds, again I spent a lot of time to find solutions as manual building glibc 2.30 or rollback to another version but how I'm supposed to know what is the proper pull request to build to obtain the latest working version using GLIBC <=2.24? 
Now, it's fixed for me, I used radical solution because I need automation working, it's a fact.
Once that is said, I really thank you to you and all developers for this software, we must make the difference, this bad recent experience does not question the respect I have for the work of developers.

**Comment by gizmocuz** [comment]
@0rsa , okey, thanks for explaining. Thats indeed the reason why we have to take care what and how we say things. I'm not a native English person as well.

Maybe in the feature could try a manual build first....

You did not mention you compiled Domoticz yourself in the Forum, but said you tried to compile GLIBC yourself...
If you did try to build Domoticz and failed, do you remember the reason why it failed?
I really think this might be related to OpenSSL 1.1.x, because previous versions used 1.0.x
And maybe 1.1.x is depending on a newer GLIBC version ?

But what I can tell is that this is not intended, the binaries are still compiles on Raspbian 9, I am able to upgrade my production machines which still runs Debian 9...

**Comment by kini24** [comment]
I have the same problem. And now I just can not start Domoticz. And I can’t test the device that I am building :-(

**Comment by gizmocuz** [comment]
@kini24 , you provide way to less information... please...
- system used
- building yourself or the binary verson
- when you start domoticz by hand (cd domoticz then ./domoticz) what is the error message
- did you try compiling yourself ?
- did you perform a 'sudo apt update and sudo apt upgrade' ?

**Comment by kini24** [comment]
I am sorry. I use Alt Linux operating system as a server.
I am using the Domoticz binary beta. The version with which I was updated was 4.11457. Domoticz is launched from under systemd, the service file is as follows:

```
[Unit]
Description = Domoticz Home Automation Server
After = network.target

[Service]
# User = root
# Group = root
PIDFile = /var/run/domoticz.pid
Type = simple
ExecStart = /opt/domoticz/domoticz -f /opt/domoticz/domoticz.conf
Restart = always
WorkingDirectory = /opt/domoticz
# CapabilityBoundingSet = CAP_NET_BIND_SERVICE
AmbientCapabilities = CAP_NET_RAW CAP_NET_ADMIN CAP_NET_BIND_SERVICE
RestartSec = 1m
# StandardOutput = null

[Install]
WantedBy = multi-user.target
```

I have not tried compiling for my system, I lack experience in this. And, as I understand it, I will not succeed because of too many dependencies that I will have to satisfy before compiling.
At the time of the Domoticz update, my operating system had the most recent updates.
I must note that I was not able to start Domoticz, most likely due to the glibc version - I have the latest available 2.23.
At the moment, I solved the problem by finding a copy of Domoticz of the same version that I had before the update

**Comment by gizmocuz** [comment]
@kini24 , could you please try

cd domoticz
./domoticz

and tell us what the error exactly is ? because "most likely due to the glibc version" is not working...

Another raspberry pi system has been updated to the latest beta (apt update/upgrade first), was not updated for a long time... working without issues:

Wait a second !! Are we talking about raspberry or Linux ? my manual buils or the Travis CI builds ?

In case of the travis builds, yes i updates Travis to "Bionic" (18.04), which is LTS correct ?
This used to be "Trusty" which is EOL at Travis
I will see if i can bring this to Xenial (16.04) ... but still it's old... we can not also use Windows 95 right ?
(Or Windows 7... you know what i mean)

I will make a branch to downgrade to Xenial now

**Comment by gizmocuz** [comment]
It's building, could take 10 minutes

**Comment by 0rsa** [comment]
@gizmocuz Thanks for efforts.
I'm happy now with Debian Buster (and I found tools to replace OMV so :))) but I can try to help you about issue:
I was talking about Debian 9.11 AMD64 (not for a rasp, for a desktop).
Message was clear using ./updatebeta and ./domoticz : Version `GLIBC_2.27' not found'
My system was up to date, doing just before an apt update & apt upgrade.

Domoticz has been installed following: curl -sSL install.domoticz.com | sudo bash

Hope it will help you.

**Comment by kini24** [comment]
No, this is not raspberry, this is linux. Unfortunately, I can’t answer about whose assembly this is - I always updated domoticz when an alert appears

**Comment by gizmocuz** [comment]
It's working... travis is building a new beta that should be available in 15 minutes
If all is working, please close the issue (if possible also mention it on the forum)
Sorry for the trouble, Had no idea that it was not for ARM but for Intel/AMD x86/x64
But.... I would recommend to upgrade your systems as in 4 months probably 20.04 LTS will be released and 14.04/16.04 is quite old

**Comment by herm42** [comment]
...maybe my problem with the latest 4.11515 domoticz version is related. im running debian buster.
version 4.11505 starts without any problems.
version 4.11515 --> 
./domoticz: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./domoticz)

/usr/lib/x86_64-linux-gnu
352 -rw-r--r--  1 root root   357056 Aug 23 00:03 libssl3.so
 980 -rw-r--r--  1 root root  1000822 Okt 12 21:56 libssl.a
    0 lrwxrwxrwx  1 root root       13 Okt 12 21:56 libssl.so -> libssl.so.1.1
  388 -rw-r--r--  1 root root   395176 Sep 25 19:56 libssl.so.1.0.0
  424 -rw-r--r--  1 root root   431232 Jun 26 20:25 libssl.so.1.0.2
  580 -rw-r--r--  1 root root   593696 Okt 12 21:56 libssl.so.1.1

maybe the info helps

**Comment by gizmocuz** [comment]
@herm42 , i don't think so, but try installing openssl 1.0.2 ?
(or try reinstalling it)

**Comment by herm42** [comment]
case 1 all version libssl1.0.0 libssl1.0.2 and 1.1 installed ...
./domoticz: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./domoticz)

case 2:
libssl1.0.2 and 1.1 installed 
./domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

domoticz version version 4.11505 starts always ... 
newest domoticz version tries to loads libssl.so.1.0.0 ... but why :-)

**Comment by rkluwen** [comment]
Did you run ldconfig?

**Comment by kini24** [comment]
@herm42 Maybe try to make symlinks to those files that are in the system? It helped me

**Comment by herm42** [comment]
yes... ldconfig, symlinks ... tried everything ...
-newest domoticz without symlink
./domoticz: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
-newest version with symlink
/usr/lib/x86_64-linux-gnu# ln -s libssl.so.1.0.2 libssl.so.1.0.0
ldconfig
... now libssl is fine ...
./domoticz: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
ln -s libcrypto.so.1.0.2 libcrypto.so.1.0.0
ldconfig
and now it's getting weird .... 
./domoticz: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./domoticz)
./domoticz: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./domoticz)
./domoticz: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by ./domoticz)
./domoticz: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./domoticz)

for me it looks like newest domoticz is linked against ssl 1.0.0 somehow (and not 1.0.2)

**Comment by herm42** [comment]
or its linked against wrong version of libcrypto ?

again... old beta 4.11505 is working fine at all (with or without symlinks)

**Comment by gizmocuz** [comment]
Seems like the build log suggests 1.0.2

https://travis-ci.org/domoticz/domoticz/builds/615554772

**Comment by SwiftingSpeed** [comment]
I also got the "/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found" problem when updating to the latest beta today. I haven't tried fiddling with symlinks since it seem herm42 has already tried everything.

I'm using Debian 10, Buster.

**Comment by herm42** [comment]
according to the build log it uses ...
-- OPENSSL library found at: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
and ...
Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")  

question: are  /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so symlinks to 1.0.2 or 1.0.0 ?

maybe there is something mixed

**Comment by Ittiz** [comment]
I've got the same openssl error on debian 9

**Comment by gizmocuz** [comment]
could you try the new beta 4.11528
I am linking ssl statically now, hope this helps

**Comment by herm42** [comment]
yes ... new beta is working again .. thx

**Comment by rwaaren** [comment]
> could you try the new beta 4.11528
> I am linking ssl statically now, hope this helps

Could [this issue for windows (as posted on the forum) ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=30278) be related to linking ssl statically  ?

**Comment by gizmocuz** [comment]
Great this is solved as well... Now if we could drop the glibc dependency then we could migrate to 19.04 again ;)
@rwaaren , No i don't think so as there have been no version changes related to openssl for windows
Let's continue in the forum thread

**Comment by SwiftingSpeed** [comment]
Can confirm it's working for me again as well. Great work!

**Comment by Ittiz** [comment]
That update also fixed my issue with the openssl as well.

**Comment by gizmocuz** [comment]
Thanks for the feedback... unfortunately the binary is now 1.5MB larger... But let's keep it this way ;)
