### ISSUE TITLE
MQTT DEPRECATED and external MQTT ?

### ISSUE THREAD

**Issue by xbeaudouin** [domoticz/domoticz#3743]
Hello 

Since MQTT 1.6.7 and latest merge with MQTT it seems we cannot use external MQTT library with Domoticz.
After looking in the current code and external code I saw that mosquittopp.h on the git repo is not the same have in the official sources of MQTT 1.6.7.

On the official sources we have in this header :

```
#ifndef MOSQUITTOPP_H
#define MOSQUITTOPP_H

#if defined(_WIN32) && !defined(LIBMOSQUITTO_STATIC)
#       ifdef mosquittopp_EXPORTS
#               define mosqpp_EXPORT  __declspec(dllexport)
#       else
#               define mosqpp_EXPORT  __declspec(dllimport)
#       endif
#else
#       define mosqpp_EXPORT
#endif

#if defined(__GNUC__) || defined(__clang__)
#  define DEPRECATED __attribute__ ((deprecated))
#else
#  define DEPRECATED
#endif

#include <cstdlib>
#include <mosquitto.h>
#include <time.h>

namespace mosqpp {


mosqpp_EXPORT const char * DEPRECATED strerror(int mosq_errno);
(...)
```

On the domoticz files we have : 

```
#ifndef MOSQUITTOPP_H
#define MOSQUITTOPP_H

#define mosqpp_EXPORT

#include <cstdlib>
#include "mosquitto.h"
#include <time.h>

namespace mosqpp {


const char * strerror(int mosq_errno);
(...)
```

We clairely see that `DEPRECATED` stuff has been removed in between.
@gizmocuz is there any reason ? Do you have this kind of difference between domoticz repo and the shared libraries ?

Maybe we have to recode the MQTT client for domoticz to not use the deprecated functions?

Regards,

**Comment by xbeaudouin** [comment]
Another difference between official MQTT and the integrated's one in to domoticz is the presence of clear_callbacks(); (line 213 in mosquittopp.cpp) 

```void mosquittopp::clear_callbacks()
{
	mosquitto_connect_callback_set(m_mosq, nullptr);
	mosquitto_connect_with_flags_callback_set(m_mosq, nullptr);
	mosquitto_disconnect_callback_set(m_mosq, nullptr);
	mosquitto_publish_callback_set(m_mosq, nullptr);
	mosquitto_message_callback_set(m_mosq, nullptr);
	mosquitto_subscribe_callback_set(m_mosq, nullptr);
	mosquitto_unsubscribe_callback_set(m_mosq, nullptr);
	mosquitto_log_callback_set(m_mosq, nullptr);
}
```

Which seems to be another added function. :(

**Comment by gizmocuz** [comment]
@xbeaudouin, yes i removed the depricated stuff because the warnings, the rest is the same
Yes we could copy/paste all code, and call it mosquittodz but many people are asking why mosquittopp will get deprecated so for the moment i see no reason to do so.

I have added the clear callbacks, they are not needed actually.
This is NOT the reason why Domoticz should not be able to compile with an external library

**Comment by xbeaudouin** [comment]
Well we can live with the "deprecated" warnings... (now why a change in a non major release is another story).
Issue is really the clear_callbacks(); function that does not exist on the external lib... 
I completly agree we should not copy all code and maintain it...
Anyway do you think we should call "clear_callbacks()" only if we use the internal mqtt lib ? Like for example :
```
#ifdef BUILTIN_MQTT
clear_callbacks();
#endif 
```
What do you think?
Regards

**Comment by gizmocuz** [comment]
Sure this could work... You want me to make a patch for this ?

**Comment by xbeaudouin** [comment]
Will make a PR, since you just confirmed this callback may be not used :)

Regards

**Comment by gizmocuz** [comment]
It could be that i noticed when MQTT was reconnecting to my server it sometimes crashed and that is why i added it
Maybe better to rename the class/file and call it mosquittodz ? so we are not depending on mosquittopp anymore ?

**Comment by xbeaudouin** [comment]
This is maybe a good idea...

**Comment by gizmocuz** [comment]
Later we could try websocket support...
Another thing i would like to add is a internal broker but time is always a issue... ;)

**Comment by gizmocuz** [comment]
@xbeaudouin , I think i will pick this one up myself.... (with maybe some help of you ... ;)
What platform are you using ? You installed libmosquitto-dev ?
What version is your libmosquitto-dev ? because for example with Ubuntu this is not 1.6.7
I am running Ubuntu 18.04 (via windows) and this installs version 1.4.15-2

This might mean that not all functions/fixes are inside that release.

We also have to rebuild the CMake project to find the libmosquitto library as this is not done by searching for mosquittopp.h which is going to be dropped...

**Comment by gizmocuz** [comment]
@xbeaudouin , new code committed, should work again

**Comment by xbeaudouin** [comment]
I confirm this is working now ... you are faster than me ^_^
