### ISSUE TITLE
 dzvents: stop() or Stop() : syntax error?

### ISSUE THREAD

**Issue by Oeil2L** [domoticz/domoticz#3774]
My Domoticz:
Version: 4.11528
Build Hash: 6ea6c9bef
Compile Date: 2019-11-24 09:09:34
dzVents Version: 2.5.1
Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124]

I try to command venetian EU device (RTS for Somfy) blind with a dummy device because the venetian never changes is status : Stay open (Off) even if it is closed.

So script working now:
```
return {
       on = {
          devices = {
369
          }
       },
       execute = function(domoticz, switch)
          if (switch.state == 'Off') then
                domoticz.devices(18).switchOff()
             domoticz.log('Hey! I am Off!')
          elseif (switch.state == 'Stop') then
            domoticz.devices(18).stop()  
             domoticz.log('Hey! Stopped')
         elseif     (switch.state == 'On') then
             domoticz.devices(18).switchOn()
             domoticz.log('Hey! ONNNN')
          end
       end
    }

```
elseif (switch.state == '**_Stop_**') then
domoticz.devices(18).**_stop_**()

**_The autocompletion propose .Stop() but the right syntaxe seems to be .stop()_**

Documentation on this pages:
https://www.domoticz.com/wiki/DzVents:_next_generation_LUA_scripting
https://github.com/domoticz/domoticz/blob/development/dzVents/documentation/README.md

This line:
**stop**(): Function. Set device to Stop if it supports it (e.g. blinds). Supports command options.

Can be ambigus because the switch.state is Stop

**Comment by rwaaren** [comment]
the autocompletion of the internal ACE editor in domoticz works as follows. First it looks for local (already in the text) words and next it looks for keywords.
In your case it found the word Stop and that's why it propose this word.

dzVents use 

- camelCase for all internal tables, methods and variables.
- UPPERCASE for all constants
- lowercase for time rules

in your line `domoticz.devices(18).stop() ` stop() is a method so camelCase.
The fact that here the state follows a different convention is of no influence.

**Comment by Oeil2L** [comment]
@rwaaren 
Thanks a lot for your complete answer.
it's give me a better understanding of the autocompletion presented between local and keyword

SwitchOn, SwitchOff, stop are not even on the list.
My bad!
