### ISSUE TITLE
Support BFT zwave card for gates/garage doors management

### ISSUE THREAD

**Issue by FrylFr** [domoticz/domoticz#3776]
Hello,

I'm a french happy domoticz user for several years with many zwave devices (mainly from Fibaro) on rpi3B / raspbian - I use the last stable version (for sure I can switch to beta version) with a gen5 usb stick as zwave controller  (previously i used s2 stick)

I have searched about BFT motors zwave card topic but it seems that nobody asked before even if BFT is the world leader in this industry

Here are some elements about this zwave card to plugged on the motor control block 

[https://www.bft-automation.com/fileadmin/user_upload/magistro/pdf_magistro/guida_rapida/D812087_00500_02_BeBa_QG.pdf](url)

Some details are listed on this document 

**Technical details**
The module is programmed as Node Types - Enhanced Slave

**Z-Wave Compatibility**
This is a Z-Wave device and can work with other manufacturers’ Z-Wave devices.

**Supporting Command Classes:**
Basic type : BASIC_TYPE_SLAVE
Generic type : GENERIC_TYPE_SWITCH_MULTILEVEL
Specific type : SPECIFIC_TYPE_CLASS_A_MOTOR_CONTROL
Class : 0x26 COMMAND_CLASS_SWITCH_MULTILEVEL
Class : 0x72 COMMAND_CLASS_MANUFACTURER_SPECIFIC
Class : 0x86 COMMAND_CLASS_VERSION

It seems that this device is not listed on openzwave device database but, as written in the document, "This is a Z-Wave device and can work with other manufacturers’ Z-Wave devices."
[http://openzwave.com/device-database/014B](url)

Could it be possible to add the B EBA ZWAVE Card to the recognized devices ?

Thanks a lot for your help

**Comment by gizmocuz** [comment]
@FrylFr , great to hear you're a happy user ;)

Unfortunately this is not the place to request openzwave configuration files, this should be done at the openzwave github repository.

When i look at the PDF document, i see no configuration parameters

If you backup your complete domoticz folder, then upgrade to the beta version (you might need to restart several times to get all zwave devices back, or request node information frames)
What happens when you include this Node ? Does it get included, do you get new devices ? Can you use those devices ?
Maybe it already works ?

**Comment by waltervl** [comment]
No feedback, issue can be closed?
