### ISSUE TITLE
AEON ZW096 and ZW100 - Z-wave Error Message -  Domoticz will use the Dimmer (and hide the Switch)

### ISSUE THREAD

**Issue by Olivier6767** [domoticz/domoticz#3816]
During Domoticz start, I have the following error message;
`Status: SendSwitchIfNotExists: Device '21.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00001501' matches '21.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).`

 for:

AEON Labs ZW096 Smart Switch 6+ (**Nodes 21 and 23**)
AEON Labs ZW100 MultiSensor 6+ (**Nodes 43, 44 and 45**)

This happens at every Domoticz startup.
These devices are not capable et dimming, they are simple On/Off switches.
I have not seen any side effect, just wondering if they is away to avoid the error message.

### Domoticz Log
`2019-12-27 11:30:57.172 Status: OpenZWave: Driver Ready
2019-12-27 11:30:57.181 Status: SendSwitchIfNotExists: Device '21.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00001501' matches '21.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).
2019-12-27 11:30:57.181 Status: SendSwitchIfNotExists: Device '23.instance.1.index.0.commandClasses.38' (Level) with DeviceID '00001701' matches '23.instance.1.index.0.commandClasses.37' (Switch). Domoticz will use the Dimmer (and hide the Switch).
2019-12-27 11:30:57.183 Status: SendSwitchIfNotExists: Device '43.instance.1.index.256.commandClasses.113' (Previous Event Cleared) with DeviceID '00002B00' matches '43.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).
2019-12-27 11:30:57.184 Status: SendSwitchIfNotExists: Device '44.instance.1.index.256.commandClasses.113' (Previous Event Cleared) with DeviceID '00002C00' matches '44.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).
2019-12-27 11:30:57.184 Status: SendSwitchIfNotExists: Device '45.instance.1.index.256.commandClasses.113' (Previous Event Cleared) with DeviceID '00002D00' matches '45.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).`

**Comment by gizmocuz** [comment]
Not at the present, please ignore them

**Comment by mcwieger** [comment]
I have a similar issue, when including the Aeotec 6 in 1 sensor:

`SendSwitchIfNotExists: Device '45.instance.1.index.256.commandClasses.113' (Previous Event Cleared) with DeviceID '00002D00' matches '45.instance.1.index.0.commandClasses.48' (Sensor). Domoticz will use the Dimmer (and hide the Switch).`

My issue is that it doesn't add the Burglar device (it should add 7 devices, it only adds 6). The Burglar device is crucial for me, as this is the only one I want to use of this device (motion sensor).

I'm on v4.11563.

**Comment by gizmocuz** [comment]
@mcwieger , that is unrelated to this message
Could you make sure accept new hardware is enabled in the settings and then trigger the burglar alarm ?
Do you see the buglar alarm in the control panel ?

**Comment by mcwieger** [comment]
Accept new hardware is enabled. As you know, when a Z-Wave device is included, one or more Domoticz devices are created. The issue in this case is that the Domoticz device called Burglar was not created (the other six devices that should be created for this Z-Wave device are created correctly).

The process of device creation is a black box to me and also something that can go wrong. Sometimes two identical Z-Wave devices have different Domoticz devices created. And in this case, one device is missing.

**Comment by gizmocuz** [comment]
If it is a version 2 node there should be an alarm sensor ? This sensor is triggered for multiple alarms
You can use blockly or the eventsystem to perform actions when a specific type of alarm (burglar) is triggerd

**Comment by mcwieger** [comment]
I don't know what a version 2 node is :-(

To clarify: these 6 devices were created:
![Devices](https://user-images.githubusercontent.com/8181621/74532893-9e3c5500-4f30-11ea-90d8-0d0fd119bbe3.jpg)

However, there should be a 7th (and perhaps even 8th), one named Burglar (see this post https://www.domoticz.com/forum/viewtopic.php?t=16665, where the user re-named it to 'WK Burglar' (Idx 71 in the start post).

I have included this Z-Wave device before (and the Burglar device was there), but had to exclude it because of issues. Now I'm trying to include it again, but not all devices show up.

**Comment by mcwieger** [comment]
From my log:

`2020-02-14 13:20:42.326 Status: OpenZWave: Alarm received (Home Security: Motion Detected at Unknown Location), NodeID: 45 (0x2d)`

So the Z-Wave device (NodeID 45 corresponds with the Aeon 6 in 1) triggers motion detection, but it's not reported in the Burglar device, since it's not there.

(and no, the Sensor device is not the same as the Burglar device).

**Comment by gizmocuz** [comment]
Motion is not the same as buglar
I think it is reported in the Alarm sensor ? (2D35) ?

**Comment by mcwieger** [comment]
I had a look and you may be right. I think the confusion was caused by two things:

1. 5 seconds after motion is detected, device switches off again.

`2020-02-17 21:30:43 | Off

2020-02-17 21:25:22 | Off

2020-02-17 21:25:17 | On`

I never saw the device switch on due to this. You can see it switches off again 5 minutes later, which is caused by a Hardware setting. Device switching off after 5 seconds is not what it should be, but we're not going to use this ticket for that.

2. When I first installed this device, there was definitely a motion alarm called Burglar and there were more than 6 devices. Apparently something evolved (either in Domoticz or in OZW), causing the hardware to create different devices than before. I'm in favour of software evolving, obviously, but I wonder if there are other devices that change over time and if/how this can be made available to users at a later stage. Also not something for this ticket, but something to communicate on the domoticz site.
