### ISSUE TITLE
No way to change switch state using JSON (/MQTT) without trigger a push (MQTT, etc .) 

### ISSUE THREAD

**Issue by mikkel75** [domoticz/domoticz#3863]
Hi,

I have searching through the forum for an answer as to how to change the state of a switch (my case a dimmer) from JSON/MQTT WITHOUT triggering a change event.
So far no luck - hence this issue post...

I have found posts saying to do something like this

```
/json.htm?type=command&param=udevice&idx=42&nvalue=0&svalue=
/json.htm?type=command&param=udevice&idx=42&nvalue=1&svalue=

```
(source: https://www.domoticz.com/forum/viewtopic.php?f=28&t=8495)

But that does trigger a change event.

If you look on the wiki (https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Selector_Switch) you find something like:
`/json.htm?type=command&param=switchlight&idx=IDX&switchcmd=Set%20Level&level=LEVEL`

but that ALSO triggers events - even though it's documented under Updating without events.

It seems really basic that a system like Domoticz should have a way of updating devices with triggering events. It is a basic need to prevent loops when you want Domoticz to show correct state for devices that can also be controlled from e.g. an IR remote or web page.

PLEASE help to solve this ASAP.

Thanks

**Comment by mikkel75** [comment]
It seems like there is something wrong with the EventSystem. Even with the g_bUseEventTrigger correctly set to false the MQTT->domoticz/out still reports the change.

I have tried to add debug in EventSystem.cpp:

```
	_log.Log(LOG_NORM, "EventSystem: g_bUseEventTrigger %d", g_bUseEventTrigger);
	if (g_bUseEventTrigger && GetEventTrigger(ulDevID, REASON_DEVICE, true))
	{
		_log.Log(LOG_NORM, "EventSystem: event trigger active, %s", devname.c_str());
```

And that shows g_bUseEventTrigger is correctly set to 0 when the parameter is set, but the event still shows in MQTT->domoticz/out

Any ideas?

@gizmocuz 
MQTT parameter or your added
`http://10.128.7.10:8080/json.htm?type=command&param=udevice&parsetrigger=false&idx=641&svalue=Off
`
gives same result. Correct g_bUseEventTrigger = 0, but still event trigger.

**Comment by gizmocuz** [comment]
The event system is something else then publishing the change to MQTT, fibaro, http push, influxdb etc.... These systems are still being called.
It should not cause a script (eventsystem) to be triggered

**Comment by mikkel75** [comment]
So how does one update a device from MQTT (domoticz/in) without creating a loop as the update then triggers a new MQTT message (domoticz/out)?

**Comment by mikkel75** [comment]
@gizmocuz 
I have a suggestion you maybe could comment on, please.

What if mainworker.cpp line 13632 (see below) was only called if g_bUseEventTrigger = 1?

```
	// signal connected devices (MQTT, fibaro, http push ... ) about the update
	sOnDeviceReceived(HardwareID, devidx, devname, nullptr);
```

Could such a feature be added to Domoticz?

**Comment by gizmocuz** [comment]
Sure but this is not related to the eventsystem at all.. it is a pusher... a pusher is also a remote domoticz system... and that also wants an update, or a value in a influxdb database
I have no idea why your MQTT is causing a infinite loop, but not here... and not with others
If you update a device, let's say via a json call, and you have a remote domoticz instance, listening via MQTT, you do want it to be published so the remote knows what changed

**Comment by mikkel75** [comment]
@gizmocuz 
I'm not alone with this issue - have a look in the forum, I see people doing all sorts of work-arounds to avoid this.
https://www.domoticz.com/forum/viewtopic.php?f=28&t=8495&start=20
https://www.domoticz.com/forum/viewtopic.php?f=11&t=2908&start=20

Yes in you example you would want a message on domoticz/out, but think of another example where you have an MQTT device with an IR remote for example. If the MQTT device is changed using IR remote or a web interface it sends a MQTT message to domoticz/in to update the status of the dummy Domoticz device. Now when that dummy device is updated that trig Domoticz to send out a MQTT message to domoticz/out whice is the sent to the device - hence we have a loop.
I want the MQTT device to listen to domoticz/out as I want to be able to control it from Domoticz.

Does that make sens? :)

**Comment by gizmocuz** [comment]
Nope sorry....
Connect to a MQTT broker
Listen to the broker (so you can see all messages) by using a application/command line

Add a dummy switch
Turn the switch on/off in domoticz, you will see the messages being published in MQTT -> Good, and no endless loop
Next update this switch via json (udevice), you will also see the messages being published and no endless loop
Next publish a MQTT message in the IN box to turn the switch on/off, and you will see the status changed in domoticz, good -> no endless loop

**Comment by dannybloe** [comment]
Just my two cents: there should be two different ways to deal with notrigger options. One of them is already in place, at least in the scripting area. You can specify a NOTRIGGER to commandArray commands and that makes sure no events are triggered in the event system. I'm not sure if you can trigger this from a json call as well. Not sure if jvandenbroek implemented that as well. In dzVents you can do `myDevice.switchOn().silent()` and the NOTRIGGER is added. 
The second is a way to update a device (either from script or from json) without triggering any of the internal actions like on/off urls or whatever. 

Imo, these two types are orthogonal and should both be possible to control. 
Also, be sure, that when any of this is implemented to run all integration tests (see dzVents tests) to make sure that everything still works. This is all a very delicate area that can easily make things fall over.

**Comment by gizmocuz** [comment]
@dannybloe , both ways are possible, i made a code patch that allows you to add a field to parse the trigger (3rd post, https://github.com/domoticz/domoticz/commit/8770e0474fb9630c3a27158da8cdf9f8103cc9e3)

The issue here is that he is not talking about triggers..... this is about the internal 'pushers' which is completely different than a trigger

I bet he got something mixed up, or is using a script that is causing a loop, let us first try my above example and see if that is working and then continue (step-by-step) to see what is not working

**Comment by rwaaren** [comment]
What I understand from the discussion so far is that @mikkel75 is looking for a way to prevent a MQTT message being send by domoticz when a device is updated. 
In domoticz speak this is a **push**.

In domoticz a **push** is not the same as an **event**
Below command does not trigger an **event** but it does change the state of a device and does trigger a **push**
`mosquitto_pub -m '{"parse" : false, "idx": 72, "nvalue" : 0 }' -t domoticz/in`

And below command does trigger both an **event** and a **push**
`mosquitto_pub -m '{ "idx": 72, "nvalue" : 0 }' -t domoticz/in`

**Comment by mikkel75** [comment]
@rwaaren @gizmocuz That summes it up right I think. I have made a drawing showing my setup, which I hope will help understand what I mean.
Link to drawing: https://1drv.ms/u/s!AlY-U_GE-GiVgsJYYFZF4eo25_vGwg?e=Ivfnb6
So the 'red' lines should only trig if the device is changed by Domoticz GUI/app etc, not if I update from MQTT.
Thats why I need a why to update a device without triggering the **push**.

**Comment by gizmocuz** [comment]
@mikkel75 , thanks for the sketch.
Yes this should NOT cause an endless loop... but I do not know what you do in NodeRed...

So again, back to my test example a view post above... try to make this first
You will see that this does not cause any loop
What is 'extra' in the setup is the 'MQTT Device' (the actual light, lets name it 'hardware', the most right block of your sketch), so when you flip the switch in the gui (or via MQTT) you want this device/hardware to turn on/off
This hardware should only listen to MQTT IN
When the state changes (either via MQTT or a user is able to flip a actual hardware switch) of the 'MQTT Device) it should publish the change in MQTT OUT

**Comment by mikkel75** [comment]
@gizmocuz My NodeRed don't do much, it only translates between MQTT formats JSON<>McLighting - nothing else. And I don't want any kind of state information in NodeRed, that must be handled by device and Domoticz and synced by MQTT.
If I publish a MQTT 'on' to the device from command-line the device turns on AND it reports it's new status back on MQTT towards NodeRed/Domoticz - hence the loop.
That is why I would like a way (JSON parameter) for Domoticz to update the device status but not trigger a *push*.

**Comment by gizmocuz** [comment]
Does the Virtual switch on the left side of your sketch has the same ID as the MQTT switch on the right side ?
Could you try this tutorial:
https://www.domoticz.com/forum/viewtopic.php?f=38&t=21608

**Comment by mikkel75** [comment]
I'm not sure what you mean here - the virtual switch is a Domoticz switch used to reflect (and control) the physical MQTT device (on the right). Only the virtual switch in Domoticz has an IDX.
The physical MQTT device only has a hook to mosquitto on a unique MQTT channel.

**Comment by gizmocuz** [comment]
Okey so the situation is as the tutorial in the above link... try to make the tutorial

**Comment by mikkel75** [comment]
Are you suggesting to change the behaviour of the McLighting MQTT device?
Change so that McLighting don't send MQTT->out if changes was made from MQTT->in?
I really don't think this is the right way to handle this - it's not very 'clean' and has potential problems with sync of the physical and dummy devices.
Furthermore, I would have to fork the McLighting project to change the MQTT behaviour. It's ofcause possible in this case, but I bet there are many other similar cases where it might be more diffecult and thus smarter to implement in Domoticz.

**Comment by mikkel75** [comment]
@rwaaren do you see a way to add the possibility to update a device and not trig the push?

**Comment by mrohner** [comment]
A sulution has already been posted by rwaaren
Below command does not trigger an event but it does change the state of a device and does trigger a push
{"parse" : false, "idx": 72, "nvalue" : 0 } send to  domoticz/in

It works like a charm.

**Comment by rwaaren** [comment]
> @rwaaren do you see a way to add the possibility to update a device and not trig the push?

Not a native domoticz one but there are workarounds possible with some scripting involved. Please open a forum topic for it or send a DM via the forum if such a workaround is acceptable for you and I will be happy to help where possible.

**Comment by gizmocuz** [comment]
First mikkel should check it's setup why it is generating an endless loop
It should not... he is not the first MQTT user
Try building a MQTT client with a ESP/Arduino

**Comment by mikkel75** [comment]
The McLighting is a ESP8266 project, so yes I already have an ESP based MQTT project.
I don't understand how you can claim this shouldn't create a loop - if you look at the setup diagram it's quite clear. Since both ends of the MQTT sends out an update if it receives a message the loop is created.
If you don't agree please explain where the message loop is broken.

**Comment by gizmocuz** [comment]
I dont think you tried the above tutorial... 
I don't know what McLighting is ... 
Could you program a simple Arduino sketch yourself and test?

The reason why i do believe everything should work as normal and not cause any loop,
is that i have quite a few wall sockets that i bought on amazon that i have reprogrammed and then now run 'Sonoff/tasmota' and they are controlled by MQTT, and i can also switch on/off the sockets by hand and the status reflects in Domoticz

See for a tutorial here:
https://www.youtube.com/watch?v=mQeSfnzkSfM

So does your sketch/setup cause an endless loop ? If yes, you better check what is wrong, this is NOT a Domoticz issue !

**Comment by mikkel75** [comment]
I don't use Sonoff currently, but if I look 8:36 into your tutorial, it seems like the off status of the lamp from turning it off in Sonoff GUI didn't get updated into Domoticz.
If updates from Sonoff (trigged from outside Domoticz) doesn't get back to Domoticz  I can see why you don't have a loop - but also you don't have a real solution...

**Comment by gizmocuz** [comment]
The status of the wall socket is being updated on the dashboard of Domoticz here
It's not my tutorial bdw
You are not the first one using MQTT and this has been in Domoticz for a very long period
You should be able to test via the command line also (mosquito pub/sub)

**Comment by mikkel75** [comment]
It's not MQTT thats the problem - it's the combination of using a switch device that can be set both from Domoticz and from other source (web, IR..) and you want Domoticz to also reflect those changes. Thats were the loop happens... 
This seems to have been an issue for a long time...
https://www.letscontrolit.com/forum/viewtopic.php?t=2660#p13071
also here:
https://www.letscontrolit.com/forum/viewtopic.php?t=850#p4627

**Comment by rwaaren** [comment]
@mikkel75
this is not going to be solved by repeating the same story in other words. Fact is that when you activate MQTT in the hardware tab in domoticz and you configured it to send out a message for the device at hand (either by sending MQTT for all devices (flat) or by putting it in a group (hierarchical)) it will send out an MQTT mesage. There is no way you can prevent that now and it will not be changed. 
The loop that occurs in your setup needs to be solved in another way and I already offered you some assistance while doing that. ( See my previous post in this issue thread.)

**Comment by mikkel75** [comment]
@rwaaren Yes thanks.
I just think this must be a rather general problem thus a nativ Domoticz solution would be nice, not having to use workaround-scripts etc.
I'm just wondering how other HA systems (OpenHAB, HA...) handle this...and if they do...

**Comment by rakustow** [comment]
Greetings.
I'm following your discussion as I'm facing the same behaviour in my implementation. As "my implementation" I mean:
- Version: 4.11670
- ESP8266 subscribed to MQTT domoticz/out listens for dummy switch (Venetian Blinds EU) changes and acts accordingly (On, Off, Stop)
- additionally ESP8266 has to update this dummy switch status in domoticz as external/physical switch can also control the blinds, so it updates dummy switch status with MQTT domoticz/in

According to Wiki I use **param=udevice** to update the status via domoticz/in:
{"command":"udevice","idx":14,"nvalue":1}
{"command":"udevice","idx":14,"nvalue":0}
{"command":"udevice","idx":14,"nvalue":17}
and it's working, but **domoticz resends same action message to domoticz/out** which (without additional logic in ESP code) triggers unwanted actions on blinds.

Can anyone summarise why this is happening ? Maybe I'm doing something wrong but as far as I understand Domoticz API/JSON Wiki:
 _"Note that when you use this &param=udevice option, the device is updated without running the associated on/off script actions."_ that should not to happen. It is very confusing.

**Comment by mikkel75** [comment]
Hi,

It's because MQTT messages is part of a push system not the event system (see earlier reply).

I'm really happy that you join this discussion as the devs don't seem to understand the need for this feature. 
rwaaren was helpfull enogh to suggest a workaround using custom scripts, but I would much like a nativ solution - though I doubt it's gonna happen...

If we are enough requesting a feature maybe, just maybe they will listen :)

**Comment by gizmocuz** [comment]
Could you post your sketch (via https://pastebin.com/)

**Comment by rakustow** [comment]
[https://pastebin.com/embed_js/SVZAkZAi](url)

**Comment by gizmocuz** [comment]
is this correct ?

 client.publish("domoticz/in","Shelly is here");
 client.subscribe("domoticz/out");

Status changes need to be send to 'domoticz/out' and the ESP has to listen to 'domoticz/in'

**Comment by rakustow** [comment]
In Domoticz Setup->Hardware->MQTT Client I have _out_ as: the Topic('s) Domoticz will use to publish outgoing messages. 
So AFAIK this is correct, this is default. 
Also Wiki says:
_"Default MQTT topics of the Domoticz for incoming and outcoming messages are:
  domoticz/in
  domoticz/out"_

**Comment by rakustow** [comment]
@gizmocuz is our discussion ends here ?

**Comment by gizmocuz** [comment]
@rakustow , nope... time is an issue...
I need to test everything step-by-step, and this means i need a full day for that...
Hopefully Sunday!

**Comment by rakustow** [comment]
@gizmocuz I appreciate that. Looking forward to hear from you.

**Comment by gizmocuz** [comment]
@rakustow , So I made a test sketch and indeed got to the same conclusion that there will be an endless loop.

https://pastebin.com/TJJGEnKT

because this sketch publishes it's state again, it is also received again

The solution is:
1. check if the switch state is different then the current, if the same then stop and do not continue to process the message
2. do not publish the same state as is received. Only publish a error message if for 'some' reason the state could not be set

**Comment by gizmocuz** [comment]
@rakustow , So I made a test sketch and indeed got to the same conclusion that there will be an endless loop.

https://pastebin.com/bKYc0Rxv

because this sketch publishes it's state again, it is also received again

The solution is to check if the switch state is different then the current, if the same then stop and do not continue to process the message

Solution:
```
  if (
    ((nvalue == 0)&&(bSwitchState == false))
    ||((nvalue == 1)&&(bSwitchState == true))
    ) {
    //same state, do not process further
    return;
  }
```

**Comment by gizmocuz** [comment]
I think because you 'publish' to the whole world that the switch is 'on', that in this case the listener (esp8266 mqtt client) updates it's state
The rest of the world that also listens to this published command assumes it is 'on' as it has not way to verify

In case of a error, the esp8266 mqtt client could send 'off' as it can not set the state (for whatever reason)

mosquitto_pub -h 172.16.0.117 -t domoticz/out -m "
{
\"Battery\" : 255,
\"RSSI\" : 12,
\"description\" : \"\",
\"dtype\" : \"Light/Switch\",
\"hwid\" : \"7\",
\"id\" : \"000140F7\",
\"idx\" : 167,
\"name\" : \"MQTT_Switch\",
\"nvalue\" : 1,
\"stype\" : \"Switch\",
\"svalue1\" : \"0\",
\"switchType\" : \"On/Off\",
\"unit\" : 1
}"

**Comment by rakustow** [comment]
@gizmocuz thanks for checking and verifying. 
I think the most important thing here is that you were able to confirm the fact that domoticz resends mqtt message back when it receives _udevice_ command, beside the fact that it shouldn't. As you can see it creates unwanted loopback effect.
Just to be sure that we are on the same page: My intention here was not to take your time and ask for your help with finding workaround for this in my sketch. I've already implemented one.
My intention (and I believe @mikkel75  intention) was to point that it should be fixed at root of the problem, in domoticz, because domoticz behaves different than it is described in Wiki.
This leads many people to wrong conclusions, implementations, security issues etc.
We should think about the solution in domoticz or at least issue should be described in Wiki to let people know about different behaviour _udevice_ command with MQTT.
What is your opinion on this ?

**Comment by gizmocuz** [comment]
The problem here is when a 'pusher' receives a update/command (for instance MQTT), it should be send to the system (domoticz), and all other pushers, EXCEPT the pusher where it originated from.
(in this case MQTT)

For instance you have the following configuration:
- Domoticz
- MQTT
- InfluxDB
- Remote Domoticz

When someone flips a switch in Domoticz, it should be send to
- MQTT
- InfluxDB
- Remote Domoticz

When someone flips a switch in a Remote Domoticz, it should be send to
- Domoticz
- MQTT
- InfluxDB

When someone flips a switch in a MQTT device, it should be send to
- Domoticz
- InfluxDB
- Remote Domoticz

The challenge here is that everything works in background threads, so internally we have to keep a record of the 'Originator', and when it is time to send to update to all pushers, we have to 'exclude' the originator

I can not tell if this is a easy implementation.... hopefully i can have a look on Sunday unless someone beats me to it

**Comment by gizmocuz** [comment]
@rakustow , okey this seemed easier then expected as it was a logical/direct calling method

Could you test beta 11763 to see if this solves the issue ?

**Comment by rakustow** [comment]
@gizmocuz Yup. I've made a quick test and it's seems that it behaves correctly :) Great. Many thanks

**Comment by gajotnt** [comment]
Damn you all !!!!!!! :P your bug fix, made domoticz for me a living hell with my wife!
Was so simple giving the same IDX to several devices and they would all sync very nicely. Now with this fix.......same idx only works if toggling from domoticz and will not work if toggling from 1 device.
Domoticz receives the info but does not relay it to the other devices with same idx.

Now how in the world do i make work a 3way switch so that i can open the lights from down stairs and close the lights when on top of the stairs and vice-versa? Using the same IDX worked like no other home automation app does, simple, easy, fast and less dummy devices/groups on domoticz...

Sorry for my rant :P just had to let you now that your fix was my downfall :P hehehehe

**Comment by gizmocuz** [comment]
First of, you should ALWAYS be able to control your lights/switches by hand (where possible of course)

Ok this is what I would do:
- Assign a unique ID for everything, all your lights, all switches
- You switches should activate a 'group' (learn it as code), in this group you put the lights you want to switch

**Comment by xury77** [comment]
I don't know how to get feedback from node red nora node?
All my voice control now not work because no feedback return to domoticz/out so Tasmota devices does not switched.  
 It should be an option to switch on or off in settings. 
Another solution to make "loopback mode" for any device available for enable or disable by user.
I think the issue should be reopened.

**Comment by gizmocuz** [comment]
@xury77 , have you tried the above ?

**Comment by xury77** [comment]
No not tried because tu much manual changes in my flows to do, but I made a workaround.  I send simultaneously to domoticz/in and also  domoticz/out using following script in function node for Node-Red:
https://www.domoticz.com/forum/viewtopic.php?f=6&t=31711&p=240110#p240110
Its works well with Tasmota as its need to get data from domoticz/out  topic and also Domoticz needs update state on /domoticz/in topic.
But I still thing is better solution will be a user control  option setting of a feedback loop.

**Comment by kisse66** [comment]
agree, this should be a settings option.  This change broke my battery logging and some other functions that took the values from domoticz/out . I guess I can change it (many separate modules to do), but it worked like that for years, so in my opinion this kind of change should have backwards compatible option.
In general at least I also think it can be assumed that if an MQTT device sends a temperature value it is broadcast out for others to follow. Using domoticz/out makes this work for different sensor types as is.

**Comment by JHurk** [comment]
Just found out this feature broke half my home automation, so please please please fix this by making it optional. The previous stable version (Synology) worked like a charm. 

Now my Homebridge setup to Domoticz is broken, so my wife and kids are giving me hell!!
Thanks during this time of quarantine when the entire family is home 24/7 :)

**Comment by kisse66** [comment]
How about restoring the old functionality and then adding a new separate configurable topic, that works as the new one?  Being able to configure both topic names makes it possible to choose which one is the default and eveyone is happy ?
Empty name or no tick in a box means don't publish anything there. That way both can also work in parallel so one could use either one for different purpose.

**Comment by gizmocuz** [comment]
Glad you made a backup as mentioned before doing the upgrade.
Time is always a problem, if someone could make a PR that add this as option in the hardware setup and code that would be great.
I will assign this to myself unless someone beats me to it

**Comment by JHurk** [comment]
I see nobody has had the time to make a PR. I have not trouble doing this, but the problem is that I am a total noob when it comes to coding. So I can make the PR, but can not attribute anything (except for some advise). Want me to make it or keep that to the professionals:)

**Comment by gizmocuz** [comment]
It could be that the reason for this is:

https://github.com/domoticz/domoticz/commits/development

@kisse66 , not sure I understand your fix. (I was not the original implementer of this in Domoticz)

- When publishing a new state (from a physical hardware switch for example >Switch_A< ) to MQTT, It does not make sense to receive that published message back correct?
Lets say this switch is publishing to **/mqtt/domoticz**

Now every other hardware that wants something to do with the state of >Switch_A< could/should listen to /mqtt/domoticz, receives it, and perform some action, maybe switch itself on >Switch_B< and publish this to **/mqtt/domoticz** as well.

I think we can all agree on this ?

Now I see we have two topics, IN/OUT, so I have to assume the above has to publish to **/mqtt/domoticz/OUT**

To publish a message to >Switch_A< (from for example the Domoticz web interface), Domoticz publish a message to **/mqtt/domoticz/IN** with a message like '>Switch_A< turn ON'

When >Switch_A< has received this (as it is listening to **/mqtt/domoticz/IN**, and checks if the message is for itself), it turns itself ON, and publishes it's state again to **/mqtt/domoticz/OUT**

I think this is how the logic should work correct ?

For me it seems not to make sense to use IN/OUT topics bdw... one topic should be OK ?
Maybe /mtt/domoticz/IDX where IDX is the unique ID of the device

**Comment by JHurk** [comment]
Great to see there is work being done on this issue, thanks!

**Comment by kisse66** [comment]
@gizmocuz I didn't really think how it should work, just how to make it usable again for me... 
Seems there are also other people wanting it to work as it used to and some need the new "filtered" mechanism.
So **one way** to make everyone happy is to restore the old functionality, but provide a separate concurrent topic, that works like the new (current). Then one can enable/use either one depending on what is neeeded, perhaps even both (I can see reason also behind the filtered notifications). My problem with the new function is more with sensors than actuators.

I use domoticz as one central piece of my HA, but a lot more is done via MQTT. I use /IN to feed commands/updates towards domoticz "domain" and /OUT is what actuator (switch) or monitoring devices listen to (unless they are connected via domoticz plugin). It's handy to use e.g. domoticz device names for logging etc without the initiating device itself knowing it since you get all the extra metadata at /OUT (echoed to an update at /IN using only the idx). If all updates echo to a topic, it is a central resource, that binds all different devices together for **external monitoring or function**. Maybe this could be done in other ways also, but it used to work before this commit, which prevented MQTT originated devices to be seen on /OUT. Hence the two-topic proposal.
I could live with keeping /OUT also as is now, but adding a separate /MONITOR (or something), that gets all updates as /OUT used to. If someone worries about the extra load this could have enable/disable.
Maybe others have different opinion?

Anyway changes to functionality needs to be taken carefully. There's a lot of different usages already adapted to the way it works and functional changes tend to break those. Backwards compatibility option is best way forward even if default is changed for good reason.

**Comment by gizmocuz** [comment]
Please try beta 11922, for MQTT there is now a settings option to Enable/Disable the loopback.
Default set to True, as this will be the default later, and this option might be removed in the feature

It goes into all core principles to broadcast the same message back, it should be one client that publishes a message and received by everyone listening to it

https://1sheeld.com/mqtt-protocol/

It was (and still is in some ways) badly designed at the start of the implementation in Domoticz.
And should be corrected in the near feature...
One option is to keep this implementation for some time and display to all users it is 'deprecated'

**Comment by kisse66** [comment]
For the MQTT principles I agree that one should not echo messages. But since we have two separate topics I don't see an issue. 
Quite often MQTT conventions use topic per sensor/actuator and listeners subscribe to what they need making it a different approach. I use nodeJS code to hook up external stuff using topic<->idx mapping, /in and /out as now again serves this well.

Anyway quick test looks like 11922 is working again for my setup at least, thank you!

**Comment by gizmocuz** [comment]
Great it is working!
We should also not use 2 topics, does not make sense at all .... 
But that is for a feature update ;)

**Comment by JHurk** [comment]
@gizmocuz Thanks for making this optional. 
As soon as I have figured out how to get this build on my Synology (Domoticz as a package) it will work again for me. I contacted Jumbotroll (Jadahl) hoping he can create a package from this build.

**Comment by GravityRZ** [comment]
i am reading this issue and am trying to understand what goes wrong
i am on build 2020.1.839 and also use nodered and nora(google devices)

i have all the domoticz/out commands coming in on the left
in the middle are all my nora devices(which have an option pass message from input to output) and on the right all the commands coming from nora are send back to domoticz/in

now as long as you turn off the "pass message from input to output" in nora there is absolutely no loopback.
indeed making a flow which connects domoticz/out to domoticz/in is not a smart idea.

so as far as i can see everything is working, i have no loop back and can control all my devices through google assistant.

could it be that my build (839) was just before we started changing this MQTT stuff.
looks like my build was around 28-3-2020 and that put's it in the middle of this discussion.
I however see people asking Jumbotroll for newer synology builds so that means that they have problems with build 839
![image](https://user-images.githubusercontent.com/16853535/79486523-1d283980-8017-11ea-98e3-f2c654585ded.png)

**Comment by mvn77** [comment]
Faced the same problem. How do I avoid looping through JSON?

**Comment by rwaaren** [comment]
@mvn77 please use the forum
