### ISSUE TITLE
Option to add IP Address to User Information

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#3879]
Adding the option to enter a IP address in the user information.
Reason: When you have allowed certain IP addresses to communicate with Domoticz without a username/password, the user that is logged when it does a 'switch' command is currently 'Admin'
We could then lookup it's IP address and log the correct User/Device name
This might also work for MQTT switch commands (if we know the origin IP address)

**Comment by dannybloe** [comment]
Is it possible to make a distinction when commands are processed because of event scripts? So that the user becomes 'dzVents'? Even better, that dzVents can add a marker to commands in the commandArray and then that marker is the actor? Then the script can provide custom 'users' like `dzVents: living_room.lua`

**Comment by gizmocuz** [comment]
That could be a/the next step... ;)

**Comment by waltervl** [comment]
I think this is already implemented in current stable 2022.1 
I see as user for example Admin (IP XX) with different IP addresses.

**Comment by gizmocuz** [comment]
Yes it is

**Comment by waltervl** [comment]
So this issue can be closed?

**Comment by waltervl** [comment]
No feedback, so close ;-)
