### ISSUE TITLE
Domoticz 4.11666 stops working on Debian Stretch (needs Buster now)

### ISSUE THREAD

**Issue by nico68000** [domoticz/domoticz#3880]
Hello,

After update, errors "version `GLIBC_2.28' not found" appears.

Domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Fri 2020-01-31 11:49:40 CET; 2min 44s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1916 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 1926 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)

janv. 31 11:49:40 domoticz systemd[1]: Starting LSB: Home Automation System...
janv. 31 11:49:40 domoticz domoticz.sh[1926]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/domoticz/domoticz)
janv. 31 11:49:40 domoticz domoticz.sh[1926]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/domoticz/domoticz)
janv. 31 11:49:40 domoticz systemd[1]: Started LSB: Home Automation System.

**Comment by salopette** [comment]
I have the same Problem.

**Comment by rwaaren** [comment]
What is your OS and what was the last domoticz version that worked for you ?

I am on Debian Buster and cannot replicate this on a NUC / PI-3B or on a  PI-4

**Comment by salopette** [comment]
Linux raspberrypi 4.19.85-v7+ #1279 SMP Fri Nov 22 15:41:04 GMT 2019 armv7l

The programs included with the Debian GNU/Linux system are free software;

**Comment by salopette** [comment]
I have last beta pi3, Debian stech

**Comment by rwaaren** [comment]
What do you see when you do a 
`sudo apt show libc6 
`from the CLI ?

If lower then 2.28 you might want to do a 
`sudo apt install libc6`

**Comment by SzemiSun** [comment]
I have the same Problem.
Pi 3 Model B rev 1.2
Raspbian GNU/Linux 9 (stretch)

root@rphome:/home/pi/domoticz# /etc/init.d/domoticz.sh status
● domoticz.service - LSB: Home Automation System
   Loaded: loaded (/etc/init.d/domoticz.sh; generated; vendor preset: enabled)
   Active: active (exited) since Fri 2020-01-31 12:02:50 CET; 21min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 13514 ExecStop=/etc/init.d/domoticz.sh stop (code=exited, status=0/SUCCESS)
  Process: 13524 ExecStart=/etc/init.d/domoticz.sh start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/domoticz.service

Jan 31 12:02:50 rphome systemd[1]: Starting LSB: Home Automation System...
Jan 31 12:02:50 rphome domoticz.sh[13524]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /home/pi/domoticz/domoticz)
Jan 31 12:02:50 rphome domoticz.sh[13524]: /home/pi/domoticz/domoticz: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/domoticz/domoticz)
Jan 31 12:02:50 rphome systemd[1]: Started LSB: Home Automation System.

**Comment by SzemiSun** [comment]
> What do you see when you do a
> `sudo apt show libc6 `from the CLI ?
> 
> If lower then 2.28 you might want to do a
> `sudo apt install libc6`

root@rphome:/home/pi/domoticz# sudo apt show libc6
Package: libc6
Version: 2.24-11+deb9u4
Priority: required
Section: libs
Source: glibc
Maintainer: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Installed-Size: 9,234 kB
Depends: libgcc1
Suggests: glibc-doc, debconf | debconf-2.0, libc-l10n, locales
Breaks: hurd (<< 1:0.5.git20140203-1), libtirpc1 (<< 0.2.3), locales (<< 2.24), locales-all (<< 2.24), nscd (<< 2.24)
Homepage: http://www.gnu.org/software/libc/libc.html
Download-Size: 2,316 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
Description: GNU C Library: Shared libraries
 Contains the standard libraries that are used by nearly all programs on
 the system. This package includes shared versions of the standard C library
 and the standard math library, as well as many others.



root@rphome:/home/pi/domoticz# sudo apt install libc6
Reading package lists... Done
Building dependency tree
Reading state information... Done
libc6 is already the newest version (2.24-11+deb9u4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by salopette** [comment]
pi@raspberrypi:~ $ sudo apt show libc6
Package: libc6
Version: 2.24-11+deb9u4

pi@raspberrypi:~ $ sudo apt install libc6
libc6 ist schon die neueste Version (2.24-11+deb9u4).

[EDIT (rwaaren] Please only post relevant lines. Thx !

**Comment by gizmocuz** [comment]
Current Arm x86 build system runs on Buster, maybe that causes problems for people still running stretch
I just updated one of my systems (arm x86) running on Buster and i have no issues

**Comment by salopette** [comment]
How can I install the necessary libc6 on stretch?

**Comment by gizmocuz** [comment]
I already had kept the old build system running for more then 180 days to be compatible with the old Debian version, how longer do i have to do this ?

http://baddotrobot.com/blog/2019/08/29/upgrade-raspian-stretch-to-buster/

**Comment by SzemiSun** [comment]
I started to upgrade

**Comment by gizmocuz** [comment]
Thanks! Please tell your upgrade experience...
Another option if you only run Domoticz is to archive the Domoticz folder, 
burn the burster firmware (on a new sd card), install Domoticz, and place the folder back
and run ./updatebeta from the command line

**Comment by nico68000** [comment]
OK after upgrade to buster and install libc6. Thank's

**Comment by gizmocuz** [comment]
@nico68000 , did you need to install libc6 because i did not had to do so at my existing system... it was already installed
Did you issue apt update/upgrade ?

**Comment by SzemiSun** [comment]
> Thanks! Please tell your upgrade experience...
> Another option if you only run Domoticz is to archive the Domoticz folder,
> burn the burster firmware (on a new sd card), install Domoticz, and place the folder back
> and run ./updatebeta from the command line

I have done, Domoticz is working perfectly

**Comment by SirJohnDoe** [comment]
Why is this closed? Nothing is resolved... I run OSMC which can't be upgraded to buster yet. Changing to stable doesn't work with the beta database. Is there any actual solution?

**Comment by gizmocuz** [comment]
@SirJohnDoe , why should we depend on 'OSMC' ? It is time to upgrade ... Ask the guys from OSMC to upgrade please
I also recommend a dedicated machine for Domoticz

**Comment by xztraz** [comment]
upgraded to buster. now it runs for 5-10 minutes max before crashing..   cant touch gui. instant crash..

**Comment by empierre** [comment]
On Odroid, there is no buster, but Ubuntu 18.04.4 LTS
version is "ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27"

broken, can cannot go back due to database format.

**Comment by gizmocuz** [comment]
I use a odroid with armbian

**Comment by empierre** [comment]
# apt-cache policy libc-bin
libc-bin:
  Installed: 2.27-3ubuntu1
  Candidate: 2.27-3ubuntu1

**Comment by gizmocuz** [comment]
Try Armbian

**Comment by empierre** [comment]
I need a LTS, and 18.04 is the latest Ubuntu...

**Comment by Dduck112** [comment]
Hi All,

I updated the RPI to Buster and my beta is running fine after that!!


Let’s first update all the currently installed packages by running the following command.

[code]sudo apt update
sudo apt dist-upgrade -y[/code]




Next, let’s go ahead and also update the Raspberry Pi’s firmware.

We can do that by running the command below on our Raspbian installation.

[code]sudo rpi-update[/code]




Now that we have prepared our Raspbian Stretch installation, we can now start the process of moving to Buster.

To do this, we will need to modify the “/etc/apt/sources.list” file.

Begin modifying the sources file by running the following command.

[code]sudo nano /etc/apt/sources.list[/code]




Within this file, find the following line and change “Stretch” to “Buster“.

This change will allow the package manager to search the Raspberry Pi package repository under the “Buster” distribution instead of the “Stretch” distribution.

Find:
[code]deb http://raspbian.raspberrypi.org/raspbian/ stretch main contrib non-free rpi[/code]

and change to:
[code]deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi[/code]
Once you have replaced all occurrences of “stretch” within the file you can save it by pressing CTRL + X then Y followed by ENTER.




Next we also need to modify the “/etc/apt/sources.list.d/raspi.list” file by running the following command.

sudo nano /etc/apt/sources.list.d/raspi.list
In this file, you need to go ahead and find the following text and change “Stretch” to “Buster“.

Find:
[code]deb http://archive.raspberrypi.org/debian/ stretch main[/code]

Replace With:
[code]deb http://archive.raspberrypi.org/debian/ buster main[/code]
Once you have again finished switching “Stretch” to “Buster“, you can save the file by pressing CTRL + X then Y and then ENTER.



Now before we do the final push to Raspbian Buster, we will first remove the “apt-listchanges” package.

The reason for removing this package is to give us a faster and smoother upgrading process. Without removing this package, the Raspbian operating system will have to load a fairly large changelog file which will slow down your upgrade process considerably.

Feel free to re-install this package after the upgrade process has completed.

Run the command below to uninstall the “apt-listchanges” package.

[code]sudo apt-get remove apt-listchanges[/code]




Finally, with the source files now modified to mention the “Buster” build instead of “Stretch” we are now ready to begin the upgrade process.

The first command will update the package lists stored on the Raspberry Pi. The second command will then update all the packages to their Raspbian Buster versions.

[code]sudo apt update
sudo apt dist-upgrade[/code]
Please note that this process can take considerable time as there are a fair few packages that will need to be updated.

Additionally, you may be required to answer prompts, so don’t stray too far from your Raspberry Pi.
(if it stops whit a error try "sudo apt --fix-broken install") It worked for me!!




Next, we need to run a few more commands to ensure we have cleaned up everything leftover from the upgrade.

The first command that we will be running is the package managers “autoremove” command. This command will remove any packages that have been marked as no longer needed due to changed dependencies.

Run the following command to remove these no longer required packages.

[code]sudo apt autoremove -y[/code]




Now we need to run the apt package managers “autoclean“.

This autoclean command will clear out the package cache. It automatically removes any package files that are no longer available for download and thus are largely useless.

Use the command below to begin the cleaning process.

[code]sudo apt autoclean[/code]




The final thing we should do is restart our Raspberry Pi. Restarting ensures that the Raspberry Pi will load in all the new Buster packages and clear out any old data sitting in memory.

Run the following command to reboot the Raspberry Pi.

[code]sudo reboot[/code]
At this point, you should now have successfully updated your Raspberry Pi from Raspbian Stretch to Raspbian Buster and Domoticz V4.11763 will run.

**Comment by mikizvi** [comment]
Running Ubuntu 18.04.4, just tried to upgrade to version 2020.1.11804: getting this error:

```
./domoticz: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./domoticz)
./domoticz: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./domoticz)
```

Did an "apt update" and "apt upgrade", didn't help.

Any advice or recommendation would be appreciated.

# apt install libc6
Reading package lists... Done
Building dependency tree
Reading state information... Done
**libc6 is already the newest version (2.27-3ubuntu1)**.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
# cat /etc/os-release
NAME="Ubuntu"
VERSION="**18.04.4 LTS (Bionic Beaver)**"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
#

**Comment by gizmocuz** [comment]
from the installation folder could you try
./updatebeta

**Comment by gitpeut** [comment]
Obvously I ran into the same issue on Ubuntu 18.04.4 LTS, Domoticz failing with dependencies on non-existing versions of GLIBC.

./updatebeta worked.

Thanks.

**Comment by gizmocuz** [comment]
Great to hear, yes it's because the release was compiled outside travis
I will copy the beta into the release folder for now

**Comment by mikizvi** [comment]
Thanks.  Working now.
