### ISSUE TITLE
buienradar still generates errors and thread closing unexpectedly

### ISSUE THREAD

**Issue by GravityRZ** [domoticz/domoticz#3921]
this is not an important bug but still it keeps  flooding the log
The first issue is known and has something to do with the way we check the buidenradar site(and the ip address used). would be nice if we implement the multiple check before generating the error
or skip it completely. if it does not update you know it is not working.

second one is strange because it seems to end the thread and automatically starts it again

> 2020-02-17 22:28:10.011 Error: BuienRadar: Error getting http data! (Check your internet connection!)
2020-02-17 22:34:18.195 Error: Buienradar hardware (9) thread seems to have ended unexpectedly
2020-02-17 22:34:32.197 Error: Buienradar hardware (9) thread seems to have ended unexpectedly
2020-02-17 22:34:39.346 Error: BuienRadar: Error getting http data! (Check your internet connection!)
2020-02-17 23:55:19.287 Error: BuienRadar: Error getting http data! (Check your internet connection!)
2020-02-18 06:12:46.167 Error: BuienRadar: Error getting http data! (Check your internet connection!)

**Comment by rwaaren** [comment]
> this is not an important bug but still it keeps flooding the log

The github issue list is for code bugs only. These are not code bugs but error messages reporting that something is wrong.  Even more so as this subject was already beaten to death in the past.

Stating that they are "Flooding the logs"  based on 4 http errors is als a bit exaggerating. 
The multiple checks you refer to, are already implemented in Domoticz V4.11430 and later versions.  

The " seems to have ended" message tells you that this hardware did not responded quickly enough to the main domoticz process. In this case either a local performance issue or because the repeated http call takes to long.

Please use the forum if you want to discuss further.

**Comment by GravityRZ** [comment]
thanks. did not know that the multiple check was implemented(did not notice any difference in message volume). ok flooding is a bit to big but 12 entries a day is still not looking good.
when there is nothing seriousa going on i like the log to be clean. maybee we should change the definition and not define this as an error but as a warning. i have domoticz display errors only so warnings should be skipped.

regarding the thread ended. i have a quadcore synology doing nothing so performance is not the problem and the repeated http calls are probably the problem. 
will take it to the forum next time
