### ISSUE TITLE
Events are not triggered when a user variable is updated from a lua script

### ISSUE THREAD

**Issue by Rimco** [domoticz/domoticz#396]
After scheduling a user variable update from LUA like:

commandArray['Variable:'..name] = target .. ' AFTER ' .. (remaining+5)

I can see the update being performed at the expected time, but the LUA script that scheduled the check in the first place is never called at that point. Is this a bug or a feature?

**Comment by nayrnet** [comment]
why call the LUA script again? I the point is so you can setup an event to execute at a later time without running the script every min.. so yeah I think this is working as designed.

**Comment by Rimco** [comment]
Thanks for your comment, but I have a bit more complicated situation:
I'm trying to have a generic way of controlling devices, but with some check first. Main check is how long ago the device was changed manually. If this manual change was recent, I want to delay automatic updates. At first sight you could just schedule the update to happen later, but because in the meantime a manual change may be performed again or actually the target changes, I want not just schedule it unconditionally.
To solve this, I wanted to update some variable in a delayed manner after which I trigger my script to check once again. In this way I can perform the check only when needed and not just every minute.

**Comment by Rimco** [comment]
After some more investigation it seems no script is triggered at all when a variable is updated from a lua script, which seems a bug to me.

**Comment by gms1** [comment]
I'm sorry, but after looking into this issue and finding the place in the code that is responsible for this, I realized that this works as designed 

and was even documented in the wiki:
https://www.domoticz.com/wiki/User_variables
quote: Note that setting a variable through an event does not trigger the event logic again since this can create a nasty loop. 

I would vote for this to be considered as enhancement, but I am afraid the event system needs refactoring (something like an event queue), if someone wants to implement this in a clean way

**Comment by gizmocuz** [comment]
Nobody is working actively on the eventsystem since years, i did some enhancements and fixes.
If you would like to refactor it, please do so ;)

**Comment by gms1** [comment]
Yes, thank you ;) Do you have any expectations for the refactored event system?
but I am currently evaluating how the alarm system could be improved ( having paritions/zones...) so that it would least meet my basic requirements. An alarm system based on scripts is not going to fullfill the acceptance test of my wife :) Any thoughts on this?

**Comment by Rimco** [comment]
I can understand the problem that loops can be a tricky situation, but this
actually is already in place when devices are used. As a work around I now
have a dummy device to trigger my script again instead of a user variable,
which does work.

So, my main surprise was that is supported for devices, but not for user
variables.

**Comment by nayrnet** [comment]
Well often the best solution for avoiding loops is to call a userVariable, what method would you propose to avoid loops if you trigger variables with events?

I think we need something like a silentCommandArray[] return where people can update a device/variable without triggering the event system, then set behavior like your expect so all CommandArray returns will trigger subsequent events.. while using a better method to escape logic loops.

the JSON API would need a silent=true option exposed.
