### ISSUE TITLE
Rflink issue with domoticz 2020.1 / 2020.2 and Blyss switch

### ISSUE THREAD

**Issue by gmatta93** [domoticz/domoticz#4022]
Hello,

I've noticed an issue with the new version 2020.1.
Rflink is works fine except with Blyss switches. When I want to turn on or turn off my light connected to a Blyss switch, nothing happens.
In logs, I can read :  
2020-03-28 20:12:42.631 Status: User: Admin initiated a switch command (362/Escalier_Blyss/Off)

When I do the same with domoticz 4.10717, the light turns On or Off and in logs I can read : 
2020-03-28 20:09:30.939 Status: User: Admin initiated a switch command (362/Escalier_Blyss/On)
2020-03-28 20:09:30.942 Status: RFLink Sending: 10;Blyss;00305b;G1;ON;

For your information, I host domoticz on a Rpi 3 (raspian buster) and my Rflink version is the R48.

Thank you in advance,
Guillaume

**Comment by gizmocuz** [comment]
Hi Guillaume,

Please use the search option before making a new issue, there are some references here.
I do not own a Blyss device, so I can not assist, but maybe someone can create a code patch with a option to switch to the old/new behavior if needed
If you find the right issue, please close this one and continue in that issue

https://github.com/domoticz/domoticz/issues/3232

https://github.com/domoticz/domoticz/issues/2228

https://github.com/domoticz/domoticz/issues/2055

**Comment by gmatta93** [comment]
Hi,

Sorry I don't know if one of these issues is the same bug of mine.
I can tell you that the problem is not solved in 2020.2.

I don't know how to help better.

Regards,
Guillaume

**Comment by stanb29** [comment]
Hi,
I have the same type of problem since the passage in 2020.1 and 2020.2. My blyss modules no longer work correctly. I have 5 blyss modules for roller shutters. Since the transition to 2020.1, a module no longer works from domoticz, it retrieves the code from one of the other 4.

I do not understand in version 4.10717
RFLink Sending: 10; Blyss; 00543d; B2; UP; works but not in version 2020.1. it will use the following code Status: RFLink Sending: 10; Blyss; 00543d; A2; UP; in 2020.1

**Comment by gizmocuz** [comment]
Please use the search option here, this has been discussed before.
Seems to be a problem with RFLink or new type of Blyss, I am unable to help, so someone with a Blyss might be able to adjust some code, maybe make a configuration option for this
Best to continue in the old thread
