### ISSUE TITLE
dzVents: device.setValue(anyValue).afterSec(someIntConstant) fails

### ISSUE THREAD

**Issue by tszalajITDev** [domoticz/domoticz#4060]
After update to 2020.1 dzVents instruction device.setValue(anyValue).afterSec(someIntConstant) fails with error:
/usr/local/domoticz/dzVents/runtime/Utils.lua:87: attempt to perform arithmetic on a nil value (local 'hours')
The error is caused inside function self.stringToSeconds(str) when .afterSec() is called with some integer constant someIntConstant for example 10.
In line 84 stringToSeconds assumes that string must be in form matching regular expression:
hours, minutes = str:match("(%d+):(%d%d)")
but the actual value of str is 10, so hours and minutes are nil. Probably function stringToSeconds shouldn't be called at all in afterSec, because according to documentation afterSec parameter should be a number.

**Comment by rwaaren** [comment]
This is already fixed in commit [Better check for numeric value in .afterXXX() and .at()]( https://github.com/domoticz/domoticz/commit/3baaa6712) (build 11883)

by changing line 174 in dzVents/runtime/TimedCommand.lua from

`			if type(value) == 'string' then value = utils.stringToSeconds(value) end -- called by 'at()' `
to
`			if tonumber(value) == nil then value = utils.stringToSeconds(value) end -- No number so called by 'at()' `

You can workaround it in your scripts by replacing 

`device.setValue(anyValue).afterSec(someIntConstant)`
with 
`device.setValue(anyValue).afterSec(tonumber(someIntConstant))`
