### ISSUE TITLE
Zwave pooling always 5 min 

### ISSUE THREAD

**Issue by fr3sh** [domoticz/domoticz#4062]
HI 

No mater what i will set the "pooling" time is 5min. I have set the aeon stick for 15 min interval but domoticz still "pooling" it 5 min interval

![000255_2020-04-08 22_24_26-Domoticz](https://user-images.githubusercontent.com/6498987/78830150-cb186000-79e7-11ea-9d00-e564f1c486ce.jpg)

![000256_2020-04-08 22_25_32-Domoticz](https://user-images.githubusercontent.com/6498987/78830247-ea16f200-79e7-11ea-9eb6-9b357f5f1bee.jpg)
![000257_2020-04-08 22_26_04-Domoticz](https://user-images.githubusercontent.com/6498987/78830283-f8fda480-79e7-11ea-98d7-1cf0d474a610.jpg)

Restart not helping

**Comment by RicardP** [comment]
The polling interval is only for controller to Ask nodes for values when a node is enabled to be polled. Normally you should not need polling the nodes, instead they have their own setting for report properties, like interval. 
If the issue is about the unidentified 0x0000 node 8 in your list, it means you no config file in OZW to fully support and configure it, please check with manufacture for parameters to make the OZW config file, more information on https://www.openzwave.com

**Comment by fr3sh** [comment]
@RicardP on my screen you can see my controller setings. Everything is set up as its supouse to be. Node 8 is my old device that is not now in the network. Dont bother this. 
Im aware od that what you are saying but pooling is not working.

**Comment by fr3sh** [comment]
For fibaro heat controller im must to set up pooling. IT willa not give me temperature readings if i dont enable pooling :(

**Comment by gizmocuz** [comment]
@fr3sh , the short log interval you display in your screenshot has nothing to do with the zwave polling interval (which is by default 60 i believe)

This is how the zwave polling interval works

- Set to 60 seconds
- You have for example 5 nodes
- each device is polled in 12 seconds (60/5)

This is not 100% true, because some nodes have multiple values, so if you have a total of 10 values, each value is polled in 6 seconds (60/10)

When a new value is received from your node, it is directly displayed in the user interface

The shortlog period is set to 5 minutes, and stores this value in the database (in 5 minute intervals, and there is sometimes some technical calculation being used for wind/temp/..)
At the end of the day (24 hours) a day log value is stored in the database (which is represented in the week/month/year graphs)

**Comment by gizmocuz** [comment]
Please use the forum

**Comment by gizmocuz** [comment]
IF you want to have a high interval, please consider using InfluxDB in combination with Grafana
(Domoticz has build in support to push to InfluxDB)

**Comment by fr3sh** [comment]
@gizmocuz so what this parametr is for if it's describead as:
 "Set the time period between polls of a node's state. The length of the interval is the same for all devices." 
Its has no effect at all. Pulling data without setting the time interval will drain batery. 

Please consider reopen this.

**Comment by gizmocuz** [comment]
@fr3sh , it is because 'some' nodes do not send any data, unless it is requested.
(For instance the GreenWave power node)

This issue is not a issue. The short-log interval is by design 5 minutes and is not going to change
As mentioned above, you can use influxDB/Grafana if you need to have a smaller window

**Comment by fr3sh** [comment]
@gizmocuz Sorry for bothering you but I have exacly the same situation on Fibaro Heat Controller. If I do not enable polling it will not send the data like temperature etc. It's battery device. When polling is turn ON on the device (termostat) readings are always 5 min no mater what I will set on the Controller Polling interval. 
Maybee "5 min" in the title misleading you with the situation of standard communication device but is in polling mode. Sorry if I make you think otherwise

**Comment by gizmocuz** [comment]
@fr3sh , please read my first response carefully .... short log, day log ... and that is does not relate to polling and some posts further about InfluxDB/Graphana
