### ISSUE TITLE
Xiaomi Aqara WXKG02LM bug with 2020.1

### ISSUE THREAD

**Issue by VBill45** [domoticz/domoticz#4072]
Hi
I used Version: 2020.1 (build 11930) Build Hash: 423448b7e Compile Date: 2020-04-10 06:53:38 dzVents Version: 3.0.2 Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
It's Beta distribution.

I have a problem with the WXKG02LM double aqara buttons since the last Domoticz updates 
normally I had this:
Left button click = 10
Right button click = 20
Button L and R click = 30
Left button double click = 40
Right button double click = 50
L and R button double click = 60
Left button long click = 70
Right button long click = 80
L and R button long click = 90

Now I have this:
Left button click = 10
Right button click = 20
Button L and D click = 30
Left button double click = **20** (Normally 40)
Right button double click = 50
L and R button double click = 60
Left button long click = **30**(Normally 70)
Right button long click = 80
L and R button long click = 90

(Text physical action on the button = return level of the button in Domoticz)

I opened a post on easydomoticz.com and I am not the only one with this problem, you would make a lot of joy to all users of aqara with domoticz.

By that Domoticz is really cool, good job.
Thanks

**Comment by Huupke** [comment]
Indeed this seems NOK. I'll check when this slipped in. From which version did you upgrade?

**Comment by VBill45** [comment]
Hello
I don't know, but I'd say the problem's been there for about 1.5 to 2 weeks.

currently i used Version: 2020.1 (build 11930) Build Hash: 423448b Compile Date: 2020-04-10 06:53:38 dzVents Version: 3.0.2 Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]
It's Beta distribution.
Before in beta distribution too.

Thank you for taking the time to address this issue.

**Comment by Huupke** [comment]
This bug is also in master and release 2020.1
You can assign me if you want. Do we want to fix this on master as well? I can create a hotfix branch for master and a separate branch and PR for development.

**Comment by Huupke** [comment]
This issue seems to be introduced when pulling in 'Solution for Xiaomi Wireless Single Wall Switch (#3962)'. I don't understand the change so need some help in explanation on what was intended here.
commit 71f848e19c8543b99f8c3a94b5f64b5f5a751d24
@EvgenaNet can you help? or @itpansic who seems to be involved before

Seeing the hot discussion on the PR in https://github.com/domoticz/domoticz/pull/3962 I think some discussion is needed to prevent other regression.
@rwaaren seemed to have tested this properly with a single rocker but didn't check the double rocker. A solution for both is needed of course so I'll look into this.

**Comment by EvgenaNet** [comment]
> This issue seems to be introduced when pulling in 'Solution for Xiaomi Wireless Single Wall Switch (#3962)'. I don't understand the change so need some help in explanation on what was intended here.
> commit [71f848e](https://github.com/domoticz/domoticz/commit/71f848e19c8543b99f8c3a94b5f64b5f5a751d24)
> @EvgenaNet can you help? or @itpansic who seems to be involved before
> 
> Seeing the hot discussion on the PR in #3962 I think some discussion is needed to prevent other regression.
> @rwaaren seemed to have tested this properly with a single rocker but didn't check the double rocker. A solution for both is needed of course so I'll look into this.

Hello!
What do you want i will explain? My switches not worked. Was trouble with "levels" from the beginning. Double and long click not recognized by DMZ, because was mistake in the code. Now, when pulled my PR, single switches work fine, but double switch not working (levels 40 and 70).
Do you understand?

**Comment by Huupke** [comment]
In that case you didn't provide a full solution but only for the single rocker. It seems that the levels have a different meaning for the single vs the double, is that correct? Does anyone know where these levels are defined?
We could fix in XiaomiGateway by also checking which device type it is but I'm not sure that's the right thing to do.

**Comment by rwaaren** [comment]
> > @rwaaren seemed to have tested this properly with a single rocker but didn't check the double rocker. A solution for both is needed of course so I'll look into this.
> 
True ! Sorry for no have emphasized that in my update. I don't own all the xiaomi devices controlled by this source so testing the whole suite must probably become a joined effort. Happy to test with the devices I have.

**Comment by Huupke** [comment]
Thanks. I have a solution for both now although it's not the most elegant one. I'm able tot test with both but a sanity check from someone else is welcome taken the history of regression into account.
This is a hotfix on master if we want that branching strategy and I'll redo the solution on development with a different branch because it requires quite some merging.
https://github.com/Huupke/domoticz/tree/fix-xiaomi-dual-button-bug-%234072
https://github.com/domoticz/domoticz/pull/4073

**Comment by VBill45** [comment]
Hello
Personally I have double switches WXKG02LM, single switches WXKG03LM and round switches WXKG01LM.
If I can help with testing, no problem, just explain the procedure to me.

**Comment by Huupke** [comment]
I made a separate branch and PR for development that is slightly different. The first branch also merges into development if needed but I prefer this one:
https://github.com/domoticz/domoticz/pull/4074

**Comment by Huupke** [comment]
> Hello
> Personally I have double switches WXKG02LM, single switches WXKG03LM and round switches WXKG01LM.
> If I can help with testing, no problem, just explain the procedure to me.

You can help by checkout out and building my branch and test your switches with all possible clicks/states.
Same holds for @EvgenaNet and @rwaaren if you like.

**Comment by rwaaren** [comment]
Tested OK with single Rocker, motion sensor, button and gateway
Tested NOK with Temp / Hum / Baro  sensor

Any reason why you moved away from #include "XiaomiHardware.h" ?

**Comment by Huupke** [comment]
Which branch did you test? And what didnt work with the weather sensor? It seems to work on my setup and it also shouldn't be affected by this change.
In the master/release we didn't have the XiaomiHardware.h yet, I recently introduced it on development and we still use it there. More inline strings can move to the XiaomiHardware.h in the future.

**Comment by rwaaren** [comment]
I tested with your first PR (the one against the master release).   The temp/hum/baro updates did not came trough.
Will try with the latest one now.

**Comment by rwaaren** [comment]
Tested with latest and single Rocker, motion/ lux  sensor, button and gateway and Temp / Hum / Baro sensor are working. 
Temp / Hum / baro with a very long interval. It updates on domoticz start and then it takes > 50 minutes until next update while temperature changed significant directly after start.
From my history log I can tell this was more frequent with build 11932 but cannot be sure which commit is responsible.

**Comment by Huupke** [comment]
Thanks, I think I see the same effect and I'll look into it. I can compare master and development. Keep in mind that this interval change is probably not due to this PR.

It seems the TempHumBaro only gets updated with a 'read_ack' or 'heartbeat' command and I think this was already the case in the past. It seems those are the cases where all 3 values are send while in the 'report' command you get only 1 value at the time.
The separate Temp and Hum sensors get updated with every 'report' command which is on every state change from Xiaomi. How the TempHum also gets updated I can't tell from the XiaomiGateway code which is strange. 

@rwaaren, are you sure the TempHumBaro gets updated more frequently on build 11932 or older?

**Comment by rwaaren** [comment]
> @rwaaren, are you sure the TempHumBaro gets updated more frequently on build 11932 or older?

Checked again and also on previous versions update frequency for this device was 50, 55 or 60 minutes on a continuously running system. The update will also happen when domoticz is (re) started and that does cloud the  analysis of the history table.
I did not take the domoticz restarts into account which do happen in my setup when I test something on my production system. ( I sometimes need to do that because I have not all hardware on my test system)
Hope this clarifies

**Comment by Huupke** [comment]
So can we conclude that there is no regression? The last PR is for the development branch and up to @gizmocuz to decide on what to do with the hotfix branch targeting the master after the beta has been stable and working for a certain period.

**Comment by VBill45** [comment]
Hello

today's update :Version: 2020.1 (build 11938)
Build Hash: b71a76815
Compile Date: 2020-04-14 11:56:55
dzVents Version: 3.0.2
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

My Aqara double-switches are working correctly.

Thanks guys, you're too strong

**Comment by dwmw2** [comment]
I have a user in https://github.com/openwrt/packages/issues/12259 reporting a failure with a Xiaomi Wireless Dual Wall Switch. I'm not familiar with the hardware or the Xiaomi Gateway; could someone attempt to help debug please?
