### ISSUE TITLE
Issue with Else_If

### ISSUE THREAD

**Issue by bigus19** [domoticz/domoticz#4146]
Hello,
Don't know why but Blocly script like this gives the result:
![bugs](https://user-images.githubusercontent.com/4159804/81344958-f9a55b80-90b7-11ea-98cb-d029ec9fb487.png)

**Comment by Sneeuwtijger** [comment]
Domoticz has a forum, in this forum is a specific section on Blocky - I suggest you post your question there, Github is not the place for this kind of problems ;)
Link to this sub section - https://www.domoticz.com/forum/viewforum.php?f=62

**Comment by bigus19** [comment]
Hello, I add question on this forum, but nobody write. I think this is a bug in Domoticz, I don't think that it is my error in code.

**Comment by rwaaren** [comment]
Probably nobody answers because the same issue was already answered multiple times. If you use the search with the words Blockly and nested you will get at least 65 hits. Also here in the issue list it was already reported and answered.
[issue on github](https://github.com/domoticz/domoticz/issues/2154)
[forum post](https://www.domoticz.com/forum/viewtopic.php?f=62&t=29560&p=225026#p225026)
