### ISSUE TITLE
Unknown nodes added in Zwave that can not be removed.

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/domoticz#4192]
RaspberryPI 3B:
Domoticz 2020 build 12106

Every time I do a restart of Domoticz I get this error:

`2020-05-30 15:21:51.930 Error: OpenZWave: Type_Notification, NodeID not found internally!. HomeID: 0, NodeID: 255 (0xff)`

This is similar to [this](https://www.domoticz.com/forum/viewtopic.php?f=24&t=31345&p=247525&hilit=NodeID%3A+0#p247525]) problem, possibly the same cause.

Possibly also related is that after a restart I got an unknown "Route binary sensor" node (without any other info, both in Domoticz and in the Zwave control panel) that was added.

Removing these nodes with the ZWave Control panel does not work, the Control panel hangs after performing one Controler action and then only shows the "cancel" button. This issue is also reported on the forum, [here](https://www.domoticz.com/forum/viewtopic.php?f=6&t=32886).

If I just use the delete button in Domoticz the hardware appears again after a restart.
![ZWCP](https://user-images.githubusercontent.com/34967010/83332636-a086ad00-a29c-11ea-9849-4b2fbf9b3d30.png)

**Comment by bikeymouse** [comment]
Update:
I repeatedly used the  OZWCP to do a "Refresh Node Info" and a "Remove Failed Node", canceling the command in between on the ghost node "Router binary sensor" because else the OZWCP else freezes/refuses to send additional commands. 
Also did a soft-reset Controller from Domoticz and a power off/reboot of the system.

After that, finally the ghost node was marked as dead, which enabled it to be removed immediately with the OZWCP "Remove Failed Node" command. After that even after a restart it does not return.

Magically I also get no more messages; "NodeID not found internally!. HomeID: 0, NodeID:0" messages anymore.

So this seems to be solved for now: however IMO there should be a consistent and user friendly way to remove "ghost nodes" or nodes that where once used be no longer in use without doing XML-editing on the OZW cache files or performing repeated actions in OZWCP.

**Comment by gizmocuz** [comment]
I'm not sure this is a Domoticz issue. It could be a controller issue or a library issue.
If we say remove node, it should be removed, it that does not work, or the XML is corrupt, this should be done on another level then Domoticz
Glad you got it removed. I am experiencing a similar issue on one controller and am also not able to add any nodes to it, or factory reset. I gave up and bought a new controller

**Comment by htilly** [comment]
@gizmocuz 
I just solved this problem with another tool that have the option:
"Mark battery device as failed" implemented - It worked instantly.

I wrote about it in the forum:
https://www.domoticz.com/forum/viewtopic.php?f=24&t=32763&p=249374&hilit=remove+dead#p251451

Could this be implemented in the Domoticz Control Panel?!

**Comment by gizmocuz** [comment]
@htilly , great you got this solved !
But does z-way work only with zwave.me hardware or does it also work with other manufacturers ?
I wonder what command is send, because I do not see a OpenZWave function that looks like it could do this

section 2.3.3
https://www.generationrobots.com/media/Domotique/Z-Way-developers-documentation.pdf

Some discussion here that stopped in 2014:
https://groups.google.com/forum/#!topic/openzwave/n60BmOimMgw

**Comment by htilly** [comment]
Agreed. After finally finding the solution to my problem I start searching for different solutions (problem with sleeping devices).. Seems like I missed an option in Domoticz and options.xml:
<Option name="AssumeAwake" value="true" />

As I understand my problem Domoticz or ozwcp didn't want to mark my dead devices as dead due to the fact that they are running on batteries and hence in sleep mode. 

If enabling the option above I would guess that Domoticz will treat all devices as awake, including my failed device, and hence probably mark them as dead, which in turn would allow me to remove them. In theory...  =)

I assume this would apply to ALL devices. Would it be possible to "AssumeAwake" per device? Might be how they solved it (guessing)?

As I no longer have dead devices I haven't tested this, but I guess it shouldn't be too hard to reproduce =)
