### ISSUE TITLE
Aeotec DoorBell 6 - Zwave 1.6

### ISSUE THREAD

**Issue by matjoker** [domoticz/domoticz#4202]
Hi,
Even if the new zwave  command class 0x79 (SOUND_SWITCH) should be now implemented in Zwave 1.6, it looks it still doesn't work for the Aeotec DoorBell 6.
This class isn't recognized (CommandClass: No operation):

Error: OpenZWave: Value_Changed: Tried adding value, not succeeded!. Node: 28 (0x1c), CommandClass: NO OPERATION, Label: Browse Tones, Instance: 1, Index:_ 1_
Status: OpenZWave: Unhandled class: 0x79 (NO OPERATION), NodeID: 28 (0x1c), Index: 1, Instance: 1

Thanks for your help

Matthieu

**Comment by gizmocuz** [comment]
@matjoker , Please send me a PM on the Forum (user GizMoCuz)

**Comment by matjoker** [comment]
I sent it.

Thks
Matthieu

**Comment by gizmocuz** [comment]
@matjoker , thanks, replied back

**Comment by Bardaf** [comment]
Hi,
today I see the following error when I try to activate my doorbell by domoticz :
Error sending switch command, check device/hardware (idx=653) !
and in the log, I have the following lines:
2020-11-24 10:10:02.219 Status: User: ****** (IP: ******) initiated a switch command (653/Sonnette 1/On)
2020-11-24 10:10:02.220 Error: ZWave: Node not found! (NodeID: 52, 0x34)

My domoticz is on the beta channel and is up to date (build 12701), but I already noticed the problem yesterday in build 12697

sorry for my bad English

Thks

**Comment by gizmocuz** [comment]
@Bardaf , did it work before ?
You could try to enable 'accept new hardware', and press the physical doorbell, have a look in the devices overview,
and see if you have multiple switches.
You might have to use another one

**Comment by Bardaf** [comment]
Yes, it works since your changes for matjoker. I do have multiple switches, but they all make the same mistake.

In addition, at the ZWave configuration level, I no longer have access to the doorbell 6 config (see attached screenshot)

I have not yet tried to delete the material to re-associate it

![Config_aeotec_doorbell6_domoticz](https://user-images.githubusercontent.com/68925998/100283639-2fcffd00-2f6e-11eb-8e56-ec5f80106fb6.png)

**Comment by gizmocuz** [comment]
Can you operate the doorbell in the zwave control panel ?

**Comment by Bardaf** [comment]
Hi, sorry for the delay.
No, I cannot make the doorbell work in the zwave control panel (see screenshot).
By the way, until now I could not access this control panel anymore because of the character encoding bug (https://github.com/OpenZWave/open-zwave/issues/2085).
Apparently something has changed, because I have access to the control panel again, but the doorbell no longer communicates with the zwave controller.
I will try in the days to come to remove the doorbell and re-associate it.


![Config_aeotec_doorbell6_openzwave_controller](https://user-images.githubusercontent.com/68925998/100803228-1c6bd880-342b-11eb-9cad-2acabfa4f079.png)

**Comment by Bardaf** [comment]
Hello,
after a while, I therefore removed the device and re-paired it. 
I have a working device again. And I no longer have access to the zwave control panel.

Thanks for the time devoted to my problem.

**Comment by gizmocuz** [comment]
Thank you for the feedback!
