### ISSUE TITLE
Warning in the upgrade popup for database change.

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4266]
It would be nice to be warned if the popup of an update of Domoticz includes a warning if the database is upgraded.
Mostly (or all the time) it is not possible to go back if a problem with Domoticz occurs to a previous version with a different database version.

**Comment by gizmocuz** [comment]
@SargonofAssyria , that's not possible. But we are always backwards compatible, not upwards.
You should never return to a previous version, or try to avoid it by all means.
Another option it to create a complete backup of the Domoticz folder once in a while (week,month), when you restore this you should be back without any problem. (At the cost of loosing the latest logs/changes)

**Comment by rwaaren** [comment]
Before pressing the button you could have a look at this [Wiki page](https://www.domoticz.com/wiki/Domoticz_versions_-_Commits) You can find there what changed and if/ when the database or dzVents version-numbers increased.

**Comment by SargonofAssyria** [comment]
Of course it is possible. When there is a will there is a way.
The local gui can know the database version. Domoticz does make a request to see if there is an update.
At that time the latest database version get be fetched too, so you can compare.
This is the easy way for a user/consumer. The wiki is the more complex way. Not everybody knows where to find that.

**Comment by gizmocuz** [comment]
Another way of saying is, No we do not support going back to a previous database without also downgrading Domoticz to a version that is compatible with that specific database
It should also not be needed.
If you do not trust Domoticz beta's, please do not use them.
Or as mentioned, just make a full backup of the domoticz folder before doing the upgrade.
You can make a very simple bash script for this. If you place call the 'updatebeta' script at the end of this backup script you could run this instead of the updater in the web-gui

**Comment by SargonofAssyria** [comment]
It's not for me, but for others. I already make double backups every hour and snapshots. Database backups every 5 minutes.
So I am good. I even have my own update version otherwise my updatebeta get overwritten everytime.
I am not convinced, but I understand it.
