### ISSUE TITLE
Updating a dummy Thermostat Setpoint caused a double event action/call

### ISSUE THREAD

**Issue by rwaaren** [domoticz/domoticz#4282]
When updating a Thermostat  device with MQTT with MQTT loop prevention enabled, the update is send regardless to the domoticz/out  topic.

I did some debugging and found that the Thermostat update command is send by both MainWorker::UpdateDevice and  MainWorker::ProcessRXMessage to sOnDeviceReceived.  The second time the loop prevention guard fails as the m_LastUpdatedDeviceRowIdx is reset to 0 after the first time the potential loop is recognized.

During debugging I also found that a dzVents script set to trigger on a Thermostat update is triggered twice on 1 update and when MQTT loop prevention is disabled a Thermostat update is also send twice to domoticz/out by MQTT.
I would not be surprised if this behavior turns out to be related to the above.

Restoring MQTT loop prevention for Thermostats can be done relatively simple by only changing the value of m_LastUpdatedDeviceRowIdx when an update of another deviceRowID is send. 
I tested this fix and it works so I will prepare a PR for it.

Preventing double script triggers and -double MQTT messages to domoticz/out is probably also needed but is likely beyond my knowledge of the process.

**Comment by gizmocuz** [comment]
I'm not sure if the PR fixes the initial issue. The loop prevention in MQTT is to prevent loops between MQTT messages.
In this case, I think it should not be send in UpdateDevice as it is received with sOnDeviceReceived?

Could it be that this is caused in MainWorker::UpdateDevice by the call to SetSetPoint ?
Which calls MainWorker::SetSetPointInt

What device Type/Subtype are you using ?

Maybe for Thermostat devices sOnDeviceReceived should not be called in MainWorker::UpdateDevice
This because the setpoint is 'set' and this causes a Update/MQTT/Trigger

**Comment by rwaaren** [comment]
The PR does indeed not solve the underlying issue but it does prevent the MQTT loop. In my tests there were no side effects.
I looked in the code causing the second pass to MQTT and spend quite a lot of time trying to understand the flow trough it but it still beyond my current understanding of the domoticz internals and C++ skills to come with a fix for this.

I tested with a virtual device type Thermostat (242) subType SetPoint (1)

**Comment by gizmocuz** [comment]
@rwaaren , It's a virtual thermostat ? The type = pTypeThermostat and subtype = sTypeThermSetpoint
Could you post the payload of the MQTT message so I can try to replicate this ?
It could very well be that in MainWorker::UpdateDevice the check if we are going to call 'SetSetPoint' should be before sOnDeviceReceived, and after this call we issue:

```
	g_bUseEventTrigger = true;
	return true;
```

**Comment by rwaaren** [comment]
> @rwaaren , It's a virtual thermostat ? The type = pTypeThermostat and subtype = sTypeThermSetpoint
> Could you post the payload of the MQTT message so I can try to replicate this ?

@gizmocuz, Yes it's a virtual thermostat. On the device tab is shows as  

Type            | subType
Thermostat | SetPoint


Prevent loop for MQTT set to true, 
dzVents script trigger on device 151

Command send:
`mosquitto_pub -m '{"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 , "parse": false}' -t domoticz/in
`

Listening:
```
mosquitto_sub -F "%U - %t - %p" -v -p 1883 -t "#" 

1598018002.830361630 - domoticz/in - {"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 , "parse": false}

1598018002.936384735 - domoticz/out - {
        "Battery" : 255,
        "RSSI" : 12,
        "description" : "",
        "dtype" : "Thermostat",
        "hwid" : "3",
        "id" : "00140E7",
        "idx" : 151,
        "name" : "KamerTemp Set",
        "nvalue" : 0,
        "stype" : "SetPoint",
        "svalue1" : "33.00",
        "unit" : 1
}


``````
domoticz log (dzVents script does not trigger):
```
2020-08-21 15:53:22.830  MQTT: Topic: domoticz/in, Message: {"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 , "parse": false}
2020-08-21 15:53:22.833  Sending SetPoint to device....
2020-08-21 15:53:22.834  (Virtual) Thermostat (KamerTemp Set)

```
--------------
Command send:
`mosquitto_pub -m '{"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 }' -t domoticz/in
`

Listening:
```
mosquitto_sub -F "%U - %t - %p" -v -p 1883 -t "#"

1598018188.793895317 - domoticz/in - {"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 }
1598018188.905757821 - domoticz/out - {
        "Battery" : 255,
        "RSSI" : 12,
        "description" : "",
        "dtype" : "Thermostat",
        "hwid" : "3",
        "id" : "00140E7",
        "idx" : 151,
        "name" : "KamerTemp Set",
        "nvalue" : 0,
        "stype" : "SetPoint",
        "svalue1" : "33.00",
        "unit" : 1
}

```
domoticz log (dzVents script triggered twice):
```
2020-08-21 15:58:20.202  MQTT: Topic: domoticz/in, Message: {"command" : "udevice", "idx": 151, "svalue": "33.00" , "battery": 34 }
2020-08-21 15:58:20.205  Sending SetPoint to device....
2020-08-21 15:58:20.211  (Virtual) Thermostat (KamerTemp Set)
2020-08-21 15:58:20.238  Status: dzVents: Info: Handling events for: "KamerTemp Set", value: "33.00"
2020-08-21 15:58:20.238  Status: dzVents: Info: ------ Start internal script: dz setPoint: Device: "KamerTemp Set (Virtual)", Index: 151
2020-08-21 15:58:20.238  Status: dzVents: !Info: setpoint device 151 was set to 33.0
2020-08-21 15:58:20.238  Status: dzVents: Info: ------ Finished dz setPoint
2020-08-21 15:58:20.279  Status: dzVents: Info: Handling events for: "KamerTemp Set", value: "33.00"
2020-08-21 15:58:20.279  Status: dzVents: Info: ------ Start internal script: dz setPoint: Device: "KamerTemp Set (Virtual)", Index: 151
2020-08-21 15:58:20.279  Status: dzVents: !Info: setpoint device 151 was set to 33.0
2020-08-21 15:58:20.279  Status: dzVents: Info: ------ Finished dz setPoint



```

**Comment by gizmocuz** [comment]
Thanks, I will do some testing very shortly ;)

**Comment by gizmocuz** [comment]
@rwaaren , this problem does not only occur with MQTT, also by calling the JSON API to update the temperature device

`http://127.0.0.1:8080/json.htm?type=command&param=udevice&idx=151&nvalue=0&svalue=20`

when I modify the top part of MainWorker::UpdateDevice to look like

	**g_bUseEventTrigger = parseTrigger;

	// Get the device index
	std::vector<std::vector<std::string> > result;
	result = m_sql.safe_query("SELECT ID FROM DeviceStatus WHERE (HardwareID=%d AND DeviceID=='%q' AND Unit==%d AND Type==%d AND SubType==%d)", HardwareID, DeviceID.c_str(), unit, devType, subType);
	if (result.empty())
		return false;
	int devIdx = std::stoi(result[0][0]);

	if (
		((devType == pTypeThermostat) && (subType == sTypeThermSetpoint)) ||
		((devType == pTypeRadiator1) && (subType == sTypeSmartwares))
		)
	{
		//Prevent double event trigger
		g_bUseEventTrigger = parseTrigger;
		_log.Log(LOG_NORM, "Sending SetPoint to device....");
		SetSetPoint(std::to_string(devIdx), static_cast<float>(atof(sValue.c_str())));
		g_bUseEventTrigger = true;
		return true;
	}

	unsigned long ID = 0;**

Then it is solved... But is this the correct way ?

The double event is caused because MainWorker::SetSetpointInt is calling 'PushAndWaitRxMessage' for pTypeRadiator1 and sTypeThermSetpoint
But only for certain hardware types

Maybe it is best to merge your patch, but could you test with a Python script, I suspect this is called twice as well

**Comment by rwaaren** [comment]
I tested from bash and using the API and indeed the script is triggered twice (or not at all when called with parsetrigger=false)

```
http://nuc:8084/json.htm?type=command&param=udevice&idx=151&nvalue=0&svalue=12.34 // script triggered twice
http://nuc:8084/json.htm?type=command&param=udevice&idx=151&nvalue=0&svalue=12.34&parsetrigger=false // no script trigger
```

**Comment by gizmocuz** [comment]
@rwaaren , thanks for testing, yes this confirms it is unrelated to MQTT
I don't use MQTT on my second test system and still get two triggers for my dzVents script

I am unable to test a Python plugin because I have no idea how the logic of this works, I even suspect that this should be redesigned.

If I look in:

CPluginSystem::DeviceModified

A python plugin does not get the device idx what is changed by a unit ?
And it is not signaled to all enabled python plugins it seems...

Anyways, I will change this topic and continue with some more debugging, It's also not a loop but it is called twice

**Comment by rwaaren** [comment]
Sorry if I was not clear enough. 

In my mind the issue is twofold: 
Updating a dummy Thermostat Setpoint causing a double event action is indeed the root cause of the problem and I tried to find a solution for that but failed because the code-flow is too complicated for my C++ debugging skills let alone my C++ coding skills. 
However, I did find a  simple mechanism (and to my knowledge without any negative side effect) to prevent this issue to cause a MQTT loop triggered by the second call that sends the update back to domoticz/out.
So yes I agree that my PR #4283 does not solve this issue but it solves one nasty side effect caused by it. 
I would call this "one down, one to go" 😀

**Comment by gizmocuz** [comment]
@rwaaren , No your PR does not solve the problem. Yes, it might prevent MQTT to not be triggered twice.
As mentioned, I do not use MQTT at the moment on my test system and also receive a event call twice.
This has to be solved, and when it does, MQTT will also be called once

**Comment by gizmocuz** [comment]
@rwaaren , Pfff think it is solved now in beta 12260, currently building at should be available within the hour.
If you compile Domoticz yourself, please try with the latest code

**Comment by rwaaren** [comment]
Top ! 
Tested with mosquitto_pub, call to API and with updateSetpoint in dzVents and everything works as expected with and without loop prevention on the hardware and with and without parsetrigger=false on the API /   "parse": false in mosquitto_pub

Many thanks again for the time / energy you spent on this

**Comment by gizmocuz** [comment]
Yes! Thanks for all testing ! ;)

**Comment by tarmacalastair** [comment]
This update has broken updates to **real** setpoints - see https://www.domoticz.com/forum/viewtopic.php?t=38159

Please revert to previous behaviour - it's driving me mad and is killing the battery on my thermostat as I have to set the wake interval as low as it will go. Others have reported similar issues but no one else seems to have tracked it down to this update.

I managed all last winter by reverting to an older version of Domoticz but this year I decided that I was getting so far behind with the updates....now I'm starting to regret updating because of this...
