### ISSUE TITLE
Google Notification system needs Admin editor to approve/edit/delete device

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#432]
The new notification system that allows Android and iOS native applications to receive 'native' push notifications is implemented, but needs at least an admin editor to allow naming/adding/removing devices.

**Comment by rkluwen** [comment]
I see one issue with this: The json is automatically) url encoded. I think this is not correct. But the strings do need to be slash-escaped. Isn't it better to construct the request with the json encoder? I think this will handle the issue transparently (but not 100% sure).
Otherwise a new encoding option can be added to CNotificationBase.

**Comment by gizmocuz** [comment]
If you can make a patch, please go ahead

**Comment by rkluwen** [comment]
Will do, when I find some time. I won't assign this ticket to me, since it is about a different thing (admin editor).

**Comment by gizmocuz** [comment]
Are you able to have a look at this?

**Comment by szczukot** [comment]
Please, 
Who will write it? This is a great thing !
I'm dont front-end developer :(

**Comment by rkluwen** [comment]
Maybe you could reward a bounty :)

**Comment by galadril** [comment]
👍
