### ISSUE TITLE
Scheduler don't start when domoticz start

### ISSUE THREAD

**Issue by julienpoirier** [domoticz/domoticz#433]
Hey,

I'm having a strange thing when using ON_TIME (`TTYPE_ONTIME`) timer. They don't start at all. I'm using a ubuntu on a VMWare. After trying to remove, add hardware, reboot VM, reinstall domoticz, changing install directory nothing change. So I've started to look inside the code to find what I was doing wrong because nobody seem to have this issue. 

I've found that the `CScheduler::ReloadSchedules` was never called at startup. So the `CScheduler::CheckSchedules` was not filled with the DB schedule. 

Changing the `Scheduler.cpp` like this correct my problem :

```
void CScheduler::Do_Work()
{
    _log.Log(LOG_STATUS, "Scheduler starting...");
    ReloadSchedules();
    _log.Log(LOG_STATUS, "Scheduler started...");

    while (!m_stoprequested)
```

But an other problem comes: setting a new timer  to the `current minute +1` was not taken into account. Adding logs show me that adding timer to the next minute was postponed to the next day. `CScheduler::AdjustScheduleItem` was faulty. In that we check if the given time plus 60 is lower than current. This one is not really a bug, but is more a documentation missing information. 

```
    //Adjust timer by 1 day if we are in the past
    while (rtime < atime + 60)
    {
        rtime += (24 * 3600);
    }
```

So perhaps it's a misuse of the app, if it's someone can tell me why, if not I can do a pull request to correct the scheduler on load issue.

**Comment by gizmocuz** [comment]
That is strange, cause its working like 3 years now....

After setting a 'break point' at the beginning of ReloadSchedules (please try this first!)
You will see that this function is called at startup, this because the schedules are reloaded when the Sun set/rise is changing

Call stack:
MainWorker::Start() Line 905    C++
MainWorker::GetSunSettings() Line 471   C++
CScheduler::SetSunRiseSetTimers(..) Line 398    C++
CScheduler::ReloadSchedules() Line 55   C++

Could it be that you where playing with the timers, like setting a timer at one minute from now, or a timer that would get scheduled the next day ?

Anyhow, there have been much work on timers lately, but on-time timers worked from release 0.01

Also checked (with breakpoints) , ReloadSchedules is called bedore ::Do_Work

Is it possible to test some more ? We could add this patch... but looking/testing the code, it seems it is not needed

**Comment by julienpoirier** [comment]
With what you said i've found that `bool MainWorker::GetSunSettings()` never call the `SetSunRiseSetTimers`. In fact i've no `Location` preferences in db.

At startup :
In `bool MainWorker::GetSunSettings()` we don't call the SetSunRiseSetTimers if no `Location` is found or a malformated one. I think that no location should not block ON_TIME timer, or that a warning should be emit in order to set the preference. 

But if we add a timer using the UI, the ReloadSchedules will be called. Based on this I propose someting like this in the `bool MainWorker::GetSunSettings()`

```
    if (!m_sql.GetPreferencesVar("Location",nValue,sValue)) {
        // Load non sun settings timers 
        m_scheduler.ReloadSchedules();
        return false;
    }
    std::vector<std::string> strarray;
    StringSplit(sValue, ";", strarray);

    if (strarray.size()!=2) {
        // Load non sun settings timers 
        m_scheduler.ReloadSchedules();
        return false;
    }
```

Note :
In the main documentation the location is important for set sunrise timing. 

```
Application Settings 
There are various application settings. For control of Light/Switches based on Sun Set /Sunrise timings, it is important 
to setup your location. 
```

**Comment by gizmocuz** [comment]
You can not apply any settings until you entered your location, this is step #1

**Comment by gizmocuz** [comment]
I added your patch, thanks.
But this should not have been possible, maybe we should force this setting

**Comment by julienpoirier** [comment]
Thank, yes perhaps a GMT location should be fine because the `GetPreferencesVar("Location"` will also return false without calling on time.

I don't known the complete code but if location is really important, adding it in the wiki will be also fine for me
