### ISSUE TITLE
No full updated zwave devices after reboot (manufacturer, ID, type)

### ISSUE THREAD

**Issue by Sarcas666** [domoticz/domoticz#4364]
Domoticz 2020.2 (build 12377)
Running for several days now. Devices seem to work, but are not fully updated in the list. (ignore nodes 7, 10, 28 and 32, they are deleted long ago but somehow stay visible like this). I did a ‘refresh node info’ and woke the nodes, but there is no change. 

<img width="1356" alt="Schermafbeelding 3" src="https://user-images.githubusercontent.com/970974/94244814-bb4ef280-ff19-11ea-9746-4ee49ff480ac.png">

**Comment by sincze** [comment]
Domoticz 2020.2 (build 12393)
![image](https://user-images.githubusercontent.com/5776333/94332503-15ad8900-ffd6-11ea-8547-56de6f9d17f9.png)

Had to convince some of the devices by **repeating** the **go** button action from the control panel and keep a close eye on the status.

**Comment by Sarcas666** [comment]
That fixed it.
Thanks!

**Comment by rrozema** [comment]
One additional tip: Do delete those devices 7, 8, 10 and 32 from the list
after every reboot, even though the delete doesn't 'stick' (they are not
removed from the controller's list of devices and are back after your next
domoticz restart), they are deleted from domoticz' device list. Devices
that are listed like this do get sent some messages periodically. Since the
devices aren't alive, your controller will keep those messages in the queue
until the message times, because the device may still come back. There are
however only a limited number of slots in the controller's queue, so while
these messages are waiting to timeout, you'll have less slots available for
the rest of your devices. i.e. you'll experience congestion of your network
faster. Not being able to correctly delete these devices has been reported
several times already, so hopefully that will be fixed soon, but until then
it helps to keep removing these devices after every reboot.

Op vr 25 sep. 2020 om 10:31 schreef Sarcas666 <notifications@github.com>:

**Comment by Sarcas666** [comment]
I’d like to delete them, but they don’t :)

I tried ‘Remove Device’, ‘Has Node Failed’ and ‘Remove Failed Node’ but nothing happens. After a few hours I just click ‘cancel’.

**Comment by rrozema** [comment]
I mean delete it from the list: highlight the line and click the 'Delete'
button ('Verwijderen' in Dutch) in the bottom.

Op vr 2 okt. 2020 om 12:12 schreef Sarcas666 <notifications@github.com>:

**Comment by Sarcas666** [comment]
Hm. Domoticz crashes after I delete the third or fourth device.
