### ISSUE TITLE
AppCache not working anymore

### ISSUE THREAD

**Issue by MAkerboom** [domoticz/domoticz#4507]
AppCache fails on Chrome 87 when Domoticz is installed on a FQDN.

Had to follow this tutorial (https://web.dev/appcache-removal/) to add an origin-trial to extent support.

Can we migrate to service workers for cache?

**Comment by gizmocuz** [comment]
Yep, I'm already looking into service workers (workbox) for quite some time but I'm not to happy about this
Still fighting around issues where the cache should be refreshed (based on a version number in the service worker file),
not all documents are being refreshed but still served from the browsers cache (like CSS files)

Do you have experience with service-workers/workbox ?

The only solution seems to version the WEB GUI files (like mycss-version-1.css)
This is doable , but then we need to cleanup old GUI versions at startup and could also be quite some work to maintain

**Comment by dannybloe** [comment]
Or just let the browser take care of all the caching and make sure you fetch all assets (images etc) with a build hash in the url and set the cache headers to indefinite. Each build will then  automatically invalidate all cached file since the build hash has changed. So fetch `<img src="path/to/file#somebuildhashornumber" />`. The only problem is to get those hashes in all urls. Usually one would build tools like webpack to compile all js/css files and that will process all urls. But it requires some work to get this working. But once it is working you have a lot easier way to get your dev code to a distribution.

**Comment by gizmocuz** [comment]
@dannybloe , exactly, so when using webpack we could use a service worker as well...
AppCache (when working) should (and is here) requesting all resources again when there is a change.
We already have a dynamic version in the appcache file based on the build number
But It's not logical to have version numbers for images etc...

**Comment by dannybloe** [comment]
Why do you need to fetch all images when the client might not need them?

**Comment by gizmocuz** [comment]
Current items in the returned appcache are items that the end user needs

**Comment by dannybloe** [comment]
That doesn't answer my question, I think. Why do you need to pre-fetch all images? The browser is perfectly capable to fetch the image when just when it needs to render it. And only then it is added to the cache. If the image is never needed by the browser then there is no need to fetch it's data. Unless you want to have an off-line application then it could be handy to have everything stored locally. But off-line Domoticz is weird because you need a connection for the api anyway. Or am I missing something/some usecase?

**Comment by gizmocuz** [comment]
First for the speed, network bandwidth and forcing a recache when some bits/bytes have been changed in the web Gui
For instance when we do not cache (appcache/service worker), and we change a line in a .css file, the browser will for sure still serve the old css file. With a service worker/appcache you can force a recache. Maybe we can create a small service worker that stores the build version numer and force a browser refresh... 
And that is one of the issues I currently face with the service worker, it refreshes my html/js files, but for example the css files are still taken from the browsers cache

**Comment by dannybloe** [comment]
With proper caching schemes and a good packaging/building system of all js/css/html assets you don't have this problem and then there's no need to keep fetching all assets. Ah well..

**Comment by gizmocuz** [comment]
True, so you want to version the url's ? and we should have a cleanup script that deletes old versions ?

**Comment by kiddigital** [comment]
One challenge is the packaging of all client-side assets (html, css, images, javascript files, everything) AND distribute them easily.

The browser caches stuff based on proper header info and URL's.

We could use the Domoticz webserver to interpret the URL's and rewrite those to the real asset location and serve the assets. The URL's could contain a versiontag or something that gets stripped by the webserver. That way, the browser thinks the URL's are new and reloads them instead of uses the (valid) cached ones.

This does btw only work when using relative URL's on the client as the base should contain the version.

Otherwise all URL's on the client side need to be updates with each version bump.

(That is what packaging tools can do for you, but they also come with some downsides)

**Comment by kiddigital** [comment]
App cache has been removed.
See #5144 and commit [1de08a49f7473ef0339570bc63d74dfcb3f2feb4](https://github.com/domoticz/domoticz/commit/1de08a49f7473ef0339570bc63d74dfcb3f2feb4)
