### ISSUE TITLE
Problem with reporting since november 2020

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#4534]
Hi Team,
Since November some of my reports have huge negative numbers in de reports, see printscreen below.
These high negative values somehow are generated by the system around 23:00 hour.
The PHP script that I use to fill these reports, checks for negative numbers so I don't understand where this comes from.
It started at the end of November all of a sudden and messes up the reporting for a while now.

Raspberry Pi 4 4MB
Buster 5.4.79-v7l+ 
Domoticz Version: 2020.2 (build 12741)

Thanks in advance,
Harry

![reporting_issue](https://user-images.githubusercontent.com/58355498/102978000-1a65d880-4504-11eb-9da7-eb8b59394e89.jpg)

**Comment by gizmocuz** [comment]
What hardware are you using ? ZWave/NeoCoolcam ?

**Comment by HB787** [comment]
These are values I am parsing from a so called Energylink via my old Homewizard. The PHP script checks for positive values.
I just added a loging to the script so i will see what will happen at 23:00 today.

**Comment by gizmocuz** [comment]
Okey, so maybe your "counter" is not increasing correctly ?

**Comment by HB787** [comment]
Still researching

**Comment by HB787** [comment]
I found out that more of my reports have negative 'spikes" every day.
Some of them are from Aeotec relays and also other brands.
I am updating an energy dummy device with this PHP code:

    // Stroom
    $stv = $data['response']['energylinks']['0']['used']['dayTotal'];  //dagtotaal
    $sta = $data['response']['energylinks']['0']['used']['po'];        //actueel
    $dagtotaal = $stv*1000;
   	if(is_numeric($stv) and is_numeric($sta) and $dagtotaal > 0) {
   	    $domoticzoutput = file_get_contents('http://127.0.0.1:7000/json.htm?type=command&param=udevice&idx=80&nvalue=0&svalue='.$sta.';'.$dagtotaal.'');
   	    echo "-------------------------\n";
   			echo "stroomverbruik:\n";
    		echo "stroom actueel: ".$sta."\n";
    		echo "stroom dagtotaal: ".$dagtotaal."\n";
    		echo $domoticzoutput;
    		echo "-------------------------\n";
   	} 

However everyday there is a huge negative number in the daily total. 
In the database table meters I can't find these negative numbers, would like to know where this comes from.
Are there other tables where this can be stored?

Thanks in advance,
Harry

**Comment by HB787** [comment]
I see there was change with the max power setting on the 21st of November. It is from that time that my reports are messing up with the huge negative values.

**Comment by gizmocuz** [comment]
@HB787 , that patch is for ZWave device I believe
Can you point me to the patch you believe is causing this issue ?
Is your device providing a continues counter ?

**Comment by HB787** [comment]
@gizmocuz 
I don't know what patch it did, yes I see the data is added to the Meter table.
I am not providing a counter as you see above, I just add values.
is it possible to prevent these devices not to have negative numbers?

**Comment by gizmocuz** [comment]
Is it possible you can log (somehow in your PHP script) the values you are sending for 24 hours and have a look at the svalues (svalue='.$sta.';'.$dagtotaal.'')
See if the counter is increasing all the time, or that it wraps to 0 every day

**Comment by HB787** [comment]
Yes I will log it

**Comment by HB787** [comment]
I already had logging on in the script:
As you see the day value starts at 0:
27-12-2020, 23:54 stroom actueel: 376 dagtotaal: 14760 
27-12-2020, 23:54 zon actueel: 0 dagtotaal: 510 
27-12-2020, 23:54 gas actueel: 0 dagtotaal: 13.13 
27-12-2020, 23:54 water: 374 liter 
27-12-2020, 23:56 stroom actueel: 380 dagtotaal: 14780 
27-12-2020, 23:56 zon actueel: 0 dagtotaal: 510 
27-12-2020, 23:56 gas actueel: 0 dagtotaal: 13.13 
27-12-2020, 23:56 water: 374 liter 
27-12-2020, 23:58 stroom actueel: 431 dagtotaal: 14790 
27-12-2020, 23:58 zon actueel: 0 dagtotaal: 510 
27-12-2020, 23:58 gas actueel: 0 dagtotaal: 13.13 
27-12-2020, 23:58 water: 374 liter 
28-12-2020, 00:02 stroom actueel: 375 dagtotaal: 0 
28-12-2020, 00:02 zon actueel: 0 dagtotaal: 0 
28-12-2020, 00:02 gas actueel: 0 dagtotaal: 0 
28-12-2020, 00:02 water: 0 liter 
28-12-2020, 00:04 stroom actueel: 412 dagtotaal: 20 
28-12-2020, 00:04 zon actueel: 0 dagtotaal: 0 
28-12-2020, 00:04 gas actueel: 0 dagtotaal: 0 
28-12-2020, 00:04 water: 4 liter 
28-12-2020, 00:06 stroom actueel: 394 dagtotaal: 30 
28-12-2020, 00:06 zon actueel: 0 dagtotaal: 0 
28-12-2020, 00:06 gas actueel: 0 dagtotaal: 0 
28-12-2020, 00:06 water: 5 liter 
28-12-2020, 00:08 stroom actueel: 385 dagtotaal: 40 
28-12-2020, 00:08 zon actueel: 0 dagtotaal: 0 
28-12-2020, 00:08 gas actueel: 0 dagtotaal: 0

**Comment by gizmocuz** [comment]
Okey so this makes sense... you need an increasing counter
What hardware are you polling and isn't there already support for this in Domoticz ?

So two solutions I can think of:

You need to use a counter incremental, and send the difference with the previous poll
Make sure you keep a internal record of the counter (used as offset) and when it loops, keep incrementing it

**Comment by HB787** [comment]
The hardware is actually a homewizard with a so called Energylink (connected to my smartmeter)  I am parsing these values from there. If I need to send the difference how did it work before november for many years?

**Comment by gizmocuz** [comment]
I have no idea, but the counter should increase.

Maybe you could invest into a P1 Smart meter cable (or create one yourself)
https://nl.aliexpress.com/item/32945187155.html

Or try to use a plugin like:

https://github.com/rvdvoorde/domoticz-homewizard

Could it be a homewizard update ?

Anyway, there was a reason why I started with the development of Domoticz...

**Comment by RicardP** [comment]
I am running 12760 on Win10

I have only ZWave devices reporting energy/Power and see also some (looks same) negative spikes, since later code commits on energy/power logging...
But also another annoying issue, if restarting Domoticz it often generates a "big" positive KWh value on some devices. I noticed yesterday it happens after a reboot, before I noticed those big numbers later on and just deleted obviously corrupt data.

**Comment by RicardP** [comment]
Here is an example KWh positive spike after restart, however this spike is only visible on the last days graph and it cannot be deleted...

![bild](https://user-images.githubusercontent.com/21274628/103243975-ce7bbf00-495b-11eb-95fe-30162246e5b0.png)

**Comment by gizmocuz** [comment]
@RicardP , this is because the value you see is the difference between two counter values
and as you loop back to zero you get a huge spike
deleting that value will cause it to use the next counter value, and as it is still looped, you will see a spike again (maybe a little smaller)
You mention you only have one zwave device that measures power, is this device OK ?
The above device, what type of hardware is this/updating this ?
But this is also a different issue, the problem here is that the counter loops, it could also be the same issue you are having, but you need to tell more about what type of device/hardware this is

**Comment by RicardP** [comment]
@gizmocuz  Hi, I meant I have only ZWave devices (several) measuring power, power measuring has never been reliable in ZWave/OZW for any device or brand. As you are aware of random huge power values is provided from OZW also in the past, now lately tried to avoid by code sanity check of OZW data.
The device in my example is ZMNHYD1 Smart Plug 16A+
I also notice in many devices now that many days does not show any power usage at all even I see those lamps burning every day and night :)

I am sick of ZWave and/or OZW, it is so badly "performing" even I have perfect signal from the Controller to 95% of all Nodes and the rest 5% is close by few meters to other Nodes but still the system is unreliable.
As you might seen ZWay is on its way to make a OZW wrapper so Domoticz users can try that alternative, soon I hope. Then we'll see were the problem is, general bad ZWave products (sw ? hw) or OZW can burn in hell ;-)

**Comment by gizmocuz** [comment]
@RicardP , well maybe you could assist with debugging ? Both Domoticz/OpenZWave ?
My ZWave network (and i have several, on several locations) is performing very stable.
I use only two brands.
But again, this is not related to this topic as the issue here is a counter that wraps
Yes I have spoken to the developer of ZWay years ago on a exhibition here and he mentioned this.
But, you should have a look in the code as well.
For instance, a big brand (that i also use) (starting with a F (not pointing fingers here), the wall plug, it transmits two Power Usage (Watt) command classes, 1 with instance 1, and 1 with instance 4 ... instance 1 is only one time updated with you turn it on, but the values on instance 4 are correct (the switch is instance 1)
Another brand (Starting with a A) also needs tweaking...
Another brand (Starting with a N ... from China), is so bad (with it's new wall plugs), it suddenly transmits a static counter value (203847 (for example)), and after some time (half hour/hour) it transmits the correct counter value again
So to say, it's OpenZWave, or ZWay can do better .... Manufacturers have to check their shit as well.
Why would a switch broadcast a thermostat field for example ?
Anyway, feel free to debug the code
I am currently working on a patch related to Power/kWh that might also solve some issues but needs to be tested before i commit the changes

**Comment by RicardP** [comment]
@gizmocuz I told before I am not a programmer, generally I try to keep a low profile in that sense. Instead I make donations when I see people like you doing a fantastic job! Domoticz is fine evolving, the real problem is OZW "project" - I think you know what I mean.
Yes, ZWave manufactures is also a big problem, or maybe the lack in market quality following up by the owner Silabs. How can they be so passive in making ZWave a reliable system, every manufacture of devices should be obligated to provide new firmware to the public with bug fixes, also any official Controller hub should be able to fetch those FW and perform any brand node updates. Because, exactly as you write there seems being issues with so many ZWave devices and as it is today it's even difficult for developers to understand ZWave protocol, communications, etc... Especially if something is wrong, wrong implemented etc... then the nightmare is a reality.
On that we have OZW that so many people put their trust in, convincing them to invest time and money in ZWave, but after years of waiting realize they being fooled by the promising words on OZW homepage. When it turns out to be fake as no real development happens... So, at least myself see ZWay as the only hope to get a serious ZWave implementation into our great Domoticz platform! :)

**Comment by HB787** [comment]
@gizmocuz  I followed your advise and used the Homewizard plugin. There is only an issue with the water meter, it logs that it is found but it did not create the device. 
However this works better, thanks for your help.

**Comment by gizmocuz** [comment]
@HB787 , Did you enabled 'accept new hardware' in the settings ?

**Comment by HB787** [comment]
@gizmocuz , Yes I have that on, the plugin works well this is the only small issue.
