### ISSUE TITLE
Remove Meteo section in Dashboard if Meteo tab is disable

### ISSUE THREAD

**Issue by ultrasuperpingu** [domoticz/domoticz#4572]
When you have a Temp+Humidity+Baro device, setting it has a favorite make the barometer to be on the Dashboard. Is it possible to remove the barometer of the dashboard if the Meteo tab is disabled ?

**Comment by gizmocuz** [comment]
It does contain a barometric sensor so that is why it is displayed.
But you could make a small workaround with a script (dzVents), when your Temp+Hum+Baro is received, update a new Temp+Hum sensor with these values
I think it should be possible to disable the weather-tab, but still have a wind sensor (or baro) on your dashboard

**Comment by ultrasuperpingu** [comment]
You're right, I just made a script to copy values into a Temp+Hum dummy device. But I don't really understand why there is a Temp+Hum+Baro sensor if the presentation of this is made of 2 devices. I'm closing this issue.
