### ISSUE TITLE
MySensors Gateway with MQTT interface duplicates all status-updates to domoticz/out/myMQTT

### ISSUE THREAD

**Issue by bikeymouse** [domoticz/domoticz#4651]
Domoticz Version: 2020.2 (build 12697)
Platform: Raspberry Pi 2B
Plugin: MQTT Client Gateway with LAN interface and
Plugin: Mysensors Gateway with QTT interface

I'm using the "MySensors Gateway with MQTT interface" to receive data from an Arduino.

Besides that, I have activated the "MQTT Client Gateway with Lan interface" to able to monitor/control other Domoticz devices via MQTT.

Now I noticed that in this configuration, all the Domoticz status messages on the MQTT domoticz/out topic are duplicated on the domoticz/out/MyMQTT topic.

It turns out that the MySensors Gateway is not only subscribing to MQTT on the configured MQTT-topic (Default; domoticz/out/MyMQTT), but also replicating all internal Domoticz messages to Domoticz/out. 

As the MQTT Client Gateway is also doing this, this effectively duplicates all messages.

To me this is not expected behaviour: the MySensor gateway should only listen/publish specific MySensor messages on its configured topic. I would not expect it to fully replicate all status messages from Domoticz. If you need that, use the MQTT Client Gateway.

Can this be fixed, or - if there are compelling reasons to have this behaviour for some use cases - made configurable?

**Comment by lkankowski** [comment]
Same here.
I have 3 hardware entries with "MySensors Gateway with MQTT interface" and "MQTT Client Gateway with LAN interface" - every outgoing message is multiplied by 4.

I didn't analyzed the code, but just looked - I suspect that bug is a result of some internal dependency:
- MySensorsMQTT (MySensors Gateway with MQTT interface)  depends on MQTT (MQTT Client Gateway with LAN interface)
- MQTT depends on MySensorsBase (base class for all MySensors implementation)
So all MQTT depends on MySensors - that is pretty mess in codebase :)

Besides that, I love using Domoticz :)

**Comment by waltervl** [comment]
Is this issue still present in current stable 2022.1 There has been a lot of changes in this release that touched MQTT (and so perhaps MySensors MQTT Gateway)

**Comment by lkankowski** [comment]
Well, Domoticz still publishes messages on MySensors MQTT topics which are not connected to their hardware devices.

Also different thing happened after update, that Domoticz ignores old type of MQTT integration like this:
domoticz/in: {"idx":39,"RSSI":5,"nvalue":0,"svalue":"88"}

**Comment by waltervl** [comment]
The multiple published topics I can believe but that normal Mqtt is not accepting normal payloads seems strange. It would give more issue here or on the forum.

But I do not use MQTT, was just checking the old issues.

Can you make a new issue for the normal MQTT regression as that seems something to be investigated too.
