### ISSUE TITLE
lately domoticz has been going offline several times a day

### ISSUE THREAD

**Issue by salopette** [domoticz/domoticz#4695]
Hello, I have the problem that my Domoticz has been offline several times for a few days.
Only a service restart helps.
I have a log, maybe you can find a bug?

Pi3- Debian Buster
Version: 2020.2 (build 13017)
Build Hash: 06f5f78dd-modified
Compile Date: 2021-02-26 10:36:14
dzVents Version: 3.1.5
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Uptime: 11 Minuten, 15 Sekunden

[Crash Log.txt](https://github.com/domoticz/domoticz/files/6056472/Crash.Log.txt)

**Comment by gizmocuz** [comment]
@salopette , It seems to be a python/plugin related issue. Could you disable the event system and try without to see if it keeps stable?

**Comment by salopette** [comment]
Which plug-in is that which should be deactivated?

![sshot-1](https://user-images.githubusercontent.com/32480002/109413435-a6392c80-79ad-11eb-8c36-f09f59297ce6.jpg)

**Comment by gizmocuz** [comment]
I would disable the python hardware and the eventsystem in the settings page

**Comment by salopette** [comment]
I only have Blokly scripts running on me.
These are from devices from z2m and Shelly, otherwise none.
Can you see from the log which event produced the error?

maybe it has something to do with what?
https://www.domoticz.com/forum/viewtopic.php?f=6&t=35655

**Comment by rrozema** [comment]
I have both zigbee2mqtt and tasmota running as well. They do interact sometimes unintended (a.o. tasmota plugin reports node errors on zigbee devices) , so I think the combination is not completely safe. Also, I have noticed that if I rename a device that is a zigbee node, zigbee often crashes and then needs a restart of my raspberry to recover from that crash. Just restarting the domoticz service is not enough. I have however not been able to properly reproduce either issue, so I have not reported them yet. Only mentioning it here because it may help you find a cause.

**Comment by gizmocuz** [comment]
Please try the latest beta version, there where some issues
