### ISSUE TITLE
Enocean Profile (EEP, Profil EnOcean® F6-02-02 not handled anymore

### ISSUE THREAD

**Issue by arno0392** [domoticz/domoticz#4722]
### Issue Guidelines

Version tested : lasted beta, 2020.2 (build 13058), Build Hash: 066f3f261-modified, Compile Date: 2021-03-08 16:27:50
Hardware: Raspberry Pi3 up to date, raspberry OS

This type of device has 4 buttons. Only one worked now, 3 other buttons are not handled anymore, but generate events in the logs
https://m2.lmcdn.fr/media/1/5ba3fd067eb45f3caa2a1d76/.pdf
I'm not sure which type of logs to provide, because I don't want provide serial number of my devices

Issue appears 3 weeks ago

**Comment by gizmocuz** [comment]
@arno0392 , who are you ? where do you live ? I think you are safe to paste the log files here
Did it work before ? There have been a recent change in EnOcean by @alexis-via, maybe something got broken

**Comment by arno0392** [comment]
Hi, I'm Arno from France.
OK, I can paste you some logs.
It worked before, but not anymore (I was away from home, so not really sure of the release that broke something).
No changes on my side, other EEP profiles are continuing as usual, and I have a lot of same type of devices with the same behavior now (only 1 event is catched)

Event not catched (same behavior with 3 buttons):
021-03-10 17:36:30.160 EnOcean: destination: 0xffffffff RSSI: -80 dBm (4/11)
2021-03-10 17:36:30.416 EnOcean: destination: 0xffffffff RSSI: -83 dBm (3/11)
2021-03-10 17:36:30.160 Status: EnOcean: 01 (07/07) F6 50 00 32 9C E3 30 01 FF FF FF FF 50 00
2021-03-10 17:36:30.416 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 20 01 FF FF FF FF 53 00

Event catched successfully (1 button):
2021-03-10 17:37:20.789 EnOcean: destination: 0xffffffff RSSI: -86 dBm (2/11)
2021-03-10 17:37:20.804 EnOcean: Lighting 2 (Inter Nodon Beige Bt Droite On)
2021-03-10 17:37:20.533 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 58 00
2021-03-10 17:37:20.788 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 20 01 FF FF FF FF 56 00

All the actions have a "device name", only this last one is linked to the device.

Probably something changed.
I'm not able to detect the device again

**Comment by gizmocuz** [comment]
Thank you for the information.

Just to double check something, could you enable 'accept new hardware' in the settings and try pressing the buttons,
next check if you have received new devices.

If not, something is indeed probably not correct now

**Comment by arno0392** [comment]
Yes I checked first when I discovered the issue ; only 1 button generates an event (device already known or something like this).
Other buttons didn't generate anythinkg (except in the logs)

**Comment by arno0392** [comment]
I tested something else with "single button" (only 1 on et 1 off) ; the 2 buttons work.
The issue is only with "double buttons" (2 on and 2 off) ; "Rocker Id" maybe?

**Comment by arno0392** [comment]
I think there is a new issue with this commit : https://github.com/alexis-via/domoticz/commit/de8d04e05984571625674c1b603f91f6e80eb608 (old lines from 1952 to 1966) ; IDs are not handled anymore.
(not very familiar with coding now)

**Comment by arno0392** [comment]
Probably issu with this line?

**Comment by arno0392** [comment]
Probably issue with this line?
https://github.com/domoticz/domoticz/commit/de8d04e05984571625674c1b603f91f6e80eb608#diff-a4268f86e8105fcd30cb74f3baf1b845843712bdeb3e8e8d0ebe1e91b384d465L1740

**Comment by gizmocuz** [comment]
Maybe you can debug this and write a patch ? Easiest could be using Visual Studio and setting breakpoints

**Comment by arno0392** [comment]
I'd like, but not able to do that (not a dev :()
Can I contribute in another way?

**Comment by alexis-via** [comment]
@arno0392 I can help you on this. I can prepare a branch for you with a modification in the code. Then you can compile it and test. I'll be available this week-end and next week.

**Comment by gizmocuz** [comment]
@arno0392 , for debugging purposes could you provide the following information

Your device has how many buttons ?

For each button, please include the log here, and mention information like 

Button 1 Down (pressed)
2021-03-10 17:37:20.533 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 58 00
Button 1 Up (released)
2021-03-10 17:37:20.533 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 58 00

Button 2 Down (pressed)
2021-03-10 17:37:20.533 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 58 00
Button 2 Up (released)
2021-03-10 17:37:20.533 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 58 00

...

This will help debugging the issue

**Comment by efdeb** [comment]
Hello, I have the same issue here.
My double rocker switch devise is based on EnOcean PTM-210 hardware. I configure each of the 4 independents buttons as a Push On button in domoticz.

Only the first of the 4 buttons still triggers an action in domoticz, called "eno-push-1" in my case.
The other 3 buttons are still sending data catched by domoticz, but no more associated with the corresponding "eno-push-2", "eno-push-3" or  "eno-push-4" device.

Had no time to debug, but just recompiled domoticz with previous versions of hardware/EnOceanESP3.cpp file.
I confirm 71be778 commited on Feb 5, 2021 runs OK and the problem occurs from fd8b266 commited on Feb 10, 2021.

1/ with oldest 71be778 version
I get the following traces when I press button 1 :
EnOcean: 01 (07/07) F6 10 00 36 BB 9F 30 00 FF FF FF FF 3D 00
dzVents: Info: Handling events for: "eno-push-1", value: "On"
EnOcean: 01 (07/07) F6 00 00 36 BB 9F 20 00 FF FF FF FF 40 00
dzVents: Info: Handling events for: "eno-push-1", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-2", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-3", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-4", value: "Group Off"

I get the following traces when I press button 2 :
EnOcean: 01 (07/07) F6 30 00 36 BB 9F 30 00 FF FF FF FF 47 00
dzVents: Info: Handling events for: "eno-push-2", value: "On"
EnOcean: 01 (07/07) F6 00 00 36 BB 9F 20 00 FF FF FF FF 47 00
dzVents: Info: Handling events for: "eno-push-1", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-2", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-1", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-2", value: "Group Off"

2/ with newest fd8b266 version
I get the following traces when I press button 1 :
EnOcean: 01 (07/07) F6 10 00 36 BB 9F 30 00 FF FF FF FF 44 00
dzVents: Info: Handling events for: "eno-push-1", value: "On"
EnOcean: 01 (07/07) F6 00 00 36 BB 9F 20 00 FF FF FF FF 47 00
dzVents: Info: Handling events for: "eno-push-1", value: "Off"

I get the following traces when I press button 2 :
EnOcean: 01 (07/07) F6 30 00 36 BB 9F 30 00 FF FF FF FF 46 00
(+ no event triggered in dzVents)

I'll try to investigate today.

**Comment by gizmocuz** [comment]
Do you have any logs of button 3 and 4 ?

**Comment by arno0392** [comment]
![IMG_20210312_141852](https://user-images.githubusercontent.com/57816174/110947658-bacbdc00-8340-11eb-8baa-c897006d5cc1.jpg)

The logs (wish that I got the correct lines because full building is "Enocean" for the lights and I receive hundreds of devices):
(1 - not handled)
2021-03-12 14:37:00.394 Status: EnOcean: 01 (07/07) F6 50 00 32 9C E3 30 01 FF FF FF FF 5B 00
2021-03-12 14:37:00.666 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 21 01 FF FF FF FF 3C 00
(2 - not handled)
2021-03-12 14:37:16.424 Status: EnOcean: 01 (07/07) F6 70 00 32 9C E3 30 01 FF FF FF FF 58 00
2021-03-12 14:37:16.698 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 20 02 FF FF FF FF 58 00
(3 - OK)
2021-03-12 14:37:46.134 Status: EnOcean: 01 (07/07) F6 10 00 32 9C E3 30 01 FF FF FF FF 5B 00
2021-03-12 14:37:46.374 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 20 01 FF FF FF FF 5C 00
(4 - not handled)
2021-03-12 14:38:13.093 Status: EnOcean: 01 (07/07) F6 30 00 32 9C E3 30 01 FF FF FF FF 56 00
2021-03-12 14:38:13.411 Status: EnOcean: 01 (07/07) F6 00 00 32 9C E3 20 01 FF FF FF FF 56 00

**Comment by efdeb** [comment]
On my side,

1/ with oldest 71be778 version
I get the following traces when I press button 3 :
Status: EnOcean: 01 (07/07) F6 50 00 3A 5F 75 30 00 FF FF FF FF 44 00
dzVents: Info: Handling events for: "eno-push-3", value: "On"

EnOcean: 01 (07/07) F6 00 00 3A 5F 75 20 00 FF FF FF FF 43 00
dzVents: Info: Handling events for: "eno-push-1", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-2", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-3", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-4", value: "Group Off"

I get the following traces when I press button 4 :
EnOcean: 01 (07/07) F6 70 00 3A 5F 75 30 00 FF FF FF FF 46 00
dzVents: Info: Handling events for: "eno-push-4", value: "On"

EnOcean: 01 (07/07) F6 00 00 3A 5F 75 20 00 FF FF FF FF 43 00
dzVents: Info: Handling events for: "eno-push-1", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-2", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-3", value: "Group Off"
dzVents: Info: Handling events for: "eno-push-4", value: "Group Off"

2/ with newest fd8b266 version
I get the following traces when I press button 3 :
EnOcean: 01 (07/07) F6 50 00 3A 5F 75 30 00 FF FF FF FF 4D 00
EnOcean: 01 (07/07) F6 00 00 3A 5F 75 20 00 FF FF FF FF 4A 00
(+ no event triggered in dzVents)

I get the following traces when I press button 4 :
2021-03-12 14:59:06.790 Status: EnOcean: 01 (07/07) F6 70 00 3A 5F 75 30 00 FF FF FF FF 44 00
2021-03-12 14:59:07.110 Status: EnOcean: 01 (07/07) F6 00 00 3A 5F 75 20 00 FF FF FF FF 46 00
(+ no event triggered in dzVents)

NB. not sure of buttons numbering, since there are no indications on my switch.

**Comment by efdeb** [comment]
After investigating, the issue comes from [this code](https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1736).

When a device doesn't exist in EnoceanSensors table in the database, it is created with F6-05-02 EEP profile, which corresponds to a smoke detector. The rocker switch device in then managed as a smoke detector instead of a switch, which causes the malfunction described above...

As a workaround, it is possible to edit domoticz.db to change EEP profile to the one corresponding to the rocker switch : F6-02-01, but I don't know how to do it through domoticz the web interface.

 I don't think "Add support for F6-05-xx" should change the behaviour of previously supported device... but in the current version only F6 EEP profiles supported are : [F6-02-01](https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1762) and [F6-05-xx](https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1921)

**Comment by gizmocuz** [comment]
I think we should revert this PR as the default behavior before was working... but not for a smoke detector

**Comment by alexis-via** [comment]
@efdeb  It's great that you identified the cause of the problem, which is linked to the fields Profile and Type in the table EnoceanSensors in the sqlite database.
In the Enocean protocol, it's not possible to know the profile of a device when it joins. In some special cases, we may guess the profile, but I can't do it in this case.
@gizmocuz This is a question that I asked you during the development of the smoke detector: how can users setup the profile of their Enocean profile via the web interface ? I didn't find a way to do it. It seems it was possible in the past.
Reverting my PR would be a step backward. If want to move forward, we need to give users the possibility to setup the profile of their Enocean devices. In the meantime, to avoid troubles for users of Rocker Switch F5-02-01, we could modify the default profile/type on that line of code: https://github.com/domoticz/domoticz/blob/development/hardware/EnOceanESP3.cpp#L1734
Instead of profile = 0x05 and type = 0x02, we could set profile=0x02 and type = 0x01. That way, it will work "by default" for users of rocker switch profile, and users of smoke detector will have to update the profile by hand in SQL (until we have a way to update the profile in the web interface).

@efdeb In order to put your rocker switch back to work, you can update the profile via SQL:
sqlite3 domoticz.db
sqlite> .headers ON
sqlite> select * from EnoceanSensors;
=> spot the ID of you device and look at the Profile and Type columns.
sqlite>update EnoceanSensors set profile=2, type=1 where ID=X;
where X is the ID of your rocker switch enocean device.

**Comment by arno0392** [comment]
I tested it and that solves the bug.
I understand that the best solution is creating an UI to change the type.
Impossible to detect the type of device with telegram or id?

**Comment by efdeb** [comment]
Depending on the device profile, EnOcean standard proposes different teach-in methods described in the documentation [EnOcean_Equipment_Profiles_EEP_v2.6.8.pdf](https://blog.zesanglier.fr/wp-content/uploads/2021/02/EnOcean_Equipment_Profiles_EEP_v2.6.8.pdf). Devices using RPS teach-in (for F5-xx-xx devices, which is our concern here), 1BS teach-in (for D5-xx-xx devices) and 4BS variation 1 teach-in (for some A5-xx-xx device) do not transfer their manufacturer ID nor EEP profile. This data must be manually supplied to the controller which I think is not possible in the web interface.

Setting default value to F5-02-01 as proposed by  @alexis-via seems to be a viable option, firstly to avoid regressions, and also because rockers switches are more common than smoke (or other) detectors.

I also agree that a next step probably is to add an interface to manage the profile in the web interface.
