### ISSUE TITLE
MQTT logs with beta version 13179

### ISSUE THREAD

**Issue by megamarco833** [domoticz/domoticz#4813]
hi, as reported inside forum: https://www.domoticz.com/forum/viewtopic.php?f=6&t=36171&p=274250#p274250
i see that since when i update with beta version from 13179 and also try right now the latest version 13240 on RPI2, i see that inside menu configuration -> logs and selecting label "all" in the previous version i was able to see all action that domoticz do, in particular in the "old" version i was able to see all mqtt messages that arrived in topic "domoticz/in"

with latest version i'm not able to see anymore these mqtt messages incoming.
example of webpage of log with version earlier that 13179
```
 2021-04-30 11:14:06.094 Python Plugin System: (tasmoticz) Handler::onMQTTConnected: Subscriptions: ['stat/tasmota_156/+', 'tele/tasmota_156/+', 'stat/tasmota_mcp/+', 'tele/tasmota_mcp/+']
2021-04-30 11:14:06.145 Python Plugin System: (tasmoticz) Handler::onMQTTPublish: topic: tele/tasmota_156/LWT
2021-04-30 11:14:06.146 Python Plugin System: (tasmoticz) Handler::onMQTTPublish: topic: tele/tasmota_mcp/LWT
2021-04-30 11:14:07.106 MQTT: Topic: domoticz/in, Message: {"command":"setuservariable","idx":27,"value":"calorifero mansarda reboot"}
2021-04-30 11:14:07.208 MQTT: Topic: domoticz/in, Message: {"idx":5,"nvalue":0,"svalue":"157;39545504"}
2021-04-30 11:14:07.317 MQTT: Topic: domoticz/in, Message: {"idx":9,"nvalue":0,"svalue":"0;36628272"}
2021-04-30 11:14:07.425 MQTT: Topic: domoticz/in, Message: {"idx":6,"nvalue":0,"svalue":"352;4749336"}
2021-04-30 11:14:07.685 MQTT: Topic: domoticz/in, Message: {"idx":7,"nvalue":0,"svalue":"160;805540"}
2021-04-30 11:14:07.791 MQTT: Topic: domoticz/in, Message: {"idx":8,"nvalue":0,"svalue":"0;38983852"}
2021-04-30 11:14:07.896 MQTT: Topic: domoticz/in, Message: {"idx":130,"nvalue":0,"svalue":"0;0"}
2021-04-30 11:14:07.006 Status: MQTT: Subscribed
2021-04-30 11:14:08.002 MQTT: Topic: domoticz/in, Message: {"idx":11,"nvalue":0,"svalue":"15.6;99.9;3"}
2021-04-30 11:14:08.115 MQTT: Topic: domoticz/in, Message: {"idx":13,"nvalue":0,"svalue":"224.10"}
2021-04-30 11:14:08.224 MQTT: Topic: domoticz/in, Message: {"idx":12,"nvalue":0,"svalue":"2.37"}
2021-04-30 11:14:08.330 MQTT: Topic: domoticz/in, Message: {"idx":101,"nvalue":0,"svalue":"842353.77000009"} 
```

example of what i'm not able see anymore in new versions:
```
2021-04-30 11:14:08.224 MQTT: Topic: domoticz/in, Message: {"idx":12,"nvalue":0,"svalue":"2.37"}
2021-04-30 11:14:08.330 MQTT: Topic: domoticz/in, Message: {"idx":101,"nvalue":0,"svalue":"842353.77000009"}
```

thanks to Waaren i understand that these messages are now only visible when hardware debug mode is on.

to implement harware logs i need to modify: `/etc/init.d/domoticz.sh ` with:
```
DAEMON_ARGS="$DAEMON_ARGS -loglevel  normal,status,error,debug" # debug enabled for now
DAEMON_ARGS="$DAEMON_ARGS -debuglevel hardware"
```

than:
```
sudo systemctl daemon-reload
sudo service domoticz stop
sudo service domoticz start
```

i'm asking if it's possible to implement inside MQTT harware page a button 
![immagine](https://user-images.githubusercontent.com/44502572/117155007-b3630500-adbc-11eb-9d36-95fc7467a480.png)

where we can flag if using hardware logs or not.
it's usefull for me to see these messages, and it's not comfort modify sh file start and stop domotiocz service...
maybe add this inside setting could be another  option?
like we have the possibility for dzvents to choose what kind of logs we would like to see....
![immagine](https://user-images.githubusercontent.com/44502572/117155384-0472f900-adbd-11eb-9235-8ce514cda4fa.png)

what do you think?

thanks!
regards

**Comment by gizmocuz** [comment]
Yes this is by design... It is also not a normal debug log message, but a hardware debug log message
If you start domoticz with "-debuglevel hardware" (without the quotes) you should be able to see them again

**Comment by megamarco833** [comment]
> 
> 
> Yes this is by design... It is also not a normal debug log message, but a hardware debug log message
> If you start domoticz with "-debuglevel hardware" (without the quotes) you should be able to see them again

but you are referring to use it to start using Raspberry ?
i was not aware about that option :)
anyway, do you think that is not usefull to add an option inside the GUI to use the hardware logs?

thanks!

**Comment by rwaaren** [comment]
> but you are referring to use it to start using Raspberry ?

Yes you can start domoticz manually with the same or other parms as set in /etc/init/domooticz.sh 
debuglevel is one of the many optional parms as I already explained in my reply on the forum.

**Comment by megamarco833** [comment]
thanks and sorry open issue...maybe we can discuss on forum if it could be optimized the usage of hardware logs :)
but i take the chance to write **_thank you both_** for your big effort to develop and maintain domoticz that's a great great great great domotic software that i love it :D

**Comment by waltervl** [comment]
> Yes this is by design... It is also not a normal debug log message, but a hardware debug log message
> If you start domoticz with "-debuglevel hardware" (without the quotes) you should be able to see them again

Why is this suddenly a hardware debug log. This was never this way. It is really annoying to have to switch on debug level now as it was not needed before. The info level switch in GUI could switch this on/off

**Comment by gizmocuz** [comment]
It was requested, and makes sense because this is not information you need to see, only when debugging, or when you are making your own MQTT messages
"In the old days, everything was better...." It's a common phrase ... sometimes things need to change.
You are probably one of the few that would like to see this, and you can...

**Comment by waltervl** [comment]
The request was to have them not shown. That could already be done with the new GUI hardware info logging switch.
So I request them to have it back under the info logging. I suppose this will be handled as quickly as the original request. :-)

**Comment by kiddigital** [comment]
> The request was to have them not shown. That could already be done with the new GUI hardware info logging switch.
> 
> So I request them to have it back under the info logging. I suppose this will be handled as quickly as the original request. :-)
> 
> 
> 
> 

@waltervl , I don't think that your reasoning for your request is any close to convincing.

The starting point that you want the 'old' behavior back fully neglects the fact that the old behavior could be wrong.

When a 'bug' (not intended behavior) gets fixed, it would be weird to revert that (and bring the 'bug' back) just because certain users where able to use it to their advantage.

Zooming in into this particular case. The different logging levels are meant for users to see what is going on at the 'domoticz' level, meaning system wide. Are all parts and (hardware) modules working and are there any warnings and errors that require the user(s) to act upon (or not).

When looking at individual hardware modules, like the MQTT module, these modules should restrain themselves to not be to verbose by default. So only when specifically requested by starting Domoticz with one or more debugging flags depending on the needs.

The problem with hardware modules that are too verbose, for example the MQTT module reporting every in- or outgoing message, that this will cause Domoticz to produce way to much logging flooding logfiles and memory quickly especially on smaller machines (like an RPi).

One can easily imagine what would happen if a system with say 10 hardware modules, that each would report everything they are doing.

Therefor I think that it is great that the developers keep fixing all kinds of bugs, including this one, so Domoticz keeps behaving as many users are expecting and depending upon.

Btw, feel free to write some code to expand on the logging system to for example implement ways to forward certain (debug) logging to external systems (without blocking Domoticz when logging can not be forwarded). Did you have a look at the SysLog options of Domoticz (or even your own environment)? Maybe leverage that in a way that works for you?

Everyone, keep up the good work and dialogues to continue bringing this great project further.

**Comment by waltervl** [comment]
I think it is great too that the Domoticz is developing. I love the way it is setup and a lot of tasks can be done without complicated scripts and file handling.
In this case the commit https://github.com/domoticz/domoticz/commit/772a02ce43d0dd6f6678a909f693a5fd04917075  in my personal opinion is one step too far for User Friendliness. Implementing MQTT is difficult enough and it is becoming more important with all these Wifi ESP2866 modules that get developed rapidly.

PS I have updated the wiki on this part to warn the users for this behaviuor: https://www.domoticz.com/wiki/MQTT#Domoticz_MQTT_communication

**Comment by jmcvieira1** [comment]
hello everyone I'm a new user of Domoticz and I don't have any programming experience I have Domoticz running on Windows and it was good to be able to turn on the log in the options and see the MQTT messages.
I started with an older version where the messages were visible and it really help to get the messages through Nodered.
thanks for all your work.
