### ISSUE TITLE
Remove PDF manual from Domoticz.com

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#4841]
Please remove or hide the really outdated pdf manual from 2015  from the menu of domoticz.com.
https://www.domoticz.com/DomoticzManual.pdf

Or put a pdf there that has only one line: Goto https://www.domoticz.com/wiki

**Comment by gizmocuz** [comment]
I think there is still lots of information in there that could be useful for the first time user.
Things I can not find in

https://www.domoticz.com/wiki/Getting_started

Maybe you could update this wiki page with the useful information from the PDF and then we can link to this wiki page ?

Remember not all users are computer nerds

**Comment by waltervl** [comment]
This information should all be available on the wiki when going to the linked pages in the getting started page. I really have no idea what you miss. I made a lot (really a lot) of changes to the wiki from December until now. I made  several new pages including https://www.domoticz.com/wiki/Managing_Devices
Most information for the user is now on this page.

There is too much information in the PDF to put in one page on the wiki so I made linked to other pages. The only part they is not well covered is the master/slave behavior of devices. But the basic information out of the wiki is there.

**Comment by gizmocuz** [comment]
It's more the work flow that is missing... Adding hardware, using the learn switch button, setting notifications on switches/sensors
If a new users goes to the wiki, It is to much information.. The getting started page is a very good entry point, but it should contain links to a logical step-by-step instructions

Settings->setup a admin username/password, local networks, geo location, ...
Hardware setup
Explanation of the views, widgets, notifications
Actions (Blockly, dzVents)

Your page is great, but could use a little simpler wording, for example the first sentence I don't understand

"Devices are only created when the Hardware gateway to were the devices are connected to is created" 

You probably mean

"The first step to work with Domoticz is to add hardware to the system. This could be a receiver that can control power plugs, read data from your Energy meter or for example receive information about weather conditions"
To do so, go to the hardware page and from the hardware type dropdown select the appropriate hardware you would like to add
[image]
Some hardware require additional information/settings, bla bla bla

I think a wiki section about hardware setup is needed

Explain the fields (data timeout, log level, enabled/disabled, display what happens when hardware is disabled but you see their widgets (screenshot)

Types of hardware supported, also talk about Python plugins, point to a link where you can find them, how to install them

... A manual

**Comment by waltervl** [comment]
The getting started page I inherited so yes, could be a more optimized.

Please check the configuration page https://www.domoticz.com/wiki/Configuration
There is a link to most of the information you requested.

**Comment by waltervl** [comment]
I have edited the Getting started and Managing devices (and some more) a little bit.
Main flow is to go from page Getting Started to Configuration to Automation etc (Domoticz & Device setup line on the main page).

But to come back to the original request: The pdf also does not have this information you requested.
Now the PDF is and looks really outdated so not a good showcase of this fantastic project.

As I have no RFLink I am not able to update sections about learning switches etc (also not available in the PDF)

**Comment by gizmocuz** [comment]
Thank you for the changes!

This is described by images/text in the manual on Page 26.
Sure I do agree the manual is extremely outdated... Nobody seems interested to keep this up-2-date.
When all sections are covered (and i know the wiki has lots and lots more) we should indeed link to the getting started page

**Comment by waltervl** [comment]
Made some extra changes on the wiki, please review. https://www.domoticz.com/wiki/Special:RecentChanges?hidebots=1&limit=500&days=30&enhanced=1&urlversion=2

**Comment by kiddigital** [comment]
@gizmocuz , I see that @waltervl has done massive work in updating the Wiki (thx @waltervl ) and the current PDF is indeed very outdated now. Also the need for an offline document is way less than years back.

**Comment by gizmocuz** [comment]
Yes that is correct... I will remove the PDF.... nostalgie is what I call it 😁
@waltervl , thanks a million for your time of course!!!

I will remove this right away

**Comment by waltervl** [comment]
Thanks!!!

**Comment by waltervl** [comment]
@gizmocuz I thought it was browser cache first :-) but on https://www.domoticz.com/downloads/ I still see a manual link to PDF....
On https://www.domoticz.com it is al OK...

**Comment by gizmocuz** [comment]
Missed that one! Done as well !
