### ISSUE TITLE
DzVents error about hardwareName having nil value

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#4961]
Today I update to build 13703 with the latest zigbee2mqtt and Domoticz version of the zigbee2mqtt plugin.
I got a lot of trubble getting the system up and running. The system all the time crashes with zigbee thread ended abnomally.
When I it up and running again, almost every zigbee device gave an error.
`2021-10-10 10:34:52.517 Error: EventSystem: in /home/pi/domoticz/dzVents/runtime/dzVents.lua:
/home/pi/domoticz/dzVents/runtime/EventHelpers.lua:454: attempt to concatenate a nil value (field
'hardwareName')`
After I actuated almost every zigbee device this error went away.
Could this error be the cause of my startup problems with Domoticz and zigbee2mqtt?
What is the cause of this error?

**Comment by Kubra** [comment]
Yesterday I updated from 13360 to 13703 and got about the same error (script runs every 5 mins):

2021-10-10 11:50:00.323 Error: EventSystem: in Script #1 - Weer: [string "--[[ ..."]:133; attempt to index a nil value (local 'jsonData)'
2021-10-10 11:55:00.493 Error: EventSystem: in Script #1 - Weer: [string "--[[ ..."]:133; attempt to index a nil value (local 'jsonData)'
2021-10-10 12:00:00.399 Error: EventSystem: in Script #1 - Weer: [string "--[[ ..."]:133; attempt to index a nil value (local 'jsonData)'
2021-10-10 12:05:00.502 Error: EventSystem: in Script #1 - Weer: [string "--[[ ..."]:133; attempt to index a nil value (local 'jsonData)'

This script gathers data for weatherforecast (Buienradar) and this doesn't work anymore because of this error. I run Domoticz in Docker.

A solution/update, to correct this issue, is welcome. 
Thanks.

**Comment by SargonofAssyria** [comment]
This is not the same kind of error. Your error originates from json data from Buienrader which is not correct or not correctly processed. My error comes from the fact that a zigbee device does not have it's hardwareName filled for some reason.

**Comment by Kubra** [comment]
That is why I said "about the same error". Fact is that version 13360 (prior 13703) worked fine. Nothing has changed in the script or setup, only ran the update.

**Comment by SargonofAssyria** [comment]
But then you better open a new issue....
And better run as the default suggest every 15 minutes.
I think there might be a max on the requests per IP.

**Comment by Kubra** [comment]
You're right. Have a nice day.

**Comment by SargonofAssyria** [comment]
I investigated a little bit further. It looks to me that it has something to do with the retained messages.
The new auto-discovery works fine, I mean it does not generate errors.
I have 1 retained message that puzzles me.
`zigbee2mqtt/bridge/groups [{"friendly_name":"default_bind_group","id":901,"members":[],"scenes":[]}]
`
I can not remember, I am sure, that I never created that one. What might be the function. And can I delete this group?

**Comment by waltervl** [comment]
Check zigbee2mqtt instructions, nothing to do with Domoticz.
To delete retained messages check https://community.openhab.org/t/clearing-mqtt-retained-messages/58221

**Comment by SargonofAssyria** [comment]
I know that it has nothing to do with Domoticz, and that the messages are send by zigbee2mqtt.
I know how to delete retained messages.
I wonder what the function of the message is and if I can delete the message without getting into trouble.
I states 'group' and 'default_bind_group' I don't have groups, but is it necessary? 

B.t.w. the real problem is the nil value in dzVents for field hardwareName comming from zigbee

**Comment by waltervl** [comment]
I don't know and unfortunately this is not the place to discuss.

**Comment by SargonofAssyria** [comment]
I am not discussing, but try to resolve a persistent error from zigbee which gives an error in dzVents and also crashes the zigbee thread.
