### ISSUE TITLE
OpenZWave Update

### ISSUE THREAD

**Issue by markruys** [domoticz/domoticz#4965]
The fork https://github.com/domoticz/open-zwave is lagging behind. https://github.com/OpenZWave/open-zwave/ contains I think important enhancements like Supervision support for Fibaro thermostats. Please consider pulling to the head of OpenZWave:master.

**Comment by Olifant1990** [comment]
I guess Domoticz is using https://github.com/OpenZWave/open-zwave/ for release.
My bet is that https://github.com/domoticz/open-zwave is a local fork of @gizmocuz to do development/improvements/PRs to OpenZWave ;)

**Comment by gizmocuz** [comment]
It also removes the auto configuration files update since the site is/was down.
Since months there have been no active c++ development in OZW.
My best advise is to use ZWaveJS2MQTT as support for this has been natively implemented in the latest domoticz beta versie (via native MQTT with auto discovery support)
The developer of OZW has seems to have stopped with this project
I will try to update our zwave repo, seems to be stuck on one file so should not be that hard

**Comment by gizmocuz** [comment]
OZW has been updated, that was not that easy... Still better to try (and when stable) move to zwavejs2mqtt, runs nicely in a docker next to Domoticz
Beta 13737 contains the new library/config files, could take an hour before available

**Comment by rrozema** [comment]
Please also included the SuperVision class source files in the VisualStudio project file (it took me quite some time to work out what was wrong building the target...)

**Comment by nebuohyrrah** [comment]
Thanks for updating the OZW files. I will have a look at ZWaveJS2MQTT to see if it is an suitable alternative to OZW. At first look it looks promising.
