### ISSUE TITLE
Bug! MQTT-Autodiscover recognizes Selector-Switch as text.

### ISSUE THREAD

**Issue by vladi1234** [domoticz/domoticz#4990]
**Additional information**
Ubuntu 20.04.3 LTS
Python version: 3.8.10
Domoticz Version: 2021.1 (build 13745)
Zigbee2MQTT Version: 1.21.2-dev commit: eaad39a1
Coordinator: TypzStack3x0
Coordinator Version: 20210120
Frontend Version: 0.6.9

**Issue description**
All these products WXKG12LM, HS1RC-EM, Tuya SS600ZB (TS0043) have the same problems, they should all be recognized as selector switches, but they are recognized and created as text.

**Comment by gizmocuz** [comment]
There are already multiple issues related to the new beta version of MQTT.
Instead of having 100 issues, it's best to join our slack channel, when you do, please send me a direct message there
If possible use MQTT Explorer and send the config json of your select object and the state message, please include the topic as well.
If uncertain, send met a DM on slack
