### ISSUE TITLE
Regular domoticz crashes

### ISSUE THREAD

**Issue by pitchoun38** [domoticz/domoticz#5046]
I'm running Domoticz on a Fedora 33 distribution on an RPI3B+

Domoticz version: 2021.1 (build 13704)
Python 3.9
fully rebuild

The following plugins are enabled
- OZW
- Zigate
- and few others

Domoticz has been rebuild on the plateform

I'm getting regular Domoticz crashes when using the WebUI from the ZiGate Plugin,

[domoticz_crash.log](https://github.com/domoticz/domoticz/files/7684144/domoticz_crash.log)

Let me know if you need more informations

**Comment by dnpwwo** [comment]
@pitchoun38,

Thanks for posting the crash log, its quite interesting.  Its not often that I've seen 2 threads calling a signal handler at the same time.

This appears to be a case where a Python native thread is allocating memory at the same time that a Domoticz thread is. To be honest, I'm amazed that no one has seen this issue before because I always thought it could happen.  I have a fix I developed some time ago but never rolled it out because no one reported it (never fix something that isn't broken).

I'll do some testing to confirm it works and roll it out if it does.

**Comment by waltervl** [comment]
did you check with @pipiche38 , the Zigate plugin developer?
I never have crashes using the Zigate Plugin UI (default on port 9440).
What version of Zigate Plugin are you using?

**Comment by pitchoun38** [comment]
Hi @waltervl , I'm @pipiche38 . Currently my GitHub account is not usable. I had enable double authentication and suddenly the code doesn't work any more and the Recovery Code don't either.
I'm in touch with GitHub support, but will take several days to be back

So it is based on the latest version of the Plugin (I had this issue since several months, but it is happening during the development when using extensively the WebUi which use the HTTP listening part of the Python Framework which I think is not often use b y other plugin developers)

**Comment by dnpwwo** [comment]
Its interesting that you are using Python 3.9.  I've seen the odd crash in Visual Studio with 3.9 that look like ths but couldn't pin it down but the crash log shows the issue quite clearly.  My guess is that the memory handling in 3.9 has been changed which is why this is happening now and wasn't before.

I have limited abilty to test the fix because my linux test server can't build Domoticz at the moment and I'm relutant to inflict this on the Beta community.  Are you building from source?  I could send you the upgrade source files if you are.  My fix seems to work on Windows.

**Comment by pipiche38** [comment]
@dnpwwo yes I do recompile from the source code and would be happy to test your patch. I'll also check with one of the user who has this crash if he is on python39 or not.

[EDIT] Got the feedback from an other user, he is based on python3.7.3 and having similar issue ( only time to time, as me)

**Comment by waltervl** [comment]
@dnpwwo is https://github.com/domoticz/domoticz/commit/43ee2af4912d67f0ee6a9d7b918ef92f71a61f12 a fix for this issue?

**Comment by pipiche38** [comment]
I think so, @dnpwwo told me that he has pushed the fix , I'm currently building domoticz based on this new commit

**Comment by dnpwwo** [comment]
Should be.

I've wanted to make this change for a while but didn't want to fix something that wasn't broken.

**Comment by kiddigital** [comment]
@pipiche38  (and @pitchoun38 ;) ) did the fix from @dnpwwo indeed fix the problem?

Would be great to now and if yes, this issue can be closed.

**Comment by pipiche38** [comment]
Yes it does, I have a very strong and reliable Domoticz now.
