### ISSUE TITLE
domoticz failed to build with error LNK2001 on Windows with MSVC of x64

### ISSUE THREAD

**Issue by YangYang129** [domoticz/domoticz#5092]
domoticz failed to build with error LNK2001 on Windows with MSVC of x64. It can reproduces on version https://github.com/domoticz/domoticz/commit/774d33586893ff9c73bf9c2bf23f24c6606e47f3. This error disappeared on Windows with MSVC of win32. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.5)
Operating system: Windows server 2019
**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/domoticz/domoticz c:\domoticz
3. cd c:\domoticz
4. git submodule update --init --recursive
5. cd msbuild
6. curl https://raw.githubusercontent.com/domoticz/win32-libraries/master/WindowsLibraries.7z -O -L
7. 7z x WindowsLibraries.7z -o"c:\domoticz\msbuild" -aoa
8. Change "./Windows Libraries/OpenZwave/bin/OpenZWave.lib" to "./Windows Libraries/OpenZwave/OpenZWave.lib" in  domoticz.vcxproj 
9. set INCLUDE=C:\domoticz\extern\jsoncpp\include;%INCLUDE%
10. set INCLUDE=C:\domoticz\msbuild\Windows Libraries\include;%INCLUDE%
11. msbuild /p:Configuration=Release;Platform=x64 domoticz.sln /t:Rebuild /m /p:PlatformToolset=v142 /p:UseEnv=true 

**Build.log:**
[msbuildx64a.log](https://github.com/domoticz/domoticz/files/7820324/msbuildx64a.log)

Error info:
2>1Wire.obj : error LNK2001: unresolved external symbol CONF_modules_unload [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1Wire.obj : error LNK2001: unresolved external symbol ERR_reason_error_string [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl Json::Value::Value(enum Json::ValueType)" (__imp_??0Value@Json@@QEAA@W4ValueType@1@@Z) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl Json::Value::~Value(void)" (__imp_??1Value@Json@@QEAA@XZ) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class Json::Value & __cdecl Json::Value::operator=(class Json::Value &&)" (__imp_??4Value@Json@@QEAAAEAV01@$$QEAV01@@Z) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class Json::Value & __cdecl Json::Value::operator[](char const *)" (__imp_??AValue@Json@@QEAAAEAV01@PEBD@Z) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl Json::Value::Value(char const *)" (__imp_??0Value@Json@@QEAA@PEBD@Z) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __cdecl Json::Value::asBool(void)const " (__imp_?asBool@Value@Json@@QEBA_NXZ) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: class Json::Value __cdecl Json::Value::get(char const *,class Json::Value const &)const " (__imp_?get@Value@Json@@QEBA?AV12@PEBDAEBV12@@Z) [C:\domoticz\msbuild\domoticz.vcxproj]
     2>1WireForWindows.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl Json::Value::Value(bool)" (__imp_??0Value@Json@@QEAA@_N@Z) [C:\domoticz\msbuild\domoticz.vcxproj]

**Comment by gizmocuz** [comment]
That is correct, current setup is using 32 bit libraries, so you need to compile a 32bit version

It is possible to compile a 64bit version, but you have to compile openzwave in 64 bit (i just make a commit that now expects the 64 bit OpenZWave library to be found in Windows Libraries\openzwave\x64\

Best to use visual studio first instead of the command line tools

I am able to build both debug/release x64 versions of Domoticz, but the installer still expects a 32bit version, current windows users installed a 32bit version, and once we migrate to 64bit, their current config/database would not be found, and there are many compile warnings that needs to be solved

1>domoticz.vcxproj -> S:\Domoticz\msbuild\x64\Release\domoticz.exe
1>Done building project "domoticz.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

You do also need to use VCPKG and not the libraries in the Windows Libraries folder (vcpkg libraries will be found first)
