### ISSUE TITLE
If you Replace a device, the new device is deleted instead of the old device.

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5102]
I created some new Temperature Devices and I wanted to transfer the "old" log from a Temperature device to the new Temperature Device.
I followed the procedure in the Wiki:

> To replace the old sensor data (history logging) to the new device act as follow: 
> 
> First, add the new device to the system, and call it for example ‘New UV Meter’. 
> Next press the Edit button on the Old device, select replace and select the new Device. (In this case the devices called ‘New UV Meter’. 
> Next press OK. The old device is deleted.
> 
> Now you can rename the new device back to ‘UV Meter’. The history sensor data of the old device is now visible in the new device.

Instead that the old device is deleted, the new device is deleted.

Regards

**Comment by kiddigital** [comment]
Isn't that the idea? The new device gets the ID of the old device so the history of the old device becomes the history of the new device.

The new device does not have a history (yet) so that is fine to get deleted.

So we end up with a new device (with the new settings/references) that re-uses the ID of the old device. Also beneficial to any scripts, etc. that before used the old device and now use the new 'old' device 😁

**Comment by gizmocuz** [comment]
This is done on purpose as the old device could be used in scripts or have other settings.

**Comment by waltervl** [comment]
The logic is somewhat different:
The latest updated device will stay, normally that is the new device as it will be updated by for example RF after battery update or plugin when a new device is created.
But if a new device is created and the old one is still being updated then the old will stay.
Edit: I have updated the wiki

**Comment by gizmocuz** [comment]
I made a very recent patch for Lights/Switches, when you replace a light/switch, press edit the 'old device', and choose 'Replace Device'. Select the New device.
What will happen internally is that the old New device get's the IDX value of the old device.
(Well actually the old device gets the HardwareID,DeviceID and Unit of the new device)
This way all logs/scripts/timers etc etc etc will stay in tact.

For other devices all logs/timers etc etc etc will be transferred to the new device and the old device is deleted

I vote for the first method (lights/switches) to be applied for all devices in Domoticz.

**Comment by waltervl** [comment]
I do not mind what logic is implemented as long that there is 1 logic for all devices. Counters and sensors are also heavily used for scripting so if that is the use case than it seems a good way. Especially when in new stable with MQTT AD a lot of people are going to migrate devices from OZW or plugin to MQTT AD hardware. (Edit: will that work with naming conventions with eg ZwaveJS2MQTT and ZigbeeJS2MQTT device naming?)

**Comment by jvanderzande** [comment]
> I vote for the first method (lights/switches) to be applied for all devices in Domoticz.

+1

**Comment by GravityRZ** [comment]
i think method 1 was already implemented but aparently not for switches(thus the reason for gizmocuz to change that behaviour)

my current experience is that if i replace an old temperature device with a new device the result is:
new device gets/keeps the id of the new device and gets the log/history of the old device.

so regarding scripting you should always use names instead of id's for reference because the id's will change overtime but the names not(because you give the new device the old, original name.

**Comment by gizmocuz** [comment]
I like to work with IDX values as the stay the same (now)
In the next beta the logic is as following

- The old device (where you pressed 'Edit/Replace Device') will get the following parameters from the new device
   - Hardware ID, DeviceID, Unit, Type, SubType
   - (not the name)
- The new device is deleted

This will cause all current logs/scripts/idx/name values to stay like the where before

@waltervl , yes i suppose so, it will be easy to transfer to new devices (openzwave->mqtt)

It is also easy to switch to another type, for instance switch from ZWave to Zigbee, or the other way arround)

@FireWizard52 , now the new device is always deleted (well internally in the database, the device with the new idx is deleted), but your new hardware will keep updating the old one now because it has all the parameters of the new device

**Comment by FireWizard52** [comment]
@gizmocuz

That is fine for me and it is the way I would like to see it functioning.
One thing.
If I press "Edit/Replace" in a specific device, I would expect that this one will disappear in favor of the new one, because you replace the old one  by a new one. I suggest that the text Replace is "replaced" by some thing as "Import from", as in fact the "old device" will continue to exist, but with the new HardwareID, DeviceID, Unit, Type and Subtype.

I think this will make it clearer.

@waltervl.
If it is is implemented, either with "Replace", "Import from" or any other text, could you update the WIKI again, so that it is clear for all users.

Regards

**Comment by gizmocuz** [comment]
You still replace it with a another sensor, and it could even be a old sensor.
Also changing GUI texts will cause all translators to update their translations again
I find 'Replace' a very good button label ;)

**Comment by FireWizard52** [comment]
Ok, yes, I agree, the impact to change it is too big.

Regards

**Comment by GravityRZ** [comment]
ok. sounds like a nice solution with only advantages, same idx as before, same name as before(no need to rename upfront) and the same history as before

**Comment by GravityRZ** [comment]
i finally got a chance to test this feature. works flawless

in settings allow hardware for 5 minutes
new device gets detected
add new device with logical name (tuin-nieuw)
goto old device
edit
replace and select the new device(tuin-nieuw)
old device(yuin) gets active again with all the history
new device(tuin-new) gets deleted

yes the new device gets deleted(with all of it's history) but you are not supposed to leave the new device active for a long time(because this device including history) get's deleted.

i would say, perfect implementation and working like it should
