### ISSUE TITLE
Domoticz 2022.1 release update problem

### ISSUE THREAD

**Issue by ilexpl01** [domoticz/domoticz#5139]
Hi,

I am running Domoticz as docker container.

Update performed:

root@NAS03:~# docker pull domoticz/domoticz
Using default tag: latest
latest: Pulling from domoticz/domoticz
6552179c3509: Pull complete
c4105197c5de: Pull complete
969aac0bb2e6: Pull complete
e205d85c7545: Pull complete
0b50b54e633c: Pull complete
Digest: sha256:57bbadc5bcf03e8b5aa46ccea796497e32206130a2cf3730d782011f4a8a3441
Status: Downloaded newer image for domoticz/domoticz:latest
docker.io/domoticz/domoticz:latest

Result:

REPOSITORY TAG IMAGE ID CREATED SIZE
domoticz/domoticz latest 38828d9023bf 32 hours ago 347MB

After container start I get:

2022-01-31 21:03:56.741 Status: Domoticz V2021.1 (build 14119) (c)2012-2022 GizMoCuz
2022-01-31 21:03:56.741 Status: Build Hash: 24d6c4f48, Date: 2022-01-30 12:05:07
2022-01-31 21:03:56.741 Status: Startup Path: /opt/domoticz/

Any hint ?

**Comment by waltervl** [comment]
That is correct, tag latest is the latest beta being V2021.1 (build 14119)
If you want the latest stable (eg 2022.1) use tag stable.
See also https://www.domoticz.com/wiki/Docker

There is an issue though with tag 2021.1 as that is giving stable 2022.1 instead of old stable 2021.1
There is also no tag 2022.1 for new stable

**Comment by ilexpl01** [comment]
Perfect advice ! Thank You. Got 2022.1 running fine :)
