### ISSUE TITLE
domoticz crashs while save settings

### ISSUE THREAD

**Issue by MarkKoshelev** [domoticz/domoticz#5141]
domoticz crashs while save settings on debian  bullseye while save settings
The call stack(under gdb + debug version) is in attachment
The reason m_pWebEm has nullptr value
I see that m_pWebEm is initialized one time but used two. The secont is the reason of the crash
[crash.txt](https://github.com/domoticz/domoticz/files/7977397/crash.txt)

**Comment by gizmocuz** [comment]
Thank you for reporting. Could you please mention your build/version number ?
Could you be a little bit more specific where it crashes ?
What are you domoticz startup parameters? Are you using both HTTP and HTTPS?

**Comment by MarkKoshelev** [comment]
1. the latest development version
2. the very simple scenario to reprodice the crash. Build debug version, run under gdb with paramets -www 8080. https is not started:
2022-02-01 17:04:22.120  Error: WebServer(SSL) startup failed on address 0.0.0.0 with port: 443: bind: Permission denied
2022-02-01 17:04:22.120  Error: WebServer(SSL) check privileges for opening ports below 1024
3. edit location in settings and save  settings

**Comment by gizmocuz** [comment]
Found the issue, but I think the issue is really that if a service can not be started, it shouldn't be added to the '**serverCollection**' array in **CWebServerHelper**
Fixed in development branch, thanks for reporting!

**Comment by kiddigital** [comment]
@gizmocuz , I sort of stumbled upon this issue as well some time ago (see [this](https://www.domoticz.com/forum/viewtopic.php?p=282984#p282984) forum thread), but in doubt if/how to really fix it.

Your checks prevent crashing indeed, but question remains if/how the calling sequence misbehaves leading to the situations that these methods are called while things are empty/stopped, etc. Somewhere/somehow it feels there is a logic issue at the root of this.

Not sure if/how/when we should try to fix the root-cause, if indeed any underlying issue is found, or we stay with fixing/preventing the 'symptom'. Or I am just totally wrong and the root-cause is fixed :).

**Comment by gizmocuz** [comment]
@kiddigital , these where the only 3 places where the check was not performed (maybe the one creating it forgot it), but as mentioned, I don't think the server should have been in the **serverCollection** at all... (As it could not start properly) and the pointer should be reset
It is also a good idea to check for pointers
