### ISSUE TITLE
[Netatmo] Air Quality not working since Build 14240

### ISSUE THREAD

**Issue by domofox** [domoticz/domoticz#5202]
Hello,

Since Build 14240, Netatmo Air Quality for the base station is not working (still stuck at 0 PPM).

I don't know why :
`_eNetatmoType m_NetatmoType;` line ?

**Comment by waltervl** [comment]
@StephaneM60 Can you please check this? As it seems https://github.com/domoticz/domoticz/pull/5174 is causing some issues.

**Comment by waltervl** [comment]
See also https://www.domoticz.com/forum/viewtopic.php?p=288051#p288051

**Comment by StephaneM60** [comment]
Hi @domofox I checked on my Domoticz installation and I'm still receiving data from the CO2 sensor. I had not made any changes regarding the weather station.

The only changes I made was that the code implied that you had either a weather station or a thermostat, but not both. So I made sure that the code was correctly checking for a thermostat when you also have a weather station.

I also added some feature to the thermostat : changing the schedule and setting frost guard and away mode. And I have changed some device IDs (I don't remember If I changed device IDs for the weather station)

So if you have data coming from your weather station, you should receive exactly the same data as before.

Maybe go in your device page, filter them for the Netatmo device and check that the CO2 sensor has not been assigned a new device ID.

Can you please telle me : if you have only a weather station ? If you still receive other data (temp from the base, temp from the module) ? Alors when you start (or restart) the netatmo integration do you see errors or warning in the logs.

Also, I do not understand your comment about m_NetatmoType; line. Do you mean you want to know what it is missing ? It's because you can have both a weather station and thermostat, m_NetatmoType was storing if you have Weather or Thermostat, so now you need two variables to hold the type of hardware owned (I could have done it in another way, but I tried to keed as much as possible from the original code, otherwise I would have changed completely the detection code)

Regards.
