### ISSUE TITLE
TimedOut not working at least used with python plugin on last beta version.

### ISSUE THREAD

**Issue by Smanar** [domoticz/domoticz#5218]
Link on forum https://www.domoticz.com/forum/viewtopic.php?t=38417

Hello there is a change on recent version that disable the Timedout parameter on python plugin.

<html><body>

TimedOut | Read/Write | Device TimedOut flag. 1=True, 0=False
-- | -- | --

</body>
</html>

Used for exemple with 
```
kwarg = {'nValue': 0, 'sValue': 'Off', 'BatteryLevel': 255, 'TimedOut': 1}
Devices[Unit].Update(**kwarg)
```

On older version the widget was marked in red, on beta (build 14315) nothing happen 

```
			"AddjMulti" : 1.0,
			"AddjMulti2" : 1.0,
			"AddjValue" : 0.0,
			"AddjValue2" : 0.0,
			"BatteryLevel" : 255,
			"CustomImage" : 9,
			"Data" : "Off",
			"Description" : "",
			"DimmerType" : "none",
			"Favorite" : 0,
			"HardwareDisabled" : false,
			"HardwareID" : 3,
			"HardwareName" : "Deconz",
			"HardwareType" : "deCONZ plugin",
			"HardwareTypeVal" : 94,
			"HaveDimmer" : true,
			"HaveGroupCmd" : true,
			"HaveTimeout" : false,
			"ID" : "90:fd:9f:ff:fe:6f:a7:cc-01-1000",
			"Image" : "Generic",
			"IsSubDevice" : false,
			"LastUpdate" : "2022-04-16 13:23:17",
			"Level" : 0,
			"LevelActions" : "fHx8fHx8fHx8",
			"LevelInt" : 0,
			"LevelNames" : "T2ZmfE9ufCt8LXw8fD58TCArfEwgLXxMIDx8TCA+",
			"LevelOffHidden" : true,
			"MaxDimLevel" : 100,
			"Name" : "Deconz - TRADFRI remote control ",
			"Notifications" : "false",
			"PlanID" : "0",
			"PlanIDs" : 
```

**Comment by gizmocuz** [comment]
First guess would be to search in the source code of Domoticz....
And specifically in WebServer.cpp, try a search for "HaveTimeout" because this is the JSON key that is set to true/false
You will see that this is set mostly by a boolean 'bHaveTimeout'

I compared the code from January and the timeout code/logic is the same

As far as I know (and how I created that a long time ago) the timeout Boolean is to mark if a sensor has been received in a specified interval. (hardware timeout setting)

You can not 'set' this field yourself

So I wonder if this ever worked ?

**Comment by pipiche38** [comment]
same issue on my end . while it was working before and still work on 2022.1

@gizmocuz it is possible to be set from the Python Plugin Framework when using the Device.Update API

Did few investigation in the Python Framework and the TimedOut value is correctly set during the Device.Update() and

`self->TimedOut = iTimedOut` is executed.

After it is beyond my skills.

CC: @dnpwwo

**Comment by Smanar** [comment]
>I compared the code from January and the timeout code/logic is the same

Yep, there is realy nothing specific to this value. Perhaps this issue is older, but I have return only recently with users on bulleyes that have updated their version to support the last python version.

>So I wonder if this ever worked ?

Yep, I can confirm and it's so uselfull ^^

**Comment by gizmocuz** [comment]
It seems only with Python (dzVents) you can 'set' the timeout... it is a variable only in that framework.
As you can see in the webserver code that returns the timeout as a JSON variable, it is based on the hardware timeout.
It is also not a variable inside the database

My guess is that it never worked (at least not in the web GUI).
If it is a older then the first of January, I guess not many people are using this feature (plugin wise)
Of course it was still working like intended, to notify users that no data has been received for a period of time (based on the setting in the hardware setup)

Talking about this, are you referring to Device.timeout or Hardware.timeout ? As these are two different issues.
I can guess that you should be able to set the hardware timeout maybe from a python plugin,
this because you say

self->TimedOut = iTimedOut 

This looks like a hardware/plugin timeout and not a 'device' timeout (a device created by the hardware)

**Comment by pipiche38** [comment]
What I'm referring is indeed Device TimedOut, which doesn't work on the latest dev, while it works on stable 2022.1

**Comment by gizmocuz** [comment]
I'll take your worth for it, only WebServer.cpp , line 8754 says otherwise

`bool bHaveTimeout = (now - checktime >= SensorTimeOut * 60);`

Also as we can see above, this is about a switch, those will not have a timeout (see line 8995 and up)

**Comment by pipiche38** [comment]
Here is what I found. So this is specific to Python and is the way the bHaveTimeout is transmitted between the Python Framework and Domoticz.

May be they were some changes between 2022.1 and now, whihc makes the root["result"][ii]["HaveTimeout"]  overwritten, or we simply don't go to this code anymore.

```
#ifdef ENABLE_PYTHON
					if (pHardware != nullptr)
					{
						if (pHardware->HwdType == HTYPE_PythonPlugin)
						{
							Plugins::CPlugin *pPlugin = (Plugins::CPlugin *)pHardware;
							bHaveTimeout = pPlugin->HasNodeFailed(sd[1].c_str(), atoi(sd[2].c_str()));
							root["result"][ii]["HaveTimeout"] = bHaveTimeout;
						}
					}
#endif
```

**Comment by gizmocuz** [comment]
I did some debugging, and that part of the code is still executed. (**Only if the hardware is enabled**)
Then it could go wrong in 'bool CPlugin::HasNodeFailed'

**Comment by pipiche38** [comment]
This doesn't sound good ;-), this seems to be disabled :-( since 2022.1.

So we found the issue !

```
 bool CPlugin::HasNodeFailed(const std::string DeviceID, const int Unit)
        {
                if (!m_DeviceDict)
                        return true;

                return false;
...



```

[EDIT]
https://github.com/domoticz/domoticz/commit/8f01ed77d5831090f34ad59d22ef1f7cd4d740f2#r71816638

**Comment by pipiche38** [comment]
I also do confirm that by removing the `return false;`line it works again.
I beleive only @dnpwwo  can tell us why it was disabled at the time of ABI interface implementation

**Comment by dnpwwo** [comment]
Looks like I disabled it during debugging and forgot to re-enable it, my bad.

**Comment by gizmocuz** [comment]
No worries! Should work again in beta 14318

**Comment by pipiche38** [comment]
no issues at all, this is also why we have a dev and stable

**Comment by Smanar** [comment]
Nice, thx all.

**Comment by averter** [comment]
> It seems only with Python (dzVents) you can 'set' the timeout... it is a variable only in that framework. As you can see in the webserver code that returns the timeout as a JSON variable, it is based on the hardware timeout. It is also not a variable inside the database
> 
@gizmocuz Can you please elaborate on how to set havetimeout to true? I am on [an errand](https://www.domoticz.com/forum/viewtopic.php?p=306037#p306037) trying to change it via json using a bash script, but python would be just fine as well. Thanks

**Comment by gizmocuz** [comment]
@averter , the timeout was not meant to be for switches as they do not change regularly like a temperature sensor.
In the application settings (Other), you will have a Sensor timeout (default 60 seconds)
That's global for all sensors, not lights/switches
So, what you are trying to do is not possible.

**Comment by averter** [comment]
> @averter , the timeout was not meant to be for switches as they do not change regularly like a temperature sensor. In the application settings (Other), you will have a Sensor timeout (default 60 seconds) That's global for all sensors, not lights/switches So, what you are trying to do is not possible.

Well, it was worth a try. Thanks!
