### ISSUE TITLE
Problem with device Thermostat SetPoint in plugin

### ISSUE THREAD

**Issue by turin400** [domoticz/domoticz#5229]
hello, I'm having problems with the beta versions of domoticz I have a plugin (which I attach) that works correctly in the stable version.
The plugin creates two devices, a switch and a setpoint thermostat. So far everything is ok, but when I change the value of the setpoint another device is created.
In addition, the switch called unit 1 stops working.

![Captura de pantalla de 2022-05-06 19-26-16](https://user-images.githubusercontent.com/42274403/167192415-9d6e2320-e342-4d61-a34a-00e6ee833161.png)
![Captura de pantalla de 2022-05-06 19-28-39](https://user-images.githubusercontent.com/42274403/167192492-35596691-c5ea-48f3-8b96-ba45f5476a7a.png)
![Captura de pantalla de 2022-05-06 19-28-11](https://user-images.githubusercontent.com/42274403/167192550-a9470d5e-436a-4711-8f61-cfbb2b494eb3.png)

[plugin.zip](https://github.com/domoticz/domoticz/files/8642634/plugin.zip)

I don't know if I'm doing something wrong.
Regards and thanks for everything.

**Comment by kiddigital** [comment]
The Beta has significant changes in its Python support trying to support the latest 3.9, 3.10 and above version of Python.

Please check the forum for more details and threads on this topic.

Might be a good idea to start a topic for your issue telling what does not work anymore for your plugin which does work with the stable.

**Comment by turin400** [comment]
@kiddigital, I also believed that it could be from the updates of Python's stable ABI but this happened in version 14221 and the plugin works correctly in version 14285. I have the problem in the **Thermostats device** and from version 14285 several important changes were made in this functionality.

**Comment by akamming** [comment]
@kiddigital  

This issue is introduced somewhere between latest stable and latest beta (found on beta 14318 on a pi4 buster. Default Domoticz installation). I have a plugin which worked ago for a very long time, but now has the same issue after upgrading to latest beta.

it is very simple. On stable you can update a setpoint using
`Devices[Unit].Update(nValue=int(Level), sValue=str(Level))
`

alle works fine (the setpoint is just updated, exactly how it should be)

however  when i update a setpoint device using the same code  after upgrade to beta the resulting behaviour is that not only the setpoint device is updated, but a setpoint device is created instantly as well with UnitID 1, having the same updated value:
![image](https://user-images.githubusercontent.com/30364409/169637477-58315f28-388b-4427-bead-8b1fa9780443.png)
 
This has 2 negative side effects:
1. There is garbage in the device list
2. The original device with unitID 1 is no longer usable... (in my case breaking the functionality of the plugin)

fyi: The devices were created using the following code:
```
def CreateSetPoint(SensorName,UnitID,DefaultValue):
    if not (UnitID in Devices):
        Debug("Creating setpoint "+SensorName)
        Domoticz.Device(Name=SensorName, Unit=UnitID, Type=242, Subtype=1, Used=1, Image=15).Create()
        Devices[UnitID].Update(nValue=int(DefaultValue), sValue=str(DefaultValue))

```
my full code can be found [at this link](https://github.com/akamming/Domoticz_Thermostate_Plugin)

**Comment by akamming** [comment]
Hi,

to reproduce easily i adjusted the baseplugin  sample to just do the following
1. Create an On/Off switch
2. Create a Setpoint
3. add the code to change the values of those 2 devices.

After you  change the setpoint using this plugin, you will see the following bug
1. An "Unknown" device of type Setpoint is created
2.  Which conflicts with the switch (both have UnitID 1) so it no longer works.

```
# Basic Python Plugin Example
#
# Author: GizMoCuz
#
"""
<plugin key="SetPointTester" name="Setpointtester" author="akamming" version="1.0.0" wikilink="http://www.domoticz.com/wiki/plugins/plugin.html" externallink="https://www.google.com/">
    <description>
        <h2>Plugin Title</h2><br/>
        Overview...
        <h3>Features</h3>
        <ul style="list-style-type:square">
            <li>Feature one...</li>
            <li>Feature two...</li>
        </ul>
        <h3>Devices</h3>
        <ul style="list-style-type:square">
            <li>Device Type - What it does...</li>
        </ul>
        <h3>Configuration</h3>
        Configuration options...
    </description>
    <params>
    </params>
</plugin>
"""
import Domoticz
#from Domoticz import Devices, Parameters

def CreateSetPoint(SensorName,UnitID,DefaultValue):
    if not (UnitID in Devices):
        Domoticz.Device(Name=SensorName, Unit=UnitID, Type=242, Subtype=1, Used=1, Image=15).Create()
        Devices[UnitID].Update(nValue=int(DefaultValue), sValue=str(DefaultValue))

def CreateOnOffDevice(SensorName,UnitID,DefaultValue):
    if not (UnitID in Devices):
        Domoticz.Device(Name=SensorName, Unit=UnitID, TypeName="Switch", Used=1).Create()
        nv=0
        if DefaultValue.lower()=="on":
            nv=1
            Devices[UnitID].Update(nValue=nv, sValue=str(DefaultValue))

class BasePlugin:
    enabled = False
    def __init__(self):
        #self.var = 123
        return

    def onStart(self):
        Domoticz.Log("onStart called")
        CreateOnOffDevice("DummyOnOffSwitch",1,"on")
        CreateSetPoint("Dummy Setpoint",2,20)

    def onStop(self):
        Domoticz.Log("onStop called")

    def onConnect(self, Connection, Status, Description):
        Domoticz.Log("onConnect called")

    def onMessage(self, Connection, Data):
        Domoticz.Log("onMessage called")

    def onCommand(self, Unit, Command, Level, Hue):
        Domoticz.Log("onCommand called for Unit " + str(Unit) + ": Parameter '" + str(Command) + "', Level: " + str(Level))

        if Unit==1:
            #Handle Switch
            NewValue=0
            if Command=="On":
                NewValue=1
            Devices[Unit].Update(nValue=NewValue, sValue=Command)

        if Unit==2:
            #Handle SetPoint
            if Devices[Unit].sValue=="" or float(Devices[Unit].sValue)!=float(Level):
                Devices[Unit].Update(nValue=int(Level), sValue=str(Level))



    def onNotification(self, Name, Subject, Text, Status, Priority, Sound, ImageFile):
        Domoticz.Log("Notification: " + Name + "," + Subject + "," + Text + "," + Status + "," + str(Priority) + "," + Sound + "," + ImageFile)

    def onDisconnect(self, Connection):
        Domoticz.Log("onDisconnect called")

    def onHeartbeat(self):
        Domoticz.Log("onHeartbeat called")

global _plugin
_plugin = BasePlugin()

def onStart():
    global _plugin
    _plugin.onStart()

def onStop():
    global _plugin
    _plugin.onStop()

def onConnect(Connection, Status, Description):
    global _plugin
    _plugin.onConnect(Connection, Status, Description)

def onMessage(Connection, Data):
    global _plugin
    _plugin.onMessage(Connection, Data)

def onCommand(Unit, Command, Level, Hue):
    global _plugin
    _plugin.onCommand(Unit, Command, Level, Hue)

def onNotification(Name, Subject, Text, Status, Priority, Sound, ImageFile):
    global _plugin
    _plugin.onNotification(Name, Subject, Text, Status, Priority, Sound, ImageFile)

def onDisconnect(Connection):
    global _plugin
    _plugin.onDisconnect(Connection)

def onHeartbeat():
    global _plugin
    _plugin.onHeartbeat()

    # Generic helper functions
def DumpConfigToLog():
    for x in Parameters:
        if Parameters[x] != "":
            Domoticz.Debug( "'" + x + "':'" + str(Parameters[x]) + "'")
    Domoticz.Debug("Device count: " + str(len(Devices)))
    for x in Devices:
        Domoticz.Debug("Device:           " + str(x) + " - " + str(Devices[x]))
        Domoticz.Debug("Device ID:       '" + str(Devices[x].ID) + "'")
        Domoticz.Debug("Device Name:     '" + Devices[x].Name + "'")
        Domoticz.Debug("Device nValue:    " + str(Devices[x].nValue))
        Domoticz.Debug("Device sValue:   '" + Devices[x].sValue + "'")
        Domoticz.Debug("Device LastLevel: " + str(Devices[x].LastLevel))
    return

```

**Comment by gizmocuz** [comment]
I thought with the latest code we did not use 'unit' anymore but DeviceID/Type/Subtype or the IDX value ?

**Comment by dnpwwo** [comment]
@gizmocuz ,

The original Plugin Framework continues to only use 'Hardware\Unit' for backwards compatibility purposes and therefore limits plugins using it to 256 Devices.

The Extended Plugin Framework now uses 'Hardware\DeviceID\Unit' which effectively allows for unlimited Devices.  This aligns well to modern technologies such as Z-Wave and Zigbee.

@akamming 

Thanks for making a demo plugin, makes things so much easier :)

Anyway, on to the issue itself.

There must have been a change in the RXMessage functionality because plugin SetPoint commands are now run through this which has 2 impacts in 'decode_Thermostat':
1. It rebuilds the DeviceID using set logic which yields one less leading zero in this case (line 10063)
2. It uses a function called 'UpdateValue' to process the update which, rather than failing, creates Devices that are not found.

The error here is that a plugin device is being subjected to non-plugin update logic so unexpected things are happening.  In fact the new device is created before the plugin 'onCommand' callback runs (that updates the Device in the sample plugin).

I suspect the behavior changed on March 22nd, 2022 because there were some Set Point specific changes in this area but the fix seems straightforward, 'MainWorker::SetSetPointInt' should return after submitting the plugin command (line 12673).

Thoughts?

**Comment by akamming** [comment]
@dnpwwo 
I can confirm i see this "one less leading zero" in the deviceID as well: both in Demo plugin as well as in the actual plugin which is suffering from this issue..

i don't know the code well enough to say anything about whether this is the correct fix, but if you can tell me which line in which file to change to what i can  easily run a test to see if the fix works.. (if you have a PR i can also test before merging...) 

thx for taking a look at this!!

**Comment by dnpwwo** [comment]
I've pushed the fix for this so you can try it out.  Looked fine in my testing.

**Comment by akamming** [comment]
Hi,

just tested this commit:  https://github.com/domoticz/domoticz/commit/191d054e0e58c1c9af4eeb07e416c3b6b2b319be 

the issue is solved on my system!!!

muchos gracias!!

**Comment by turin400** [comment]
I haven't been able to test it yet because I have an rpi and there is no version 14353 for arm.
When I install it, I'll let you know.
Thanks for everything.

**Comment by akamming** [comment]
> I haven't been able to test it yet because I have an rpi and there is no version 14353 for arm.
> When I install it, I'll let you know.
> Thanks for everything.

You can build from source using as described [here ](https://www.domoticz.com/wiki/Build_Domoticz_from_source)

**Comment by jgaalen** [comment]
When could this be merged? I'm having this issue on my plugin as well and it is pretty nasty

**Comment by gizmocuz** [comment]
@jgaalen , it seems it is already working in the beta version ?

**Comment by jgaalen** [comment]
Beta build 14352 his this exact same issue for me. I have a python plugin for a heatpump. As soon as I change the setpoint via web, a Unit 1 Unknown device is created and the initial unit 1 device isn't working anymore. Workaround is to completely remove the hardware, add it again and never touch the setpoint

**Comment by akamming** [comment]
@gizmocuz  i checked, in the beta code it is fixed, so when i compile domoticz myself using the latest code indeed it works.

However the rpi downloads are still from june 3rd, and don't seem to include the latest sourcecode... that might explain why @jgaalen  still has this issue also in latest beta

**Comment by jgaalen** [comment]
I'm not using a rpi, but linux install

**Comment by gizmocuz** [comment]
I compiled all platforms , could you test again please?

**Comment by jgaalen** [comment]
Updated the just released new beta version and it now worksl No new 'Unknown' device. Thanks a lot guys!!

**Comment by gizmocuz** [comment]
Thanks for the feedback! (And cheers to all here!)
