### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by MatthieuF44** [domoticz/domoticz#5240]
Hi,

I observed that we can't export to csv values of logs when sensor is type "general/text" or "general/alert".
I have to get this solution for analyzing values with Excel.

Could you implement this option ?

Kind regards.

**Comment by waltervl** [comment]
The current csv export in graphs is there because the library to create the graphs has a build in function to export to csv and excel.
To create something for non graph sensors will probably need some major change. So unlikely to be executed until a programmer feels the same need.

There is another option to create a dzvents script that will export the data in a csv file. See for example the forum next topic.
https://www.domoticz.com/forum/viewtopic.php?t=30725

I will close this issue.
