### ISSUE TITLE
Counter incremental - daily total incorrect

### ISSUE THREAD

**Issue by Gert05** [domoticz/domoticz#5270]
I have noticed that the daily total for counter incremental is computed/displayed incorrectly.
See attached graph. Thu 3 occurred vs 2 displayed, Fri 3 vs 2, Sun 4 vs 2. Mon (1 vs 1) is correct so far.
Raspberry Pi, running 2021.1 build 14105.

![image](https://user-images.githubusercontent.com/12745187/177129892-f1785e1b-779f-40e5-989a-3cf365dd96b1.png)

**Comment by gizmocuz** [comment]
That seems quite odd.
Could you add a manual counter incremental and use the json API to add some test values and test these ?

**Comment by Gert05** [comment]
Thanks for the quick reply.
All increments come from Node-Red, use domoticz/in and have a payload of {"command": "udevice", "idx":219, "svalue":"1"}.
If I were to manually increment the counter I would use the same command through MQTTBox (and probably get the same result).

**Comment by gizmocuz** [comment]
Best to test.... seems to me maybe node-red could not make a correction to the domoticz and could not deliver a update
Pretty sure the counter incremental is working correctly
That is why testing manually is important.... like we say in the Netherlands "Meten is weten!"

**Comment by Gert05** [comment]
Umm, but I don't see the point. It's not that Domoticz is not receiving the increments (upper half of the graph), it's that there is a discrepancy within Domoticz between the upper half and the lower half... That fully resides within Domoticz and (in my humble opinion) has nothing to do with Node-Red.

**Comment by gizmocuz** [comment]
Sorry about that! I have to look better. I thought that the counting was incorrect.
It is the daily values that are incorrect....
I have a look at this

**Comment by gizmocuz** [comment]
Okey I debugged the routine that creates the daily values, this one is correct

Now I'm debugging the routine that generates the day chart (from the 5 minute intervals), I suspect here 'could' be an issue, but it depends on how you look at this, but I modified the code so behaves like below:

For example the data in the 'meter' table:

```
0	2022-07-06 07:40
6	2022-07-06 07:45
9	2022-07-06 07:50
12	2022-07-06 07:55
14	2022-07-06 08:00
19	2022-07-06 08:05
22	2022-07-07 07:50
```

And the last counter value from the DeviceStatus table (sValue) = 31

As you see I have a big time cap between 2022-07-06 08:05 and 2022-07-07 07:50, let's say no data was received between that time

The day chart renders per hour

If you call the below API call (with the correct ip/idx value) you should see the values for the day chart

`http://127.0.0.1:8080/json.htm?idx=8095&range=day&sensor=counter&type=graph`

currently my modified code outputs:

```
		{
			"d" : "2022-07-06 07:00",
			"v" : "12"
		},
		{
			"d" : "2022-07-06 08:00",
			"v" : "5"
		},
		{
			"d" : "2022-07-07 07:00", == last value = sValue - last meter table value (31-22)
			"v" : "9"
		}}
```

I think this is correct .... but maybe we should increment the hour ? the first value 12 is the count between 07:00 and 08:00

But bare in mind, that if the last value in the 'meter' table is 22, and no data has been received (meaning the sValue in the DeviceStatus table also equals 22) the value for '2022-07-07 07:00' will be 0 (because 22-22 = 0)

If you think the above is correct, let me know and I will push the modified code

**Comment by gizmocuz** [comment]
I made a PR if you would like to compile/test the code

https://github.com/domoticz/domoticz/pull/5272

**Comment by Gert05** [comment]
Thanks for your efforts. I'm afraid I don't follow your example, especially taking sValue into account. I have followed the API call:

```
                {
			"d" : "2022-07-05 00:00",
			"v" : "0"
		},
		{
			"d" : "2022-07-05 05:00",
			"v" : "2"
		},
		{
			"d" : "2022-07-05 06:00",
			"v" : "1"
		},
		{
			"d" : "2022-07-05 10:00",
			"v" : "1"
		},
		{
			"d" : "2022-07-05 11:00",
			"v" : "0"
		},
		{
			"d" : "2022-07-08 13:00",
			"v" : "1"
		},
		{
			"d" : "2022-07-08 14:00",
			"v" : "0"
		},
		{
			"d" : "2022-07-09 11:00",
			"v" : "1"
		},
		{
			"d" : "2022-07-09 12:00",
			"v" : "0"
		},
		{
			"d" : "2022-07-09 13:00",
			"v" : "0"
		}

```
Funny thing is the daily value for 07-05 is correct, but the ones for 07-08 and 07-09 aren't (they are displayed as 0).
Would love to test the PR - is there a way do directly update to that on a Pi or do I need to go through a compile cycle?

**Comment by gizmocuz** [comment]
A counter should always increment and in your shortlog I see values with 0 that seems quite odd.
(I assume these are the values from the short log ?)

**Comment by averter** [comment]
Hello, I'm experiencing exactly the same issue with my dummy custom counter

![image](https://github.com/user-attachments/assets/c3e3896d-4079-441a-974b-89e333b2adea)

although the value that is being sent to the device is correct and shown in the left bottom corner
![image](https://github.com/user-attachments/assets/f85e252e-1186-4886-9bab-500c29096da6)

**Comment by averter** [comment]
It might have to do with the way how domoticz rounds up small numbers into integers, i.e., it is being assumed that the meter will contain large values. If so, this this assumption should probably be lessened whenever the type of meter is set to custom (in contrast to "water", "energy", "gas", etc.)?
