### ISSUE TITLE
Issue with blinds (DC106 and RFY) since beta 14414 and 14420

### ISSUE THREAD

**Issue by joost12345** [domoticz/domoticz#5282]
Running: 
Version: 2022.1 (build 14420)
Build Hash: 81ce5798b
Compile Date: 2022-07-22 12:02:09
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]

Since last 2 betas (14420 and 14414) there's a problem with the blinds (DC106).
From now OPEN is CLOSE and CLOSE is OPEN....

**Comment by gizmocuz** [comment]
@joost12345 , are you using zwave or zigbee ? Do you configured blind-inverted or normal blinds ?
There have been made some recent changes that should solve a lot of blind issues

**Comment by gizmocuz** [comment]
@joost12345 , could you delete the blind and restart the MQTT hardware to have it detected again ?

**Comment by joost12345** [comment]
> 

@gizmocuz I'm using a 433 Mhz Dooya motor (RFXCOM) configured as normal blinds

**Comment by joost12345** [comment]
> @joost12345 , could you delete the blind and restart the MQTT hardware to have it detected again ?

Not at the moment, I'm on the way to the 4-Daagse ;)

**Comment by remco-k** [comment]
Same issue here with build 14420. Open and close are swapped using a virtual switch with type 'Blinds' selected.
Reverted back to a previous build I started using Domoticz on; 14352; and its good again.

**Comment by CyrilB1531** [comment]
@remco-k and @joost12345  : It was the goal of the fix. Before this fix, with MQTT blinds, even if your device is properlly wired, you have to set blinds as inverted one but it won't work perfectly. With the fix, you have to set blinds as non inverted one and Open should be 100% and Close 0%. 
There is no need to remove your blinds devices, just changing blind types.

**Comment by joost12345** [comment]
@CyrilB1531 I changed the Blinds DC106 (Roller blinds) from "Blinds" to "Blinds Inverted" and now it's working fine.
I also have some Roller shutters (RFY blinds) and these should not be changed to "Blinds Inverted".

I also have to change some code in my scripts:

Old:
```
// Close: if it is dark and status is Stopped
elseif ((Status($idx94) == 'On') AND Status($idx389) == 'Stopped') {
	SwitchDevice($idx389,'On');
}
```

New:

```
// Close: if it is dark and status is Stopped
elseif ((Status($idx94) == 'On') AND Status($idx389) == 'Stopped') {
	SwitchDevice($idx389,'Off');
}
```

But the new code is more logic..

**Comment by CyrilB1531** [comment]
@joost12345 thanks for your feedback I will check that

**Comment by joost12345** [comment]
@CyrilB1531 , please see the picture below

**Blinds:**
If I press the "Open" button, then screen will be opened
![roller shutter](https://user-images.githubusercontent.com/35629573/180598836-bab09653-88fb-4b35-aa64-c84b0f2e91ad.png)

**Blinds Inverted:**
If I press the "Open" button, then screen will be closed
![roller shutter1](https://user-images.githubusercontent.com/35629573/180598978-fb25d69d-6b96-4e6a-a59e-e113a61ec46e.png)

But both (blinds or blind inverted) get status "Closed" when I click on the Open button

**Comment by CyrilB1531** [comment]
@joost12345 could you please refresh your browser cache? sometimes cache is not refreshed and you have this behaviour :(

**Comment by joost12345** [comment]
@CyrilB1531 I refreshed my browser cache and now I still have strange (but different) behaviour:

**DC106 Blinds:**
Pressing Close button | Roller blinds will go down | Status is Open | Command is Off
![3](https://user-images.githubusercontent.com/35629573/180600715-129e664f-1df1-446b-a213-1d56ac42cae9.png)

**DC106 Blinds Inverted:**
Pressing Open button | Roller blind will go down | Status is Closed | Command is Off
![1](https://user-images.githubusercontent.com/35629573/180600653-a05380b3-866c-4fc2-bc54-2dcc2398c584.png)


**RFY Blinds:**
Pressing Close button | Roller blinds will go up | Status is Closed | Command is Off
![4](https://user-images.githubusercontent.com/35629573/180600830-ab3b3a8b-cfff-4c83-bfc7-e9dd6daed76c.png)

**RFY Blinds Inverted:**
Pressing Open button | Roller blinds wil go up | Status is Open | Command is Off
![2](https://user-images.githubusercontent.com/35629573/180600656-bc3bd544-c9c8-4cb1-bdd4-be42b89e666e.png)

**Comment by gizmocuz** [comment]
Please note there is no browser cache in the beta version for quite some time now (~ half year and up)

**Comment by gizmocuz** [comment]
@CyrilB1531 , another strange thing, the open/close icons/buttons seams swapped
The idea is to always have open on the left, closed on the right, but when you have 'inverted' the commands should change, still the visual representation should stay the same for the user.

The open/close icons are changed/swapped here:

![image](https://user-images.githubusercontent.com/2265299/180602195-a4afa5ee-4634-4d26-81d3-6b44bd2e247c.png)

**Comment by CyrilB1531** [comment]
I fix all issues (open / close on DC106 / RFY and buttons swap) in PR #5284 5284

**Comment by gizmocuz** [comment]
PR has been merged and a new beta version is available (14432)

**Comment by FredWst** [comment]
Hi,

Action are correct but title text is still inverted.

Fred

**Comment by gizmocuz** [comment]
@FredWst , thanks for the feedback, I assume the tooltip, or when you press the icon the popup ?

**Comment by SargonofAssyria** [comment]
This morning I updated to version 14420 and found out that my Somfy roller shutters (type RFY) where changed in the GUI.
I found this issue, and now upgraded to version 14432. But still the issue is not fixed compared to pre 14420 versions, which where working fine for years. Also inverting does not solve the problem. I control the shutters with dzVents which opened the shutters on version 14420 as they should.
Text, icon and action are inverted on the GUI.

**Comment by CyrilB1531** [comment]
@SargonofAssyria I will check that

**Comment by FredWst** [comment]
@gizmocuz tooltip is ok (mouse over button), text box not ok (upper right side) (rfy blind somfy)

dummy blind objet still inverted : tooltip ok, text box  ok but action inverted

PS: i'm not using MQTT autodiscover.

**Comment by CyrilB1531** [comment]
@FredWst Hello, I'm on it

**Comment by joost12345** [comment]
@CyrilB1531 I updated to 14435 a couple of mins ago:

From the "Switches" tab everything works fine now but from the Dashboard tab not!

**DC106 Blinds Inverted:** 
- First press "Open" -> blinds goes up
- Press "Stop" -> blind stops
- Press "Open" again -> blinds goes down
- Press "Stop" -> blind stops
- Press "Close" -> blinds goes up

**RFY Blinds Inverted:**
- Press "Open" -> blinds goes down
- Press "Stop" -> blind stops
- Press "Close"-> blinds goes up

**Comment by SargonofAssyria** [comment]
Looking at the commits after version 14432 from today there is no change (yet) in the Blinds.
So watch for the right commit(s).

**Comment by joost12345** [comment]
> @CyrilB1531 I updated to 14435 a couple of mins ago:
> 
> From the "Switches" tab everything works fine now but from the Dashboard tab not!
> 
> **DC106 Blinds Inverted:**
> 
> * First press "Open" -> blinds goes up
> * Press "Stop" -> blind stops
> * Press "Open" again -> blinds goes down
> * Press "Stop" -> blind stops
> * Press "Close" -> blinds goes up
> 
> **RFY Blinds Inverted:**
> 
> * Press "Open" -> blinds goes down
> * Press "Stop" -> blind stops
> * Press "Close"-> blinds goes up

@gizmocuz , @CyrilB1531 .
In beta 14438 are Open and Close swapped again and the issue from Dashboard tab (see 2 posts above) still exists.

**Comment by CyrilB1531** [comment]
I will check that

**Comment by sebastienfr** [comment]
Version 

Version: 2022.1 (build 14438)
Build Hash: de8c92ec5
Compile Date: 2022-07-28 13:01:01
dzVents Version: 3.1.8
Python Version: None

Is fine again for my fibaro shutter.

**Comment by joost12345** [comment]
> I will check that

BTW, the RFY blinds work fine, the DC106 blinds not.

**Comment by gizmocuz** [comment]
Maybe it is wise to revert the patches for the blinds until we have one working one ?

**Comment by CyrilB1531** [comment]
Yep, I think it should be safe. I cannot work on it for 2 weeks

**Comment by gizmocuz** [comment]
I'm afraid reverting ain't that simple because of all the changes and it's almost working correctly. I will try to look at the remaining issues... 

@joost12345, seems the RFY goes OK with inverted on the dashboard? open=close and close=open, seems inverted
But you do not need to use inverted RFY, if you do, you have connected some wires wrong

**Comment by JurgenLB** [comment]
In my experience the inverted RFI are used for solar screens. The normal RFI is for the blinds/shutter

**Comment by gizmocuz** [comment]
Hmmm inverted should not be necessary in normal conditions

Is it possible to try beta 14440 ... made some changes, hope for the better (hope DC106 is working ok as well now)

**Comment by joost12345** [comment]
@gizmocuz I updatet to beta 14440. RFY and DC106 work fine now (from tab Dashboard and Switches)!
Also icons and commands (on/off) are fine.
Thanks!

ps. I switched back to devices to non-inverted.

**Comment by SargonofAssyria** [comment]
Today I updated to 14440. The Somfy RFY seems OK. The zigbee TS0601 ( https://www.zigbee2mqtt.io/devices/TS0601_cover.html#tuya-ts0601_cover ) works OK too, but has something strange.
![01 08 2022_09 38 03_REC](https://user-images.githubusercontent.com/24824113/182098108-5d9a93ac-5d65-42b0-b5c0-34eeb5f1b76a.png)
I restarted domoticz after the update and only tested the 'RolgordijnRechts' with some Open/Close and Up/Down movements.
And then set it back to 20%. The icons differ in state. What should be the right state? Is 0% to 99% Open, or is 1% to 100% Closed?

**Comment by SargonofAssyria** [comment]
Found a problem with the Somfy RFY together with dzVents.
When dzVents scipts opens the rollershutter with 'open()' it opens the rollershutters.
In the script I check if the shutter is already open so it does not have to open an already opened rollershutter.
`                    if dz.devices("Voorraam rolluik").state ~= "Open" then
                        dz.devices("Voorraam rolluik").open()
                    end
`
The problem lies in the fact that the state in dzVents is all the time 'Closed'
If I do and 'http://192.168.2.xxx:8080/json.htm?type=devices&rid=198' I see that the status is 'Open' and the rollershutter is in real live open.
So it looks that dzVents gets reversed status.

**Comment by sebastienfr** [comment]
All the same here with fibaro, shutters via blocky all inverted but works from web interface. Also Pilot app doesn't work.

**Comment by gizmocuz** [comment]
What does the event editor status display say?
What happens when you log the status in your script ?

**Comment by sebastienfr** [comment]
Ok I just checked the status are fine, pb is about the percentage which are now inverted.

Looks line the Pilot iOS App os also a bit lost, I have to push the buttons twice to close my shutters. 

![image](https://user-images.githubusercontent.com/5099537/185153525-35cbd73b-562a-4ff5-98b2-9d9400f64b4c.jpeg)

**Comment by SargonofAssyria** [comment]
@gizmocuz Sorry forgot to mention here that all my issues are resolved concerning RFY rollershutters and zigbee blinds. The only problem left for me is here: https://github.com/domoticz/domoticz/issues/5302 I think it is related.

**Comment by gizmocuz** [comment]
I just logged the state of a blind and it reports indeed correctly , the level is not updated for open/close or inverted I will check this
But @SargonofAssyria , the state IS reported just fine and is for sure not always closed

**Comment by SargonofAssyria** [comment]
Yep state is good and slider works correctly, but the display is always 'full'

**Comment by gizmocuz** [comment]
Seems like pressing a second time on open/close displays the level correct

**Comment by SargonofAssyria** [comment]
In my case the slider always jumps to full. I can click on the slider, and it displays for a second the right percentage, but then jumps to 'full' (100%) but the **bulb** stays correctly at the set level. Sorry mix-up issues.

**Comment by gizmocuz** [comment]
@sebastienfr , the issue was caused in the dzVents runtime. I have made a patch and new beta's are building but that could take a while....
I am not a LUA guru, but my patch seems valid

see:
https://github.com/domoticz/domoticz/commit/19f8c41da560a7e5d84b9cd084f7759f708f8f32

I now checked dzVents and logged the level and state of the blinds for all types and they all report correctly now

Edit: beta 14456 is now available

**Comment by sebastienfr** [comment]
Hello, the status and percentage are now fine, but there is still an issue with the scripts, even on domoticz HMI, when you put 10% of the blinds, the display switches quickly to 90% and stops at the right 10% but there is a glitch and it still prevents the scripts to work properly with percentages. My shutters closed instead of opening this morning.

**Comment by gizmocuz** [comment]
@sebastienfr , first try with a dummy blind. when you set it to 10% in the gui, there should be no glitch
Then add a dummy switch and add a dzVents script like

```
local TEST_BLIND = 26
local RolluikLinks = 23

return {
	on = {
		devices = {
			TEST_BLIND
		}
	},
	logging = {
		level = domoticz.LOG_DEBUG,
		marker = 'blindstest',
	},
	execute = function(domoticz, item)
 	        domoticz.devices(RolluikLinks).setLevel(10)
 	end
}

```

There is no glitch

**Comment by waltervl** [comment]
Can you check this issue again please as there are a lot of changes recently that could have fixed this issue.

**Comment by SargonofAssyria** [comment]
See: https://github.com/domoticz/domoticz/issues/5330

**Comment by sebitop** [comment]
Hi,

I'm following this discussion as I also have an issue on my blinds since beta update.
I'm on 14498 and it seems that the On/Off commands have been inverted

I temporarily solved the issue by setting Blinds instead of Blinds inverted in the device properties and using CLOSED instead of OFF in the LUA code as if I use OFF in the code blinds open

Now the problem is on the groups, as I have a group managing my blinds which close all when you click OFF. Now it's impossible to make it work, I have to click ON on the group to close my blinds...

my modules are basics 433mhz ON/OFF using RFXCOM Lighting 6 protocol

any ideas to solve this ?

thanks !
sebastien

**Comment by sebitop** [comment]
Hi,

I'm following this discussion as I also have an issue on my blinds since beta update.
I'm on 14498 and it seems that the On/Off commands have been inverted

I temporarily solved the issue by setting Blinds instead of Blinds inverted in the device properties and using CLOSED instead of OFF in the LUA code as if I use OFF in the code blinds open

Now the problem is on the groups, as I have a group managing my blinds which close all when you click OFF. Now it's impossible to make it work, I have to click ON on the group to close my blinds...

The issue seems to come from the fact that now CLOSED=ON 

my modules are basics 433mhz ON/OFF using RFXCOM Lighting 6 protocol

any ideas to solve this ?

thanks !
sebastien

**Comment by gizmocuz** [comment]
@sebitop , I never tested with blinds in a group, but I just did
When adding a normal (not inverted or with percentage) to a group, And I press the 'On' button, I am expecting the blinds should close
This seems to work, same as if I press the OFF button, the blinds seems to close

**Comment by sebitop** [comment]
@gizmocuz thanks for your reply.

I don't get your point as you mentioned "close" twice :)
but well this is where I think something changed:

in the previous versions the blinds were closing when I pressed OFF in the group which was (at least for me :) ) logical to have CLOSE= OFF and OPEN= ON

now after the update it's the contrary I need to press OFF to get them OPEN so I believe something as been changed (I was using blinds and groups since more than 5 years) and I have to admit that it's a bit confusing :)

Maybe is there another way to make a group and get back the logic of OPEN=ON ? or to group blinds ?

thanks !
sebastien

**Comment by sebitop** [comment]
Hello @gizmocuz 

To follow up on this topic could to tell us or just confirm me that the status ON/OFF has been inverted in the update ?

thanks
sébastien

**Comment by gizmocuz** [comment]
@sebitop , not sure if it changed, but yes OFF = Open and On = Close, for lights Off = Off and On = On

**Comment by gizmocuz** [comment]
Closing issue as it's about multiple issue where (if not all) issues should be solved by now
