### ISSUE TITLE
Set last sat/hue/bri on Hue lights if lights switched off/on from wall switch

### ISSUE THREAD

**Issue by arjanwaard** [domoticz/domoticz#530]
Is this something that people would like ? Should not be to difficult to implement.

**Comment by GravityRZ** [comment]
i believe this is already working that way in my situation
if i turn on 5 of my Hue lights(triggered by S2 switch and calling a script) the go to the last position they were at.

i call this function and can easily toggle my hue lights on and off and they goto the last setting they were at
curl -s "http://192.168.1.50:8084/json.htm?type=command&param=switchlight&idx=11&switchcmd=Toggle"

**Comment by arjanwaard** [comment]
Ok, but were the Hue lights without power ? If the Hue lights are on a normal wall switch and you switch off the lights with this wall switch they are without power. Switching on the wall switch turns on the Hue lights on full brightness and white.

**Comment by GravityRZ** [comment]
Hi Arjan,
ok I understand what You mean.

that would be nice indeed.
this setting is available in the regular fibaro/qubino module but apparently Phillips did not think of it to put it in the hub(where it should be)

for me however it will not be a problem

if the lights loose power(because of outage) al the power is gone.
when the power comes back my synology will start up again and initially the lights will go out which i like for safety reasons.

**Comment by wmn79** [comment]
I think it would be nice, If you have people in your household or visiting who turn of the light with the traditional switch. 

What also would be a nice to have is if the sValues for Hue lights could also be used in events and scripts, for example to use the dim state of a bulb or the hue value and brightness. Not sure how difficult that is to implement though.

**Comment by gizmocuz** [comment]
You could also replace that wall switch, put a KaKu switch in there, not connected to the visual light
when the switch action is received in domoticz, it will turn on/off the hue with the right color ?
And i am not sure if you can catch this behavior you described above ? But... would be nice
