### ISSUE TITLE
Timer buttons on switches tab not visible correctly in Internet Explorer

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#531]

**Comment by gizmocuz** [comment]
Tested for this bug with two different systems with the edge browser, and no problem
It could have been a browser cache issue, waiting users response

**Comment by gizmocuz** [comment]
Problem seems solved after a restart of Domoticz

**Comment by IBlackI** [comment]
I have tested this bug on two different systems and can confirm the timers don't appear on Internet Explorer. Edge is not internet explorer.

**Comment by gizmocuz** [comment]
Tested this (just) again with Edge , and IE 11, and no problem.
Try using chrome

**Comment by IBlackI** [comment]
Tested with IE version 11.420.10586.0 result: ![ie](https://cloud.githubusercontent.com/assets/4059637/16187239/760594de-36cf-11e6-9ed6-3c6d3d2a8944.png)
Tested with IE version 10.0.9200.17607 same result as other IE. 
Tested with Edge version 25.10586.0.0 result: ![edge](https://cloud.githubusercontent.com/assets/4059637/16187240/76083bb2-36cf-11e6-8882-fab3a6d175f4.png)
Tested with Firefox version 47.0 result: ![ff47 0](https://cloud.githubusercontent.com/assets/4059637/16187241/76093dc8-36cf-11e6-8ea1-6a0197f95b7b.png)
Tested with IE on windows phone 8.1: ![wpie](https://cloud.githubusercontent.com/assets/4059637/16187376/3bafb9bc-36d0-11e6-842e-ca2776b46361.jpg)

So this is especially a problem when trying to change the timers while on a mobile device (tablet or phone) because there is no other browser available.

**Comment by gizmocuz** [comment]
You seem to report a totally different issue that stated in this topic !!!????
This topic is about the timer BUTTON not visible on the switches tab!
You are now talking about the timer entries when you are editing the timers

**Comment by gizmocuz** [comment]
Is this only with HUE switches, or also with normal switches ?

**Comment by IBlackI** [comment]
It seems to be any switch / scene.

**Comment by gizmocuz** [comment]
Dont have this issue with IE11.0.14367 and Firefox 47

**Comment by IBlackI** [comment]
Hmm strange, tried it on all different themes just in case that would be it, but they all didn't display the timers. And its still only IE thats not working.  I am running domoticz on a Raspberry pi 1 let me try and install it on a vm to see if it makes any difference.

**Comment by gizmocuz** [comment]
Themes? Also tried the default theme ?
Else, use chrome/firefox/edge

**Comment by IBlackI** [comment]
Yes tried all the themes.

Timers are working on a clean install of domoticz on ubuntu 14.04, however this was domoticz v3.5262. Upgrading the rasppi1 to v3.5259 instead of 4834.

**Comment by IBlackI** [comment]
Updating from v3.4834 to v3.5259 fixed this problem.
