### ISSUE TITLE
Multi state switch set Level 10 For 1 not working

### ISSUE THREAD

**Issue by cherowley** [domoticz/domoticz#533]
When setting up a lua script with the command:

commandArray['Selector Switch Test']='Set Level 10 For 1' the switch doesn't go off..

**Comment by gaudryc** [comment]
For now, this is not a bug because it is not intended to be managed. There is no default value or previous setted value to allow the Event system to determine which value should be setted after the "FOR" period.

You can use a Blockly event to do :
- set Level 10
- set Level 0 After 1

(You cannot do it in lua because you cannot set two commands for one device in the returning array)

**Comment by cherowley** [comment]
Ah I see, thanks for the info :)

I can't use blockly in this case unfortunately.

What would be ideal is that the selector device could be amended so that the "off" level is the default  state returned to.

This would allow the Off delay to save and work as normal. 
I only tried using a script as the off delay didn't work.

In my situ i'm turning on a tv by pir and then using the off delay it turns it off after 90 seconds of no pir activity. 

I found that using on "FOR" didn't quite give continuous on as it seems to not set to on again until its timed out. There is a minute delay between the off and coming back on which because a modern lcd tv takes  several seconds to come back on makes that way unusable. Even for a light there is a flicker.

Thanks anyways :)

**Comment by gaudryc** [comment]
I'm fixing an Off delay issue (#538)

**Comment by nayrnet** [comment]
you can do it in lua: 
commandArray[1]={['Device']='Set Level 10'}
commandArray[2]={['Device']='Set Level 20 AFTER 30'}

**Comment by gaudryc** [comment]
I will sleep less stupid. (a french joke ;-)

Thank you !

**Comment by gaudryc** [comment]
@cherowley,

The Off delay issue on the selector switch is fixed and the patch will be merged soon. This makes the selector switch goes off automatically after the Off delay (or OnDelay + OffDelay if OnDelay != 0).

**Comment by cherowley** [comment]
Nice 1! Look forward to it being compiled up :) I presume it'll be in a beta?

**Comment by ghost** [comment]
@nayrnet and @gaudryc  thank you both very much! 

Gaudryc's mention that you cannot send two commands for one device made me realize that I had been barking up the wrong tree for hours. I could not get my head around 'On for' and 'Off after'.

I want a light switch to go on for 10 seconds.  I could not use 'On for' because that is specified in minutes (for some reason...).  So I tried to set my light switch to 'On' and then off again in 10 seconds. But could get this to work with first sending 'On' and then sending 'Off after 10'. Now I realize I was trying to put two commands in the same key of the commandArray.  Nayrnet's solution fixed it:

`commandArray = {}
if otherdevices['LightSwitch)'] == 'Off' then
    commandArray[1]={['LightSwitch)']='On'}
    commandArray[2]={['LightSwitch']='Off AFTER 10'}
end
return commandArray`

Sorry if this is not the appropriate place (I'm very new to programming, Lua and Github) but want to send you a big 'thank you'.
