### ISSUE TITLE
MQTT auto discovery and IKEA Tradfri devices

### ISSUE THREAD

**Issue by narel** [domoticz/domoticz#5338]
I recently migrated from Zigbee plugin to MQTT auto discovery. Everything went smoothly but I have an issue with some of IKEA Tradfri devices (switches; light bulbs are OK). They are working with Zigbee plugin, but they are not added to Domoticz via MQTT auto discovery.

I tried with a new device, it was succesfully added to Zigbee2MQTT but not showing on Domoticz (all other devices work great).
I've got:

- LED1837R5, LED1732G11 (and they are OK)
- E1524/E1810, E1743, E1812, E1744 (not showing in Domoticz)

Domoticz version: 2022.1 (build 14498)
Running on Ubuntu 20.04 (x86–64).
zigbee2mqtt version: 1.27.0

**Comment by gizmocuz** [comment]
@narel , is it possible to contact me on Slack ?

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

I just checked the E1743, you should get some devices like a push On and a push Off switch which you can use as activator for a scene/group

**Comment by frepkovsky** [comment]
I'm testing Domoticz MQTT AD and Zigbee2MQTT with only single device - IKEA E1743. It has been discovered successfully by Domoticz - two devices have been added, two switches for action on and off. The devices are working ok, status is updated correctly in Domoticz on every switch on/off action but there are errors "MQTT_Discovery: Invalid/Unhandled data received! <msg data>" logged by Domoticz (during device discovery and on every action). I think this is something that need to fixed in MQTT AD to handle those messages correctly. I can provide you with the logs if needed.

Except Zigbee GW, I have another MQTT AD Client gw configured in Domoticz for Zwave devices (with using Zwave JS UI) and this is working fine, no any errors logged.

Domoticz Version: 2022.1 (build 14519)
Zigbee2MQTT version 1.28.0
Debian Buster on RPI

**Comment by gizmocuz** [comment]
@frepkovsky , can you verify you are using two different topics
- one for the auto discovery (like homeassistant/domoticz) (HA integration settings)
- and your zigbee base topic (zigbee2mqtt) (MQTT settings)

They should not both be the same

Is it possible you can enable debug logging and post some log lines?

**Comment by frepkovsky** [comment]
@gizmocuz , yes exactly, I use different topics for Zigbee2mqtt (topic: zigbee2mqtt) and for Zwave JS UI (topic: homeassistant) and the topics are set accordingly in MQTT AD Client gateways in Domoticz.

Please find attached logs below from normal logging (not in debug mode) when I enable zigbee MQTT AD and try to do switch on/off. If not useful, I can try to collect logs in debug mode but please let me know required verbose level.

[zigbee-mqtt-domoticz.log](https://github.com/domoticz/domoticz/files/9691966/zigbee-mqtt-domoticz.log)

**Comment by gizmocuz** [comment]
Thanks for the logs, they are very helpful

The issues found in the log is because unexpected data is received from the MQTT broker, like message in topics like:
(Assuming homeassistant is your auto discovery prefix)

homeassistant/bridge/info
homeassistant/bridge/devices
homeassistant/bridge/logging
homeassistant/bridge/..... <- many more bridge related messages

Maybe you enabled some additional checkbox/logging?

Then some other unknown MQTT topics were found on topics:

homeassistant/vypinac1/action
homeassistant/901/availability

No idea where they are coming from, but they should not be there

I made some changes in beta 14524, the errors should not appear anymore, but it still might be worth investigating why these messages appear in these topics on your side

**Comment by frepkovsky** [comment]
Thanks gizmocuz for quick reply,

I'm not aware of any specific settings I would apply in Zigbee2MQTT for logging etc. I only set `legacy: false` for the switch device  to disable click event as recommended for E1743 [here](https://www.zigbee2mqtt.io/devices/E1743.html) (but even if I change it to false "unhandled data" error msgs are still logged).

I'm not sure why those additional topics are sent by Zigbee2MQTT, if you think they should not be but the topics are described [here](https://www.zigbee2mqtt.io/guide/usage/mqtt_topics_and_messages.html) so it seems normal.

My discovery topic is set to 'zigbee2mqtt' so correct topics are i.e.:

zigbee2mqtt/vypinac1/action
zigbee2mqtt/901/availability
...

- vypinac1' is friendly name for the switch device and when I do switch on/off the following is published by Zigbee2MQTT (from its logs):
```
MQTT publish: topic 'zigbee2mqtt/vypinac1', payload '{"action":"on","battery":74,"linkquality":49,"update":{"state":"available"},"update_available":true}'
MQTT publish: topic 'zigbee2mqtt/vypinac1', payload '{"action":"","battery":74,"linkquality":49,"update":{"state":"available"},"update_available":true}'
MQTT publish: topic 'zigbee2mqtt/vypinac1/action', payload 'on'
MQTT publish: topic 'zigbee2mqtt/vypinac1', payload '{"action":"off","battery":74,"linkquality":55,"update":{"state":"available"},"update_available":true}'
MQTT publish: topic 'zigbee2mqtt/vypinac1', payload '{"action":"","battery":74,"linkquality":55,"update":{"state":"available"},"update_available":true}'
MQTT publish: topic 'zigbee2mqtt/vypinac1/action', payload 'off'`
```
- 901 is Group ID of 'default_bind_group' created by default by Zigbee2MQTT. Availability is reported for groups so this topic is sent.

**Comment by gizmocuz** [comment]
zigbee2mqtt/vypinac1/action
zigbee2mqtt/901/availability

This is not confirm the MQTT AD protocol

not all errors should be gone now with the latest beta correct?

**Comment by frepkovsky** [comment]
Now upgraded to beta build 14525 and I confirm it is working OK without any errors. Many thanks gizmocuz!
