### ISSUE TITLE
14543: MQTT Auto Discovery - Blinds problems

### ISSUE THREAD

**Issue by ajarzyn** [domoticz/domoticz#5364]
Hello,

I've seen lots of changes regarding blinds.
Thus moved from custom python mqtt plugin to `MQTT Auto Discovery Client Gateway with LAN interface`

Version: 2022.1 (build 14543)
Build Hash: 428f21c3c

Observation:
Blinds were selected as `Blinds + Stop` which I've changed to `Blinds Percentage`

Few problems:

1. Partially opening - It's possible to open partially but the behaviour for bar is erratic. The selector jumps from % I want to set to 0.
2. After `Real life device` stop in the middle Blinds instantly display state `Closed` event thought `Real life device` is set to any % (ex 20%)
3. When Blinds fully opened - state `Closed` is displayed
4. Event's device state is almost always `Off` (only when `real life device` moves the value changes to numeric value)
![gate_estate](https://user-images.githubusercontent.com/18590439/194783502-8bf4a837-bfaa-4284-90da-5a91f925cddf.gif)

**Comment by MarcelBaas** [comment]
Goodmorning, this morning I received another update "build 14549" However since two updated last Saturday evening al my blinds do not respond correct to en open command from the created scenes. The scene should give 50%  some blinds turn 100% other just stay closed. Closing the blinds looks ok.
Already rebooted the Raspberry, without "luck". 
Nice to know: the blinds have been working fine for the last 3 years
Something in the code maybe?

Regards
Marcel

**Comment by gizmocuz** [comment]
@ajarzyn, are you using zigbee/zwave ? You ar not able to use the 'stop' button?
What happens when you set the slider to a value, is that your real device is at that moment not at this position
it takes a while, and you get updates for this device until it reaches that point
Same when you press the 'open' icon, internally we already set the status to 100% (Open=100), but the device is not yet open, and gives updates until it reaches this state

What I can propose is that we do not update the position/state internally for MQTT-AD and always expect the real device to give feedback of it's position, this will avoid the jump

Regarding the 'closed state' , you have not edited the blind and activates a reverse option? (It should be a standard blind)
You have no scripts running that could influence the state of the blind ?

**Comment by ajarzyn** [comment]
I'm not using zigbee/zwave devices, it's a MQTT esp32 device.
No problem with using stop button it works fine I'm just used not to have `stop` icon there.

> What happens when you set the slider to a value

`Real device` goes to correct position, event though in Web UI is presented as closed. You can see it on the give in the first post.
It reached 33% (the gate opened to 33%). Actually those values presented in the gif should be factual values sent by the `Real device`, you can observe it at the end of opening the gate, the movement slows down, just as the gate is slowing down before complete stop.

> What I can propose is that we do not update the position/state internally for MQTT-AD and always expect the real device to give feedback of it's position, this will avoid the jump

I feel like in my case that would be the solution, but can't be sure if it won't break any other device there are.

No edits for the reverse:
![image](https://user-images.githubusercontent.com/18590439/194817705-e74571b4-9b44-45db-bab4-9a90d3ebefc2.png)

No script running.

**Comment by gizmocuz** [comment]
@ajarzyn , is it a ESPHome sketch or did you create something yourself ?
The reason for asking is that I always test with a ESPHome blind/cover test and it's working excelent!

I suspect your ESP is sending these values to MQTT, maybe it is best if you log it first with the below script (change 8232 to the IDX of the ESP blind)

```
local MyBlind = 8232

return {
	on = {
		devices = {
			MyBlind
		}
	},
	logging = {
		level = domoticz.LOG_DEBUG,
		marker = 'Blind Log',
	},
	execute = function(domoticz, item)
	        domoticz.log(domoticz.devices(MyBlind).name .. ' state = ' .. domoticz.devices(MyBlind).state, domoticz.LOG_DEBUG)
            domoticz.log(domoticz.devices(MyBlind).name .. ' level = ' .. domoticz.devices(MyBlind).level, domoticz.LOG_DEBUG)
	end
}

```

**Comment by gizmocuz** [comment]
Issue has been solved
