### ISSUE TITLE
Inverted blinds

### ISSUE THREAD

**Issue by vespino** [domoticz/domoticz#5371]
I use homebridge to use domoticz with Google Assistent. As of the latest beta my blinds seem to be inverted. When I ask Google to close them, they’re opened and vice versa. I have tried toggling “reverse open/close state” and “reverse position” but this results in the domoticz icon being inverted.

Is this something I need to report here of with homebridge (they have made changes as of lately).

**Comment by gizmocuz** [comment]
The blinds in Domoticz have been redesigned to reflect the same behavior as other hardware/software

The workings are explained here:
https://www.domoticz.com/wiki/Blinds

I think homebridge internally inverted the blinds already and this can be undone
Maybe it is possible to change this in the homebridge settings, else i suspect it needs to be patched @ homebridge

**Comment by vespino** [comment]
I really don’t understand the logic. Are you saying domoticz was always wrong concerning blinds? It worked great, open meant the blinds were up and closed meant they were down. Don’t fix what ain’t broken?

**Comment by gizmocuz** [comment]
Yes that was the case and a lot of people needed to use inverted blinds or created inverted routines in their plugins
But the current way it is designed you can choose its behavior

**Comment by ksacca** [comment]
@vespino : I believe you should be able to fix your issue (for now, until homebridge edomoticz is updated) by editing the file domoticz_accessory.js in your /homebridge/node_modules/homebridge-edomoticz/lib folder.

Line 696 (https://github.com/PatchworkBoy/homebridge-edomoticz/blob/11a9d90e8fd0c1d860981dc6e71480609e25415a/lib/domoticz_accessory.js#L696)

`var command = (shouldOpen ? "On" : "Off");`
should be
`var command = (shouldOpen ? "Close" : "Open");`

**Comment by vespino** [comment]
@ksacca thanks, that works great.

**Comment by ksacca** [comment]
No problem, just found this out for myself today. Downside is this will not work for blinds with reversed states. For that, a complete change of homebridge edomoticz is needed. Currently the check is for the switchtypes that are inverted, but they don't exist anymore. But if you don't have any inversed blinds (I don't need it anymore since the blind changes in domoticz), you can use this as a temporary solution.

**Comment by gizmocuz** [comment]
@ksacca , I have not looked into the code yet, but if this part is specific for opening/closing blinds, you need to rewrite this to:

var command = (shouldOpen ? "Open" : "Close");

**Comment by ksacca** [comment]
Yes indeed, you are right @gizmocuz . We should really start using "Open" and "Close" instead of On/Off.
It is a function for blinds only, so I modified my comment. But the code should actually be:

`var command = (shouldOpen ? "Close" : "Open");`

I know this is not a clean fix, but If you don't have any inverted blinds it was the easiest workaround with minimal code change.
This is of course only to be used in very specific cases only.

**Comment by gizmocuz** [comment]
Regardless of how you configured the blind (inside domoticz) the plugin should 'always' send Open for Open and Close for Close
Also, it should set '20%' if it wants 20%

Reverse state/position will be taken care of by Domoticz and should 'not' be performed by a plugin

**Comment by ksacca** [comment]
Ok, now I get it (and now feel stupid 🤣 ). So actually it should be "pretty easy" to fix the issue by removing all the code that checks for inverted blinds and that recalculates positions. I can understand the logic of code, but adapting it is something else. Anyway, I'll try to look at it tomorrow and see if removing unnecessary code makes it work as it should. Sorry to have taken up your precious time, as this is totally not a domoticz issue. I just wanted to provide a workaround for this specific use case.

**Comment by vespino** [comment]
@ksacca @gizmocuz thanks for discussing this. I have made the necessary changes in the file mentioned, I don't however see whose "problem" this is. Who maintains this plugin? The plugins are stored outside the docker container, so no issues when updating the container, but it's best to have things up-to-date and not having to make these kind of changes on-the-fly just because I need them.

**Comment by ksacca** [comment]
I believe it was nicely explained in https://domoticz.com/forum/viewtopic.php?f=6&t=39219. Homebridge is maintained on https://github.com/PatchworkBoy/homebridge-edomoticz/ and is a homebridge plugin that is made for domoticz (but is not part of domoticz). Everyone can make changes and request them to be merged. There's already an open issue on github for the changes in blinds (but there's not a lot of activity on that repo lately). As you are using a beta version, it is normal that when big changes are made, plugins needs to be adapted too (and that can take time). You can track changes on https://www.domoticz.com/wiki/Domoticz_versions_-_Commits. As you can see, 14535 is the last version before the changes to blinds. You can pull image domoticz/domoticz:2022-beta.14535 in docker to revert. You can check all available tags on https://hub.docker.com/r/domoticz/domoticz/tags (just mind that builds since the blind changes have 2021 instead of 2022).

**Comment by vespino** [comment]
Thanks. I’ll leave things the way they are for now.

**Comment by ksacca** [comment]
I just posted something in the homebridge-edomoticz topic on the domoticz forum (https://domoticz.com/forum/viewtopic.php?p=293567#p293567). 

I was able to modify to code to work with both old and new blinds (open/close/set position), including recalculating the actual current state and position when inverted (the nvalue and levels are different when inverted). For me it works correctly, and it did too with dummy devices. I tested on my prod (old blinds) and test system (new blinds). Feel free to test and report any issues. I propose we continue this conversation on the forum or on the homebridge-edomoticz github page.
