### ISSUE TITLE
Issue with blinds in UI, reverse Open/Close state(build 14575)

### ISSUE THREAD

**Issue by lokonli** [domoticz/domoticz#5374]
Build 14575
Debian 10

I've created a dummy blinds device with reversed open/close state:

![image](https://user-images.githubusercontent.com/22852111/196512067-cabee7c9-7d02-4ebc-ad0d-c535d5321a5b.png)

Moving the slider completely to the right marks the blinds as closed (=correct):
![image](https://user-images.githubusercontent.com/22852111/196512281-03545ef3-6a61-4706-877e-48d42107a279.png)

However, when clicking the 'close' icon this results in a state 'closed' with slider on the left (=incorrect):
![image](https://user-images.githubusercontent.com/22852111/196512530-fd32d86b-d234-463c-8cf8-e295b6102dd6.png)
Expected behavior is that the slider stays in the right position.

Behavior of normal slides, and slides with Reverse Position seem to be ok.

**Comment by gizmocuz** [comment]
Are you sure you don't need to check botch checkboxes ?

**Comment by Rouzax** [comment]
What @lokonli says is correct but also kind of expected.
You are not reversing the slider position, so 0 is Closed and 100 is Open, but you are reversing the State Label, so Open will be shown as Closed and vice versa.
![2022 10 20-14 00 50_Domoticz_-_LightSwitches_—_Mozilla_Firefox_s03a6vBtQs](https://user-images.githubusercontent.com/4103090/196942873-c2beebbe-49ba-416b-8cb3-35aa227af45d.gif)

Since you are reversing the State Label, that causes confusion and @gizmocuz there seems to be a bug here, or at least an inconsistency.
Pressing `Close Blind` will still send 0  (or Close command, not sure what is being sent underwater) and pressing `Open Blind` will still send 100 (or Open Command). These should however be reversed in this case.
See this screen recording, first I do it twice via the sliders after with the buttons, notice the inconsistency on the State Label.
![2022 10 20-14 07 52_Domoticz_-_LightSwitches_—_Mozilla_Firefox_mB7ReLu4X2](https://user-images.githubusercontent.com/4103090/196944600-9b14d7dc-6986-4dba-90b8-4799ce21595b.gif)

To be honest, I can't really think of any use case where you would only enable `Reverse Open/Close State`

**Comment by lokonli** [comment]
The second recording of @Rouzax indeed shows the inconsistency.

I was testing my Slide device. This device reports 100 in case the blinds are closed. So I thought, let's reverse the state labels, and then it should be ok. Then I noticed the inconsistency.
In the mean time I've solved this by updating the python plugin.

**Comment by gizmocuz** [comment]
When you set the blind to normal blinds (so not with stop or percentage) and you revert the state, does it work ?
When you have a percentage slider, you also want to reverse this
What @Rouzax says, maybe we should just make one option, 'Invert state/percentage' instead of two options?

**Comment by Rouzax** [comment]
@gizmocuz, not sure, but would it make sense to also invert the action buttons when you enable Reverse State?

**Comment by gizmocuz** [comment]
@Rouzax , no in the GUI/scripts it should stay the same, it is only swapped(send) to the actual devcice

**Comment by gizmocuz** [comment]
Closing issue as it's solved by updating the plugin
