### ISSUE TITLE
Extend json.htm?type=devices API to add the value as a numerical value

### ISSUE THREAD

**Issue by sbouchex** [domoticz/domoticz#5492]
Current json.htm?type=devices implementation add the unit to the "Data" field, so it's not very easy to make the data parsable to read by an external poller to insert the data to Prometheus (for example)

Proposal : 
- Add a new "nData" field that contains a floating value
- Reuse CBasePush::ProcessSendValue code to generate this floating value

This requests was some kind also requested in #1870

I can work on this MR

**Comment by sbouchex** [comment]
Question for @gizmocuz : I was planning to reuse the code from CBasePush::ProcessSendValue (to avoid duplicating code), where do I have this code ?

**Comment by gizmocuz** [comment]
@sbouchex , The 'Data' field can be anything and is related to the type of the device. For instance 'On' 'Close' '123;456;789', 'Hello World'

Instead of using propitious, you can use the InfluxDB pusher that is available in Domoticz, this does an excellent job and does what you probably want to do

I made a few changes, and the 'CBasePush::ProcessSendValue' is now static.
This means you can use it anywhere you like by calling

std::string sResult = CBasePush::ProcessSendValue(......)

But still, some devices have multiple values. For example a Temp+Hum+Baro sensor

So using a pusher is best. Maybe you can use another available pusher to get your data inside.

But as mentioned, I myself use a docker-compose influx2 instance that get's the data perfectly fine from the default pusher (and on top of that I use Grafana)

**Comment by sbouchex** [comment]
I agree that metrics may have multiple entries and push is supporting that correctly. I have written a small prometheus exporter for domoticz (see https://github.com/sbouchex/domoticz_exporter) but I would need to add an option in the "%" push formatting options to indicate that this metrics is a counter (i.e. always increasing) to correctly return the value to prometeus.

I know that this gauge/counte behavor is not really indicated in the devices types but I would modify the RFX_Type_SubType_Values structure and add an extra field to indicate if it is a counter. ok for you ?

**Comment by gizmocuz** [comment]
Can’t you use the influxDB pusher?

**Comment by kiddigital** [comment]
@sbouchex , what is your use-case/scenario for using Prometheus?

InfluxDb is a time-series database which is great for long term storing and aggregation of time-series data. And also for using it with tools like Grafana for visualization.

Prometheus is more a monitoring and alerting tool aimed at providing actual dashboards on incidents (and problems) and perform alerting and escalation. So quite different from InfluxDb (and yes, more and more overlap can be found nowadays).

Interested to learn why/how you (intend to) use Domoticz with Prometheus.

**Comment by sbouchex** [comment]
@gizmocuz The line protocol could be an option but my choice was more prometheus oriented.

**Comment by sbouchex** [comment]
@kiddigital I agree that influxDB is an good option and I'm using it for years (more than 10 I think, I even wrote the HTTP push code in domoticz) but I'm using prometheus at work also and I wanted to add that capability to domoticz also.

I agree that Prometheus brings less features than InfluxDB (like continuous queries, variable expiry) but eco-system around Prometheus is larger (especially in the kubernetes world)

**Comment by kiddigital** [comment]
> @kiddigital I agree that influxDB is an good option and I'm using it for years (more than 10 I think, I even wrote the HTTP push code in domoticz) but I'm using prometheus at work also and I wanted to add that capability to domoticz also.
> 
> I agree that Prometheus brings less features than InfluxDB (like continuous queries, variable expiry) but eco-system around Prometheus is larger (especially in the kubernetes world)

@sbouchex , thanks for explaining. Do you intend to use Prometheus for storing the metrics (similar to InfluxDB) and do reporting on them using Prometheus? Or (maybe _and_) do you want to perform actual _monitoring_ by watching certain metrics, checking thresholds and/or automated anomalies, etc. and perform active alerting, etc.?

I was thinking about adding a `/metrics` HTTP route to Domoticz which presents Domoticz metrics in [OpenTSDB](http://opentsdb.net/docs/build/html/user_guide/writing/)/[Prometheus](https://prometheus.io/docs/concepts/data_model/) format.
Also make it usable as [liveness/startup/readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) for Kubernetes.
And for use with [Docker Healthcheck](https://docs.docker.com/engine/reference/builder/#healthcheck).

Any suggestions for what metrics would be relevant and/or interesting to gather/monitor? Maybe we can work on a MR for this together? Or are you more looking into _scraping_ device data into Prometheus instead of Domoticz itself?

**Comment by sbouchex** [comment]
I will probably switch to Prometheus and plug the Prometheus-alert-manager (with custom alerts) and other Prometheus docker images.

Regarding /metrics, that's a good idea as that's the Prometheus standard route.

For liveness/readyness probes, changes may be needed in domoticz in order to expose the 2 states.

Regarding new metrics, database calls, hardware count, devices count, http pushes, everything around events...

**Comment by kiddigital** [comment]
I created a new issue #5537 to describe the enhancement as I see it.

@sbouchex , Feel free to extend/enhance it if needed. If you are happy with the new issue as successor of this request, please close this one.
