### ISSUE TITLE
Log page of weather sensor show also the weather widgets

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5510]
Hello @gizmocuz 

Various users, including myself, see if they open the log page for the weather sensors, also the widgets below the log graphics.
In my case it is all, except the widget for visibility and rain, but this may be different for other users.

For more details, including screenshots, see: https://www.domoticz.com/forum/viewtopic.php?p=296681#p296681

Forget, what I mentioned there about the log in "Scenes". This is solved, as I do not see it in version 14901.

Regards and a Happy new Year

**Comment by gizmocuz** [comment]
Happy new year!!

I noticed this as well on my live system (armbian), not on my test system (windows)
Also with the edge browser

I think this is caused by PR #5272

@soif , is it possible you could have a look at this? I tried solving it, but it seems the 'weatherwidgets' div is not hidden when we go to the log

**Comment by soif** [comment]
After investigating, I think I've found the culprit...

I will certainly push a PR soon to fix it...
