### ISSUE TITLE
Managed Counters don't get their "Last Seen" updated

### ISSUE THREAD

**Issue by SargonofAssyria** [domoticz/domoticz#5527]
Using:
```
Version: 2022.2 (build 14922)
Build Hash: 338aa8e9b
Compile Date: 2023-01-06 16:48:51
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
```
I am using a managed counter to update that counter with day ahead prices from entsoe.
I get a nice graph for the last 3 days or the last 2 days and 1 future day after the update of prices a 16:00
So that works perfectly, the only problem is that the "Last Seen" in the GUI is not updated.
The widget gets red and stays red, and I can't see by the GUI if the prices are updated at 16:00 by the widget.
Only with a mouseover over the latest (future) times in the graph it is possible.
It would be handy if the "Last Seen" is updated when I update the database.

**Comment by waltervl** [comment]
What is the command you use to update the counter?

**Comment by waltervl** [comment]
If I use /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=COUNTER;USAGE  according https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Managed_counter it updates the last seen value and the red widget gets it normal color back.

**Comment by SargonofAssyria** [comment]
I use (of course) dzVents to update the managed counter.
The managed counter is Type 243, SubType 33, SwitchType 3 (Custom Counter)
So conclusion is that it is dzVents bug?
B.t.w. it should be /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=COUNTER;USAGE;**DATE**

**Comment by waltervl** [comment]
No it should not be with date as that is the command to put something in the history. It could be that due to the date Domoticz decides it is a history action and not a current reading. Did you try that?

Edit: Perhaps an option to put daily something irrelevant in the counter without date and put your data from yesterday (or earlier) with the script.

**Comment by SargonofAssyria** [comment]
Yes it should be in WITH date, see first post. I am using managed counter to put in every day the prices of electricity per hour of the **future day** in the device. And that does works perfectly. So the device is updated one per day, but the widget stays red and the "Last Seen" never changes.
I tried /json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=0;0  (NO date)
But that deletes the last value from the graph, also strange.

**Comment by waltervl** [comment]
I know that in YOUR use case it is with a date but apparantly the developer of the history function (counterdata + date) did not take into account this functionality to update Last_Seen too . Probably because it should be a kind of cleanup action and a last seen would only be problematic. 
Unfortunately my workaround is not working for you. Then hopefully someone can enhance the API with your request (or you can try to do it). It does not look like a bug as normal function is updating the Last_Seen of the device.

**Comment by WillemD61** [comment]
There are 3 commands related to managed counter:
1) an updateHistory with Date (resulting in a JSON). This inserts a value into the meter_calendar table.
2) an updateHistory with a date and time. This inserts a value into the meter table. This is probably the one used for the hourly prices (I did a test with the same).
3) an updateCounter command. I think this one is needed to update the icon and remove the red color.

Sidenote: although you say it works perfectly, please note managed counters cannot handle negative prices (you cannot store it with updateHistory or a JSON since it will result on 0 and, if you do otherwise such as via SQL, the graphs will get messed up). I have now raised an enhancement request to get a device that can.

**Comment by gizmocuz** [comment]
@SargonofAssyria , please try beta 14964, this should now update Last Update when you push values

**Comment by SargonofAssyria** [comment]
Yes, it works now, Tnx a lot.
