### ISSUE TITLE
Livesearch enhancement idea

### ISSUE THREAD

**Issue by gizmocuz** [domoticz/domoticz#5536]
At the moment we have 4 fields the 'live search' searches in

```
var name	=$(this).find('#name').html()
var desc	=$(this).find('#name').attr('data-desc')
var idx		=$(this).find('#name').attr('data-idx')
var status	=$(this).find('#name').attr('data-status')
```

Maybe this could be reduced to one field and for each device we keep on adding additional data into this field

Reason for this is that for some sensors we need different fields to search on

Maybe create one global function that adds data to this field and returns the new field value

pseudo:
```
function AddToLiveSearch(current_data, new_value) {
  if (current_data.empty()
    return new_value;
  return current_data + " " +  new_value;
}
```
usage:

`search_value = AddToLiveSearch(search_value, "some value")`

With this we can also significantly reduce the search function (and speed as a bonus)

@soif , How do you think about this?

**Comment by gizmocuz** [comment]
@soif , I'm working on this feature.
Question, could it be that the 'current' live search does not work when a update is received and the 'bigtext' changed?
Reason for asking is that you add a data-status object to the widget and you use that in the live search, but this is not updated in the RefreshItem function

**Comment by gizmocuz** [comment]
If you have some time, could you check the above branch/code?
When it is finished we only will use 'searchText' in **WatchLiveSearch**
Initial text in the Lights/Switches overview

**Comment by gizmocuz** [comment]
@soif , more changes have been pushed in the branch, only dashboard remains and it is finished

**Comment by soif** [comment]
Hi, sorry for the very late reply... _I was Offline..._

I had quickly reviewed your code, and I had a few remarks/suggestions,... 
but after reading your next commit, I've noticed that you've now included all of them! 🍺 

> Question, could it be that the 'current' live search does not work when a update is received and the 'bigtext' changed?

Certainly yes!


BTW now that you've added all fields to the searchText string, the data-status attribute is no longer used, and could/should be removed.

Would you like me to remove it  (in a new PR) ?

**Comment by gizmocuz** [comment]
Thanks for the review!
Yes i thought the status update was not working for o.a. the light/switches page

Maybe the data-idx and data-desc can also be removed now

I have a look at this soon :)

thanks

**Comment by soif** [comment]
Sure, **data-idx** could also be removed, 
but **data-desc** is used to display the  description when hovering the device name (very useful IMHO). 
_See:  domoticz.js / WatchDescriptions function._ 

So it should remain!

**Comment by gizmocuz** [comment]
Didn't know that ;) yep let's keep that one! ;)

**Comment by gizmocuz** [comment]
Removed data-idx and data-status.
I think I will merge this for the upcoming release and after that focus on the dashboard as this will be a lot of code (if we want it on the dashboard)
The Weather/Temperature sensors are in a widget, but maybe we have to see if this can be done for Utility and Light/Switches/Scenes as well.
Then we can maybe make the dashboard code more angular style

**Comment by soif** [comment]
Damm You're too fast, I've also made those changes  at:
https://github.com/domoticz/domoticz/compare/livesearch-enhancements...soif:domoticz:livesearch-enhancements

A few remarks:
I've separated removing data-status and data-idx in two separate commits:
- data-status : was added by me, and can be safely removed.
- data-idx: some was added by me, b**ut some ALREADY existed before**, so I guess that they should NOT be removed (or one should carrefully check if they are really used in the code)

May I suggest that you revert your last commit, then merge my Two commits, instead.
(I did not touched the Dashboard, as i thought you were working on it, but  you should **remake your changes** in this file excluding all those lines where there is no "data-desc" (it means that those data-idx was NOT added by me, and might then be used elsewhere)

>I think I will merge this for the upcoming release and after that focus on the dashboard as this will be a lot of code (if we want it on the dashboard)

Yep a lot, but is this really needed on the dashboard as it is supposed to be a selection of just a few favorites devices?  But of course it doesnt hurt to also add this to the dashboard...

>The Weather/Temperature sensors are in a widget, but maybe we have to see if this can be done for Utility and Light/Switches/Scenes as well.

It would be great if all pages use the SAME architecture. Might I suggest that the "Build item" Should be a GLOBAL function, that could be called by each page controller, and according to the device type, always build a consistent  item html block.... it would be more clear, less duplicate code, and more bug proof...

>Then we can maybe make the dashboard code more angular style

Once "Build item" is global, making the dashboard would be really more easy, instead of repeating "if device is xxx then yyy" again and again....

**Comment by gizmocuz** [comment]
I did a search in the complete www folder for data-idx and it was not used.
I can't remember if I added this, or someone else. Maybe the idea was to find the object by it's ID,
but it's now done by the name+idx

**Comment by soif** [comment]
Remeber that in jQuery   `$.attr('data-idx')` is equivalent to `$.data('idx')` ... 
SO depending on how you made the global search, you might have missed some needed idx.... 😉

**Comment by gizmocuz** [comment]
Hmmmmz yep :) okey, going to revert this data-idx/status removal

**Comment by gizmocuz** [comment]
Done, just removed the data-status
Let's keep the data-idx, we can also use it for the drag/drop or feature code

**Comment by soif** [comment]
😬 

BTW regarding a global "Build Item" function, I'm not used with ANgular, but It should ceratinly be performed in some VIEWs, rather than in the Controller.
ie, templates (Views) would be:
- itemWrapper : which depending on the item type, call a sub template : 
- itemSubSwitch
- itemSubSelector
- itemSubDimmer
- itemSubColor
- itemSubTemperature
- ItemSubWeather
etc....

And the ItemWrapper should then be called from the main items loop, in each page view.

_I dont know if you see what i mean..._

**Comment by gizmocuz** [comment]
This is the code in the weater view to generate all items

```
	<div class="devicesList">
		<div id="weatherwidgets" class="row divider">
			<h2 ng-show="ctrl.items.length == 0" data-i18n="No Weather sensors found or added in the system...">No Weather sensors found or added in the system...</h2>
			<div ng-repeat-start="t in ctrl.items" class="clearfix" ng-if="$index % 3 == 0 && !$first"></div>
			<dzweatherwidget ng-repeat-end class="span4 itemBlock" id="{{t.idx}}" item="t" tempsign="config.TempSign" windsign="config.WindSign" ordering="config.AllowWidgetOrdering" dragwidget="DragWidget(idx)" dropwidget="DropWidget(idx)"></dzweatherwidget>
		</div>
	</div>
```

there is a dzweatherwidget that checks what is should render and how
The same is done for the temperature widgets
If the same is done for utility/lights/switches/scenes it should be quite easy to build a dynamic page

But indeed the BuildItem function/code/decision should be global
It should check what type it is, and render the item accordingly, if it is a temperature device, render it as a temperature device, if it is a selector switch, render it as a switch etc.
With this we can use things like angular-gridster2 or similar.

**Comment by soif** [comment]
Yep the current weather/temperature widgets are almost the right way to do, and should be extented to all other pages.

I just wished to highlight that all those widgets could/should depend on a global widget, which determine how the common HTML (main div, icon, links,date) is printed, then depending on the type, call the relevent Sub Widgets wich then print the specialized HTML for each type.

This way changing the main widget HTML would affect ALL widgets, at once...

_and BTW angular-gridster2 looks amazing 👍_

**Comment by soif** [comment]
BTW when you'll reafactor all the widgets, please remember to remove all those `id` attribute that should rather be replaced by `class` attributes, ie: 'item-name', 'item-bigtext', 'item-img', etc...

Because in CSS, an [ID is supposed to be unique per page](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id)

**Comment by gizmocuz** [comment]
It's not going to be any time soon here... to much work on the fork ;)

**Comment by soif** [comment]
Was just a friendly remenber, Take your time. 😸 

Then when you would make those changes, feel free to ring me a bell, if I may help in some fields. 😎

**Comment by gizmocuz** [comment]
Sure you may, you may start now hahaha ;)

**Comment by soif** [comment]
There is an issue introduced by your changes in #5591 :

You've asked in #5518 to be able to search by Status, and I then pushed #5525 to do that.

But your latest change is adding the item.type to the search strings. As most Switches are of type "Switch On/Off", searching by "On" or "Off" simply return ALL switches...

Code:
https://github.com/domoticz/domoticz/pull/5591/files#r1105721038

**Comment by gizmocuz** [comment]
Thanks for spotting, fixed in current code
