### ISSUE TITLE
Bar charts show extreme high value in 'last 7 days' chart

### ISSUE THREAD

**Issue by fwieringen** [domoticz/domoticz#5569]
Updated to beta 15006 today. Charts worked ok during the day, but right after midnight, all devices which use bar charts (eg gas) show similar 7 days charts. When I change the view to last 3 days or less, it works ok.

Last 7 days:
![image](https://user-images.githubusercontent.com/4232879/214712909-422c6a14-a58c-4759-9d21-6397bbdfce57.jpeg)

Clicking the 3d button:
![image](https://user-images.githubusercontent.com/4232879/214713052-a8df0277-115b-4b5e-9078-bf7853431cb4.jpeg)

**Comment by gizmocuz** [comment]
So, it looks it's the first value that gives a problem?
I made some changes to 'some' charts. so that it now includes a 'usage' option.
My charts are currently keeping history for 48 hours and I do/did not experience this behavior.

I now set it to 7 days, so it will take some days before I may experience this too.

I can debug the issue sooner, for this, please contact me on our slack channel

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg

(And mention a link to this issue)

You can revert to a previous version

**Comment by fwieringen** [comment]
Interestingly enough, the charts looked normal this morning... so it was just last night. Let's see how they look tonight after midnight.

**Comment by fwieringen** [comment]
Problem occurs only between 0:00 and 0:55 am.

**Comment by gizmocuz** [comment]
I think in this case that at 00:00 the daily values are added to the calendar database table and a new first value of the day is added to the short log interval table
When you see this, could you make a backup from your system/database from the settings page and send me this in Slack?

**Comment by fwieringen** [comment]
Done

**Comment by gizmocuz** [comment]
Thanks, solved in beta 15017

**Comment by GravityRZ** [comment]
is my problem related to this issue
#5608

i noticed this since build 15082. i think i did not hsve this in build 15006
