### ISSUE TITLE
Huge value of incremental counter

### ISSUE THREAD

**Issue by ZonPV** [domoticz/domoticz#5581]
Reading the gasmeter with a optical tracker sensor , TCRT5000 to a NodeMCU ESP8266 with ESPeasy version ESP_Easy_mega_20220809.. I selected a pulse counter in that device.
It works for years without any problem. The only thing is that every morning the sensor on the dashboard of Domoticz shows a very high value: 184467440737095520.000 m³. In a graph there is no pile. The value at that moment is 0.
As soon as I use some gas the daily counter starts at 0,01 m³ and shows the right value for the rest of the day.
It is a dummy, virtual sensor, Type General, SubType Counter Incremental, Field Data shows the correct total value of 36501.137 m³. Exactly as the physical gasmeter itself.

The actual build of Domoticz is 15006. I can tell this cosmetic failure is there for years, so in V2022.2, V2022.1, and so on.

It is not related to a browser. It is there in Firefox, Chrome and on all my devices like PC, smartphone or tablet.

I do not have a smart meter for reading electricity. Still the oldfashioned ferraris meter. No P1-reading.

Running Domoticz in Docker on my Synology NAS.
In the log, after the value is send to InfluxDB is shown: 
`2023-02-02 11:54:54.378 InfluxLink: value Counter-Incremental,idx=734,name=Gasmeter value=3650113.7`

Found no way in this forum to add a screenshot; sorry for that.

It is not a dramatic issue. I just want to tell it as feedback and I love Domoticz. Just to make the application better. ;-)

**Comment by waltervl** [comment]
Please use the Forum for this type of issues. It seems that your NodeMCU ESP8266 with ESPeasy is not connecting to Domoticz correctly. Could still lead to a bug in Domoticz but there is a far bigger audience for these kind of issues then on this github.

**Comment by Zuikkis** [comment]
This is actually a domoticz bug. I have a lot of incremental counters. They all move slightly backwards at midnight, and because domoticz counters don't handle negative numbers it shows very large positive integer instead.

It's fixed automatically whenever the counter is incremented forwards again.

**Comment by gizmocuz** [comment]
I use counter incrementals myself and don't have these issues

Maybe you could adopt my watermeter code (MQTT Autodiscovery) to work with your optical sensor?

https://github.com/gizmocuz/esp_proximity_sensor_mqtt

When you make a screenshot, you can just paste it in here (control-v)

![image](https://user-images.githubusercontent.com/2265299/224533333-a40a15a1-8cd5-4f09-a5ba-302225609107.png)

As you see here, no spikes at midnight

**Comment by Zuikkis** [comment]
The bug doesn't show in graphs.

Only shows in the "utility" page display.

My guess is the midnight switch does some rounding which rewinds the counter slightly? 

Anyway, I'm currently working on a fix on the counters which allows negative increments.. If fixes this too.

**Comment by gizmocuz** [comment]
Okey but incremental means incremental?

**Comment by gizmocuz** [comment]
How can your gas meter value decrement? I am not getting it.... a incremental counter used with decremental values... and a gas meter that should only increment?

**Comment by Zuikkis** [comment]
The decrement is done by domoticz midnight magic... It's very small decrement, like -0.000000000001 or something, but I have seen it in my electricity price counters.

**Comment by gizmocuz** [comment]
Hmmmm that's very odd .... Have not experienced this before....
Thanks for the PR, I will have a look at it and merge it (and afterwards remove all strange strtoll/strtoull calls as well ;)

**Comment by gizmocuz** [comment]
Your PR also does this for pTypeRFXMeter, have you tested your patch for a few days?

**Comment by Zuikkis** [comment]
Yeah I noticed there already was a mix of stoull / strtoull and also a mix of "unsigned long long" and "uint64_t".. I didn't know which was the prefererred method so I didn't change them. I just removed "u" or "unsigned" from each. :)

About the midnight decrement, it perhaps only happens if counter value has a lot of decimals. It could something as simple as integer->double->integer cast causing a bit of inaccuracy. Anyway I don't think this is an issue anymore. 

> Your PR also does this for pTypeRFXMeter, have you tested your patch for a few days?

Yes, for two days now, with negative and positive increments. They show up correctly in daily/weekly/monthly/yearly graphs as well. 

Interestingly if you create a dummy counter with custom units (€), it becomes type pTypeRFXMeter / sTypeRFXMeterCount...  That's why I modified that too.

**Comment by ZonPV** [comment]
@gizmocuz The problem in the start of this issue is different as the problem of Zuikkis.. This is a picture of the widget every morning. 
![afbeelding](https://user-images.githubusercontent.com/11488827/224542989-2fa29e64-8328-4d9d-99d7-ab90ba5a0d23.png)
And this is the discussion on the forum:
https://www.domoticz.com/forum/viewtopic.php?p=298985&hilit=pieters#p298985

There is no spike at midnight in the graph. 
![afbeelding](https://user-images.githubusercontent.com/11488827/224543287-e412f3b4-3e47-4da5-b920-58c351491258.png)

As I said before, I do not know what sort of data is send from the ESP to Domoticz.

This is config of ESP:
![afbeelding](https://user-images.githubusercontent.com/11488827/224543542-fc7c8055-4140-4e51-a6f2-18ad6fc3e015.png)

**Comment by gizmocuz** [comment]
@ZonPV , please also use this version and check if this is still hapening

**Comment by Zuikkis** [comment]
I'm pretty sure it's the exact same bug that I saw at midnight.

Negative number "-1" is 18446744073709551615 if interpreted as 64bit unsigned integer.  If you add "1" to that number it becomes zero.

With this new Domoticz version you should see -0.001 m3 or perhaps it's even rounded to just 0.000...

**Comment by Zuikkis** [comment]
in main/WebServer.cpp, in a lot of different places, CounterToday is calculated so that "sValue" is taken from DeviceStatus table, and today's first "Value" is taken from Meter table, then calculate like this:
```

int64_t total_first = std::stoll(sd2[0]);      // Value from Meter table
int64_t total_last = std::stoll(sValue);       // sValue from DeviceStatus table
int64_t total_real = total_last - total_first; // calculate difference

```

sValue is really a string that contains a floating point number, and Meter table values are integers. "stoll()" will just ignore the decimals, 16.999999999 becomes just 16. 

I'm not sure where Meter table is written to, but perhaps it uses different conversion there and rounds 16.99999 into 17? Then total_real becomes -1.

Anyway there's probably no point to investigate this further as I think my latest PR fixes it already.

**Comment by ZonPV** [comment]
Yesterday I updated to V15151.
This morning I noticed this value in the widget of gasusage: 
![afbeelding](https://user-images.githubusercontent.com/11488827/224728627-43a1be81-fa86-457a-8f4f-c03b875b6b24.png)

But in the graph there was a small pile around midnight, we did not use gas at those hours...
![afbeelding](https://user-images.githubusercontent.com/11488827/224729335-c903078c-be85-4e83-acfa-b17d0841ef39.png)

@gizmocuz :
I do not understand how to read my gasmeter with a ESP8266 Proximity meter... At the moment I read the gasmeter with a optical tracker in front of the last digit. That has a small mirror in the number 6.. 
BTW: Your info in the link gives me not enough information how to build that hardware.

And what wonders me too: 
Why gave the gasmeter that huge value since midnight?
![afbeelding](https://user-images.githubusercontent.com/11488827/224731692-e271b5dd-ebe4-436c-ade4-d5f2ea5ed700.png)
And the watermeter does not?
![afbeelding](https://user-images.githubusercontent.com/11488827/224732246-0677ee85-bd66-48f2-9512-7c9e269ee64c.png)

Both use a ESP8266 and http-protocol on the ESP and the same firmware 220809_normal.. The sensor of the watermeter is a LJ12A3-4-Z/BX. The same as you suggest.
Yesterdayafternoon I disabled the sensor on the ESP so that it does not upload any data to Domoticz. And the widget gives a usage since midnight of 0 liters. And the graph give no bar around midnight either..
![afbeelding](https://user-images.githubusercontent.com/11488827/224734608-c4aa871e-7f44-4d1e-95d6-6b9eb9903a73.png)
![afbeelding](https://user-images.githubusercontent.com/11488827/224734768-dd8cc5c4-3d76-43ac-92ea-155103ba2d8c.png)


Just curious why this strange behaviour happens. Not very important for me to solve this problem. I hope to change to a heatpump for heating the house and water later this year :-)

**Comment by Zuikkis** [comment]
So with latest domoticz, the 18446744073709551615 becomes 0.000? 

Interesting that the value must be just a very tiny bit negative, to round up to 0.000 without minus sign.

The midnight problem is probably related to this issue:
https://github.com/domoticz/domoticz/issues/5437

There is some tiny inaccuracy. It might all come down to the fact that table "DeviceStatus" has floats and table "Meter" and "Meter_Calendar" have integers.

**Comment by gizmocuz** [comment]
There should be no float value in a incremental meter... who put's a float in there? Must be a script then?

**Comment by Zuikkis** [comment]
> There should be no float value in a incremental meter... who put's a float in there? Must be a script then?

Hmm... There's nothing preventing putting floats there? Both JSON API and dzVents scripting accepts floats there.

**Comment by gizmocuz** [comment]
There is the usage (like 14.5 Watt) and a counter value for counters ...

**Comment by Zuikkis** [comment]
But surely even kWh counter has decimals! You can't just decide it's supposed to be integers when they are not.. :)

And most custom counters don't have separate "usage" and "counter", just single value. Usage is not displayed at all if device does not support it.

Like, this is my energy cost counter (starting from last november)

![kuva](https://user-images.githubusercontent.com/6397305/224762649-63e966a5-7289-4d10-85d6-1a06f57433b8.png)

I guess I could live with a slightly smaller amount of decimals, but the formatting comes from WebServer.cpp:

https://github.com/domoticz/domoticz/blob/225506eef4c24fdb2c7b285d7aa38e4b2b947c1e/main/WebServer.cpp#L11007-L11039

I wonder why there is all different kinds of formatting for different counter types, if they all are supposed to be integers? Could replace the whole switch statement with %lld?

**Comment by gizmocuz** [comment]
`But surely even kWh counter has decimals! You can't just decide it's supposed to be integers when they are not.. :)`
Yes this is assumed

And the 6 decimals, what is inside the DeviceStatus table? %g should print no decimals or a maximum of 10 if there are more
Why there are multiple formats, because for water meters 3 decimals is common.

So again, for kWh counter values this is stored with a multiple of 1000 in the database.
That is why there is a devider
You should do the same, so no decimals for counters!

Anyway, pointless discussion, your case is solved, and if you had sticked to the program you should not see these errors.
(Probably documentation needs to be clearer, but that is made by volunteers like me as well so please feel free to contribute)

**Comment by waltervl** [comment]
In general the documentation is clear about integer usage on counters, eg https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Counter

**Comment by ZonPV** [comment]
After a few days of absence and no gasusage I see a negative value of gas in Domoticz. Had that never before.
![afbeelding](https://user-images.githubusercontent.com/11488827/228886729-c426eea6-c6dd-479e-bc46-0374f1ed69d0.png)
Running (Build  15175) in Domoticz. Did not upgrade the ESP. It is stil on ESP_Easy_mega_20220809..
![afbeelding](https://user-images.githubusercontent.com/11488827/228887630-bead464c-43fd-42cb-a232-ed8df8130f73.png)
So I think there is something wrong in the code of Domoticz when there is no usage that day... 

Don't understand the discussion about Watts, kWh, etc. But these screens with misinformation is what I see in my case here. No hard feelings and I just want to give feedback to you to make Domoticz better.

**Comment by Zuikkis** [comment]
@ZonPV in the start of this issue you had "huge value of incremental counter". Since you are now running Build 15175, instead of huge value you now see a negative number.

They are the same thing. Earlier domoticz used unsigned numbers so negative value wrapped to very high positive.

I don't know what causes the issue really.

Here's an example from my running system:

![image](https://user-images.githubusercontent.com/6397305/228901995-74777b69-99fc-4850-9f27-cc1d7d1c08a5.png)

It's the energy cost of the washing machine. Since it's not used today, the cost should be zero but instead it's slightly negative. With earlier domoticz versions I saw a huge positive number.

It's only the "CounterToday" value that is incorrect. Actual counter does NOT go backwards. Negative is not visible in logs:

![image](https://user-images.githubusercontent.com/6397305/228903053-328a4ae3-526b-4bbb-b1de-5e39716a0731.png)

"Meter" table shows just 1489 value through midnight:

![image](https://user-images.githubusercontent.com/6397305/228904299-8735a13b-b82e-4222-9129-067885bba648.png)

**Comment by Zuikkis** [comment]
Ah and just after posting I now understand what is causing this, it is exactly what we speculated above. The current counter value has decimals, it's 1488.7 ... So obviously 1488.7 - 1489 = -0.3.

So yes this is caused by incorrect plugin that feeds floats to counter which should only have integers. :)

Still it's only cosmetic error. It will fix itself when counter rises above 1489 (in my case). Just the daily usage is not exact.

In my case I should have used 1000 instead of 100 as multiplier, and then do all calculations in 1/1000th euros with integer math. It's a bit tricky to fix now that I have already half a year of logs and dozens of devices.
