### ISSUE TITLE
Menu/tabs have gone after setting an admin account 

### ISSUE THREAD

**Issue by Zaphod-dev** [domoticz/domoticz#5604]
After rolling back to version 2022.2 after a failed domoticz upgrade (see below), domoticz web UI is working just fine, until I save what looks like any change in the settings menu pages (eg when disabling the upgrade notification option...). After which the web UI looses all but two menus/tabs in the top header (I am left with Home and Configuration tabs only).
The various menus/tabs are enabled in each of the users (switches, temps, etc). As shown in the screenshot below there is however no "active user" which I believe may be due to my local network being configured as passwordless.
![image](https://user-images.githubusercontent.com/12284507/219244944-8eca37f6-d4b3-4cdb-a5cc-a6a4b3d8e547.png)

When I log in from outside my local LAN via the domoticz auth login page, I also get the same bug : only the two basic menus/tabs are visible (ie missing temp/switches/weather etc.). The About page doesn't display any "Active user" info :
![image](https://user-images.githubusercontent.com/12284507/219249491-6f8f94ec-6020-4e6e-aaad-3a1a9044df43.png)

Domoticz has been running on this raspian Pi2 server for years (debian stretch). I can't upgrade to the latest Feb stable release because I did try by pressing on the red "Upgrade now" button which poped up yesterday, but then domoticz wouldn't start with the following error :
` févr. 15 20:34:43 zeworks domoticz.sh[10306]: /home/pi/domoticz/domoticz: /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1: version OPENSSL_1_1_1' not found (required by /home/pi/domoticz/domoticz)`

The openssl 1.1.1 isn't available as a raspian stretch package, so I tried compiling openssl 1.1.1 but it failed at make test, so I reverted to domoticz 2022.2 version, but am now stuck with lost menus/tabs.

The menus/tabs are absent in two different browsers (FF & chromium), after full cache purging, as well as in Private Windows. Nothing significant observed in the browser console (F12), but I can include this if needed).

**Comment by gizmocuz** [comment]
You can not downgrade. But there should be a backup in your backups folder (if the automatic backup was already introduced 4 november 2021)
Make sure you clear the browser cache + appcache (two different things)
Another option, make a full backup of your sd card (with win32imager or another program),
backup your database and any external scripts you which to keep (backup the complete domoticz folder!)
Now install a clean raspbian distribution (the latest) on the sd card, make sure it is working (correct timezone etc etc)
Next install domoticz (with the command line option, see our webpage/download)
Now go to the settings, backup/restore, and restore your database, if that works, reinstall any extra scripts (if you were using them)

**Comment by kiddigital** [comment]
@Zaphod-dev , few things:

- The fact that the tabs are gone make sense because after your upgrade, somehow Domoticz is not able to find an active admin user when accessing the UI from within the Trusted network. If it can not determine which admin user to use (which is weird, but it seems to do so in your case), it can also not determine which tabs are active or not and therefor you are left with only Home and Setup tabs.
- Try to clear (but remember) the 'trusted network' settings. This way you should be forced to provide valid login credentials and Domoticz does not try to find admin user AND somehow fails.
- Due to the upgraded and tightened security settings, Domoticz expects a more up-to-date OS (actually up-to-date libraries like OpenSSL, etc.). Please upgrade your OS to at least Buster or better BullsEye. This cause the startup failure. You could try to disable Domoticz starting the secure webserver (use `-sslwww 0` to set the security port to use to zero meaning disable it).
- Clear all caches! TIP: You can use the 'developer-console' of most Browser and under 'Network' there often is a `Disable cache` cache option. This option forces the Browser not to decide to use anything it has locally AND sends a 'no-cache' request to Domoticz as well which forces the Domoticz webserver to serve the full content.

**Comment by Zaphod-dev** [comment]
Many thanks for your fast suggestions. I was dreading having to upgrade, but it is sound advice. I spent all day starting with a fresh Bullseye from scratch, many services running that have been tweaked over the years were tricky to reinstall and configure.
But I'm there now, all tabs and menus are visible in domoticz 2022.2 - I even managed to get altogether rid of Python 2.
Thanks again for your time. It is great software that I've become quite dependent on, including for my heating which means the temp droped steeply while I was debugging...

**Comment by kiddigital** [comment]
@Zaphod-dev , great to hear.

You mention that everything works with 2022.2? I hope you mean 2023.1? You should be fine running the latest stable.

**Comment by Zaphod-dev** [comment]
> You mention that everything works with 2022.2? I hope you mean 2023.1?

My bad, I meant latest 2023.1.
