### ISSUE TITLE
Limitless all lights switch not showing in Switches tab

### ISSUE THREAD

**Issue by jlpdiez** [domoticz/domoticz#564]
The "All lights" switch of my limitless disappeared some patches ago. I'm not sure on which though, but it had worked before.

I can control them all using the devices list no problem. I tried removing the device and adding it again but the issue is still there.

![2](https://cloud.githubusercontent.com/assets/3782057/13799359/c44a855c-eb1e-11e5-9e2c-f692e156c8f1.png)
![1](https://cloud.githubusercontent.com/assets/3782057/13799358/c4452cec-eb1e-11e5-952d-e30d65322cee.png)

**Comment by gizmocuz** [comment]
I dont have that issue here
- make sure accept new hardware is enabled in the settings
  I added a new limitedless hardware (fake udp address)
  Then i edited the hardware, set the type to RGBW
  Then added the 5 new switches

![image](https://cloud.githubusercontent.com/assets/2265299/13804834/8bd8cc2e-eb50-11e5-8a5b-d973eed7824a.png)

**Comment by jlpdiez** [comment]
Yeah, removing the hardware and adding it again did the trick, thanks.
