### ISSUE TITLE
P1 Smart Meter USB plugin causing high cpu load

### ISSUE THREAD

**Issue by barts2108** [domoticz/domoticz#5677]
Discussed in : [https://www.domoticz.com/forum/viewtopic.php?t=40290](https://www.domoticz.com/forum/viewtopic.php?t=40290)

Version : Latest beta build 15200
Platform : Raspberry Pi 4 Model B Rev 1.1
MQTT broker : mosquitto V1.5.7

WiFi plugs (Blitzwolf) with Tasmota firmware that used to work without any problems suddenly started to fail normal operation. In all cases it taks >10 seconds to get them the switch ON or OFF, in many cases they simply won't switch at all.

Checked the load and found that Domoticz has a high CPU load (the screenshot is a snapshot, CPU load ranges up to 75%)
![domoticz high load - with smart meter](https://user-images.githubusercontent.com/520875/234076932-c3c18cb5-dced-4f4d-be13-19215c2b5069.JPG)

As this happened since updating to latest beta (15200) and there have been changes to the P1 Smart meter plugin, I have disabled that plugin to test and I can see the CPU load is dropping to more normal levels

![domoticz normal load - no smart meter](https://user-images.githubusercontent.com/520875/234077328-c1a1c84d-a6cf-40ee-b32f-86349d474e08.JPG)

When the P1 Smart Meter USB plugin is disabled, all WiFi plugs switch ON and OFF again as they normally dit. Enabling the P1 plugin again causes the WiFi plugs to fail switchin on/of again. 

Seems that the changes of the P1 plugin cause this issue.

**Comment by gizmocuz** [comment]
Don't think the 'change' in the P1 meter code is causing this issue
What did you specify for rate limit? Mine is specified to 10

What's new is that every 10 seconds (not related to the rate limit) a few additional devices are updated.
There is hardly any calculation so that can not be it.
Of course you can revert to an older version to test this

Now for completion, my CPU usage from the last month, where sinds a few days it is using the new P1 code

![image](https://user-images.githubusercontent.com/2265299/234195595-050a87a0-4f15-47a0-b70e-370868b6b49a.png)

Edit: Also try disabling scripting/event system... just to check that there is no issue with this

**Comment by barts2108** [comment]
Rate limit is set to 0 (=Disabled) which has been set to this value since beginning. The P1 of the meter sends a set of data every second, if I understand well this will also cause the meter values to be processed in Domoticz ? When set to 10, will it collect the data for 10 seconds and process it in one shot, or just skip data for 10 seconds and the update one set ?

**Comment by gizmocuz** [comment]
Currently the last one, it ignores the previous 9 updates.
Like with the old meters where you got a update every 10 seconds

However, I want to change this, so it will average all received but ignored values, but that is not related to this issue
(As I have done for the new devices)

Anyway, when you have set the rate limit, how is your CPU?
And you can also disable the CRC check, this was mentioned by other users as well

I am very (99,99998 %) sure, the high cpu load has nothing todo with these new devices... but even the best make mistakes 😂

**Comment by barts2108** [comment]
Going to test several things, and will feedback. As far as I have seen those new P1 calculations *are* published to MQTT every meter update. I also cannot find a way to disable publishing data to MQTT (per device). Currently I only use MQTT as bridge for the Tasmota WiFi plugs, but all P1 meter values seem to be sent to MQTT as well.

**Comment by gizmocuz** [comment]
And you run MQTT on the same machine as Domoticz? Should not be that high CPU load

Now sure how the Tasmotta integration work with MQTT, but maybe we could speed up the code for MQTT publishing:

Place the send messages in a queue in these functions:

void MQTT::SendDeviceInfo
void MQTT::SendSceneInfo

Or somehow specify which devices to publish in the first place

If you disable MQTT all is fine as well?

**Comment by barts2108** [comment]
`And you run MQTT on the same machine as Domoticz? ` .. yep. all on the same rpi 4. Will do some investigations on this during the (long) weekend.

**Comment by RoepieRoepie** [comment]
every P1 meter update a lot of mqtt message like : Sending PUBLISH to DVES_BAF9B7 (d0, q0, r0, m0, 'domoticz/out', ... (277 bytes))
not only P1 meter updates cause mqtt messages, it looks like every value change causes mqtt messages. for example i use an http poller to read json from a smart meter every 1 sec, this event also sends mqtt messages.

**Comment by gizmocuz** [comment]
@RoepieRoepie , Sorry no idea wat DVES_BAF9B7 (d0, q0, r0) is?
Yes, every device that has a update gets published to MQTT.... has been since day one...
That 6 extra P1 devices (updated every 10 seconds) can cause the above issue, I'm not sure about that

@barts2108 , when you set your rate limit to 10 seconds, all is OK?
Why would you want this on 1 second anyway? (Unless you are monitoring something, but then set it to 1 for that time)

**Comment by barts2108** [comment]
@gizmocuz I will test tonight. I will also check the 6 new devices as I think I have seen them updating with *every* P1 meter update, but I will have to re-check that.

**Comment by RoepieRoepie** [comment]
@gizmocuz i changed the refresh of both devices (P1 meter and http poller) to 10 sec. and mqtt is working fine again.

**Comment by gizmocuz** [comment]
@barts2108, only the Actual Usage and Actual Delivery will update on each rate limit interval

**Comment by gizmocuz** [comment]
Okey, It is indeed updated every second when the rate limit is 0 ... working on it!

**Comment by barts2108** [comment]
Quoted : Even the best make mistakes 😉 

Is it an option to add another default value to the P1 rate limit, and a little extra text explaining what it is meant for ? AFAIK the default now is 0 (that's why mine is set to 0). I have no particular reason to have it at max speed other than .. "if I get the data every second, why not process it every second"

During this event : [Kortsluiting in Flevoland](https://nos.nl/artikel/2443055-na-kortsluiting-flevoland-ging-er-van-alles-mis) I could see this in Arnhem in my Grafana graphs. Furthermore I have notifications if there are severe power drops/spikes on L1, L2 and L3

**Comment by gizmocuz** [comment]
Yep, and the best also admit its faults 😁... But this wasn't my fault 😂

Please try beta 15215, that should solve many issues.

In this version, when using the rate limit, the average is calculated, and this will be used/displayed instead of the last received value.

There is a yes and a no for changing the default rate limit to a fixed default value (like 10 seconds)
A yes, less updates, system more relaxed, a no, you would not know how frequent your meter sends updates.

I think it is pretty clear that when you update each second, and also have the CRC check enabled, that this will have some impact on performance.

I added a warning notice in the P1 hardware setup.

**Comment by barts2108** [comment]
@gizmocuz : updated to build 15215 and tested WiFi plugs without any other changes, and it works as before. 

Further tested : disable MQTT plugin : not much change in cpu usage (maybe -10% at most)
Further tested : rate limit 1 -> no change; rate limit 2 -> little less cpu load; rate limit 10 -> cpu load around 10%

During all tests, mosquitto broker is always less than 1% cpu load but gets the same load of MQTT (and even more).  Would be interesting to know how and approx 950 character message per second can give such a high load.

**Comment by gizmocuz** [comment]
@barts2108 , okey so this is not related to the new devices

"it works as before.", before you updated to 15200?

If you disable MQTT, there was no CPU decrease? Or 10%, 10% is a lot... and what is your normal CPU rate?

When you make a bash script (with a loop) and publish messages to your MQTT broker, is this slow as well?

Do you have the CRC check enabled, what happens when you disable this?

**Comment by barts2108** [comment]
"Works as before" was indeend meant as before update to 15200.

Tests:
-------------------------------------------------
**Using "top" on domoticz rasberry pi with the following options**
- Irix mode  : On
- Scan delay : 1s
- Sorted col : TIME+

**CRC ON**

- Rate limit 0: CPU load : ~45-75% ( With MQTT OFF : Cpu load : ~35-68% )
- Rate limit 1: CPU load : ~40-75% 
- Rate limit 2: CPU load : ~30-65% 

**CRC OFF**

- Rate limit 0: CPU load : ~40-65% 
- Rate limit 1: CPU load : ~40-65% 
- Rate limit 2: CPU load : ~30-65% 

**P1 Smart meter plugin DISABLED**
- CPU load : ~0-35%

-----------------------------------
**Using "top" on domoticz rasberry pi with the following options**
- Irix mode  : Off
- Scan delay : 1s
- Sorted col : TIME+

**CRC ON**
- Rate limit 0: CPU load : ~7-15%  ( With MQTT OFF : Cpu load : ~7-15% )
- Rate limit 1: CPU load : ~7-15% 
- Rate limit 2: CPU load : ~3-12% 

**CRC OFF**
- Rate limit 0: CPU load : ~7-13% 
- Rate limit 1: CPU load : ~7-13% 
- Rate limit 2: CPU load : ~1-20% (more irregular)

**P1 Smart meter plugin DISABLED**
- CPU load : ~0-10%

---------------------------

Then sent some load to the MQTT broker from the terminal using following bash script (and no 12345 is not the real password, nor is 'raspberry' )

```
#!/bin/bash
#
# mqtt_data.sh - send data to MQTT broker
#
# Get Data values

# Publish Data
server="192.168.199.200"
cntr=1

for ((j=1;j<1000;j++)); do
  for ((i=1; i < 100; i++)); do
    ((cntr=cntr+1))
    mosquitto_pub -h $server -u pi -P 12345 -t mqtt/test/temp -m  $cntr
  done
  sleep .5
done
```

Takes ~1% CPU according to 'top' with Irix mode OFF
Takes ~3-5% CPU according to 'top' with Irix mode ON

-----------------

The CPU load reading is fluctuating (maybe that's why my readings are different from before), tried my best to get the best *hi* and *lo* values. Also the ```top Irix``` mode is showing a very different percentage. If I take an educated guess Irix mode OFF is the one that is to use for CPU usage, while the default is Irix mode ON.

The numbes above show (I think) that still the P1 plugin is causing quite high load compared to the rest. 

Yesterday installed VS2022 and will see if I can get somehting profiled in there.

**Comment by gizmocuz** [comment]
You’ve seen my CPU load above …. That’s nothing
What are you using for hardware?

your rate limit is still very low, try setting this on 10

i have a rpi 2 running with p1 as well with lower cpu

**Comment by barts2108** [comment]
I have a pi4 rate limit on 0, setting it to 10 lowers CPU, but kills my option to trigger on low/high voltages from the grid.

**Comment by barts2108** [comment]
![Screenshot_20230426_202122_Firefox](https://user-images.githubusercontent.com/520875/234667984-1439cbed-4017-470e-86fb-7beca14b3805.jpg)

I thought the rpi info was not enabled, but it is. This is my cpu load. I guess cpu load when using the top command is at least confusing.

**Comment by gizmocuz** [comment]
Okey going back to the original issue

Please revert to a version before 15200 (see your backup folder)

Do you still have the same CPU load? In this case, please close this issue and of course try to do a performance/profile test with visual studio

This because in the recent beta, only each 10 seconds you get a few additional devices and that will not spike up your cpu load
Your load is already high to begin with

I just checked on my old raspberry, it has a load of 5% with a rate limit of 10

And for you high voltage detection, remember that smart meters (before ESM 5.0) reports every 10 seconds
So you should still be able to perform your check with this data rate

What are you going to do when your voltage is on your 'high' threshold? Using a Shelly EM3 Pro to disconnect the house of the grid? 😂

If you have solar panels installed, voltages are higher and can even go to 240+ volts

**Comment by barts2108** [comment]
In the history from the pi sensors you can see that the cpu load is quite stable. Until now I did not disable the dzVents yet, but now I just disabled the dzVents (from settings, and my 60% cpu drops to below 10% (with default top command). 
Then with dzVents on again I disabled all scripts one by one, but only if I disable ALL scripts the cpu load drops. if I switch on 1 script, cpu load goes back up already. The script triggers posted here... nothing serious.

(device 205 is a LacrosseTX3 temperature sensor... this script is executing once per 10 minutes and when the (living room) temperature changes.)

```
local devicemap = {
    [205] = {remoteidx = 25}, -- Temperature, Livingroom   (Eurtronics Thermostaat)
}

return {
	on = {
		devices = {
			205
		},
		timer = {
		    'every 10 minutes'
		},
	},
	logging = {
        level = domoticz.LOG_ERROR,
        marker = "SendTemperaturesToSlave"
    },
	
	
	execute = function(dz, device)
	    if (device.isTimer) then
            local temp  = dz.devices(205)
            dz.openURL({
                url = 'http://192.168.199.20:8080/json.htm?type=command&param=udevice&idx=' .. devicemap[205].remoteidx .. '&nvalue=0&svalue=' .. temp.temperature,
                method = 'GET',
                callback = ''
            })
    		dz.log('Device ' .. devicemap[205].remoteidx .. ' was changed to ' .. temp.temperature, dz.LOG_INFO)

	    else
            dz.openURL({
                url = 'http://192.168.199.20:8080/json.htm?type=command&param=udevice&idx=' .. devicemap[device.idx].remoteidx .. '&nvalue=0&svalue=' .. device.temperature,
                method = 'GET',
                callback = ''
            })
    		dz.log('Device ' .. devicemap[device.idx].remoteidx .. ' was changed to ' .. device.temperature, dz.LOG_INFO)
	    end
	end
}
```

My electricity meter reports every second, gas is slower. I put the notifications when the supplied voltage is under or above [allowed tolerance](https://www.stedin.net/klantenservice/veelgestelde-vragen/zelf-energie-opwekken/spanningsproblemen/welke-eisen-zijn-er-gesteld-aan-de-maximale-en-minimale-waarde-van-de-spanning). 

In case an overvoltage causes damage to my connected devices, I have at least a notification, that there has been an overvoltage

![image](https://user-images.githubusercontent.com/520875/234806698-96a64226-6e28-42b9-bda6-2877ffb08bf6.png)
![image](https://user-images.githubusercontent.com/520875/234807347-e007e119-db20-4bab-9aa7-8c47478ec3c5.png)

I will close this issue as it was solved in 15215 ... of course when I find other issues, you will find me back here 😝

**Comment by gizmocuz** [comment]
When you use the EMR5.0 (And I think also the DSMR 4.0) you should also have devices like P1 Voltage swells L1/L2/L3, and those are the numbers you are looking for

So probably you have an issue with one of your scripts, you did not post your complete script, and by looking at the name of it, this could indeed be the issue

"SendTemperaturesToSlave" ... how/what

If you find anything, please create a new issue, always good to have faster software, aldo I think it is already superfast and efficient 🤣😎

**Comment by barts2108** [comment]
I just do this here (as not to open a new issue). Updated earlier post with full script. The script is not executed more than once in 10 minutes, as the temperature is quite stable. Wondering why cpu load goes up when all scripts except this one are disabled. it should nearly not do anything, but probably it does. 

I had a look at the new devices... indeed there is swell and sags devices with numbers in it. Usefull but it doesn't tell how much the sag or swell was. Small feature request here... can you add a device for the `P1TIP` as well somewhere in the (near) future ?

I will try my best to spend some more time on this...

**Comment by Barry40** [comment]
Same problem here with p1 and high cpu on rpi 4b.. when do an update of 5 seconds instead of 0, my cpu went down to 15-25%, but after using 0 it goes up to 108% and higher, and the core temp is rising from 62°c to 75°c..
Also with update 0 mqtt does not work properly, it misses a lot of hits after pressing a button.
It looks like that the raspberry is very, very busy with its p1 data when do 0 seconda updating.

When update to 5 seconds everything works normal again..
I'm not using mqtt for p1, just the p1 meter in hardware.

My guess it that domoticz is pushing a lot of data out to mqtt as well when using 0 seconds in p1 hardware?

0 seconds update > high cpu:
![Screenshot_20230523_181447_JuiceSSH](https://github.com/domoticz/domoticz/assets/18517382/4c978970-bd1e-44d1-8c62-1b7b373f789e)
Update 5 seconds > low cpu:
![Screenshot_20230523_181350_JuiceSSH](https://github.com/domoticz/domoticz/assets/18517382/04c35d48-6722-4d60-875e-d2359aff1fdc)

**Comment by Barry40** [comment]
Temperature core log:
![Screenshot_20230523_182623](https://github.com/domoticz/domoticz/assets/18517382/26e6851b-23de-4f5c-9a04-2d26dc4b8b0b)
As you could see, after set the p1 to 5 sec the temp is going down to 65°c instead of 80+...

**Comment by gizmocuz** [comment]
Yes, so use a poll interval of 10 seconds. When you want to debug your grid, set it to 1, in normal scenario 10 or 60 would do

And yes, you get a lot of sensors that are being send to MQTT

Question, where do you use MQTT for? Domoticz master/client connection not working out?

**Comment by Barry40** [comment]
Thanks for answering, but as far as i know, it was never this high before..?
I'm on beta, Version: 2023.1 (build 15248)
Build Hash: cbeebf26a

Op wo 24 mei 2023 08:09 schreef gizmocuz ***@***.***>:

**Comment by gizmocuz** [comment]
There have been added some additional sensors
Is it possible to answer my last questions to get a better insight ?

**Comment by Barry40** [comment]
> Yes, so use a poll interval of 10 seconds. When you want to debug your grid, set it to 1, in normal scenario 10 or 60 would do
> 
> And yes, you get a lot of sensors that are being send to MQTT
> 
> Question, where do you use MQTT for? Domoticz master/client connection not working out?

I use it for zigbee2mqtt, phoscon conbee, mqtt autodiscover and a lot of mqtt devices like tasmota flashed devices (sonoff/esp82* for example)

**Comment by gizmocuz** [comment]
@Barry40 , there are two different types of MQTT in Domoticz.
- Normal MQTT that outputs inputs all devices (do you need this??)
- MQTT Auto discovery (you should not get a high cpu load with this)

With your tasmotta devices, I believe when you enable option 19, you could use the MQTT Auto Discovery with this and you wont need the first MQTT implementation

https://techoverflow.net/2022/01/18/how-to-enable-home-assistant-mqtt-auto-discovery-on-tasmota/

**Comment by Barry40** [comment]
Thanks for answering.
I need mqtt out because if i disable it my sonoff and other switches does
not work anymore..
In a new setup im want to use z2m and mqtt autodiscover and not phoscon anymore, but for now i need to leave it like this because otherwise i have to add all devices again.

Op vr 26 mei 2023 08:56 schreef gizmocuz ***@***.***>:
