### ISSUE TITLE
P1 Wattage sensor is showing different usage then power.

### ISSUE THREAD

**Issue by paulkoorn** [domoticz/domoticz#5703]
the wattage en power shown is totally different.
the power consumption is correct but i don't know how the wattage got so different.
updated a week or so ago then the problem started. think one of the p1 changes.
224 is the correct usage 
![domoitcz](https://github.com/domoticz/domoticz/assets/3087495/80db135f-97f7-4d9c-8f27-d13c3430ffed)

**Comment by gizmocuz** [comment]
That is because the newly added sensors are averaged.
So if you have set your poll interval to 10 seconds (which is a good value), it will keep a record of all records received in these 10 seconds and do a average. It is actually much more accurate.
The new meter ESMR5 will output it's status every second

**Comment by paulkoorn** [comment]
ah i put the poll interval to 10 seconds and now its giving the correct value.
i had it on 300 seconds before and then it just gave it a really high value.

**Comment by gizmocuz** [comment]
Thanks for reporting. That could very well be the reason as I expected that one put a lower interval then 255 seconds.
This has been corrected and now you can set an interval time up to 32767 seconds (~ 9 hours)
Solved in beta 15332
