### ISSUE TITLE
Graph error No Data to display

### ISSUE THREAD

**Issue by differentieel** [domoticz/domoticz#5707]
Version: 2023.1 (build 15330)
Build Hash: c91461ca0
Compile Date: 2023-06-03 08:07:05
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

error:

Status: [WebServer] Depricated RType (graph) for API request. Please use correct API Command!

update && upgrade + full-upgrade done
./updaterelease - no change - error still there
./updatebeta - webserver comes up - no data to display is back
error appears on all graph windows

**Comment by kiddigital** [comment]
Make sure you clear the browser cache as your UI/Browser is using an old call instead of the updated one.

See also the status message. If your cache is clear, that status message should not appear when using the Domoticz UI.

TIP: open your Browser Dev-tools (F12), select the network-tab and check the 'Disable cache' option. Now request the index page again ('/') and all javascript gets reloaded.

**Comment by differentieel** [comment]
thank you for responding
after restarting my iPad - where i look all te time - graphs are back again
