### ISSUE TITLE
new error  message "Depricated RType"  since last beta update

### ISSUE THREAD

**Issue by sebitop** [domoticz/domoticz#5716]
Hi All
since update 2023.1 15344  I have a new message in the log:

_Depricated RType (scenes) for API request. Handled via fallback (getscenes), please use correct API Command! (192.168.0.X)_

could you help me find how to solve it ?

thanks

**Comment by kiddigital** [comment]
Hi @sebitop , it is not an error but a status message. So nothing is broken.

But you are probably running some custom scripts and/or alternative dashboard or something.

That 'something' is making API calls from 'myraspip' to domoticz.

The API has been update and instead of using `/json.htm?type=scenes&...` it should now be `/json.htm?type=command&param=getscenes&...`.

The domoticz UI already uses the updatend API-calls.

**Comment by sebitop** [comment]
Brilliant
thaks for this precious info
right i found that I have a script calling scenes
so replaced "json.htm?type=scenes"
by json.htm?type=command&param=getscenes"

thanks a lot for your quick answer and support !
