### ISSUE TITLE
Openssl3.0 and 2023.2

### ISSUE THREAD

**Issue by Krakinou** [domoticz/domoticz#5751]
Following https://www.domoticz.com/forum/viewtopic.php?p=304816#p304816
It seems that compiling the source code with ubuntu:latest instead of ubuntu:20.04 as prior to version 2023.1 makes domoticz not runable on OS with openssl1.1 instead of openssl3.0 (such as debian bulleyes and I assume many other OSes).

I don't know if it can be reverted now, as it is already officialy released, but at least a warning somewhere may be a good idea.

**Comment by gizmocuz** [comment]
Yes, and we might update to a new openssl version soon (maybe not 3, but the new version 1)
And this is released like this on purpose because a lot of users are not using that ubuntu version you are running on (or raspbian, or armbian)
So to solve your current issue, and for users using the new openssl version (1,2 or 3.......) you can use the docker (compose) version of Domoticz.
