### ISSUE TITLE
Meter device issues since 2023.2 upgrade 

### ISSUE THREAD

**Issue by HB787** [domoticz/domoticz#5763]
I have a managed counter device that is fed by a PHP script to show water usage.
Since the update it starts with a negative number, it seems to use the negative value of the real usage from the day before.

The device is not accurate anymore and that is a pity because it worked for years.
Tried to start the new day with a zero, the PHP script is also checked on not sending negative numbers.
Nothing works it just starts with a huge negative number everyday. 

Raspberry, z-wave, 2023.2 firmware
Build Hash: 19efd039c
Compile Date: 2023-07-21 17:23:44
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

**Comment by gizmocuz** [comment]
Could you try with the latest beta version? There have been made some changes
Or was there counter reset and the next day it was correct?
Maybe your script could provide some details, could you post this?

**Comment by HB787** [comment]
I wrote a PHP script to add the data, here is the part that sends it to the device:
   if (strlen($status) < 100){goto start;}
    $data = json_decode($status,true);
    // watermeter
    $watertot  = $data['response']['energylinks']['0']['s2']['dayTotal'];
    // $watertot = max(0, $watertot); // $watertot will be set to 0 if it was less than 0
    // Schrijf in log
    web('n',"http://localip:channel/json.htm?type=command&param=addlogmessage&message=Retrieve water from HomeWizard, liters: ".$watertot);
    // $waterlive  = $data['response']['energylinks']['0']['s2']['po'];
    if(is_numeric($watertot) and $watertot > 0) {
                web('n',"http://localip:channel/json.htm?type=command&param=udevice&idx=5671&nvalue=0&svalue=".$watertot);
        }
    echo "-------------------------\n";
    echo "Waterverbruik:\n";
    echo "Water dagtotaal: ".$watertot." liter\n";
    echo "-------------------------\n";

The outcome of the script:
-------------------------
Waterverbruik:
Water dagtotaal: 311 liter
-------------------------

I can't move to the Beta version yet because I need to get rid of the Open Z-wave stuff.
BTW the script worked for many years until the 2023.2 upgrade.
I saw that there was a change in the code, I will install the new Z-Wave environment first and try the move to the Beta version.

**Comment by gizmocuz** [comment]
Thank you for the script. I will wait until you can test the beta version. You can also make a complete backup of the domoticz folder and restore this
But better to solve your zwave issue first ( I recommend docker compose for this)

**Comment by sincze** [comment]
Cewl script. tnx.

However to keep it simple, I went for the plugin version to get the data from homewizard watermeter into Domoticz
https://github.com/Eraser3/HomeWizard-Wifi-Watermeter

**Comment by waltervl** [comment]
Just for the record: API command for updating a Managed meter is:

/json.htm?type=command&param=udevice&idx=IDX&nvalue=0&svalue=COUNTER;USAGE

Its seems your script is missing the COUNTER value.

**Comment by GravityRZ** [comment]
@waltervl 

can you explain what needs to be changed
i am using the exact json call to update my watermeter
SendToHTTP 192.168.1.50,8084,/json.htm?type=command&param=udevice&idx=344&nvalue=0&svalue=[Watermeter#Total]

device 344 is a counter(i think it is not managed it states rfxmeter)) and the svalue pushed is the total counter value.
i understand we need to add the usage  part but why. we never update the usage, domoticz does that when we push the svalue

also sending out the usage will maybe overwrite the current usage and that is the last thing we want.

please explain how to change the json code(or do we only need to add a ; after the counter value or perhaps ;-1)

my setup should be good to go because i have  a normal counter but i switched back to 2023.1 so i can not test it
@HB787 states he is using a managed counter
maybe he can change it into  a normal  counter if that still works

**Comment by waltervl** [comment]
For a counter https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Counter
the command is
 `/json.htm?type=command&param=udevice&idx=IDX&svalue=COUNTER`

**Comment by waltervl** [comment]
Closing this issue due to no feedback from @HB787
