### ISSUE TITLE
Netatmo hardware do not connect anymore

### ISSUE THREAD

**Issue by didi31** [domoticz/domoticz#5766]
Hi
Since version 2023.1 and the change from Netatmo on the autorisation process, the Netatmo plug-in generate the following error: Access not granted check username and password whilst I can connect to the Netatmo web site with.

**Comment by jpcasta** [comment]
Hello,
Same issue here.
It seems it is due to the security change on Netatmo side to get the data.
Any workaround does no longer work. 
Is there a possibility the way to connect to Netatmo is updated?
Thanks

**Comment by gizmocuz** [comment]
Indeed, since another change on the Netatmo side it does not seem to work anymore
I have used their hardware in the past, but it broke and I found it to expensive to replace.
I am not using it anymore and someone else need to have a look at this… I am using zigbee now

This could be a solution

https://github.com/seblucas/netatmo2mqtt

In combination with the domoticz MQTT Auto discovery hardware

**Comment by didi31** [comment]
I saw that it work on Homeassistant. Maybe someone could have a look on how it is done?

If it can help...

I followed the Netatmo instruction [https://dev.netatmo.com/apidocumentation/oauth](url) manually
I have declare an application in dev.netatmo.com and I have a clientId and client_secret keys.
I constructed the url in a text editor and copy it in a browser.
I have been redirected to a page to grant the application the access to my data.
They send me back a code inside the url of the browser
`https://app.netatmo.net/oauth2/domoticz.luberriaga.fr?state=%22A1B2C3ddddddd444443333311111%22&code=xxxxxxxxxxxxxxxxxxxxxxxxxxx`
with an error message 
`{
error: {
code: 404,
message: "method not found"
}
}`
With dzVent code below I succeed to retreive the tokens

` 			dz.openURL({
                url = 'https://api.netatmo.com/oauth2/token',
                method = 'POST',
                callback = 'Netatmo_getToken',
                headers = { ['Content-Type']='application/x-www-form-urlencoded;charset=UTF-8' },
                postData = 'grant_type=authorization_code'
                    ..'&client_id='..client_id
                    ..'&client_secret='..client_secret
                    ..'&code='..code
                    ..'&redirect_uri=domoticz.luberriaga.fr'
                    ..'&scope='..scope
             })
`
Is it possible to do the same process from dzVents?

**Comment by Onshuis** [comment]
Since July 2023 the bridge described on this page (https://skyynet.de/netatmo.php) no longer works due to a change at Netatmo. The programmer has archived the project at GitHub, so that no further development can be assumed. If there's a working fork, I'd be happy to hear about it.

So yeah, bit pitty though. Perhaps ask Netatmo to losen their security and get the special character out??

**Comment by gizmocuz** [comment]
So that is two projects having a issue with their change….

**Comment by Onshuis** [comment]
Yes, but i refuse to migrate to home assistant!!!!!!

**Comment by gizmocuz** [comment]
Okey, how about swiching to Zigbee or 433Mhz (RFXCom) instead?

**Comment by didi31** [comment]
As far as I understood, the modification of the code should be minor.
Unfortunately I don't know cpp...
DzVents could be a solution: https://www.domoticz.com/forum/viewtopic.php?p=305373#p305373

**Comment by waltervl** [comment]
@pipiche38 @olivierberthomme  @StephaneM60 
As you previously fixed some issues in the netatmo.cpp hardware, are you able to fix this netatmo authorization issue?

**Comment by StephaneM60** [comment]
Hi,

I reviewed the code and the issue is that since October 2022 the authentication API used here is no longer available.

Instead we must use an authentication method that requires interactive user input.

The flow is : you configure in Domoticz the Netatmo hardware, and there will be a redirect to the Netatmo web site so that the user can authenticate here and send back to Domoticz a code, that we can use instead of the username / password used today, to get the token needed for the Netatmo integration to work. So there is a need of a redirect URL.

I don't know how to do that in Domoticz (that is : from the hardward setup, make the user authenticate on Netatmo website and set up a web listener (or intercept the redirect url wich contains the code needed, as it is passed in the request uri)

If there is already a hardware integration that does this, could you tell me which one to see how it's done and apply it to the Netatmo integration.

PS: on my domoticz setup, the Netatmo integration still works because, it's only the initial setup that changed, renewing the token after the initial authentication still works (and if your domoticz instance is not stopped for too long will not requires a new authentication)

**Comment by gizmocuz** [comment]
This is called OAuth2, from the hardware class you can make a https connection to that site, check the response, there is probably some hidden input with a data/key , but maybe not.
Then you can use the same call as this page with the username/password, and you will get the token back
If you search for token, you find more hardware in domoticz that adopts this

**Comment by StephaneM60** [comment]
Yes this is OAuth2, though I really don't see how I can from the code make the user browser go to the Netatmo web site to authenticate itself and then get the code back.

For me to get the code back there is 2 way: 

1) Having a webhook in Domoticz to receive the data the Netatmo server will send back (the webhook uri is given to the netatmo api when redirecting the user to the netatmo web site in the first place)

2) Or as it's only a browser redirect (and not a server to server communication) intercept the redirect response if we are in control of the view making the web call to the Netatmo web site.

The only thing I know how to do is : HTTPClient::POST from the cpp code, but I don't know how to present to the user the Netatmo web site.

**Comment by gizmocuz** [comment]
There is no need to present the user with a netatmo website as explained above. You have to perform the steps above.
First start looking into the already existing hardware classes that also use OAuth to retrieve the token.
Better yet, first use your browser and have the developer console open and look whats happening and being posted
Then use Postman , then start the implementation in the netatmo hardware inside domoticz

**Comment by kiddigital** [comment]
@StephaneM60 ,

Depending on the type of OAuth2 flow (or actually [grant type](https://alexbilbie.github.io/guide-to-oauth-2-grants/)), there are different ways to obtain a _Token_.

Most common usage, and probably what Netatmo uses, is the _authorization code grant_. This means you have to request an _access_code_ first. You can get this code via the right request to the Netatmo site. The site will request user identification and will redirect the user back to a given URL with an _access_code_ as parameter.

This _access_code_ can then be exchanged for a _Token_ and usually also a _Refresh_Token_. This exchange is done __without__ user interaction.

In most Domoticz setups where domoticz runs on an internal network and does not have an outside reachable FQDN (not recommended as it is hard to secure properly), you cannot redirect a domoticz UI user to the internet AND get redirected back to the UI (problem for your point 2 as we are _not_ in control).

Therefor some hardware modules let the user perform the first step 'on their own' and ask for an _access_code_ in the Hardware setup. The hardware module can exchange that code to get a _Token_. And using the _Refresh_Token_, once a Token expires, a new _Token_ (and new _Refresh_Token_) can be requested. That way, no user interaction is needed as long as the module keeps refreshing the Tokens and Refresh Tokens.

Although not the most User-Friendlies method, it is not hard to implement and domoticz owners don't have to perform that procedure often. Normally 1 time (unless something is down and Token are not refresh and the Refresh Token expires).

Hope that helps.

**Comment by gizmocuz** [comment]
Have a look here

https://github.com/philippelt/netatmo-api-python

**Comment by StephaneM60** [comment]
I do understand how the system works. I'm not Ok with user going to the dev.netatmo.com web site to register an application and get a token (especially as I don't know if the client id and client secret are related to the token to work properly)

The way to do it properly is : 

when adding the netatmo hardware in domoticz, the hardware cpp should have a method to call so that domoticz during setup opens for the user a new browser window to the netatmo web site (with parameters set up by the hardware cpp code)

The user authenticates and then the netatmo web site redirects to the domotociz user web site (it doesn't need to be accessible from the Internet at this is a browser redirect). The domoticz URL is a URL the hardware cpp code has passed as a parameter initially

Upon redirecting, domoticz must have a way to call back the hardware cpp code again : because the URI is formatted to do so; additionnaly netatmo forward a parameter that we initially embedded in the first request; but this one is intended for the hardware cpp code.

This way the hardware cpp code can get the token and nothing else has to change. The second method that act upon the redirect should requires a response code from the hardware cpp code for letting know to the user if the setup was successfull in the end.

**Comment by gizmocuz** [comment]
If the token/secret stays valid now (so no need for a refresh token), it might be easiest to start with the copy/paste thing and later build some c++ http handshaking around it.

**Comment by leopoldwang** [comment]
It seems only login function needs polishing but I don't have c++ development environment setup. :(

https://github.com/domoticz/domoticz/blob/development/hardware/Netatmo.cpp#L190-L261

**Comment by StephaneM60** [comment]
@leopoldwang It's not that it needs "polishing". There is two options :

for both : removing netatmo username and passord for the hardware configuration.

Option 1 : ask to the user instead of username and password, a code that it will get itself from Netatmo dev web site (so there is documentation to write somewhere to let know the user how to do this)

Option 2 : implement the oauth authentication process as I described.

For Option 1 : I can do it but not right now (and I do not have currently my C++ dev env. ready).

For Option 2 : I don't know how to do it (as it implies domoticz web ui and callbacks from the web ui to the hardware integration code)

**Comment by leopoldwang** [comment]
Thanks @StephaneM60.

Option 1 looks good enough for me? Asking a user to put in client id, secret and access token is surely straightforward enough with some documentation.

**Comment by Fill1234** [comment]
Option 1 indeed. Is it also possible for smoke and co2 detectors?

**Comment by kiddigital** [comment]
If someone with 1 or more Netatmo connected devices is willing to lend me their development credentials, I can see if option 1 can be realized.

Send me a PM if so.

**Comment by jcbraem** [comment]
> If someone with 1 or more Netatmo connected devices is willing to lend me their development credentials, I can see if option 1 can be realized.
> 
> Send me a PM if so.

Hello,
I have sent all informations by email.
Thanks in advance for your work :)

**Comment by kiddigital** [comment]
Great, a few Netatmo device owners reacted so I now have some devices to test with.

I will update this issue on progress.

**Comment by Fill1234** [comment]
Do you still need a smoke/co2 sensor?

**Comment by kiddigital** [comment]
> Do you still need a smoke/co2 sensor? 

For now I think we are fine. The working assumption is that only the login part has to be updated/fixed and all the devices remain the same.

**Comment by kiddigital** [comment]
> Do you still need a smoke/co2 sensor?

@Fill1234 , Please test Beta 15535 (or higher) and let us know if your smoke/co2 sensor works now in domoticz.

**Comment by Phil353556** [comment]
Hi, I am testing the last version of netatmo plugin with domoticz beta [2023.2 (build 15667)]
Great job, it works with the latest authentification implemented by netatmo. Thank you!
However the behavior is that percentage level, for netatmo devices with battery, is tested only one time at startup. (in /tmp/domoticz.txt reference is Netatmo: General/Percentage)
Is it normal?
How to enhanced that?  one time per day could be good enough.
Thank you

**Comment by Fill1234** [comment]
Hi, i'am on the latest Beta (2023.2 built 15727).
The hardware Netatmo is added and the credentials filled in (username : client id, pw : client secret).
Should i run a script, and if so which one?
Thanks

**Comment by Phil353556** [comment]
no
go to "configuration" "hardware"   netatmo should be seen
then go to "configuration" "device"     and add each device you want using the green arrow on the right.

**Comment by Fill1234** [comment]
With devices non netatmo device is show.
With hardware i only see the netatmo that i added

**Comment by jpcasta** [comment]
In the settings, did you allow the creation of the devices?

**Comment by Fill1234** [comment]
Yes, but i keep having this : Error: Netatmo: No access granted, check credentials...

**Comment by jpcasta** [comment]
That means something is wrong in the information you specified for authentication.
As specified in the wiki:
- the username should contain <client_id>:<client_secret> (do not forget the colon character)
- The password is not client_secret as you wrote in your previous message
   The password is the code you get after using the URL specified in the wiki and that starts with: 
       https://api.netatmo.com/oauth2/authorize?client_id=<YOURCLIENTID>&redirect_uri............
Hope that can help

**Comment by Fill1234** [comment]
Hi,
I'am sorry. I found out the password thing allready.
Now i don't get that error anymore but still not a smoke detector with devices

**Comment by JurgenLB** [comment]
Currently not all Netatmo devices are available in Domiticz. The API and the scopes need to change for that.

**Comment by Phil353556** [comment]
and do not modify the URL indicated on the webpage: https://www.domoticz.com/wiki/Netatmo
scope=xxxx
I tried to remove one (the smoke detector because I don't have it, wrong choice)
with the URL as written it is ok.
https://api.netatmo.com/oauth2/authorize?client_id=<YOURCLIENTID>&redirect_uri=http%3A%2F%2Flocalhost%2Fnetatmo&state=teststate&scope=read_station%20read_thermostat%20write_thermostat%20read_homecoach%20read_smokedetector%20read_presence%20read_camera

**Comment by Fill1234** [comment]
I do use the url from the website.
Is it possible that the smoke detector has to give an alarm before it is visible in the devices list?

**Comment by JurgenLB** [comment]
@Fill1234 I believe Netatmo changed the Endpoint for some off their devices
