### ISSUE TITLE
Last beta: openzwave usb has disapeared

### ISSUE THREAD

**Issue by ldrolez** [domoticz/domoticz#5789]
After upgrading to Version: 2023.2 (build 15503),
my Zwave USB stick does not work. On the hardware section I don't see "OpenZWave USB".
Hardware type is now "Unknown".

**Comment by sincze** [comment]
Isn't that because OpenZWAVE was removed from that Domotiz version onwards ??
Needs migration to Zwave-JS-UI.

https://www.domoticz.com/wiki/Zwave

From Domoticz BETA 2023.2 (30-jul-2023) you have to use [Zwave-JS-UI](https://www.domoticz.com/wiki/Zwave-JS-UI) autodiscover with standard Domoticz [MQTT Auto Discover client Gateway.](https://www.domoticz.com/wiki/MQTT#Add_hardware_.22MQTT_Auto_Discovery_Client_Gateway.22)

See wiki page [Zwave-JS-UI](https://www.domoticz.com/wiki/Zwave-JS-UI) . Domoticz version Stable 2023.2 is the last version with OpenZwave (OZW) integration.

!!! OpenZwave has been removed from Beta 2023.2 !!!

**Comment by ldrolez** [comment]
ok! lots of lost hours in migration in view :)

**Comment by sincze** [comment]
> ok! lots of lost hours in migration in view :)

If you follow the wiki and ... keep fingers crossed ... can be done quicker.
