### ISSUE TITLE
V_PERCENTAGE for Blinds

### ISSUE THREAD

**Issue by boe666** [domoticz/domoticz#5843]
V_PERCENTAGE is not working (mysensors) for BLIND type.

**Comment by gizmocuz** [comment]
What's not working? Did you enable accept new devices?
There should be a switch/dimmer with the percentage

**Comment by boe666** [comment]
For S_COVER, domoticz don't show roller blind's status. The progress bar not work in both direction (show status and set status).
The same NOD, but with S_DIMMER definition - works fine. The progress bar work in both direction.
Diference between DIMMER and COVER is STOP BUTTON - longterm us BLIND as DIMMER is not a solution. That's why a wrote this issue.

**Comment by gizmocuz** [comment]
Thanks, it is getting a bit clearer now.
Are you able to compile Domoticz?

Please have a look in hardware/MySensorsBase.cpp

For S_DIMMER we set the vType as V_PERCENTAGE
For S_COVER we set the vType as V_UP

It has been years since I worked with MySensors, but it might be solved when you change V_UP to V_PERCENTAGE ?

**Comment by boe666** [comment]
I won't be able to compile the entire "domoticz". But you may be right that there is an error in this file. The question is whether it would be possible to release a version with the change, because no one from mysensors uses S_COVER for roller blinds anyway.

**Comment by gizmocuz** [comment]
Find a guide below how to compile Domoticz:

https://www.domoticz.com/wiki/Build_Domoticz_from_source

What OS are you using?

What are others from mysensors using for blinds?

**Comment by boe666** [comment]
according to my knowledge (I do it myself) - NODs report as DIMMER for each blind (V_UP,V_DOWN,V_PERCENTAGE). The additional V_STOP is implemented via an additional SWITCH. We have two controllers for each roller shutter.
I use WINDOWS10 and UBUNTU 10.

**Comment by boe666** [comment]
Can You change code in this one place (replace V_UP to V_PERCENTAGE) on the next domoticz's version ?

**Comment by gizmocuz** [comment]
This could mean that current MySensor users could get issues.
Could you not just compile yourself?
Under Windows this is quite easy

**Comment by gizmocuz** [comment]
No response, please feel free to re-open when you compiled yourself and tested this (and made a PR if it is solved... and only if it will not break devices for existing users)

**Comment by dziura666** [comment]
hi, I have same problem with blinds (percentage not working for device type: "Blinds, RollerTrol/Hasta,BlindsPercentage" and "Blinds, RollerTrol/Hasta,Blinds + Stop" )

tried this:
"Please have a look in hardware/MySensorsBase.cpp

For S_DIMMER we set the vType as V_PERCENTAGE
For S_COVER we set the vType as V_UP

It has been years since I worked with MySensors, but it might be solved when you change V_UP to V_PERCENTAGE ?"

and compiled domoticz locally- same problem still exists. 

Do you have any other suggestions what can be checked?

Also other question, maybe answered somewhere else, but cannot find: why domoticz creates 2 devices per one blind configured in mySensors ("Blinds" and "Light/Switch")?
![image](https://github.com/domoticz/domoticz/assets/175212947/0fa5f38e-a7ca-4b00-9f69-cb60c1bc8dbc)
