### ISSUE TITLE
mqtt auto discovery merges 2 different sensors into one

### ISSUE THREAD

**Issue by HV-NL** [domoticz/domoticz#5870]
_Domoticz2023.2 (build 15640), running in a Docker image on Raspberry Pi 4_

I try to add the Faikin module data (proprietary Daikin wifi replacement) to my Domoticz. 
Faikin supports mqtt discovery. The faikin module announces itself (`308398CEE264`, all airco related items) and its sensors (`outside`, `liquid`, `comp`, `fanfreq`). 

As I added a BLE temperature/humidity sensor to the Faikin config, it also announces those 2 items (`bletemp` & `blehum`)

These are the announcements:
[mqtt advertisements.txt](https://github.com/domoticz/domoticz/files/13310446/mqtt.advertisements.txt)

But as a result Domoticz does not create a dedicated sensor using only the BLE data, but it seems to mix the outside temperature (`outside`), the ble temperature (`bletemp`) and the ble humidity (`blehum`) data into the one new sensor (`Faikin-eetkamer (blehum)`) .

99% of the time the temperature that is shown in this sensor is the outside temperature, so the contents of `outside`, with some flashes of the correct `bletemp` temperature. 

But 'outside' is temperature-only. so it does not have a humidity value, only a temperature value.

- the sensor belonging to `outside` is not created 
  (but merged into `blehum`)
- for `liquid` I do not see a related Domoticz sensor

This is what I expect to see (screenshot taken in a fresh HomeAssistant environment):
![afbeelding](https://github.com/domoticz/domoticz/assets/33630544/f9d5ce42-84c6-44af-b409-9df00a4278a4)

But this is what I see using mqtt auto discovery in a fresh Domoticz (`Domoticz2023.2 (build 15640)`):
![afbeelding](https://github.com/domoticz/domoticz/assets/33630544/bf96629f-3203-46f6-b9ad-c23fb36a859f)

**Comment by gizmocuz** [comment]
Yes, that is because Domoticz expects only one combination of Temp+Hum per device.
In this case, ESP32-Faikin creates one device (identifier) with multiple sensors.
If it created seperate device/identifiers this problem does not exist
One device for ble temp+hum would also be preferred (by most users that is...)

There are two solutions for this issue

Domoticz side:
- check if a device as multiple temp or humidity sensors and if so, threat them always separate

or

ESP-Faikin side:
- create multiple devices (with different identifiers) and group where it makes sense (like ble temp+hum)

I will work on the Domoticz side as I just received another github issue from a user having the same issue where there is one device with two temps and two humidity sensors grouped and no way to distinguish them.

The downside of separating them is that you get more devices and therefor have not a quick overview like you would have when Domoticz creates one combined Temp+Hum device

**Comment by gizmocuz** [comment]
Should be solved in beta 15643

**Comment by HV-NL** [comment]
Just downloaded the latest beta: my problem is solved! Thank you!
