### ISSUE TITLE
Update to latest Beta (15697) failed

### ISSUE THREAD

**Issue by FireWizard52** [domoticz/domoticz#5913]
As @waltervl has closed the previous issue too fast, I have to open a new issue.

After updating to version 15697, I noticed that this version does not work on older Raspberry PI 's (armv6)
Update process goes as expected, but Domoticz on Raspberry Pi 1B+ does not start.

It gives:

> Dec 04 18:45:57 RPi1 systemd[1]: Starting LSB: Home Automation System...
> Dec 04 18:45:58 RPi1 domoticz.sh[1501]: Illegal instruction
> Dec 04 18:45:58 RPi1 systemd[1]: Started LSB: Home Automation System.

Updating my other Pi (armv7) goes normal and no issues discovered.

See also forum post https://www.domoticz.com/forum/viewtopic.php?t=41100&start=20

Regards

**Comment by waltervl** [comment]
You could have asked to reopen the old issue ;-) I would have been happy to do so.

What if you update again? Seems that your domoticz.sh got broken somehow.

**Comment by gizmocuz** [comment]
Het is using a RPI1 with arm6
Build server has been setup for arm7
Also this can be changed back but he could also build domoticz himself
This is a very old device , almost 14 years old

**Comment by gizmocuz** [comment]
Let’s say after 14 years it is time to buy something new
This device has many issues with storage and is extreme slow

**Comment by jbfenris** [comment]
The issue is the same on RPi 2B when it had been working quite well for many years.

**Comment by kiddigital** [comment]
> The issue is the same on RPi 2B when it had been working quite well for many years.

The Pi 2(B) is armv7 and should work.

**Comment by SumDum** [comment]
Please reopen this issue, I have the same problem:
> Dec  9 14:44:53 pi3-domoticz systemd[1]: domoticz.service: Succeeded.
> Dec  9 14:44:53 pi3-domoticz systemd[1]: Stopped LSB: Home Automation System.
> Dec  9 14:44:53 pi3-domoticz systemd[1]: Starting LSB: Home Automation System...
> Dec  9 14:44:53 pi3-domoticz domoticz.sh[23762]: Illegal instruction
> Dec  9 14:44:53 pi3-domoticz systemd[1]: Started LSB: Home Automation System.

This is disappointing:
> Let’s say after 14 years it is time to buy something new This device has many issues with storage and is extreme slow

I run Domoticz on two Pi 1 B+ and three Pi Zero W.  None of them is the slightest bit taxed and response speed is fine.  Just because something is old does not mean it needs to be replaced.

None of this hardware is obsolete:
>Raspberry Pi 1 Model B+ will remain in production until at least January 2026
https://www.raspberrypi.com/products/raspberry-pi-1-model-b-plus/

**Comment by kiddigital** [comment]
@SumDum , although I sort of want to agree with you that just because something is old it does not have to be replaced, but unfortunately this is not the way thing work especially when it comes to IT. Hard- and software still develops rapidly 'aging' even relatively new things quickly.

Although the hardware is still fine, including the  'old' software running on it, it does not automatically mean that new(er) software runs fine as well.

Domoticz keeps evolving and growing, new features being added using newer underlying software/os/libraries/etc. slowly forcing 'old' software to become unusable/unmaintainable/unsupported and therefore no longer available.

Keeping domoticz 'alive' for older hardware like armv6 (Pi 1, Pi Zero, etc) requires additional maintenance and given relative limited time/people/capacity choices have to be made.

But, if you are willing to spend some time, it is not too difficult to setup a build environment for armv6 yourself. You can either try a cross-compile environment using Qemu for example or use a dedicated 'spare' Pi 1 to build an armv6 binary from source.

You can than distribute this binary to your other machines and maybe even others 😁.

**Comment by SumDum** [comment]
@kiddigital 
OK, I'll give it a shot.  I'll start a new topic on the forum when I hit problems (which I will - I ain't no coder!).  I'll try it on a Pi4 desktop first as that should be the easiest way to get my toes wet then have a go at producing arm6 binary after.

**Comment by gizmocuz** [comment]
This could also be a good starting guide

https://www.domoticz.com/wiki/Build_Domoticz_from_source

**Comment by kiddigital** [comment]
> @kiddigital 
> 
> OK, I'll give it a shot.  I'll start a new topic on the forum when I hit problems (which I will - I ain't no coder!).  I'll try it on a Pi4 desktop first as that should be the easiest way to get my toes wet then have a go at producing arm6 binary after.

Nice 👍 Give it a try.

Your goal is to create an armv6 binary to run on your Pi 1 and Zero.

By default compiling on a Pi 4 will give you an armv7 binary! The easiest and most straightforward way is to use an armv6 device (Pi 1) to compile domoticz.

If you want to compile armv6 on a different hardware architecture (like a Pi 4 which is armv7 or Linux which is x86_64) you have to setup a cross-compile environment which is not as easy.

Good luck and I think with the help of the community you will succeed 💪
