### ISSUE TITLE
Device order of a user get lost after change of assigned devices

### ISSUE THREAD

**Issue by Bewo** [domoticz/domoticz#5979]
Firstly: I have been using Domoticz on various objects for many years now and I am still absolutely convinced. I like the "separation" by device. Great project => **Many thanks to everyone who has worked on it and continues to do so!**

I've looked through the forum and issue list, if I (hopefully) haven't missed anything, then unfortunately I've found a "bug":

Platform: Linux/amd64
I have several users in this Domoticz environment and about 280 used devices. Each user has different assigned devices, which they also sort individually.

With the current version 2024.1, I have noticed that the individual sorting of user's devices is COMPLETELY LOST if his assigned devices are changed (regardless of whether a device is added or removed). After changing his devices the sorting is simply alphabetical. However, when a new device is added, it is not sorted alphabetically, but at the bottom.

I know there is the possibility of rooms and we've configured it, but most of the time the kids and my wife are using the whole list (room "all"), because they sorted their devices as they wish. The biggest problem is that the WAF drops to almost zero with alphabetical sorting. :-P

Does anyone know where the sorting of the devices is stored? At first glance, I couldn't find something in the database... If there are entries for this, I could save and restore them manually first... ;-)

If I have forgotten any important information -> Sorry. Please let me know and I'll supply it immediately.
Best regards from Bavaria,
Bernd

**Comment by gizmocuz** [comment]
@Bewo, I think that this is correct.
To see this, make a database backup of your system via the Settings page.
Open this (with for Example SQLite Personal Edition), and open the 'SharedDevices' table
You will see a Order column. This column is Unique and when a new devices is inserted, it always get a higher number.
So when you 'add' a new device, it will always get the highest number
There should be no alphabetical sorting, unless the user has no devices assigned to his/her user account.
If this is the case, could you contact me on Slack (GizMoCuz) and send me a backup of your database?
(Please mention a link to this issue, and also the user that sees an alphabetical order instead of the correct order)

https://join.slack.com/t/domoticz/shared_invite/zt-wo7hrgc3-qIH0EFX_jcBrG2dBSOTRwg
