### ISSUE TITLE
Cannot add new node from the 2024.1 and 2024.2 version

### ISSUE THREAD

**Issue by dlebrat** [domoticz/domoticz#5994]
After upgrade to the version 2024.1 and 2024.2 later then beta, I can't add a new node.
Unfortunatly I reset my controler and lost all nodes. None of my module can associate with the controler. The database backup didn't restore them.
The controler is Zwave-me on OpenZwave and it appaer ok from the 2024.2 domoticz version.
I miss somethink or a further update can resolve my problem ?
I try to back on previous version without success.
I hope for posting on the right place, thanks for help!

**Comment by gizmocuz** [comment]
Please use our forum.
When you reset your zwave stick it is really gone. It is not something a backup can restore.
Why did you reset? Because when you want to switch to ZWaveJS-UI you could/should also keep everything paired.
When re-adding OZW in beta 2024.2, I of course tested if it is working... first step is to add a node
