### ISSUE TITLE
GPIO no longer works as kernel 6.6 on raspberry pi os

### ISSUE THREAD

**Issue by akamming** [domoticz/domoticz#6040]
Hi,

i just updated my raspberry pi4B to latest version with "apt update && apt upgrade -y". It also installed a new kernel (version 6.6)

And after that GPIO no longer works in domoticz. 

I did some investigation and this [link](https://forums.raspberrypi.com/viewtopic.php?t=359302) provided useful info. The link is about a raspberry pi 5, but since 6.6 my pi 4 now has the exact same behaviour: the pin numbering on the sysfs driver has drastically changed.

- with  "cat /sys/kernel/debug/gpio" i can find correct pin numbers and it turns out that the pins i am using (GPIO14 and 15) are configured on pins 526 and 527. 
- on the FS i can switch them like i want to, but just using the new pin number
- in domoticz exported pins are recognized (Status: gpio: Startup - polling:yes interrupts:no debounce:50msec inputs:1 outputs:1)
- but the switches don't appear, so i cannot do anything with it..

Reading the docs i also noticed that the SYSFS API for GPIO was [deprecated and code will be removed in the near future](https://www.kernel.org/doc/Documentation/gpio/sysfs.rst) so hopefully someone can adjust the code to make gpio work again with domoticz using the new api's

Note: apparently this is all pretty new to other developers to, cause rpi.GPIO (the standard python lib to control gpio) also no longer works. I also now get an error if a want to set add_event_detect to GPIO using  this lib. So my python watermeter script also no longer functioning...

**Comment by Tobeytt** [comment]
________________________________
发件人: akamming ***@***.***>
发送时间: 2024年3月18日 15:32
收件人: domoticz/domoticz ***@***.***>
抄送: Subscribed ***@***.***>
主题: [domoticz/domoticz] GPIO no longer works as kernel 6.6 on raspberry pi os (Issue #6040)


Hi,

i just updated my raspberry pi4B to latest version with "apt update && apt upgrade -y". It also installed a new kernel (version 6.6)

And after that GPIO no longer works in domoticz.

I did some investigation and this link<https://forums.raspberrypi.com/viewtopic.php?t=359302> provided useful info. The link is about a raspberry pi 5, but since 6.6 my pi 4 now has the exact same behaviour: the pin numbering on the sysfs driver has drastically changed.

  *   with "cat /sys/kernel/debug/gpio" i can find correct pin numbers and it turns out that the pins i am using (GPIO14 and 15) are configured on pins 526 and 527.
  *   on the FS i can switch them like i want to, but just using the new pin number
  *   in domoticz exported pins are recognized (Status: gpio: Startup - polling:yes interrupts:no debounce:50msec inputs:1 outputs:1)
  *   but the switches don't appear, so i cannot do anything with it..

Reading the docs i also noticed that the SYSFS API for GPIO was deprecated and code will be removed in the near future<https://www.kernel.org/doc/Documentation/gpio/sysfs.rst> so hopefully someone can adjust the code to make gpio work again with domoticz using the new api's

Note: apparently this is all pretty new to other developers to, cause rpi.GPIO (the standard python lib to control gpio) also no longer works. I also now get an error if a want to set add_event_detect to GPIO using this lib. So my python watermeter script also no longer functioning...

―

**Comment by waltervl** [comment]
This Issue seems to be related, originally reported on RPi 5 but now other RPi's are also using the new kernel https://github.com/domoticz/domoticz/issues/6014

**Comment by waltervl** [comment]
This merged PR should solve the issue. https://github.com/domoticz/domoticz/pull/6019
Please check in latest Beta.

**Comment by akamming** [comment]
i tested and the fix which is now in beta works
