### ISSUE TITLE
Python Framework is not notified when a Device Widget replace is done

### ISSUE THREAD

**Issue by pipiche38** [domoticz/domoticz#6136]
Since Domoticz 2022.1 the Replace behaviour has changed, and the old device remains and the new device is removed.

This is not propagated correctly to the Python Framework and a Replace API must be implemented in the Python Framework so the right actions are done.

**Comment by gizmocuz** [comment]
The old device gets the settings from the new device indeed.
This is outside the scope of the python framework, and does not happen often.
Most of the times the devices being created/updated via the python framework do not need replacement

**Comment by pipiche38** [comment]
I agree that is not so often, but as soon as a feature is provided that should work.

The use case is the following

- you use a Temperature sensor, and after few years, this was doesn't work anymore. So you create a new one. This new one as a new Mac Address and eventually work differently ( different EndPoint for exemple).
- When the user is doing Replace Old by New, Domoticz request the removal of the new one in the plugin framework , which is for me a bug as it shouldn't happen as it is the new one. Eventually we can say the Old one must be removed.

Instead of sending a Removal, the Python framework should be notified about the replacement bvetween Old and New and leave the plugin what is required for the replacement done correctly at the plugin level

**Comment by jp-keros** [comment]
Another real use case : My Lynky electrical sensor (all house) using ZigBeeForDomoticZ plugin is dead. I purchased exactly the same on in order to replace it.
Without that replacement function working with python framework, I will not be able to continue my 6 years historical measurements and see the comparing usage (example image) : 
![147738528-09969486-764e-4402-b6d6-c9c449208f16](https://github.com/user-attachments/assets/39ef90bf-0371-42d1-ac36-b63706e79eb4)

**Comment by gizmocuz** [comment]
The problem is with ZigbeeForDomoticz. This isn't a problem when you use RF or Zigbee2MQTT

I urge you to look at **CWebServer::Cmd_DoTransferDevice** to see what actually IS going on

This is especially made for RF devices as when you replace the battery it will get a new DeviceID/Unit

The DeviceID,Unit, Type, Subtype of the NEW device IS being used

And IF you are using this in your python code instead of an IDX you will be fine

**Comment by gizmocuz** [comment]
@jp-keros , there should be no problem when you switch to Zigbee2MQTT to replace your devices

**Comment by pipiche38** [comment]
The Idx is not the issue, the issue is that  CWebServer::Cmd_DoTransferDevice is requesting the deletion of the new Device in the Python Framework, while at no point the Framework was notified a Transfer is going on.

So yes, the Old device get the new DeviceID, Unit ..., but unfortunately you are requesting the deletion in the Framework, which then break the all thing.

You closed the issue, without giving the possibility to anyone to implement this feature. Great ... this is really a nice Open Source community way of behaving

**Comment by gizmocuz** [comment]
It's just your tone (again) over the years.... could be your native language, like the reply above, and 'bugs' you could have been written as 'problem'
I am friendly to most people....

So, the solution is not to get notified of the removal as the (new) device is not removed.

This is done in 'CSQLHelper::DeleteDevices', this function could have an optional boolean (bDoNotifyFramework) (default true)

And specifying 'false' in the call from 'CWebServer::Cmd_DoTransferDevice'

Again, when using Zigbee2MQTT this was not a problem
