### ISSUE TITLE
Passwords are not stored encrypted

### ISSUE THREAD

**Issue by LoukKamp** [domoticz/domoticz#6145]
Passwords (and other fields that should be secure) are stored in the Domoticz database without any form of encryption and can be read by anyone who has access to the system or backups /copies of the system or the database file. 

I believe, this is a major security risk!

This is also true for other fields, like e.g. API client secrets and tokens.

**Comment by gizmocuz** [comment]
Correct for some hardware. For the user/password combination this is stored secured
If one has access to your database you are screwed anyway

**Comment by kiddigital** [comment]
@LoukKamp , there are always ways to make it harder to capture sensitive data.

But that often comes with a cost, making things _less_ User Friendly.

As mentioned, user credentials are stored encrypted, but people that get hold of your database can just as easily get hold of the encryption/decryption keys.

And when it comes to API keys and tokens, when done properly these credentials should be temporary and rotating. So they can only be abused for a short period of time.

A simple example is your Netatmo auth updates. What to do with the refresh token? You can store it (encrypted) but then it can be captured. Much safer to 'just only keep it in memory' (not storing it). Much harder to capture.
But also less user friendly because with every restart of domoticz, the user has to re-enter credentials.

There is no definitive answer, it depends on ones risk appetite and preferences.

**Comment by LoukKamp** [comment]
All true, but when you leave your house, do you leave your door wide open, or do you just close, or do you lock it and put the keys under the doormat, or do you take them with you?

I'm not a security guru or freak, but leaving the door wide open, is not the best choice, I believe. And in this case, I'm just the messenger...

Yes, indeed, the refresh token is also a sensitive entity: When someone gets hold on it, this token can be used to get access to the room temperature in your living, or even your bedroom. Not a big problem at first sight, but someone who wants to steal all your Apples, can see when you go to bed or leave the house for work... And what about if Netatmo starts selling "smart" door locks, and you can control this lock using the same API??? 

That's why I thought about this while working on the oAuth2 changes. And that's why I clear the refresh token as soon as it is transported to the back-end. After that, It will never return to the front-end again. So when a hacker managed to log in, he will need to know the user credentials of the user's account at Netatmo to get a new refresh token. The only possibilty left is caputuring the (unsecure) wifi data (by the-man-in-the-middle software) and waiting for the owner to login at Netatmo... I think he will be the most patienced hacker in the world...

I think encryping the passwords before storing them, and decrypting when they are read back, would be a first step to improve this. This encrypting and decryping can be done in a non-public protected part of the code, so the keys would be hard to find.

**Comment by gizmocuz** [comment]
And what encryption method are we going to use?
See the database as your house keys, sure leave them in front of frontdoor
But when they are locked inside a box (raspberry pi), it's a lot safer
