### ISSUE TITLE
MQTT Temp/Hum devices choose strange name.

### ISSUE THREAD

**Issue by dwmw2** [domoticz/domoticz#6164]
These devices combine to make a single Temp/Hum device:

```
{
   "avty_t" : "bathroom/status",
   "dev" : {
      "cns" : [
         [
            "mac",
            "782184bb134c"
         ]
      ],
      "ids" : "782184bb134c",
      "mdl" : "esp32-gateway",
      "mf" : "Espressif",
      "name" : "bathroom",
      "sw" : "2024.9.0-dev (Sep  6 2024, 22:54:39)"
   },
   "dev_cla" : "temperature",
   "name" : "Bathroom Temperature",
   "obj_id" : "bathroom_bathroom_temperature",
   "stat_cla" : "measurement",
   "stat_t" : "bathroom/sensor/bathroom_temperature/state",
   "uniq_id" : "782184bb134c-sensor-fb9dd5d9",
   "unit_of_meas" : "°C"
}
```

```
{
   "avty_t" : "bathroom/status",
   "dev" : {
      "cns" : [
         [
            "mac",
            "782184bb134c"
         ]
      ],
      "ids" : "782184bb134c",
      "mdl" : "esp32-gateway",
      "mf" : "Espressif",
      "name" : "bathroom",
      "sw" : "2024.9.0-dev (Sep  6 2024, 22:54:39)"
   },
   "dev_cla" : "humidity",
   "name" : "Bathroom Humidity",
   "obj_id" : "bathroom_bathroom_humidity",
   "stat_cla" : "measurement",
   "stat_t" : "bathroom/sensor/bathroom_humidity/state",
   "uniq_id" : "782184bb134c-sensor-b74eb23e",
   "unit_of_meas" : "%"
}
```

That much is sensible. Including this device, however, is less sensible...

```
{
   "avty_t" : "bathroom/status",
   "clrm" : true,
   "cmd_t" : "bathroom/light/blue_led/command",
   "dev" : {
      "cns" : [
         [
            "mac",
            "782184bb134c"
         ]
      ],
      "ids" : "782184bb134c",
      "mdl" : "esp32-gateway",
      "mf" : "Espressif",
      "name" : "bathroom",
      "sw" : "2024.9.0-dev (Sep  6 2024, 22:54:39)"
   },
   "name" : "Blue LED",
   "obj_id" : "bathroom_blue_led",
   "schema" : "json",
   "stat_t" : "bathroom/light/blue_led/state",
   "supported_color_modes" : [
      "onoff"
   ],
   "uniq_id" : "782184bb134c-light-6a29e1c2"
}
```

![Screenshot from 2024-09-12 19-25-46](https://github.com/user-attachments/assets/e87d73cb-16bb-4ea3-b97e-4850a15002b5)

Not sure what's going on, but shouldn't 'Blue LED' appear as a device of its own? The Temp/Hum sensor appears to have eaten it, and taken its name.

**Comment by dwmw2** [comment]
Ah, I think the absence of the real 'Blue LED' switch is a separate issue: https://github.com/domoticz/domoticz/pull/6165

~~The combined Temp+Hum sensor takes its name because it just picks *a* random name from all the devices attached to the same ESPHome unit.~~

~~Perhaps choosing a name is hard, but choosing the name of a device which is already registered in its own right almost certainly isn't right? Should we skip those? Or try stripping 'Temperature/Humidity' from the names of the constituent devices?~~

Edit: s/device/sensor/ in most of that but it's still wrong. As noted in the following comment, it *is* using the device name for the Temp+Hum sensor, but the device name is wrong.

**Comment by dwmw2** [comment]
Oh... devices and sensors are different things. I'll edit my previous comment. And it *is* trying to use a device name, not a sensor name. But we *change* the device name every time we find a new sensor attached to that device.

```
--- a/hardware/MQTTAutoDiscover.cpp
+++ b/hardware/MQTTAutoDiscover.cpp
@@ -755,9 +755,11 @@ void MQTTAutoDiscover::on_auto_discovery_message(const struct mosquitto_message*
                        std::string subname = root["name"].asString();
                        if (subname.find("0x") != 0)
                        {
+                               Log(LOG_NORM, "Changing name of device %s ... ", pDevice->name.c_str());
                                pDevice->name = dev_name;
                                if (dev_name != subname)
                                        pDevice->name += " (" + subname + ")";
+                               Log(LOG_NORM, ".. to %s ... ", pDevice->name.c_str());
                        }
                        else
                        {

```
```
2024-09-13 09:18:57.284  Status: mqtt: Discovered: power-ashp1 (Heap Free)/power-ashp1 (Heap Free) (unique_id: 508bb9a83209-sensor-acee5b6b)
2024-09-13 09:18:57.384  mqtt: Changing name of device power-ashp1 (Heap Free) ... 
2024-09-13 09:18:57.384  mqtt: .. to power-ashp1 (Loop Time) ... 
2024-09-13 09:18:57.384  Status: mqtt: Discovered: power-ashp1 (Loop Time)/power-ashp1 (Loop Time) (unique_id: 508bb9a83209-sensor-8a395f6a)
2024-09-13 09:18:57.485  mqtt: Changing name of device power-ashp1 (Loop Time) ... 
2024-09-13 09:18:57.485  mqtt: .. to power-ashp1 (Uptime) ... 
2024-09-13 09:18:57.485  Status: mqtt: Discovered: power-ashp1 (Uptime)/power-ashp1 (Uptime) (unique_id: 508bb9a83209-uptime)
```

**Comment by gizmocuz** [comment]
I also have not seem a switch with a temp+hum sensor in it.
It probably tries to match devices that belong to each other, like W and kWh, temp and hum etc

**Comment by dwmw2** [comment]
Yeah, the matching of *sensors* to each other to make a combined sensor is fine. It's just that each time we see a sensor/switch which belongs to a given device, we update the *device's* name to include the sensor/switch name.

So the device ends up with the name of the last sensor/switch found on it.

And then when we make up a name for the combined sensor based on the device name, it ends up with the name of whatever sensor/switch was last found on that device.

**Comment by dwmw2** [comment]
> I also have not seem a switch with a temp+hum sensor in it.

FWIW I built this ESPHome device specifically to be a switch with a Temp+Hum sensor in it. It drives the bathroom fan and heated mirror when the humidity goes up.

https://git.infradead.org/?p=users/dwmw2/esp32-pool.git;a=blob;f=humidity.yaml;h=064d86796c2ec75e553f7e7316f74997315583e0;hb=0f3a22ac83c8d327e14589a019f74fff6b4c00aa

**Comment by gizmocuz** [comment]
Seems like an issue in your sketch. As mentioned by you, the status light you also do not want to control, so you can remove this from the sketch and this should probably solve your issue as well

**Comment by dwmw2** [comment]
But then the device will just have some other random name of a different sensor or switch attached to it. The Domoticz bug will still be there.

I think it's actual the Uptime sensor which is second to last. So the Temp+Hum sensor will be called "Bathroom  (Uptime)". Not better.

Why do we add a sensor name to the device name, and change the device name for every sensor we find, leaving it with the name of the last one? Surely that makes no sense?

**Comment by dwmw2** [comment]
Ah, I worked out why we did it. It's because we later just set `pSensor->name = pDevice->name`. We're overriding the device name each time because we actually end up using it for the sensor name. Fixed in #6167 to keep track of the device and sensor names separately instead of confusing the two.

**Comment by GravityRZ** [comment]
Can we take a look at this change.
i also use esphome and have a separate temperature, humidity and barometer device.(2 different devices)
After this change MQTT-AD recreates 1 new combined device.

Aso a device which was combined temp/humidiy now suddenly is recreated  as seperate temp and humidity device.

the new mqtt-ad names probably lso afffects new devices like thermostat 6
old thermostat devices are recreated into new thermostat 6 devices

**Comment by gizmocuz** [comment]
should be one device...

**Comment by GravityRZ** [comment]
ok if this is by design i understand. what i do not understand is that after this change a temp/hum device(combined device) i had in domoticz suddenly did not work anymore. i rediscovered it with mqtt-ad and now i have a separate temp and a seperate humidity device.

these 2 devices are in 1 ESP  which obviously are 1 device

ESPsensor/temperature
ESPsensor/humidity.

i would expected tha tif things get combined this will happen with every device, espacially when the naming would suggest it is one device

**Comment by gizmocuz** [comment]
It is not the 'naming' that suggests the combining, but the unique id's and types.
Best to setup a development environment (I recommend Visual Studio Community so you can set breakpoints and have a look step-by-step what is going on)

Tested this with zigbee2mqtt, zwavejs-ui and it has also been tested with lots of devices from dwmw2, and it's working perfectly now

Sure, maybe not for some strange ESPHome device combination projects, but for 95% it is, and that is mainstream user.

**Comment by dwmw2** [comment]
Please can you show the MQTT content for the devices, much like the example shown when I opened this issue? I'll take a look and try to work out what's happening. Although I'm away a lot in the next couple of weeks so it might not be quick.

**Comment by GravityRZ** [comment]
this is the temp device mqtt config code
`{"unit_of_meas":"C","name":"Temperature","ic":"mdi:thermometer","stat_t":"esp32-thermometer/sensor/temperature/state","avty_t":"esp32-thermometer/status","uniq_id":"ESPsensortemperature","dev":{"ids":"c04e30821360","name":"ESP32-Thermometer","sw":"2026.1.3 (config hash 0x1651a540)","mdl":"esp32-c3-devkitm-1","mf":"Espressif","cns":[["mac","c04e30821360"]]}}`

this is the humidity device mqtt config code
`{"unit_of_meas":"%","name":"Humidity","ic":"mdi:water-percent","stat_t":"esp32-thermometer/sensor/humidity/state","avty_t":"esp32-thermometer/status","uniq_id":"ESPsensorhumidity","dev":{"ids":"c04e30821360","name":"ESP32-Thermometer","sw":"2026.1.3 (config hash 0x1651a540)","mdl":"esp32-c3-devkitm-1","mf":"Espressif","cns":[["mac","c04e30821360"]]}}`

before the MQTT-AD change this was discovered as a combined device(which it is)
after migrating this device stopped working. i enabled device discovery on domoticz and it recreated 2 different devices instead of 1 combined.

i noticed that playing with the names(eg rename to woonkamertemperature and woonkamerhumidity) had some effect.

changing names on sensors definately has an effect on how they are combined

other sensor with the following sensornames

Temperatuur Slaapkamer

BME680 Temperatuur (not send out with mqtt)
BME680 Humidity
BME680 Barometer

before the change this created 2 devices
1 combined temp/humidity device
1 Barometer device

after the change it created 
1 temp/hum/barometer device

 i changed the sensor names to
Slaapkamer Temperatuur

BME680 Temperatuur (not send out with mqtt)
Luchtvochtigheid
BME680 Barometer

now it created a combined temp/humidity device and a seperate barometer device just like before.

in the past i noticed that MQTT did look at icon names and based on that it created devices(which were not always good)

what exactly is mqtt-ad looking at now to create a device and what makes it decide to combine devices
