### ISSUE TITLE
MQTTAutoDiscovery sensor update generates a loss of precision in the measure 

### ISSUE THREAD

**Issue by mealgi** [domoticz/domoticz#6168]
Hello,

1 - Context
Version: 2024.7 (build 16178)
Build Hash: bc750e2df-modified
Compile Date: 2024-08-07 15:43:48
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

2 - Issue
MQTTAutoDiscovery sensor update generates a loss of precision in the measure.

I am using MQTT Auto Discovery Client Gateway with LAN interface along with Z-Wave JS UI to control my ZWAVE devices configuration.
I have installed a Home Energy Meter - Gen5 ZW095 from AEONS Labs to collect the electricity usage (kwh) in a usage device directly read from hardware device (Type=243, SubType=29).

For example the information read from MQTT Explorer is :
{
"time": 1726212707587,
"value": 12955.483,
"nodeName": "Compteur Central",
"nodeLocation": "Compteur Electrique"
}
or
{
"time": 1726212707982,
"value": 12955.524,
"nodeName": "Compteur Central",
"nodeLocation": "Compteur Electrique"
}

whereas in Domoticz I get 12955.500 kWh in the electricity consumption device.

The issue is caused in the line 307 of MQTTAutoDiscover.cpp.
306 //until we have c++20 where we can use std::format
307 retVal = std_format("%g", root.asDouble());

When using %g format the double 12955.483 is converted to the string 12955.5. In the same way the double 12955.524 is converted to the string 12955.5. As a result a loss of precision of the measure sent by Zwave.

3 - Fix proposed
Replace %g by %f as format in the line  307 of MQTTAutoDiscover.cpp.
306 //until we have c++20 where we can use std::format
307 retVal = std_format("%f", root.asDouble());

BR

**Comment by gizmocuz** [comment]
Thank you for spotting!

With %f it creates a string like 12955.483**000**

A better alternative would be better to use:

`retVal = std_format("%.*g", FLT_DECIMAL_DIG, root.asDouble());`

This routine is also used for other sensors values like temperature.

**Comment by dwmw2** [comment]
> With %f it creates a string like 12955.483000

That's OK. It doesn't matter that it's not "pretty" because it's only going to be consumed into by `atof()` anyway. Nobody's going to *see* it.

> A better alternative would be better to use:
> retVal = std_format("%.*g", FLT_DECIMAL_DIG, root.asDouble());

Careful. With `%g` that probably ought to be called `FLT_SIGNIFICANT_FIGURES`. That's the difference between `%f` and `%g`: the former gives you significant figures, the latter give you decimal places (both 6 by default).

In #6163 I'd also converted to `%f`. For kWh meters in particular we mostly don't care about the high values *(hundreds of thousands of kWh over the lifetime of the meter)*; it's the individual Wh (that is, .001kWh) that have been used *today* which we care about. Which is why I'd also gone for `%f` to give a fixed number of decimal places, rather than significant figures.

Nine significant figures should generally work even for that use case though.
