### ISSUE TITLE
Meteorologisk institutt Norway prognosis is two hours off

### ISSUE THREAD

**Issue by CherAlban** [domoticz/domoticz#6169]
When using the Meteorologisk institutt Norway hardware, the current Domoticz values are always two hours "ahead" of time (the red circle), compared to the home assistant values:

![image](https://github.com/user-attachments/assets/cd7a2647-7c4d-4817-bb4b-3f3670a2eda6)

HA correctly reports 20.6°C, while Domoticz falsely reports 17.3°C 

Version 2024.7 (16253) on Windows 11, CEST time zone (+2h)

**Comment by gizmocuz** [comment]
Could be a timezone issue. But what hardware/plugin are you using?

**Comment by CherAlban** [comment]
I am using the build in hardware, no extra plugin.

**Comment by gizmocuz** [comment]
Thanks, then the issue is in hardware/Meteorologisk.cpp

`void CMeteorologisk::GetMeterDetails()`

Around/From line 237

I had a quick look in the code, and it seems the first value returned from the API is the actual value.
The code is indeed using the 3rd value resulting in a 2-hour difference

Could you try beta 16256, in this version I just take the first returned value

**Comment by CherAlban** [comment]
That seems to have fixed the problem, Domoticz and HA are both reporting the same value, thanks.

**Comment by gizmocuz** [comment]
Thanks for the feedback!
