### ISSUE TITLE
Italian Translation in scene schedule is broken

### ISSUE THREAD

**Issue by ilpol984** [domoticz/domoticz#6170]
Hello,
I've version 2024.7.

If I try to edit a scene schedule I see the screen like this:

![immagine](https://github.com/user-attachments/assets/d1abf839-4414-49d8-aceb-1f18a86fac8c)

If I swith the browser in english everithing is just fine.

Thank you, regards,

**Comment by gizmocuz** [comment]
I'm sorry, I am unable to reproduce this.
I also do not have a Table/Grid option for a scene/Group
Did you just update from a old version to this version? If yes, try clearing your browser cache

**Comment by Claude2666** [comment]
I have noticed something similar, my language is set to English.  
It only happens in the scene tab when I hit log or timers (and sometimes also with edit)
This is when I hit log:
![image](https://github.com/user-attachments/assets/152bd67b-11e7-41bb-9b64-4e6782633288)

And timers:
![image](https://github.com/user-attachments/assets/808b3cad-4058-490d-b4da-8b3887ae107d)

However, it only happens with Chrome browser, no issues with Firefox.

And if you refresh the page by hitting F5 or the reload button, it loads correctly loads the page and stays good for a while. It looks to me that initially something is not loaded, and after page refresh all works fine.

**Comment by gizmocuz** [comment]
Thanks for reporting. I can now reproduce this. It is when you open a new browser tap and then go to scenes/log
The reason is that the sceneAPI factory is not loaded yet (for some strange reason)
I can fix it by moving all the factory functions in the scenelog/timer controller directly, but that defeats the purpose of having one nice factory with all the functions.

While here, I also noticed another issue, the widget does not show that there are timers for the scenes (if does for group types)

**Comment by Claude2666** [comment]
About the timer widget, I have noticed that if you have a persistent timer, it does not show in switches and scenes tab.  Non persistent timers have a different colour when a timer is active.

**Comment by gizmocuz** [comment]
I fixed the timer notation issue and also made a temp. fix for this one (beta 16267)
Maybe someday, someone can have a better look into this, I tried and failed to see how this could be... and how it should be solved
