### ISSUE TITLE
sent data via MQTT results in integer vaue iso float

### ISSUE THREAD

**Issue by Nifrabar** [domoticz/domoticz#6185]
When I sent data from Domoticz (push MQTT) that data differs from real sent value.
![gas2](https://github.com/user-attachments/assets/f3a0e34f-db72-4cce-9a3b-e68e9da319cc)
![image](https://github.com/user-attachments/assets/55c85fe5-0bdf-4c54-a949-a477a91730c3)
IDX762 is gas-meter. Realvalue to be sent is 1165130
pushed via MQTT is value 1165.  So the decimal part is not pushed
note that the screenshot of device shows 1165.167 iso 1165130. That's because I needed to force gas-usages to be able to catch the mqtt-push value.
See also domoticz forum https://www.domoticz.com/forum/viewtopic.php?t=42751

**Comment by gizmocuz** [comment]
SValue contains 1165167, that is correct, and is also in the database.
In Domoticz/Settings/Metering you can set the counter divider for gas, default 100, so 1165167 becomes 1165.167

**Comment by waltervl** [comment]
@gizmocuz as mentioned in the forum topic normal Domoticz MQTT sends value 1165167  but the special pushMQTT  sends only 1165. So nothing to do with the divider setting.

See also this message screenshot where both are shown Domoticz/out and DomoHome (pushMQTT) https://www.domoticz.com/forum/viewtopic.php?p=320720#p320720

**Comment by gizmocuz** [comment]
Ahhh, got distracted by looking at the first MQTT 'out' message above

I guess this was also the case with temperatures that contained decimal points.

Please try beta 16288

**Comment by Nifrabar** [comment]
@gizmocus
just tried build beta 16288
it's getting better but not fully Oke
![bug1](https://github.com/user-attachments/assets/aa6ea3bd-f86d-42d5-ab0a-d208ece7fede)

**Comment by gizmocuz** [comment]
Can't change this. Seems the JSON library is doing this. But the value is correct

**Comment by Nifrabar** [comment]
no, value is not correct.
Real value is 1165.183
dz pushed value is 1165.18 + many zero's +1
As this concerns a gasmeter consumption it should show correct values.
But as this bugs cannot be fixed I have to look for other solutions.

**Comment by gizmocuz** [comment]
Well, instead of just throwing the towel in the ring, you could also look at the modification I made for you yesterday.

I had another try, and this time I used:

`root[vType] = std::stod(sendValue);`

This seems to work for whole number (1165), but also for 1165.18 and 1165.183, it just sends these numbers here now, well MQTT Explorer displays it correctly, or rounds it correctly. 1165.18000000000003 is still 1165.18, strangely with 3 digits it just sends 3 digits.

"If" you want to have another go, you could try beta 16289 and see if that solves your issue

We could just send it as tekst, but that's not desired as it is really a number/double

Other applications using this value will probably have no issues with it

**Comment by Nifrabar** [comment]
tried built 16289
thanks for your efforts
but sorry to say still not good
![bug3](https://github.com/user-attachments/assets/b438e19f-bde2-4c7a-bfd2-44215d6ec0e6)

**Comment by gizmocuz** [comment]
That is odd.... very odd....  

Hmmmmz... Okey, so this problem was not part of the MQTT Pusher, but a general issue with the 'push' gas value.
It was already rounded here before it got pushed out

Could you try beta 16290?

{"gas_usage":5533.1760000000004}

which MQTT Explorer displays as 

"gas_usage": 5533.176

Which is correct as it's a double field type

I like the last remark here

https://stackoverflow.com/questions/29832984/jsoncpp-writing-float-values-incorrectly

> "Too much digits is a cosmetic problem. Too few gives wrong results. 17 is always sufficient for an IEEE754 double"

**Comment by Nifrabar** [comment]
I did the measuring twice
first gave exact good results
but second has some weird decimal value again with lots of zero's
![bug4](https://github.com/user-attachments/assets/fda53256-9352-4d71-ad2b-8b25e035dac2)

**Comment by gizmocuz** [comment]
Correct, as mentioned above this is normal. It is a double value.
If you read the link from my previous comment, you will understand why
There is absolutely nothing wrong with this. It is not a textual representation, it is a real 'double' value
Great it's finally working correct!

If you use MQTT explorer (like mentioned above), you will also see when you select the state topic, it displays correctly the value on the right.

With what do you use the MQTT pusher value with? I am pretty sure the receiving end handles it correctly

**Comment by Nifrabar** [comment]
I use the domoticz built-in facility to push data using mqtt.
I'm not a real programmer so don't understand fully the explanation.
I don't understand you say this is OKe while I see a decimal part containing lots of zero's and as last digit a non-zero value now and then.

Ah, you meant to where it's data pushed.
It's to Homeassistant and no, data is not received well yet. But maybe I'm doing something wrong at HA site. Will investigate and report back.

Thanks fof your help sofar.

**Comment by gizmocuz** [comment]
HASS should have no problem using this value. What does it display?

**Comment by Nifrabar** [comment]
This is what's shown in HA. Apart from decimal sign it looks fine.
Thanks again for faultfinding en corrections.
![HA-gas1](https://github.com/user-attachments/assets/3581e83d-6276-4457-8e31-6c1869b5b9d5)

**Comment by gizmocuz** [comment]
Maybe you can add a divider somehow (/1000)
Glad this is solved, and thanks for reporting!!
