### ISSUE TITLE
Export PNG or jpg from graph is blocked by highcharts

### ISSUE THREAD

**Issue by waltervl** [domoticz/domoticz#6188]
When exporting a PNG or jpg from a graph we get the following error. Perhaps Domoticz lacks the required HTTP referer and user-agent headers?

See also https://www.highcharts.com/docs/export-module/privacy-disclaimer-export

```
`Sorry, you have been blocked
Your are unable to access export.highcharts.com
Why have I been blocked?

Most likely your request lack the required HTTP referer and user-agent headers. Also, chart configurations that fail to render properly, excessive requests ("hammering") and similar will result in progressively longer periods of blocking.
What can I do to resolve this?

First of all check your headers, and also read our Fair Usage Policy to make sure your usage is not significantly above expected levels. Blocking is based on your IP, which may be shared, so blocking might not be caused by your actions. `
```

**Comment by gizmocuz** [comment]
No idea what's going on ... many highchart users seems to experience this issue.
Tried using the offline export but my browser (Edge) did not want to support this (blob)
Tried updating highcharts, same issue

It is possible to setup our own export server, but I don't think this is a desired solution.

Hope someone else have a go at this to solve it.

(Might be that the reason is that it's called from a private ip address? (192.168.0.123:8080), but I have no option to test it from a external host as I am using Wireguard to access all my internal stuff)

Ps. We are using the cors header, so I don't think it has anything to do with this. (Also tried removing it without success)

**Comment by feelingwalnut** [comment]
same issue here, thought domoticz was using a built-in linux program to generate these charts, not an external website.
my bad, wonder how many other items are reliant on external services.

**Comment by gizmocuz** [comment]
@feelingwalnut , maybe you could modify the code to use the internal exporter? I tried this but failed.
Quick solution until someone is able to solve it, use your keyboard shortcut to make a screenshot?

**Comment by feelingwalnut** [comment]
Lol yes screenshot works.
Did notice that library has an internal export variant, will take a look at it and figured its the most likely path for the domoticz team to take.

**Comment by gizmocuz** [comment]
Feel free to make a PR to support this. I tried as you could have read a few posts up

**Comment by raibisch** [comment]
..same issue.

**Comment by feelingwalnut** [comment]
so, i saved the code from this page.
https://code.highcharts.com/modules/offline-exporting.js
and compressed it as gzip offline-exporting.js.gzip
placed it into the domotitz/www/js/highcharts/modules folder
went into /domoticz/www/index.html and removed 
<script charset="utf-8" src="js/highcharts/modules/export-data.js"></script>
replaced it with 
<script charset="utf-8" src="js/highcharts/modules/offline-exporting.js"></script>

so, it looks like a partial fix, as an example, 24hr temperature charts will download, monthly charts will go to highcharts domain, yearly the same. other sensors seem to go to their domain as well.
tried in private, tried after clearing cookies and cache, doesnt work at all without rigging with the above.

**Comment by gizmocuz** [comment]
That would be great! Because what I did was upgrade the complete highcharts library/theme/code and added that off-line export include underneath the normal export option.
Going to test it today, would be great if it was that simple

... Tested it, still receiving "Sorry, you have been blocked"

As my test system did not had any day for the day graphs, I tested with the month/year graphs

**Comment by feelingwalnut** [comment]
Yeah... Sorry. I can export these only.
![chart](https://github.com/user-attachments/assets/dcf787c8-9834-40c5-b2ed-50dbed4e754e)

**Comment by feelingwalnut** [comment]
![temperature_chart](https://github.com/user-attachments/assets/44a655fa-9269-4e8f-a6bd-0402820c9afe)
is there any aversion to switching to something like charts.js and rendering the png/jpg/svg as base64 for export?

i'm playing with using an api call to get the json data, render it into a chart on the page and then have the ability to export it locally. it should only need the external resource of downloading the current chart.js code, in my test i'm just using it saved locally.

not sure about browser compatibility or other requirements, just spitballing an idea.

**Comment by gizmocuz** [comment]
How about you make a screenshot? Sure you can find an application that allows you to drag a rectangle?

**Comment by Potatof** [comment]
Hi all,
same for me,  i've replaced <script charset="utf-8" src="js/highcharts/modules/export-data.js"></script> with <script charset="utf-8" src="js/highcharts/modules/offline-exporting.js"></script>
then, cleaned browser cache and receive the same message  :

Sorry, you have been blocked
Your are unable to access export.highcharts.com
Why have I been blocked?
Most likely your request lack the required HTTP referer and user-agent headers. Also, chart configurations that fail to render properly, excessive requests ("hammering") and similar will result in progressively longer periods of blocking.

What can I do to resolve this?
First of all check your headers, and also read our Fair Usage Policy to make sure your usage is not significantly above expected levels. Blocking is based on your IP, which may be shared, so blocking might not be caused by your actions.

**Comment by gizmocuz** [comment]
I am thinking about removing the export option in the menu.
You can make a screenshot

**Comment by waltervl** [comment]
I think removing the screenshot function is indeed a valid suggestion when implementing the highcharts local export module is so cumbersome.

**Comment by gizmocuz** [comment]
Done in beta 16326, closing issue for now

**Comment by gizmocuz** [comment]
After updating Highcharts to 12.1 all seems to be working again.

(Available in beta 16495)
