### ISSUE TITLE
MQTT setpoint device not made.

### ISSUE THREAD

**Issue by Brugje** [domoticz/domoticz#6204]
I have a ems-esp who have serveral sensors and switches. These came in domoticz without problem. Only the adjustible switches are not shown as device. I can see them at the hardware en config page. 
![image](https://github.com/user-attachments/assets/fe06246f-f434-4d07-a07a-deb15d29f5df)
Also I can adjust the vallues there but why is there not a device made like a setpoint device.
The vallues at the config page are updated by mqtt and also changes to the vallues work. So the read and write to mqtt works. How do i get this as a device like:
![image](https://github.com/user-attachments/assets/eb06d772-00d7-4b54-91aa-70fdea662e94)

**Comment by gizmocuz** [comment]
These are number devices and made for (one time) configuration

**Comment by Brugje** [comment]
Thats correct these are adjusteble number devices but I would like to configer them with domoticz. For example the first (marked Yellow) is a temperatur value. This sets my heatpump to a certain temperatur. I would write a script depending on the weather and demand on heat to how high it must be. There for i need a device in domoticz. I found that the (dummy) device setpoint should do it. Is there a possebillity to make this work.

**Comment by waltervl** [comment]
Is this the same question as in this forum topic? https://www.domoticz.com/forum/viewtopic.php?t=42755
Perhaps better keep the discussion on the forum instead of here. For Setpoints it looks like EMS-ESP should create climate/HVAC config topics.

**Comment by Brugje** [comment]
Yes because we don't get an answer. Domoticz points to ems-esp and ems-esp to domoticz. Please say what is needed to make it work. I my opinion domoticz can read and write these through mqtt. See my message on the forum. The only thing is that domoticz makes the devices for number devices as she does with all the other sensors and switches from ems-esp.

**Comment by gizmocuz** [comment]
number configs are configuration options, like max_allowed_temp, min_allowed_temp, default_volume_level ... things like that
MQTT-AD has sensors types for the real temperature sensor, switch types for... switches ... lights for ... 
and 'climate' for example setpoint devices

This is an example of a climate config payload

{
  "temp_stat_t": "~/ess_setpoint/state",
  "dev": {
    "manufacturer": "PA1DVB",
    "ids": [
      "0x8000000002"
    ]
  },
  "~": "my_victron",
  "name": "ESS Setpoint",
  "uniq_id": "0x8000000002",
  "temp_unit": "Watt",
  "temp_cmd_t": "~/set/ess_setpoint",
  "temp_stat_tpl": "{{ value_json.ess_setpoint }}",
  "temp_step": 100,
  "min_temp": -5000,
  "max_temp": 5000
}

And yes, this needs to be fixed by ems-esp

You can question yourself this... why would it work correct with 100 zigbee/zwave real manufactures hardware, and not with an custom ESP project?

Now, be sure that these are not configuration settings !!! because they do need to be in number format.
You can set these, select them, change the number and press update
Like the offset option, this really seems a configuration setting, and indeed needs to be in the number format, and you need to change it where you can see them above!

So, the real SetPoint device (like what you use to set your actual room temperature... not a limit!) should be a MQTT-AD climate type
Now you may question yourself, but the 'hot water' temperature should also be a SetPoint device... Well... maybe it could.. but it is perfectly fine to have this as a configuration setting (number type)
Because these kind of settings you normaly also need to configure on your CV ketel!

**Comment by waltervl** [comment]
Continue on the forum.....  https://www.domoticz.com/forum/viewtopic.php?t=42755
