### ISSUE TITLE
Replace a temperature device with a temp+humidity device

### ISSUE THREAD

**Issue by gaeljw** [domoticz/domoticz#787]
When you edit a temperature device you can replace it with another temperature device (really useful when changing batteries implies a new device ID).

Same, you can replace a temperature+humidity device with another temperature+humidity device.

All of this works perfectly. History is kept as expected.

But could it be possible to replace a temperature device with a temp+humidity device ? In both ways ?

**Comment by gizmocuz** [comment]
No, the types don't match.... you could try it by hand, change the type of the old sensor to be a THB in the DeviceStatus table

**Comment by gaeljw** [comment]
This worked like a charm :)

In case, someone wants to do this. This is what I did : 
- Open _domoticz.db_ with `sqlite3`
- Find the devices, and the Type and SubType needed
  - `SELECT ID,Name,Type,SubType FROM DeviceStatus;`
- Update the row, for example :
  - `UPDATE DeviceStatus SET Type = '82' WHERE ID = XX;`
  - `UPDATE DeviceStatus SET SubType = '1' WHERE ID = XX;`

**Comment by rkluwen** [comment]
We should have a forum for this on the site: Hacking domoticz!

**Comment by TomMalfrere** [comment]
I needed this also. 
One of my temp sensors got "redetected" as a temp sensor with humidity. I replaced the old sensor with the new one to keep the temp history.
Today my temp sensor got "redetected" as a temp sensor (without humidity). Replacing the sensor did not work. I had to edit the type from 82 to 80 and set the subtype to 0.
After restoring the DB I could replace the sensor again...
I used DB Browser to edit domoticz.db

**Comment by gizmocuz** [comment]
@TomMalfrere , what type of hardware are you using?
This sensor, is this a Temp+Hum sensor?
If yes, enable 'accept new devices' under settings, It should 99% be detected as temp+hum when both values are received and continue to update the temp+hum
Meaning, ignore the separate sensors

**Comment by TomMalfrere** [comment]
@gizmocuz 
The device is a fibaro universal binary sensor (ZWave). This device can have up to 3 temp probes (DS18B20) (without humidity).
I have one in my aquarium since junu 2019.
on september 29th I stopped receiving temperature values....
I have been tinkering around in zwavejsui. There, values where still being reported.
I noticed that a NEW device was sending values since sept 29th. (hickup in zwavejsui???)
At first I could not see the new device because it was NOT added to my user even though I'm admin. 
*** I would prefer that new devices are automatically added for admin users. ***
The new device created by zwavejsui was a temp+humidity. (seems wrong to me, but hey I still got my temp values)
This device recorded all temp values since sept 29th.
So, I did a replace on my 'aquarium temperature'. All temp values where nicely merged.
This morning I noticed I wasn't getting any temperature values again.
zwavejsui had created a new device (temp only) after my tinkering in zwavejsui (reinterview node, ...)
So, I wanted to replace the temp sensor for my 'aquarium temperature' but I could because the old one was (temp+humidity) and the new one was only (temp).
So, I had to change the type of the old sensor manually from (temp+humidity) to (temp)...

**Comment by gizmocuz** [comment]
For the Admin user, make sure you have NO devices assigned to it.
You will then see all devices.
You can create a new user that you trust 100.000%, give it admin rights, but assign specific devices to him/her, so they have not to see 'everything' and can make their own favorites and lineup
This new user should NOT have the name 'admin'

Now back to the topic...

I made a patch and we now support replacing **Temp** or **Temp+Hum** or **Temp+Hum+Baro** with a **Temp** or **Temp+Hum** or **Temp+Hum+Baro** sensor in version **15607**
