### ISSUE TITLE
[Feature] LDAP Authentication

### ISSUE THREAD

**Issue by ImNtReal** [domoticz/domoticz#838]
Please, consider adding a LDAP backend for user accounts, so I can tie this in with my existing LDAP server.

**Comment by gizmocuz** [comment]
Sorry, this is not planned

**Comment by adec** [comment]
Hi, I am currently working on integrating Domoticz with Cytech Comfort but when that's completed, I'm happy to pick up the gauntlet of LDAP authentication if gizmocuz is okay with me doing so.  I can't offer any kind of ETA though at this moment in time.  

@gizmocuz: is there likely to be any dependency from the My Domoticz side or is user authentication always performed solely in Domoticz locally?

Regards,
Ade.

**Comment by sbouchex** [comment]
Why not using pam authentication and rely on what linux is offering instead of using some dependencies libraries ?

**Comment by adec** [comment]
@sbouchex I agree that PAM is a good option for Linux but I have a couple of potential reservations though.  

PAM won't work for folk who run Domoticz under Windows - so we'd need a separate integration for windows users to use LDAP.  

Also PAM is great for people of a more technical persuasion (granted this is most Home Automation folk) but it can get a bit complex for normal folk, although nothing that can't be solved with a suitable Wiki page.

Regards,

Ade.

**Comment by sbouchex** [comment]
For Windows, using standard Win32 API to do the authentication should be fine. Then Windows will (like PAM) use the underlaying authentication method.

I agree that PAM can be a bit difficult to understand but it gives you the ability to support all kind of authentication without having to implement all of them.

**Comment by adec** [comment]
@sbouchex Yes, I can see the sense in using the standard OS authentication mechanisms.  I know this wouldn't work for folk who are running Windows and using a separate LDAP servers but I'm straying into the realms of edge cases now.

@ImNtReal What OS are you running?  If Windows are you using AD or an separate LDAP?

In terms of handling the in-built users, I'm thinking that we should try to authenticate against local users first then if that fails try PAM/Windows auth.  This would allow Domoticz-only users to be handled.  Do you agree?   I don't want to clutter the UI with loads of options and would rather have a single Use PAM authentication (for Linux & Mac) or Use Windows authentication (for Windows).

@gizmocuz Are you happy with this approach?

**Comment by gizmocuz** [comment]
I see it like this:
Domoticz is like your router/switch, that has users with passwords/rights.
My router/switch has no LDAP login support... even my Cisco Catalyst 3750 does not have this, neither does my Edge-Core
You can even check the option 'remember me'

So, all this hard work, for just a login screen ? I think it is a bit way over the top

But maybe i am missing something here ;)

**Comment by ImNtReal** [comment]
I'm running Linux. I wouldn't mind having to use PAM, but it would actually be easier for me if I could use Basic Auth in Apache, and have those users have the rights assigned in Domoticz than PAM because I only use local authentication at the system level, but I have several web apps that all authenticate to my LDAP server, so it would be nice if my wife could have the same password across all of them without having to manually keep them in sync.

**Comment by sbouchex** [comment]
Basic Auth is already supported in domoticz, so you should be able to configure your frontend to point to domoticz, no ?

**Comment by adec** [comment]
The problem is more about how to use a single password for sign-on to multiple applications.  So, either Domoticz uses LDAP as a backend or alternatively there is an option to use single sign-on where something upstream of Domoticz (like Apache) performs the authentication and then passes the username to the Domoticz (for example in a HTTP header).

The last option is fine provided you can ensure that Domoticz can only be accessed via whatever component is doing the authentication (either by using localhost for communications between Apache & Domoticz or using firewall rules, etc).

Thinking about this for a second, I can imagine that this latter could be implemented by checking whether the request is from a trusted IP address.  If it is, then check for the existence of a particular HTTP header.  If the HTTP header doesn't exist, then assume that the normal unauthenticated superuser is logged in.

If the HTTP header exists, then have Domoticz look to see if there is a Domoticz user defined whose username is the same as the value in the HTTP header.  If there is, the act as if this user has authenticated.   If the user doesn't exist, deny access.

Just flying a kite here...  It does mean people can roll their own web access management layer to implement single sign-on if they want to without needing LDAP integration etc.  Of course, the correct way to pass credentials around is via SAML assertions but I think that massively fails @gizmocuz's KISS principle test. ;-)

**Comment by xbeaudouin** [comment]
Hum. If you want LDAP auth, just consider adding a proxy like nginx for example and bind domoticz to local host (127.0.0.1 / ::1).
Adding libldap (or whatever) dependency on domoticz sound really lots of work for such usage.
Also notice that PAM is "dependant" of the plateform you use. For example PAM doesn't exist on Windows, but PAM exist (somewhat) on Linux, FreeBSD, Solaris (variant), but all API are not the same.

**Comment by ImNtReal** [comment]
Sorry it took so long, but I finally got around to testing this. I already had Apache frontending Domoticz with LDAP auth. It does allow me to limit who can log in to the site, but it doesn't seem to matter what permissions I set for th user inside of Domoticz. Everyone is an admin.

**Comment by l-t-k** [comment]
+1 for LDAP, would be great. Yes, you can proxy with Apache/Nginx, but can't set permissions with it. I'm running other services like nextcloud, subsonic etc. All of them are able to use my local ldap server for authentication. In that case, it's really useful to have domoticz working with LDAP as well.

**Comment by gizmocuz** [comment]
Not going to implement... maybe you could write a php application around it ?
