### ISSUE TITLE
New Notification service for domoticz

### ISSUE THREAD

**Issue by appzer** [domoticz/domoticz#880]
Hi,

based on the Pushover notification package from domoticz, i created a version for the service from [Pushsafer.com](https://www.pushsafer.com).

Pushsafer offers client apps for ios, android and windows 10 (phone & desktop) and webpush for Chrome and Firefox. You have the possibilty to modify the push notification and set up icon, sound, vibration, title, text.

I hope you can implement this feature in your next update. I attached the files directly to this post.

Thanks Kevin

[domoticz-pushsafer.zip](https://github.com/domoticz/domoticz/files/480258/domoticz-pushsafer.zip)

**Comment by jrich523** [comment]
You should really make a pull request for this sort of thing

**Comment by appzer** [comment]
done! hope I did everything right

**Comment by jrich523** [comment]
It looks like your still committing to the branch, which isn't a huge deal,
just know it's branch based. Changes you make after creating the pr are
also included. Usually you make a branch for the pr and leave it after
creation. After the pr has been accepted and merged you blow away the
branch.

On Sep 19, 2016 10:42 AM, "Kevin" notifications@github.com wrote:

done! hope I did everything right

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/domoticz/domoticz/issues/880#issuecomment-248065335,
or mute the thread

**Comment by appzer** [comment]
i opened a pull request > All checks have passed

Thanks Kevin
