### ISSUE TITLE
Aeotec ZW096 Smart Switch 6 State always reports ON after Domoticz restart

### ISSUE THREAD

**Issue by drdrone** [domoticz/domoticz#969]
After a restart of Domoticz these switches always reports the state ON when they're in fact OFF.
The OZW panel shows correctly OFF so it must be a bug in Domoticz?
Parameter 80. Notification status: set to BASIC

**Comment by gizmocuz** [comment]
No issues here, do you added the correct switch ? Because you get multiple switches
This is also discussed on the forum, please ask this on the forum

**Comment by drdrone** [comment]
Yea I think so, the one ending with 01. What's your parameter 80 set to when you tested?

**Comment by gizmocuz** [comment]
Yes, but edit the switch, set it to a normal On/Off type
Parameter 80, no idea... lets see:
Parameter 80 is notification status, it is set to default (nothing)

![image](https://cloud.githubusercontent.com/assets/2265299/20149680/ae28c414-a6b2-11e6-96ae-775c663939fd.png)
![image](https://cloud.githubusercontent.com/assets/2265299/20149686/ba3cab62-a6b2-11e6-836e-bc85e1b23ce2.png)

Can't remember i touched something, but probably your switch type is set on 'Level' instead of On/Off

**Comment by drdrone** [comment]
My switch is On/Off. I checked all parameters again and tried default values without any luck.
Also it seems that parameter 83 & 84 is missing, RGB value and Brightness.

**Comment by gizmocuz** [comment]
Maybe try with the latest beta, and exclude/include again, maybe the configuration file has been changed

**Comment by drdrone** [comment]
Nope, same result sadly.

**Comment by gizmocuz** [comment]
tried again here with another switch... working with issues... must be something else wrong
If not, please contact me on the forum, if you could send your switch to debug, i might be able to tell if something is wrong
